// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: clipmap_render (ground + common + materials + clipmap_render)
// Entry point: canopy_vertex_main, compile with /T vs_5_0 /E canopy_vertex_main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) frame -> b0  constant buffer
//   @group(1) @binding(8) height_texture -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(9) world -> b1  constant buffer
//   @group(1) @binding(11) clamp_sampler -> s0  SamplerState
//   @group(1) @binding(12) ground_layers -> t1  Texture2DArray (Sampled { kind: Float, multi: false })

struct FrameUniforms {
  row_major float4x4 view_proj;
  float4 camera_position;
  float4 camera_forward;
  float4 camera_right;
  float4 camera_up;
  float4 sun_direction;
  float4 atmosphere;
  float4 sky_tint;
  float4 mist_params;
  float4 mist_colour;
  float4 mist_wind;
  float4 cloud_params;
  float4 cloud_motion;
  float4 cloud_colour;
  float4 water_params;
  float4 water_shallow;
  float4 water_deep;
  float4 water_current;
  float4 wave_params;
  float4 wave_params2_;
  float4 water_origin;
  float4 vegetation;
  float4 vegetation2_;
  float4 viewport;
  row_major float4x4 shadow_view_proj;
  float4 shadow_params;
  float4 weather;
  float4 weather2_;
  float4 surface;
  float4 clouds2_;
  float4 clouds3_;
  float4 clouds4_;
  float4 weather3_;
  row_major float4x4 previous_view_proj;
  float4 temporal;
  float4 distances;
  float4 fades;
  float4 output;
  float4 cold;
  float4 sea_ice;
  float4 rivers;
  float4 ground;
  float4 vegetation3_;
  float4 rock;
  float4 regional;
  float4 air;
  float4 light;
  float4 gust;
  float4 weather4_;
  float4 clouds5_;
  float4 alto;
  float4 rivers2_;
  float4 waterside;
  float4 mouths[16];
};

struct WorldInfo {
  float4 species[8];
  float4 species_tint[8];
  float4 terrain;
  float4 terrain2_;
  float4 material_tints[12];
  float4 trees;
  float4 species_canopy[8];
};

struct VertexIn {
  float3 position : LOC0;
  float2 normal : LOC1;
  uint3 materials : LOC2;
  float4 climate : LOC3;
  uint4 biome : LOC4;
};

struct CanopyOut {
  float4 clip_position : SV_Position;
  float3 world_position : LOC0;
  float3 normal : LOC1;
  float crowns : LOC2;
  nointerpolation uint species : LOC3;
  float2 climate : LOC4;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const int MAT_LUSH = int(0);
static const int MAT_DRY = int(1);
static const int MAT_FOREST = int(2);
static const int MAT_SAND = int(3);
static const int MAT_ROCK = int(4);
static const int MAT_SNOW = int(5);
static const int MAT_MUD = int(6);
static const int MAT_VOLCANIC = int(7);
static const int MAT_ICE = int(8);
static const int MAT_TUNDRA = int(9);
static const int MAT_GRAVEL = int(10);
static const int MAT_SCREE = int(11);
static const int MATERIAL_COUNT = int(12);
static const float FIELD_RANGE = 16.0;
static const float FIELD_SPEED_STEP = 0.5;
static const float FIELD_BAND_STEP = 0.07;
static const float3 WET_SOIL = float3(0.11, 0.085, 0.06);

cbuffer frame : register(b0) { FrameUniforms frame; }
Texture2D<float4> height_texture : register(t0);
cbuffer world : register(b1) { WorldInfo world; }
SamplerState clamp_sampler : register(s0);
Texture2DArray<float4> ground_layers : register(t1);

struct VertexOutput_canopy_vertex_main {
  float3 world_position : LOC0;
  float3 normal : LOC1;
  float crowns : LOC2;
  nointerpolation uint species_1 : LOC3;
  float2 climate : LOC4;
  float4 clip_position : SV_Position;
};

float hash12_(float2 p)
{
  float3 p3_ = (float3)0;

  p3_ = frac((float3(p.x, p.y, p.x) * 0.1031));
  float3 _e9 = p3_;
  float3 _e10 = p3_;
  float3 _e11 = p3_;
  p3_ = (_e9 + (dot(_e10, (_e11.yzx + (33.33).xxx))).xxx);
  float _e20 = p3_.x;
  float _e22 = p3_.y;
  float _e25 = p3_.z;
  return frac(((_e20 + _e22) * _e25));
}

float skirt_height(float edge, float sea, float distance_, float noise_)
{
  float foot = min(edge, (sea - 60.0));
  if ((distance_ >= SKIRT_METRES)) {
    return (foot - ((distance_ - SKIRT_METRES) * 0.08));
  }
  float s = smoothstep(0.0, 1.0, (distance_ / SKIRT_METRES));
  return (lerp(edge, foot, s) + (((((edge - foot) * 0.6) * noise_) * s) * (1.0 - s)));
}

float skirt_noise(float2 xz)
{
  float2 p_1 = (xz / (700.0).xx);
  float2 cell = floor(p_1);
  float2 f = (p_1 - cell);
  float2 u = ((f * f) * ((3.0).xx - (2.0 * f)));
  const float _e13 = hash12_(cell);
  const float _e18 = hash12_((cell + float2(1.0, 0.0)));
  float top = lerp(_e13, _e18, u.x);
  const float _e25 = hash12_((cell + float2(0.0, 1.0)));
  const float _e30 = hash12_((cell + float2(1.0, 1.0)));
  float bottom = lerp(_e25, _e30, u.x);
  return ((lerp(top, bottom, u.y) * 2.0) - 1.0);
}

int2 naga_f2i32(float2 value) {
  return int2(clamp(value, -2147483600.0, 2147483500.0));
}

float texel_height(Texture2D<float4> heights, float4 terrain2_, float2 texel)
{
  float2 clamped = clamp(texel, (0.0).xx, (terrain2_.xy - (1.001).xx));
  float2 base = floor(clamped);
  float2 f_1 = (clamped - base);
  int2 i = naga_f2i32(base);
  float4 _e14 = heights.Load(int3(i, int(0)));
  float h00_ = _e14.x;
  float4 _e21 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(1), int(0)))), int(0)));
  float h10_ = _e21.x;
  float4 _e28 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(0), int(1)))), int(0)));
  float h01_ = _e28.x;
  float4 _e35 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(1), int(1)))), int(0)));
  float h11_ = _e35.x;
  return lerp(lerp(h00_, h10_, f_1.x), lerp(h01_, h11_, f_1.x), f_1.y);
}

float ground_height(Texture2D<float4> heights_1, float4 terrain, float4 terrain2_1, float2 xz_1)
{
  if ((terrain2_1.z < 0.5)) {
    return -100000.0;
  }
  const float _e12 = texel_height(heights_1, terrain2_1, ((xz_1 + terrain.xy) / terrain.zw));
  float outside = length(max((abs(xz_1) - terrain.xy), (0.0).xx));
  if ((outside <= 0.0)) {
    return _e12;
  }
  const float _e23 = skirt_noise(xz_1);
  const float _e24 = skirt_height(_e12, terrain2_1.w, outside, _e23);
  return _e24;
}

float terrain_height_at(float2 xz_2)
{
  float4 _e4 = world.terrain;
  float4 _e7 = world.terrain2_;
  const float _e8 = ground_height(height_texture, _e4, _e7, xz_2);
  return _e8;
}

bool over_terrain(float2 xz_3)
{
  bool local = (bool)0;

  float _e4 = world.terrain2_.z;
  if ((_e4 > 0.5)) {
    float4 _e12 = world.terrain;
    local = all((abs(xz_3) <= _e12.xy));
  } else {
    local = false;
  }
  bool _e17 = local;
  return _e17;
}

float4 ground_layer_at(float2 xz_4, int layer)
{
  float4 _e4 = world.terrain2_;
  float2 size = max(_e4.xy, (1.0).xx);
  float4 _e11 = world.terrain;
  float4 _e16 = world.terrain;
  float2 uv = ((((xz_4 + _e11.xy) / _e16.zw) + (0.5).xx) / size);
  float4 _e26 = ground_layers.SampleLevel(clamp_sampler, float3(uv, layer), 0.0);
  return _e26;
}

float4 cover_at(float2 xz_5)
{
  const float4 _e2 = ground_layer_at(xz_5, int(2));
  return _e2;
}

float3 decode_normal(float2 encoded)
{
  float3 n = (float3)0;

  n = float3(encoded.x, ((1.0 - abs(encoded.x)) - abs(encoded.y)), encoded.y);
  float _e13 = n.y;
  if ((_e13 < 0.0)) {
    float3 _e20 = n;
    float2 signs = ((_e20.xz >= (0.0).xx) ? (1.0).xx : (-1.0).xx);
    float _e27 = n.z;
    float _e34 = n.y;
    float _e36 = n.x;
    n = float3(((1.0 - abs(_e27)) * signs.x), _e34, ((1.0 - abs(_e36)) * signs.y));
  }
  float3 _e43 = n;
  return normalize(_e43);
}

float species_height(uint species)
{
  switch(species) {
    case 0u: {
      return 0.7;
    }
    case 1u: {
      return 0.8;
    }
    case 2u: {
      return 0.75;
    }
    case 3u: {
      return 0.5;
    }
    case 4u: {
      return 1.0;
    }
    case 5u: {
      return 0.6;
    }
    case 6u: {
      return 0.3;
    }
    default: {
      return 0.0;
    }
  }
}

uint naga_f2u32(float value) {
  return uint(clamp(value, 0.0, 4294967000.0));
}

VertexOutput_canopy_vertex_main canopy_vertex_main(VertexIn in_)
{
  float3 position = (float3)0;
  CanopyOut out_ = (CanopyOut)0;

  position = in_.position;
  float4 _e5 = world.terrain;
  float2 edge_1 = _e5.xy;
  float3 _e7 = position;
  float2 inside = clamp(_e7.xz, -(edge_1), edge_1);
  float3 _e11 = position;
  if (any((inside != _e11.xz))) {
    const float _e16 = terrain_height_at(inside);
    position = float3(inside.x, _e16, inside.y);
  }
  float3 _e19 = position;
  const float4 _e21 = cover_at(_e19.xz);
  float red = (_e21.x * 255.0);
  float _e28 = frame.vegetation3_.x;
  float3 _e33 = position;
  const bool _e35 = over_terrain(_e33.xz);
  float crowns_1 = (_e35 ? (((_e28 * red) * red) * 6.15148e-5) : 0.0);
  uint species_2 = naga_f2u32(round((_e21.y * 255.0)));
  float lift = float(in_.biome.z);
  float _e48 = position.y;
  const float _e49 = species_height(species_2);
  position.y = (_e48 + ((lerp(8.0, 28.0, _e49) + lift) * saturate((crowns_1 * 10.0))));
  float4x4 _e63 = frame.view_proj;
  float3 _e64 = position;
  out_.clip_position = mul(float4(_e64, 1.0), _e63);
  float3 _e69 = position;
  out_.world_position = _e69;
  const float3 _e72 = decode_normal(in_.normal);
  out_.normal = normalize(lerp(_e72, float3(0.0, 1.0, 0.0), 0.5));
  out_.crowns = crowns_1;
  out_.species = min(species_2, 7u);
  out_.climate = in_.climate.xy;
  CanopyOut _e87 = out_;
  const CanopyOut canopyout = _e87;
  const VertexOutput_canopy_vertex_main canopyout_1 = { canopyout.world_position, canopyout.normal, canopyout.crowns, canopyout.species, canopyout.climate, canopyout.clip_position };
  return canopyout_1;
}
