// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: clipmap_render (ground + common + materials + clipmap_render)
// Entry point: canopy_fragment_main, compile with /T ps_5_0 /E canopy_fragment_main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) frame -> b0  constant buffer
//   @group(1) @binding(0) linear_sampler -> s0  SamplerState
//   @group(1) @binding(5) noise_texture -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(9) world -> b1  constant buffer
//   @group(1) @binding(10) terrain_shadow_texture -> t1  Texture2D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(11) clamp_sampler -> s1  SamplerState
//   @group(1) @binding(13) regional_texture -> t2  Texture2D (Sampled { kind: Float, multi: false })

struct FrameUniforms {
  row_major float4x4 view_proj;
  float4 camera_position;
  float4 camera_forward;
  float4 camera_right;
  float4 camera_up;
  float4 sun_direction;
  float4 atmosphere;
  float4 sky_tint;
  float4 mist_params;
  float4 mist_colour;
  float4 mist_wind;
  float4 cloud_params;
  float4 cloud_motion;
  float4 cloud_colour;
  float4 water_params;
  float4 water_shallow;
  float4 water_deep;
  float4 water_current;
  float4 wave_params;
  float4 wave_params2_;
  float4 water_origin;
  float4 vegetation;
  float4 vegetation2_;
  float4 viewport;
  row_major float4x4 shadow_view_proj;
  float4 shadow_params;
  float4 weather;
  float4 weather2_;
  float4 surface;
  float4 clouds2_;
  float4 clouds3_;
  float4 clouds4_;
  float4 weather3_;
  row_major float4x4 previous_view_proj;
  float4 temporal;
  float4 distances;
  float4 fades;
  float4 output;
  float4 cold;
  float4 sea_ice;
  float4 rivers;
  float4 ground;
  float4 vegetation3_;
  float4 rock;
  float4 regional;
  float4 air;
  float4 light;
  float4 gust;
  float4 weather4_;
  float4 clouds5_;
  float4 alto;
  float4 rivers2_;
  float4 waterside;
  float4 mouths[16];
};

struct WorldInfo {
  float4 species[8];
  float4 species_tint[8];
  float4 terrain;
  float4 terrain2_;
  float4 material_tints[12];
  float4 trees;
  float4 species_canopy[8];
};

struct CanopyOut {
  float4 clip_position : SV_Position;
  float3 world_position : LOC0;
  float3 normal : LOC1;
  float crowns : LOC2;
  nointerpolation uint species : LOC3;
  float2 climate : LOC4;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const int MAT_LUSH = int(0);
static const int MAT_DRY = int(1);
static const int MAT_FOREST = int(2);
static const int MAT_SAND = int(3);
static const int MAT_ROCK = int(4);
static const int MAT_SNOW = int(5);
static const int MAT_MUD = int(6);
static const int MAT_VOLCANIC = int(7);
static const int MAT_ICE = int(8);
static const int MAT_TUNDRA = int(9);
static const int MAT_GRAVEL = int(10);
static const int MAT_SCREE = int(11);
static const int MATERIAL_COUNT = int(12);
static const float FIELD_RANGE = 16.0;
static const float FIELD_SPEED_STEP = 0.5;
static const float FIELD_BAND_STEP = 0.07;
static const float3 WET_SOIL = float3(0.11, 0.085, 0.06);

cbuffer frame : register(b0) { FrameUniforms frame; }
SamplerState linear_sampler : register(s0);
Texture2D<float4> noise_texture : register(t0);
cbuffer world : register(b1) { WorldInfo world; }
Texture2D<float4> terrain_shadow_texture : register(t1);
SamplerState clamp_sampler : register(s1);
Texture2D<float4> regional_texture : register(t2);

struct FragmentInput_canopy_fragment_main {
  float3 world_position : LOC0;
  float3 normal_1 : LOC1;
  float crowns : LOC2;
  nointerpolation uint species_1 : LOC3;
  float2 climate : LOC4;
  float4 clip_position : SV_Position;
};

float hash12_(float2 p)
{
  float3 p3_ = (float3)0;

  p3_ = frac((float3(p.x, p.y, p.x) * 0.1031));
  float3 _e9 = p3_;
  float3 _e10 = p3_;
  float3 _e11 = p3_;
  p3_ = (_e9 + (dot(_e10, (_e11.yzx + (33.33).xxx))).xxx);
  float _e20 = p3_.x;
  float _e22 = p3_.y;
  float _e25 = p3_.z;
  return frac(((_e20 + _e22) * _e25));
}

float remap(float value, float old_min, float old_max, float new_min, float new_max)
{
  return (new_min + (((value - old_min) / max((old_max - old_min), 0.0001)) * (new_max - new_min)));
}

float3 sun_dir()
{
  float4 _e2 = frame.sun_direction;
  return normalize(_e2.xyz);
}

float henyey_greenstein(float cos_theta, float g)
{
  float g2_ = (g * g);
  return ((1.0 - g2_) / (12.566371 * pow(max(((1.0 + g2_) - ((2.0 * g) * cos_theta)), 0.0001), 1.5)));
}

float air_mass(float cos_zenith)
{
  float c = clamp(cos_zenith, -0.2, 1.0);
  float zenith_degrees = degrees(acos(c));
  return (1.0 / max((c + (0.50572 * pow(max((96.07995 - zenith_degrees), 0.05), -1.6364))), 0.02));
}

float3 rayleigh_beta()
{
  float _e4 = frame.atmosphere.x;
  return (RAYLEIGH_BETA * max(_e4, 0.0));
}

float3 mie_beta()
{
  float _e4 = frame.atmosphere.y;
  float4 _e14 = frame.air;
  return ((MIE_BETA * (0.1 + (max(_e4, 0.0) * 0.45))) * _e14.xyz);
}

float3 sun_transmittance(float cos_zenith_1)
{
  const float _e1 = air_mass(cos_zenith_1);
  const float3 _e2 = rayleigh_beta();
  const float3 _e5 = mie_beta();
  float3 transmittance = exp((-(((_e2 * RAYLEIGH_HEIGHT) + (_e5 * MIE_HEIGHT))) * _e1));
  return (transmittance * smoothstep(-0.08, 0.02, cos_zenith_1));
}

float3 sun_light()
{
  const float3 _e0 = sun_dir();
  const float3 _e2 = sun_transmittance(_e0.y);
  float _e6 = frame.sun_direction.w;
  float _e13 = frame.light.x;
  return (((_e2 * _e6) * 2.35) * _e13);
}

float luminance(float3 colour)
{
  return dot(colour, float3(0.2126, 0.7152, 0.0722));
}

float3 sky_radiance(float3 direction)
{
  float3 sky = (float3)0;

  const float3 _e1 = sun_dir();
  float3 dir = normalize(float3(direction.x, max(direction.y, 0.0), direction.z));
  float mu = dot(dir, _e1);
  const float3 _e10 = rayleigh_beta();
  const float3 _e11 = mie_beta();
  const float _e13 = air_mass(dir.y);
  float3 depth_r = ((_e10 * RAYLEIGH_HEIGHT) * _e13);
  float3 depth_m = ((_e11 * MIE_HEIGHT) * _e13);
  float3 extinction = (depth_r + depth_m);
  float phase_r = (0.0596831 * (1.0 + (mu * mu)));
  float _e29 = frame.air.w;
  const float _e30 = henyey_greenstein(mu, _e29);
  const float3 _e32 = sun_transmittance(_e1.y);
  float3 sun_colour = (sqrt(_e32) * smoothstep(-0.08, 0.02, _e1.y));
  float3 inscatter = ((((depth_r * phase_r) + (depth_m * _e30)) / max(extinction, (1e-6).xxx)) * ((1.0).xxx - exp(-(extinction))));
  float3 fill = (float3(0.004, 0.009, 0.022) * smoothstep(-0.3, 0.2, _e1.y));
  float3 night = float3(0.0012, 0.0018, 0.004);
  float _e71 = frame.sun_direction.w;
  float4 _e77 = frame.sky_tint;
  sky = ((((((inscatter * sun_colour) * SUN_RADIANCE) * _e71) + fill) + night) * _e77.xyz);
  float overcast = frame.weather2_.y;
  if ((overcast > 0.001)) {
    float zenith_mu = _e1.y;
    float _e101 = frame.air.w;
    const float _e102 = henyey_greenstein(zenith_mu, _e101);
    float3 zenith_inscatter = ((((((_e10 * RAYLEIGH_HEIGHT) * 0.0596831) * (1.0 + (zenith_mu * zenith_mu))) + ((_e11 * MIE_HEIGHT) * _e102)) / ((_e10 * RAYLEIGH_HEIGHT) + (_e11 * MIE_HEIGHT))) * ((1.0).xxx - exp(-(((_e10 * RAYLEIGH_HEIGHT) + (_e11 * MIE_HEIGHT))))));
    float _e128 = frame.sun_direction.w;
    float4 _e134 = frame.sky_tint;
    const float _e137 = luminance(((((((zenith_inscatter * sun_colour) * SUN_RADIANCE) * _e128) + fill) + night) * _e134.xyz));
    float deck = ((((_e137 * 2.0) * (1.0 + (2.0 * dir.y))) / 3.0) * (1.0 - (overcast * 0.4)));
    float3 _e153 = sky;
    sky = lerp(_e153, ((deck).xxx * float3(0.92, 0.95, 1.0)), overcast);
  }
  float3 _e161 = sky;
  float _e169 = frame.weather2_.x;
  return (_e161 + ((float3(0.75, 0.8, 1.0) * _e169) * 1.6));
}

float3 sky_irradiance(float3 normal)
{
  const float3 _e5 = sky_radiance(float3(0.0, 1.0, 0.0));
  float towards_sky = saturate(((normal.y * 0.5) + 0.5));
  if ((towards_sky >= 0.9999)) {
    float _e19 = frame.light.z;
    return ((_e5 * 2.4) * _e19);
  }
  const float3 _e21 = sun_dir();
  const float3 _e24 = sun_dir();
  const float3 _e30 = sky_radiance(normalize(float3(-(_e21.x), 0.2, -(_e24.z))));
  float _e35 = frame.light.w;
  float3 sky_1 = lerp(lerp(_e30, _e5, towards_sky), _e5, _e35);
  const float3 _e37 = sun_light();
  float3 bounce = ((_e37 * 0.035) * saturate(((-(normal.y) * 0.5) + 0.5)));
  float _e65 = frame.light.z;
  return ((((sky_1 * (0.55 + (0.45 * saturate(((normal.y * 0.5) + 0.5))))) * 2.4) + bounce) * _e65);
}

float4 regional_weather_at(float2 xz)
{
  float4 _e3 = frame.regional;
  float _e9 = frame.regional.z;
  float2 uv = ((xz - _e3.xy) * _e9);
  float4 _e14 = regional_texture.SampleLevel(clamp_sampler, uv, 0.0);
  return _e14;
}

float canopy_clumps(float2 xz_1)
{
  float nearest = 2.0;
  int j = int(-1);
  int i = (int)0;

  float2 p_1 = (xz_1 / (9.0).xx);
  float2 cell = floor(p_1);
  uint2 loop_bound = uint2(4294967295u, 4294967295u);
  bool loop_init = true;
  while(true) {
    if (all(loop_bound == uint2(0u, 0u))) { break; }
    loop_bound -= uint2(loop_bound.y == 0u, 1u);
    if (!loop_init) {
      int _e46 = j;
      j = asint(asuint(_e46) + asuint(int(1)));
    }
    loop_init = false;
    int _e9 = j;
    if ((_e9 <= int(1))) {
    } else {
      break;
    }
    {
      i = int(-1);
      uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
      bool loop_init_1 = true;
      while(true) {
        if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
          int _e43 = i;
          i = asint(asuint(_e43) + asuint(int(1)));
        }
        loop_init_1 = false;
        int _e14 = i;
        if ((_e14 <= int(1))) {
        } else {
          break;
        }
        {
          int _e17 = i;
          int _e19 = j;
          float2 c_1 = (cell + float2(float(_e17), float(_e19)));
          const float _e23 = hash12_(c_1);
          const float _e27 = hash12_((c_1 + (17.31).xx));
          float2 centre = (c_1 + float2(_e23, _e27));
          const float _e33 = hash12_((c_1 + (41.7).xx));
          float size = (0.67 + (0.67 * _e33));
          float _e38 = nearest;
          nearest = min(_e38, (length((p_1 - centre)) / size));
        }
      }
    }
  }
  float _e49 = nearest;
  return saturate((1.0 - _e49));
}

bool clumps_unresolved(float distance_)
{
  float _e4 = frame.camera_forward.w;
  float _e11 = frame.viewport.w;
  return ((((distance_ * _e4) * 2.0) * _e11) > 4.5);
}

float2 cloud_weather_level(float2 xz_2)
{
  float coverage = (float)0;

  float _e4 = frame.cloud_params.x;
  coverage = _e4;
  float _e9 = frame.regional.w;
  if ((_e9 > 0.5)) {
    const float4 _e12 = regional_weather_at(xz_2);
    coverage = _e12.x;
  }
  float4 _e16 = frame.cloud_motion;
  float2 uv_1 = ((xz_2 + _e16.xy) / (26000.0).xx);
  float4 large = noise_texture.SampleLevel(linear_sampler, uv_1, 0.0);
  float4 _e35 = noise_texture.SampleLevel(linear_sampler, ((uv_1 * 3.3) + float2(0.37, 0.71)), 0.0);
  float medium = _e35.y;
  float weather = ((large.x * 0.7) + (medium * 0.3));
  float _e43 = coverage;
  float _e50 = coverage;
  const float _e57 = remap(weather, ((1.0 - (_e43 * 0.95)) - 0.05), (1.0 - (_e50 * 0.35)), 0.0, 1.0);
  return float2(saturate(_e57), large.w);
}

float cloud_weather(float2 xz_3)
{
  const float2 _e1 = cloud_weather_level(xz_3);
  return _e1.x;
}

bool alto_on()
{
  float _e3 = frame.clouds5_.z;
  float _e7 = frame.clouds5_.w;
  return (max(_e3, _e7) > 0.001);
}

float2 alto_wind()
{
  float4 _e2 = frame.clouds2_;
  float2 wind = _e2.zw;
  return float2(((wind.x * 0.9396926) + (wind.y * 0.3420201)), ((wind.y * 0.9396926) - (wind.x * 0.3420201)));
}

float alto_ripple(float2 q, float warp)
{
  const float2 _e2 = alto_wind();
  return (0.5 + (0.5 * sin(((dot(q, float2(-(_e2.y), _e2.x)) * 0.0069813174) + warp))));
}

float3 alto_coarse(float2 xz_4)
{
  float scale = 1.0;

  float4 _e3 = frame.alto;
  float2 q_1 = (xz_4 + _e3.xy);
  const float2 _e6 = alto_wind();
  float2 across = float2(-(_e6.y), _e6.x);
  float2 local_4 = float2((dot(q_1, _e6) / 2.5), dot(q_1, across));
  float4 n = noise_texture.SampleLevel(linear_sampler, ((local_4 / (48000.0).xx) + float2(0.29, 0.53)), 0.0);
  float _e32 = frame.regional.w;
  if ((_e32 > 0.5)) {
    const float4 _e35 = regional_weather_at(xz_4);
    float cover = _e35.x;
    float _e40 = frame.cloud_params.x;
    scale = (1.0 + (0.3 * clamp(((cover - _e40) / 0.2), -1.0, 1.0)));
  }
  float _e54 = frame.clouds5_.z;
  float _e55 = scale;
  float cumulus = saturate(((_e54 * _e55) * lerp(0.3, 1.7, n.x)));
  float _e66 = frame.clouds5_.w;
  float _e67 = scale;
  float stratus = ((_e66 * _e67) * (0.7 + (0.3 * n.y)));
  return float3(cumulus, stratus, ((n.w - 0.5) * 7.5));
}

float alto_shadow_depth(float2 xz_5)
{
  const float3 _e1 = alto_coarse(xz_5);
  float4 _e5 = frame.alto;
  const float _e9 = alto_ripple((xz_5 + _e5.xy), _e1.z);
  float cumulus_1 = (_e1.x * lerp(0.25, 0.45, _e9));
  return (ALTO_EXTINCTION * ((cumulus_1 * ALTOCUMULUS_THICKNESS) + (_e1.y * ALTOSTRATUS_THICKNESS)));
}

float alto_shadow(float3 position)
{
  bool local_1 = (bool)0;

  float _e4 = frame.alto.z;
  float rise = (_e4 - position.y);
  const bool _e7 = alto_on();
  if (!(!(_e7))) {
    local_1 = (rise <= 0.0);
  } else {
    local_1 = true;
  }
  bool _e15 = local_1;
  if (_e15) {
    return 1.0;
  }
  const float3 _e17 = sun_dir();
  float sun_y = max(_e17.y, 0.05);
  const float _e26 = alto_shadow_depth((position.xz + (_e17.xz * (rise / sun_y))));
  return exp((-(_e26) / sun_y));
}

float cloud_shadow(float3 position_1)
{
  float lit_ = 1.0;

  float _e4 = frame.cloud_colour.w;
  if ((_e4 < 0.5)) {
    return 1.0;
  }
  float _e13 = frame.cloud_params.x;
  if ((_e13 > 0.001)) {
    const float3 _e16 = sun_dir();
    float _e20 = frame.cloud_params.y;
    float _e24 = frame.cloud_params.z;
    float mid_height = (_e20 + (_e24 * 0.35));
    float travel = (max((mid_height - position_1.y), 0.0) / max(_e16.y, 0.08));
    float2 shadow_point = (position_1.xz + (_e16.xz * travel));
    const float _e40 = cloud_weather(shadow_point);
    float _e47 = frame.cloud_motion.w;
    float density = (smoothstep(0.05, 0.6, _e40) * saturate(((_e47 * 1.4) + 0.2)));
    float _e57 = frame.shadow_params.w;
    lit_ = (1.0 - (density * _e57));
  }
  const bool _e61 = alto_on();
  if (_e61) {
    float _e62 = lit_;
    const float _e63 = alto_shadow(position_1);
    float _e67 = frame.shadow_params.w;
    lit_ = (_e62 * lerp(1.0, _e63, _e67));
  }
  float _e71 = lit_;
  return _e71;
}

float terrain_shadow(float3 position_2)
{
  bool local_2 = (bool)0;
  bool local_3 = (bool)0;

  float strength = frame.shadow_params.z;
  if (!((strength <= 0.001))) {
    float _e13 = world.terrain2_.z;
    local_2 = (_e13 < 0.5);
  } else {
    local_2 = true;
  }
  bool _e17 = local_2;
  if (_e17) {
    return 1.0;
  }
  float4 _e22 = world.terrain;
  float4 _e27 = world.terrain;
  float2 uv_2 = ((position_2.xz + _e22.xy) / max((_e27.xy * 2.0), (1.0).xx));
  if (!(any((uv_2 < (0.0).xx)))) {
    local_3 = any((uv_2 > (1.0).xx));
  } else {
    local_3 = true;
  }
  bool _e47 = local_3;
  if (_e47) {
    return 1.0;
  }
  float4 _e52 = terrain_shadow_texture.SampleLevel(clamp_sampler, uv_2, 0.0);
  float lit_1 = _e52.x;
  return lerp(1.0, lit_1, strength);
}

bool beyond_render_distance(float distance_1)
{
  float _e4 = frame.distances.x;
  return (distance_1 > _e4);
}

float species_height(uint species)
{
  switch(species) {
    case 0u: {
      return 0.7;
    }
    case 1u: {
      return 0.8;
    }
    case 2u: {
      return 0.75;
    }
    case 3u: {
      return 0.5;
    }
    case 4u: {
      return 1.0;
    }
    case 5u: {
      return 0.6;
    }
    case 6u: {
      return 0.3;
    }
    default: {
      return 0.0;
    }
  }
}

float4 canopy_fragment_main(FragmentInput_canopy_fragment_main fragmentinput_canopy_fragment_main) : SV_Target0
{
  CanopyOut in_ = { fragmentinput_canopy_fragment_main.clip_position, fragmentinput_canopy_fragment_main.world_position, fragmentinput_canopy_fragment_main.normal_1, fragmentinput_canopy_fragment_main.crowns, fragmentinput_canopy_fragment_main.species_1, fragmentinput_canopy_fragment_main.climate };
  bool local = (bool)0;
  float clump = 0.57;
  float gap = 0.0;
  float3 albedo = (float3)0;

  float3 position_3 = in_.world_position;
  float4 _e4 = frame.camera_position;
  float distance_2 = length((position_3 - _e4.xyz));
  float canopy_distance = frame.vegetation3_.y;
  const float _e20 = hash12_((floor((position_3.xz / (9.0).xx)) + (3.71).xx));
  if (!((distance_2 < ((canopy_distance * 0.8) + ((_e20 * canopy_distance) * 0.2))))) {
    const bool _e31 = beyond_render_distance(distance_2);
    local = _e31;
  } else {
    local = true;
  }
  bool _e33 = local;
  if (_e33) {
    discard;
  }
  float4 _e36 = frame.camera_position;
  float3 view = normalize((_e36.xyz - position_3));
  float facing = max(abs(dot(view, in_.normal)), 0.05);
  const float _e46 = species_height(in_.species);
  float side = (0.11 * lerp(8.0, 28.0, _e46));
  float seen = (1.0 - exp((-(in_.crowns) * (1.0 + ((side * sqrt((1.0 - (facing * facing)))) / facing)))));
  const bool _e70 = clumps_unresolved(distance_2);
  if (_e70) {
    float _e74 = frame.camera_forward.w;
    float _e79 = frame.viewport.w;
    float level = exp2(ceil(log2((((distance_2 * _e74) * _e79) / 4.5))));
    float2 cell_1 = (floor((position_3.xz / ((9.0 * level)).xx)) + ((level * 7.13)).xx);
    const float _e96 = hash12_(cell_1);
    gap = ((_e96 < seen) ? 0.0 : 1.0);
    const float _e104 = hash12_((cell_1 + (19.7).xx));
    clump = (0.2 + (0.8 * _e104));
  } else {
    const float _e110 = canopy_clumps(position_3.xz);
    clump = _e110;
    float _e111 = clump;
    gap = ((1.0 - _e111) - sqrt(seen));
  }
  float _e116 = gap;
  if ((_e116 > 0.0)) {
    discard;
  }
  float moisture = in_.climate.x;
  float temperature = in_.climate.y;
  float dryness = saturate((((temperature - 0.45) * 1.5) + ((0.5 - moisture) * 1.5)));
  float4 _e137 = world.species_canopy[in_.species];
  albedo = _e137.xyz;
  float3 _e140 = albedo;
  float3 _e141 = albedo;
  albedo = lerp(_e140, (_e141 * float3(1.25, 1.05, 0.55)), (dryness * 0.35));
  float _e150 = clump;
  float shade = (0.45 + (0.55 * _e150));
  float _e156 = clump;
  float3 normal_2 = normalize((in_.normal + float3(0.0, (_e156 * 0.6), 0.0)));
  const float3 _e164 = sun_dir();
  const float _e165 = cloud_shadow(position_3);
  const float _e166 = terrain_shadow(position_3);
  float visibility = (_e165 * _e166);
  float wrap = saturate(((dot(normal_2, _e164) + 0.45) / 1.45));
  const float3 _e174 = sun_light();
  float3 direct = ((((_e174 * visibility) * wrap) * 0.85) * shade);
  const float3 _e184 = sky_irradiance(float3(0.0, 1.0, 0.0));
  float3 ambient = ((_e184 * (0.55 + (0.2 * normal_2.y))) * shade);
  float3 _e192 = albedo;
  float3 colour_1 = (((_e192 * (direct + ambient)) / (3.1415927).xxx) * 2.6);
  return float4(colour_1, 1.0);
}
