// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: clipmap_render (ground + common + materials + clipmap_render)
// Entry point: vertex_main, compile with /T vs_5_0 /E vertex_main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) frame -> b0  constant buffer
//   @group(1) @binding(9) world -> b1  constant buffer
//   @group(1) @binding(11) clamp_sampler -> s0  SamplerState
//   @group(1) @binding(12) ground_layers -> t0  Texture2DArray (Sampled { kind: Float, multi: false })

struct FrameUniforms {
  row_major float4x4 view_proj;
  float4 camera_position;
  float4 camera_forward;
  float4 camera_right;
  float4 camera_up;
  float4 sun_direction;
  float4 atmosphere;
  float4 sky_tint;
  float4 mist_params;
  float4 mist_colour;
  float4 mist_wind;
  float4 cloud_params;
  float4 cloud_motion;
  float4 cloud_colour;
  float4 water_params;
  float4 water_shallow;
  float4 water_deep;
  float4 water_current;
  float4 wave_params;
  float4 wave_params2_;
  float4 water_origin;
  float4 vegetation;
  float4 vegetation2_;
  float4 viewport;
  row_major float4x4 shadow_view_proj;
  float4 shadow_params;
  float4 weather;
  float4 weather2_;
  float4 surface;
  float4 clouds2_;
  float4 clouds3_;
  float4 clouds4_;
  float4 weather3_;
  row_major float4x4 previous_view_proj;
  float4 temporal;
  float4 distances;
  float4 fades;
  float4 output;
  float4 cold;
  float4 sea_ice;
  float4 rivers;
  float4 ground;
  float4 vegetation3_;
  float4 rock;
  float4 regional;
  float4 air;
  float4 light;
  float4 gust;
  float4 weather4_;
  float4 clouds5_;
  float4 alto;
  float4 rivers2_;
  float4 waterside;
  float4 mouths[16];
};

struct WorldInfo {
  float4 species[8];
  float4 species_tint[8];
  float4 terrain;
  float4 terrain2_;
  float4 material_tints[12];
  float4 trees;
  float4 species_canopy[8];
};

struct VertexIn {
  float3 position : LOC0;
  float2 normal : LOC1;
  uint3 materials : LOC2;
  float4 climate : LOC3;
  uint4 biome : LOC4;
};

struct VertexOut {
  float4 clip_position : SV_Position;
  float3 world_position : LOC0;
  float3 normal : LOC1;
  float4 materials_a : LOC2;
  float4 materials_b : LOC3;
  float4 materials_c : LOC4;
  float4 climate : LOC5;
  nointerpolation uint biome : LOC6;
  float canopy : LOC7;
  float scree : LOC8;
  float2 bed : LOC9;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const int MAT_LUSH = int(0);
static const int MAT_DRY = int(1);
static const int MAT_FOREST = int(2);
static const int MAT_SAND = int(3);
static const int MAT_ROCK = int(4);
static const int MAT_SNOW = int(5);
static const int MAT_MUD = int(6);
static const int MAT_VOLCANIC = int(7);
static const int MAT_ICE = int(8);
static const int MAT_TUNDRA = int(9);
static const int MAT_GRAVEL = int(10);
static const int MAT_SCREE = int(11);
static const int MATERIAL_COUNT = int(12);
static const float FIELD_RANGE = 16.0;
static const float FIELD_SPEED_STEP = 0.5;
static const float FIELD_BAND_STEP = 0.07;
static const float3 WET_SOIL = float3(0.11, 0.085, 0.06);

cbuffer frame : register(b0) { FrameUniforms frame; }
cbuffer world : register(b1) { WorldInfo world; }
SamplerState clamp_sampler : register(s0);
Texture2DArray<float4> ground_layers : register(t0);

struct VertexOutput_vertex_main {
  float3 world_position : LOC0;
  float3 normal : LOC1;
  float4 materials_a : LOC2;
  float4 materials_b : LOC3;
  float4 materials_c : LOC4;
  float4 climate : LOC5;
  nointerpolation uint biome : LOC6;
  float canopy : LOC7;
  float scree : LOC8;
  float2 bed : LOC9;
  float4 clip_position : SV_Position;
};

bool over_terrain(float2 xz)
{
  bool local = (bool)0;

  float _e4 = world.terrain2_.z;
  if ((_e4 > 0.5)) {
    float4 _e12 = world.terrain;
    local = all((abs(xz) <= _e12.xy));
  } else {
    local = false;
  }
  bool _e17 = local;
  return _e17;
}

float4 ground_layer_at(float2 xz_1, int layer)
{
  float4 _e4 = world.terrain2_;
  float2 size = max(_e4.xy, (1.0).xx);
  float4 _e11 = world.terrain;
  float4 _e16 = world.terrain;
  float2 uv = ((((xz_1 + _e11.xy) / _e16.zw) + (0.5).xx) / size);
  float4 _e26 = ground_layers.SampleLevel(clamp_sampler, float3(uv, layer), 0.0);
  return _e26;
}

float4 cover_at(float2 xz_2)
{
  const float4 _e2 = ground_layer_at(xz_2, int(2));
  return _e2;
}

float canopy_at(float2 xz_3)
{
  bool local_1 = (bool)0;

  const bool _e1 = over_terrain(xz_3);
  if (!(!(_e1))) {
    float _e9 = frame.vegetation3_.x;
    local_1 = (_e9 <= 0.0);
  } else {
    local_1 = true;
  }
  bool _e13 = local_1;
  if (_e13) {
    return 0.0;
  }
  const float4 _e15 = cover_at(xz_3);
  float red = (_e15.x * 255.0);
  float _e22 = frame.vegetation3_.x;
  return (1.0 - exp((((-(_e22) * red) * red) * 6.15148e-5)));
}

float3 decode_normal(float2 encoded)
{
  float3 n = (float3)0;

  n = float3(encoded.x, ((1.0 - abs(encoded.x)) - abs(encoded.y)), encoded.y);
  float _e13 = n.y;
  if ((_e13 < 0.0)) {
    float3 _e20 = n;
    float2 signs = ((_e20.xz >= (0.0).xx) ? (1.0).xx : (-1.0).xx);
    float _e27 = n.z;
    float _e34 = n.y;
    float _e36 = n.x;
    n = float3(((1.0 - abs(_e27)) * signs.x), _e34, ((1.0 - abs(_e36)) * signs.y));
  }
  float3 _e43 = n;
  return normalize(_e43);
}

VertexOutput_vertex_main vertex_main(VertexIn in_)
{
  VertexOut out_ = (VertexOut)0;

  float4x4 _e5 = frame.view_proj;
  out_.clip_position = mul(float4(in_.position, 1.0), _e5);
  out_.world_position = in_.position;
  const float3 _e14 = decode_normal(in_.normal);
  out_.normal = _e14;
  uint _e17 = in_.materials.x;
  out_.materials_a = (float4(_e17 & 0xFF, _e17 >> 8 & 0xFF, _e17 >> 16 & 0xFF, _e17 >> 24) / 255.0);
  uint _e21 = in_.materials.y;
  out_.materials_b = (float4(_e21 & 0xFF, _e21 >> 8 & 0xFF, _e21 >> 16 & 0xFF, _e21 >> 24) / 255.0);
  uint _e24 = in_.materials.z;
  float4 slots_c = (float4(_e24 & 0xFF, _e24 >> 8 & 0xFF, _e24 >> 16 & 0xFF, _e24 >> 24) / 255.0);
  out_.materials_c = float4(slots_c.xy, (float(in_.biome.w) / 255.0), slots_c.z);
  out_.scree = slots_c.w;
  out_.climate = in_.climate;
  out_.biome = in_.biome.x;
  out_.bed = (float2(float((in_.biome.y >> 4u)), float((in_.biome.y & 15u))) / (15.0).xx);
  const float _e59 = canopy_at(in_.position.xz);
  float litter = out_.materials_a.z;
  float spare = max((litter - _e59), 0.0);
  float _e68 = out_.normal.y;
  float gentle = smoothstep(0.75, 0.9, _e68);
  float _e76 = out_.materials_a.x;
  out_.materials_a.x = (_e76 + (spare * (0.6 + (0.4 * gentle))));
  float _e87 = out_.materials_a.y;
  out_.materials_a.y = (_e87 + ((spare * 0.4) * (1.0 - gentle)));
  out_.materials_a.z = (litter - spare);
  float shade = smoothstep(0.5, 0.9, _e59);
  float _e102 = out_.materials_b.x;
  float rock = ((_e102 * shade) * 0.5);
  float _e110 = out_.materials_a.z;
  float _e113 = out_.materials_a.x;
  float _e116 = out_.materials_a.y;
  out_.materials_a.z = ((_e110 + ((_e113 + _e116) * shade)) + rock);
  float _e125 = out_.materials_a.x;
  out_.materials_a.x = (_e125 * (1.0 - shade));
  float _e133 = out_.materials_a.y;
  out_.materials_a.y = (_e133 * (1.0 - shade));
  float _e141 = out_.materials_b.x;
  out_.materials_b.x = (_e141 - rock);
  out_.canopy = _e59;
  VertexOut _e144 = out_;
  const VertexOut vertexout = _e144;
  const VertexOutput_vertex_main vertexout_1 = { vertexout.world_position, vertexout.normal, vertexout.materials_a, vertexout.materials_b, vertexout.materials_c, vertexout.climate, vertexout.biome, vertexout.canopy, vertexout.scree, vertexout.bed, vertexout.clip_position };
  return vertexout_1;
}
