// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: terrain_shadow (terrain_shadow)
// Entry point: bake, compile with /T cs_5_0 /E bake
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) heights -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(1) output -> u0  RWTexture2D (Rgba8Unorm)
//   @group(0) @binding(2) params -> b0  constant buffer

struct BakeParams {
  float4 sun;
  float4 grid;
};

Texture2D<float4> heights : register(t0);
RWTexture2D<unorm float4> output : register(u0);
cbuffer params : register(b0) { BakeParams params; }

int2 naga_f2i32(float2 value) {
  return int2(clamp(value, -2147483600.0, 2147483500.0));
}

float height_at(float2 texel)
{
  float4 _e3 = params.grid;
  float2 size = _e3.zw;
  float2 clamped = clamp(texel, (0.0).xx, (size - (1.001).xx));
  float2 base = floor(clamped);
  float2 f = (clamped - base);
  int2 i_1 = naga_f2i32(base);
  float4 _e16 = heights.Load(int3(i_1, int(0)));
  float h00_ = _e16.x;
  float4 _e24 = heights.Load(int3(asint(asuint(i_1) + asuint(int2(int(1), int(0)))), int(0)));
  float h10_ = _e24.x;
  float4 _e32 = heights.Load(int3(asint(asuint(i_1) + asuint(int2(int(0), int(1)))), int(0)));
  float h01_ = _e32.x;
  float4 _e40 = heights.Load(int3(asint(asuint(i_1) + asuint(int2(int(1), int(1)))), int(0)));
  float h11_ = _e40.x;
  return lerp(lerp(h00_, h10_, f.x), lerp(h01_, h11_, f.x), f.y);
}

uint2 NagaRWDimensions2D(RWTexture2D<unorm float4> tex)
{
  uint4 ret;
  tex.GetDimensions(ret.x, ret.y);
  return ret.xy;
}

[numthreads(8, 8, 1)]
void bake(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  float lit_ = 0.0;
  float travelled = 1.0;
  float step_ = 1.0;
  float horizon = -1000000.0;
  int i = int(0);
  bool local_1 = (bool)0;

  uint2 out_size = NagaRWDimensions2D(output);
  if (!((id.x >= out_size.x))) {
    local = (id.y >= out_size.y);
  } else {
    local = true;
  }
  bool _e13 = local;
  if (_e13) {
    return;
  }
  float4 _e16 = params.sun;
  float3 sun = normalize(_e16.xyz);
  if ((sun.y > 0.0)) {
    float _e32 = params.grid.y;
    float2 origin = ((float2(id.xy) + (0.5).xx) * _e32);
    float4 _e36 = params.grid;
    float2 size_1 = _e36.zw;
    const float _e38 = height_at(origin);
    float h0_ = (_e38 + 0.5);
    float flat_length = length(sun.xz);
    float sun_slope = (sun.y / max(flat_length, 0.0001));
    lit_ = 1.0;
    if ((flat_length > 0.001)) {
      float2 direction = (sun.xz / (flat_length).xx);
      float metres = params.grid.x;
      bool loop_init = true;
      [allow_uav_condition] while(true) {
        if (!loop_init) {
          int _e98 = i;
          i = asint(asuint(_e98) + asuint(int(1)));
        }
        loop_init = false;
        int _e65 = i;
        if ((_e65 < int(96))) {
        } else {
          break;
        }
        {
          float _e68 = travelled;
          float2 p = (origin + (direction * _e68));
          if (!(any((p < (0.0).xx)))) {
            local_1 = any((p > (size_1 - (1.0).xx)));
          } else {
            local_1 = true;
          }
          bool _e84 = local_1;
          if (_e84) {
            break;
          }
          float _e85 = horizon;
          const float _e86 = height_at(p);
          float _e88 = travelled;
          horizon = max(_e85, ((_e86 - h0_) / (_e88 * metres)));
          float _e92 = travelled;
          float _e93 = step_;
          travelled = (_e92 + _e93);
          float _e95 = step_;
          step_ = (_e95 * 1.06);
        }
      }
      float _e104 = params.sun.w;
      float penumbra = (0.01 + (_e104 * 0.12));
      float _e110 = horizon;
      lit_ = smoothstep(-(penumbra), penumbra, (sun_slope - _e110));
    }
  }
  float _e116 = lit_;
  float _e117 = lit_;
  float _e118 = lit_;
  output[int2(id.xy)] = float4(_e116, _e117, _e118, 1.0);
  return;
}
