// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: tree_generate (ground + lattice + generate_common + tree_generate)
// Entry point: generate_main, compile with /T cs_5_0 /E generate_main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(1) heights -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(2) surface_texture -> t1  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(3) banks_texture -> t2  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(4) cover_texture -> t3  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(5) bins -> t4  ByteAddressBuffer
//   @group(0) @binding(6) jobs -> t5  ByteAddressBuffer
//   @group(0) @binding(7) trees -> u0  RWByteAddressBuffer
//   @group(0) @binding(8) counts -> u1  RWByteAddressBuffer

struct Job {
  int2 tile;
  uint first;
  uint capacity;
  uint slot;
  float keep;
  uint2 unused;
};

struct Mapping {
  float4 terrain;
  float4 terrain2_;
  float inverse;
  int _end_pad_0;
  int _end_pad_1;
  int _end_pad_2;
};

struct NearChannel {
  float edge;
  uint base;
};

struct TreeParams {
  float4 terrain;
  float4 terrain2_;
  float4 mesh;
  float4 rules;
  uint4 shape;
  float4 max_slopes[2];
  float4 roots[2];
};

struct TreeInstance {
  float3 position;
  float scale;
  float rotation;
  float tint;
  uint species;
  float dryness;
};

typedef uint ret_Constructarray19_uint_[19];
ret_Constructarray19_uint_ Constructarray19_uint_(uint arg0, uint arg1, uint arg2, uint arg3, uint arg4, uint arg5, uint arg6, uint arg7, uint arg8, uint arg9, uint arg10, uint arg11, uint arg12, uint arg13, uint arg14, uint arg15, uint arg16, uint arg17, uint arg18) {
  uint ret[19] = { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18 };
  return ret;
}

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const int CLUMP_CELLS = int(4);
static const uint CLUMP_SALT = 1013904242u;
static const float JITTER = 0.45;
static const float FADE_BAND = 0.05;
static const float MAX_GROWTH = 1.8;
static const uint BIN_WORDS = 11u;
static const float SLOPE_SPAN = 1.5;
static const float BOULDER_PITCH = 2.0;
static const uint BOULDER_SALT = 2135587861u;
static const float BOULDER_WATER_LINE = 0.3;
static const float BOULDER_WATER_CLEARANCE = 1.0;
static const float SIZE_EXPONENT = 1.2;
static const float FOOTPRINT = 0.55;
static const float TALUS_PROBABILITY = 0.6;
static const float STONE_PITCH = 1.0;
static const float STONE_REACH = 1.5;
static const float COBBLE_METRES = 0.5;
static const float TREE_PITCH = 3.0;
static const uint TREE_TRAITS_SALT = 625341585u;
static const uint TREE_SHAPE_SALT = 1540483477u;
static const float LEAN_WATER_METRES = 8.0;
static const uint OLD_SHARE = 70u;
static const float TREE_WATER_LINE = 0.6;
static const float TREE_WATER_CLEARANCE = 1.0;
static const float TRUNK_CLEARANCE = 0.5;
static const uint YOUNG_SHARE = 90u;
static const float RANK_LEVELS = 2047.0;
static const uint VARIANT_SHIFT = 10u;
static const uint AGE_SHIFT = 12u;
static const uint LEAN_SHIFT = 14u;
static const float2 PREVAILING_WIND = float2(0.8, 0.6);
static const uint MATURE = 0u;
static const uint YOUNG = 1u;
static const uint OLD = 2u;
static const uint KRUMMHOLZ = 3u;
static const uint GROUNDED = 256u;
static const uint STUNTED = 512u;
static const uint LATTICE = 1048576u;
static const uint RANK_SHIFT = 21u;
static const uint COVER_STUNTED = 128u;
static const uint SHRUB = 7u;
static const uint ICE_ARCTIC = 18u;
static const uint ALPINE_TRANSITION = 15u;
static const uint RIPARIAN_SALT = 1759714725u;
static const float SCRUB_CHANCE = 0.45;
static const float SCRUB_FROM = 1.0;
static const float SCRUB_DESERT = 2.5;
static const uint SAVANNAH = 8u;
static const uint SCRUB_SPECIES[19] = Constructarray19_uint_(2567u, 2567u, 2311u, 2055u, 3959u, 3959u, 3959u, 0u, 3959u, 2359u, 3959u, 2359u, 2103u, 2391u, 0u, 0u, 0u, 0u, 0u);

Texture2D<float4> heights_4 : register(t0);
Texture2D<float4> surface_texture : register(t1);
Texture2D<float4> banks_texture : register(t2);
Texture2D<float4> cover_texture : register(t3);
ByteAddressBuffer bins : register(t4);
ByteAddressBuffer jobs : register(t5);
cbuffer params : register(b0) { TreeParams params; }
RWByteAddressBuffer trees : register(u0);
RWByteAddressBuffer counts : register(u1);

float density_multiplier(float value)
{
  float byte = round((value * 255.0));
  return ((byte > 128.0) ? (1.0 + ((byte - 128.0) / 127.0)) : (byte / 128.0));
}

float hash12_(float2 p)
{
  float3 p3_ = (float3)0;

  p3_ = frac((float3(p.x, p.y, p.x) * 0.1031));
  float3 _e9 = p3_;
  float3 _e10 = p3_;
  float3 _e11 = p3_;
  p3_ = (_e9 + (dot(_e10, (_e11.yzx + (33.33).xxx))).xxx);
  float _e20 = p3_.x;
  float _e22 = p3_.y;
  float _e25 = p3_.z;
  return frac(((_e20 + _e22) * _e25));
}

float skirt_height(float edge, float sea, float distance_, float noise_)
{
  float foot = min(edge, (sea - 60.0));
  if ((distance_ >= SKIRT_METRES)) {
    return (foot - ((distance_ - SKIRT_METRES) * 0.08));
  }
  float s = smoothstep(0.0, 1.0, (distance_ / SKIRT_METRES));
  return (lerp(edge, foot, s) + (((((edge - foot) * 0.6) * noise_) * s) * (1.0 - s)));
}

float skirt_noise(float2 xz)
{
  float2 p_1 = (xz / (700.0).xx);
  float2 cell_5 = floor(p_1);
  float2 f = (p_1 - cell_5);
  float2 u_3 = ((f * f) * ((3.0).xx - (2.0 * f)));
  const float _e13 = hash12_(cell_5);
  const float _e18 = hash12_((cell_5 + float2(1.0, 0.0)));
  float top = lerp(_e13, _e18, u_3.x);
  const float _e25 = hash12_((cell_5 + float2(0.0, 1.0)));
  const float _e30 = hash12_((cell_5 + float2(1.0, 1.0)));
  float bottom = lerp(_e25, _e30, u_3.x);
  return ((lerp(top, bottom, u_3.y) * 2.0) - 1.0);
}

int2 naga_f2i32(float2 value) {
  return int2(clamp(value, -2147483600.0, 2147483500.0));
}

float texel_height(Texture2D<float4> heights, float4 terrain2_, float2 texel)
{
  float2 clamped = clamp(texel, (0.0).xx, (terrain2_.xy - (1.001).xx));
  float2 base_1 = floor(clamped);
  float2 f_1 = (clamped - base_1);
  int2 i = naga_f2i32(base_1);
  float4 _e14 = heights.Load(int3(i, int(0)));
  float h00_ = _e14.x;
  float4 _e21 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(1), int(0)))), int(0)));
  float h10_ = _e21.x;
  float4 _e28 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(0), int(1)))), int(0)));
  float h01_ = _e28.x;
  float4 _e35 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(1), int(1)))), int(0)));
  float h11_ = _e35.x;
  return lerp(lerp(h00_, h10_, f_1.x), lerp(h01_, h11_, f_1.x), f_1.y);
}

float ground_height(Texture2D<float4> heights_1, float4 terrain, float4 terrain2_1, float2 xz_1)
{
  if ((terrain2_1.z < 0.5)) {
    return -100000.0;
  }
  const float _e12 = texel_height(heights_1, terrain2_1, ((xz_1 + terrain.xy) / terrain.zw));
  float outside = length(max((abs(xz_1) - terrain.xy), (0.0).xx));
  if ((outside <= 0.0)) {
    return _e12;
  }
  const float _e23 = skirt_noise(xz_1);
  const float _e24 = skirt_height(_e12, terrain2_1.w, outside, _e23);
  return _e24;
}

float band_offset(float grid)
{
  float g = abs(grid);
  float band_1 = floor((g / LOD_BAND_WIDTH));
  float step_ = exp2(band_1);
  return (sign(grid) * ((LOD_BAND_WIDTH * (step_ - 1.0)) + ((g - (LOD_BAND_WIDTH * band_1)) * step_)));
}

float band_grid(float offset)
{
  float band = (float)0;

  band = floor(log2(((offset / LOD_BAND_WIDTH) + 1.0)));
  float _e8 = band;
  float _e10 = band;
  band = (_e8 - ((offset < (LOD_BAND_WIDTH * (exp2(_e10) - 1.0))) ? 1.0 : 0.0));
  float _e20 = band;
  float _e22 = band;
  band = (_e20 + ((offset >= (LOD_BAND_WIDTH * (exp2((_e22 + 1.0)) - 1.0))) ? 1.0 : 0.0));
  float _e34 = band;
  float step_1 = exp2(_e34);
  float _e37 = band;
  return ((LOD_BAND_WIDTH * _e37) + floor(((offset - (LOD_BAND_WIDTH * (step_1 - 1.0))) / step_1)));
}

float2 mesh_cell(float sample_, float centre, float last, float reach)
{
  float grid_1 = (float)0;
  bool local_10 = (bool)0;
  bool local_11 = (bool)0;
  bool local_12 = (bool)0;
  bool local_13 = (bool)0;
  bool local_14 = (bool)0;
  bool local_15 = (bool)0;

  float offset_1 = (sample_ - centre);
  const float _e6 = band_grid(abs(offset_1));
  grid_1 = _e6;
  if ((offset_1 < 0.0)) {
    float _e10 = grid_1;
    grid_1 = (-(_e10) - 1.0);
  }
  float _e14 = grid_1;
  const float _e15 = band_offset(_e14);
  float low = clamp((centre + _e15), -(reach), (last + reach));
  float _e20 = grid_1;
  const float _e23 = band_offset((_e20 + 1.0));
  float high = clamp((centre + _e23), -(reach), (last + reach));
  if ((high > last)) {
    local_10 = (sample_ == low);
  } else {
    local_10 = false;
  }
  bool _e33 = local_10;
  if (_e33) {
    local_11 = (low == last);
  } else {
    local_11 = false;
  }
  bool _e38 = local_11;
  if (_e38) {
    local_12 = (last > 0.0);
  } else {
    local_12 = false;
  }
  bool _e44 = local_12;
  if (_e44) {
    float _e45 = grid_1;
    const float _e48 = band_offset((_e45 - 1.0));
    return float2(clamp((centre + _e48), -(reach), (last + reach)), low);
  }
  if ((low < 0.0)) {
    local_13 = (sample_ == high);
  } else {
    local_13 = false;
  }
  bool _e60 = local_13;
  if (_e60) {
    local_14 = (high == 0.0);
  } else {
    local_14 = false;
  }
  bool _e66 = local_14;
  if (_e66) {
    local_15 = (last > 0.0);
  } else {
    local_15 = false;
  }
  bool _e72 = local_15;
  if (_e72) {
    float _e73 = grid_1;
    const float _e76 = band_offset((_e73 + 2.0));
    return float2(high, clamp((centre + _e76), -(reach), (last + reach)));
  }
  return float2(low, high);
}

typedef float2 ret_Constructarray3_float2_[3];
ret_Constructarray3_float2_ Constructarray3_float2_(float2 arg0, float2 arg1, float2 arg2) {
  float2 ret[3] = { arg0, arg1, arg2 };
  return ret;
}

typedef float ret_Constructarray3_float_[3];
ret_Constructarray3_float_ Constructarray3_float_(float arg0, float arg1, float arg2) {
  float ret[3] = { arg0, arg1, arg2 };
  return ret;
}

float mesh_height(Texture2D<float4> heights_2, float4 terrain_1, float4 terrain2_2, float4 mesh, float2 xz_2)
{
  bool local_16 = (bool)0;
  bool local_17 = (bool)0;
  bool local_18 = (bool)0;
  bool local_19 = (bool)0;
  bool local_20 = (bool)0;
  bool local_21 = (bool)0;
  bool local_22 = (bool)0;
  float2 t = (float2)0;
  float2 corners[3] = (float2[3])0;
  float h[3] = Constructarray3_float_(0.0, 0.0, 0.0);
  int k = int(0);
  bool local_23 = (bool)0;
  bool local_24 = (bool)0;
  bool local_25 = (bool)0;

  if ((mesh.z > 0.0)) {
    local_16 = (terrain2_2.z > 0.5);
  } else {
    local_16 = false;
  }
  bool drawn = local_16;
  float metres = (drawn ? mesh.z : max(terrain_1.z, 0.001));
  float2 last_1 = round(((terrain_1.xy * 2.0) / (metres).xx));
  float2 sample_1 = ((xz_2 / (metres).xx) + (last_1 * 0.5));
  const float2 _e35 = mesh_cell(sample_1.x, mesh.x, last_1.x, mesh.w);
  const float2 _e40 = mesh_cell(sample_1.y, mesh.y, last_1.y, mesh.w);
  if (drawn) {
    local_17 = (_e35.x < _e35.y);
  } else {
    local_17 = false;
  }
  bool _e47 = local_17;
  if (_e47) {
    local_18 = (_e40.x < _e40.y);
  } else {
    local_18 = false;
  }
  bool _e54 = local_18;
  if (_e54) {
    local_19 = (sample_1.x >= _e35.x);
  } else {
    local_19 = false;
  }
  bool _e61 = local_19;
  if (_e61) {
    local_20 = (sample_1.x <= _e35.y);
  } else {
    local_20 = false;
  }
  bool _e68 = local_20;
  if (_e68) {
    local_21 = (sample_1.y >= _e40.x);
  } else {
    local_21 = false;
  }
  bool _e75 = local_21;
  if (_e75) {
    local_22 = (sample_1.y <= _e40.y);
  } else {
    local_22 = false;
  }
  bool inside = local_22;
  t = ((sample_1 - float2(_e35.x, _e40.x)) / max(float2((_e35.y - _e35.x), (_e40.y - _e40.x)), (1.0).xx));
  float2 _e101 = t;
  t = (inside ? _e101 : (0.0).xx);
  float _e104 = t.x;
  float _e106 = t.y;
  bool upper = ((_e104 + _e106) > 1.0);
  corners = Constructarray3_float2_(float2(_e35.x, _e40.y), float2(_e35.y, _e40.x), (upper ? float2(_e35.y, _e40.y) : float2(_e35.x, _e40.x)));
  float stride = (terrain_1.z / metres);
  uint2 loop_bound = uint2(4294967295u, 4294967295u);
  bool loop_init = true;
  while(true) {
    if (all(loop_bound == uint2(0u, 0u))) { break; }
    loop_bound -= uint2(loop_bound.y == 0u, 1u);
    if (!loop_init) {
      int _e180 = k;
      k = asint(asuint(_e180) + asuint(int(1)));
    }
    loop_init = false;
    int _e134 = k;
    if ((_e134 < int(3))) {
    } else {
      break;
    }
    {
      int _e137 = k;
      float2 _e139 = corners[min(uint(_e137), 2u)];
      float2 corner = (inside ? _e139 : sample_1);
      if (inside) {
        local_23 = all((corner >= (0.0).xx));
      } else {
        local_23 = false;
      }
      bool _e148 = local_23;
      if (_e148) {
        local_24 = all((corner <= last_1));
      } else {
        local_24 = false;
      }
      bool on_map_1 = local_24;
      if (on_map_1) {
        local_25 = (stride < 1.5);
      } else {
        local_25 = false;
      }
      bool _e160 = local_25;
      if (_e160) {
        int _e161 = k;
        float4 _e166 = heights_2.Load(int3(naga_f2i32(round(corner)), int(0)));
        h[min(uint(_e161), 2u)] = _e166.x;
      } else {
        if (on_map_1) {
          int _e168 = k;
          const float _e172 = texel_height(heights_2, terrain2_2, (corner / (stride).xx));
          h[min(uint(_e168), 2u)] = _e172;
        } else {
          int _e173 = k;
          const float _e179 = ground_height(heights_2, terrain_1, terrain2_2, ((corner - (last_1 * 0.5)) * metres));
          h[min(uint(_e173), 2u)] = _e179;
        }
      }
    }
  }
  float bottom_left = h[0];
  float top_right = h[1];
  if (!(upper)) {
    float top_left = h[2];
    float _e192 = t.x;
    float _e197 = t.y;
    return ((top_left + ((top_right - top_left) * _e192)) + ((bottom_left - top_left) * _e197));
  }
  float bottom_right = h[2];
  float _e204 = t.x;
  float _e211 = t.y;
  return ((bottom_right + ((bottom_left - bottom_right) * (1.0 - _e204))) + ((top_right - bottom_right) * (1.0 - _e211)));
}

float grounded_base(Texture2D<float4> heights_3, float4 terrain_2, float4 terrain2_3, float4 mesh_1, float2 xz_3, float root)
{
  float lowest = 1e30;
  int point_ = int(0);
  bool local_26 = (bool)0;

  int points = ((root <= 0.0) ? int(1) : int(5));
  uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
  bool loop_init_1 = true;
  while(true) {
    if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
    loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
    if (!loop_init_1) {
      int _e43 = point_;
      point_ = asint(asuint(_e43) + asuint(int(1)));
    }
    loop_init_1 = false;
    int _e15 = point_;
    if ((_e15 < points)) {
    } else {
      break;
    }
    {
      int _e17 = point_;
      float angle = (float(_e17) * 1.5707964);
      int _e27 = point_;
      if (!((_e27 == int(4)))) {
        local_26 = (points == int(1));
      } else {
        local_26 = true;
      }
      bool _e36 = local_26;
      float2 out_ = (_e36 ? (0.0).xx : round(float2(cos(angle), sin(angle))));
      float _e38 = lowest;
      const float _e41 = mesh_height(heights_3, terrain_2, terrain2_3, mesh_1, (xz_3 + (out_ * root)));
      lowest = min(_e38, _e41);
    }
  }
  float _e46 = lowest;
  return (_e46 - (0.05 * root));
}

uint3 pcg3d(uint3 input)
{
  uint3 v = (uint3)0;

  v = input;
  uint3 _e2 = v;
  v = ((_e2 * 1664525u) + (1013904223u).xxx);
  uint _e9 = v.x;
  uint _e11 = v.y;
  uint _e13 = v.z;
  v.x = (_e9 + (_e11 * _e13));
  uint _e17 = v.y;
  uint _e19 = v.z;
  uint _e21 = v.x;
  v.y = (_e17 + (_e19 * _e21));
  uint _e25 = v.z;
  uint _e27 = v.x;
  uint _e29 = v.y;
  v.z = (_e25 + (_e27 * _e29));
  uint3 _e32 = v;
  uint3 _e33 = v;
  v = (_e32 ^ (_e33 >> (16u).xxx));
  uint _e39 = v.x;
  uint _e41 = v.y;
  uint _e43 = v.z;
  v.x = (_e39 + (_e41 * _e43));
  uint _e47 = v.y;
  uint _e49 = v.z;
  uint _e51 = v.x;
  v.y = (_e47 + (_e49 * _e51));
  uint _e55 = v.z;
  uint _e57 = v.x;
  uint _e59 = v.y;
  v.z = (_e55 + (_e57 * _e59));
  uint3 _e62 = v;
  return _e62;
}

float unit(uint word)
{
  return (float((word >> 8u)) * 5.9604645e-8);
}

int naga_div(int lhs, int rhs) {
  return lhs / (((lhs == int(-2147483647 - 1) & rhs == -1) | (rhs == 0)) ? 1 : rhs);
}

int naga_mod(int lhs, int rhs) {
  int divisor = ((lhs == int(-2147483647 - 1) & rhs == -1) | (rhs == 0)) ? 1 : rhs;
  return lhs - (lhs / divisor) * divisor;
}

int floor_div(int a, int n)
{
  return asint(asuint(naga_div(a, n)) - asuint(((naga_mod(a, n) < int(0)) ? int(1) : int(0))));
}

int fourth_power(int value_1)
{
  return asint(asuint(asint(asuint(asint(asuint(value_1) * asuint(value_1))) * asuint(value_1))) * asuint(value_1));
}

float clump(int2 cell, uint seed)
{
  const int _e4 = floor_div(cell.x, CLUMP_CELLS);
  const int _e6 = floor_div(cell.y, CLUMP_CELLS);
  int2 c = int2(_e4, _e6);
  int2 f_2 = asint(asuint(cell) - asuint(asint(asuint(c) * asuint(CLUMP_CELLS))));
  uint s_1 = (seed ^ CLUMP_SALT);
  const uint3 _e14 = pcg3d(uint3(asuint(c), s_1));
  const int _e19 = fourth_power(int((_e14.x >> 28u)));
  const uint3 _e26 = pcg3d(uint3(asuint(asint(asuint(c) + asuint(int2(int(1), int(0))))), s_1));
  const int _e31 = fourth_power(int((_e26.x >> 28u)));
  const uint3 _e38 = pcg3d(uint3(asuint(asint(asuint(c) + asuint(int2(int(0), int(1))))), s_1));
  const int _e43 = fourth_power(int((_e38.x >> 28u)));
  const uint3 _e50 = pcg3d(uint3(asuint(asint(asuint(c) + asuint(int2(int(1), int(1))))), s_1));
  const int _e55 = fourth_power(int((_e50.x >> 28u)));
  int sum = asint(asuint(asint(asuint(asint(asuint(asint(asuint(asint(asuint(_e19) * asuint(asint(asuint(CLUMP_CELLS) - asuint(f_2.x))))) * asuint(asint(asuint(CLUMP_CELLS) - asuint(f_2.y))))) + asuint(asint(asuint(asint(asuint(_e31) * asuint(f_2.x))) * asuint(asint(asuint(CLUMP_CELLS) - asuint(f_2.y))))))) + asuint(asint(asuint(asint(asuint(_e43) * asuint(asint(asuint(CLUMP_CELLS) - asuint(f_2.x))))) * asuint(f_2.y))))) + asuint(asint(asuint(asint(asuint(_e55) * asuint(f_2.x))) * asuint(f_2.y))));
  return (float(sum) * 5.6028366e-6);
}

float2 jittered(int2 cell_1, uint3 hash, float pitch)
{
  const float _e4 = unit(hash.x);
  const float _e6 = unit(hash.y);
  float2 jitter = ((float2(_e4, _e6) - (0.5).xx) * 0.9);
  return (((float2(cell_1) + (0.5).xx) + jitter) * pitch);
}

float4 thinning(float distance_1, float radius, float floor_)
{
  float share = (float)0;

  float ratio = (radius / max(distance_1, 0.001));
  float keep = clamp((ratio * ratio), floor_, 1.0);
  float band_2 = min(FADE_BAND, (keep - floor_));
  float end = min((keep + band_2), 1.0);
  share = keep;
  if ((band_2 > 0.0)) {
    float cut = (((keep + band_2) - end) / band_2);
    share = (keep + ((band_2 / 3.0) * (1.0 - ((cut * cut) * cut))));
  }
  float _e29 = share;
  float growth = sqrt((1.0 / max(_e29, 0.001)));
  float height = min(growth, MAX_GROWTH);
  return float4(keep, band_2, height, (growth / height));
}

float thinning_fade(float4 t_1, float u)
{
  if ((u < t_1.x)) {
    return 1.0;
  }
  if ((t_1.y > 0.0)) {
    return clamp((((t_1.x + t_1.y) - u) / t_1.y), 0.0, 1.0);
  }
  return 0.0;
}

int tile_first(int tile, int size, int pitch_1)
{
  int a_1 = asint(asuint(tile) * asuint(size));
  return asint(asuint(naga_div(a_1, pitch_1)) + asuint(((naga_mod(a_1, pitch_1) > int(0)) ? int(1) : int(0))));
}

bool on_map(Mapping m, float2 xz_4)
{
  return all((abs(xz_4) <= m.terrain.xy));
}

float2 texel_position(Mapping m_1, float2 xz_5)
{
  return ((xz_5 + m_1.terrain.xy) * m_1.inverse);
}

int2 nearest(Mapping m_2, float2 xz_6)
{
  const float2 _e2 = texel_position(m_2, xz_6);
  float2 t_5 = floor((_e2 + (0.5).xx));
  return clamp(naga_f2i32(t_5), (int(0)).xx, asint(asuint(naga_f2i32(m_2.terrain2_.xy)) - asuint((int(1)).xx)));
}

uint4 naga_f2u32(float4 value) {
  return uint4(clamp(value, 0.0, 4294967000.0));
}

uint4 bytes_at(Texture2D<float4> t_2, int2 texel_1)
{
  float4 _e3 = t_2.Load(int3(texel_1, int(0)));
  return naga_f2u32(round((_e3 * 255.0)));
}

float height_at(Mapping m_3, float2 xz_7)
{
  const float2 _e4 = texel_position(m_3, xz_7);
  const float _e5 = texel_height(heights_4, m_3.terrain2_, _e4);
  return _e5;
}

float water_distance(Mapping m_4, float2 xz_8)
{
  const float2 _e2 = texel_position(m_4, xz_8);
  float2 t_6 = clamp(_e2, (0.0).xx, (m_4.terrain2_.xy - (1.001).xx));
  float2 base_2 = floor(t_6);
  float2 f_3 = (t_6 - base_2);
  int2 i_1 = naga_f2i32(base_2);
  float4 _e16 = banks_texture.Load(int3(i_1, int(0)));
  float d00_ = _e16.x;
  float4 _e24 = banks_texture.Load(int3(asint(asuint(i_1) + asuint(int2(int(1), int(0)))), int(0)));
  float d10_ = _e24.x;
  float4 _e32 = banks_texture.Load(int3(asint(asuint(i_1) + asuint(int2(int(0), int(1)))), int(0)));
  float d01_ = _e32.x;
  float4 _e40 = banks_texture.Load(int3(asint(asuint(i_1) + asuint(int2(int(1), int(1)))), int(0)));
  float d11_ = _e40.x;
  return (lerp(lerp(d00_, d10_, f_3.x), lerp(d01_, d11_, f_3.x), f_3.y) * 40.0);
}

bool in_water(Mapping m_5, float2 xz_9, float clearance)
{
  const float _e3 = water_distance(m_5, xz_9);
  return (_e3 < ((0.25 * m_5.terrain.z) + clearance));
}

float slope_degrees(Mapping m_6, float2 xz_10)
{
  const float _e6 = height_at(m_6, (xz_10 + float2(1.5, 0.0)));
  const float _e11 = height_at(m_6, (xz_10 - float2(1.5, 0.0)));
  float dx_1 = (_e6 - _e11);
  const float _e17 = height_at(m_6, (xz_10 + float2(0.0, 1.5)));
  const float _e22 = height_at(m_6, (xz_10 - float2(0.0, 1.5)));
  float dz_1 = (_e17 - _e22);
  return degrees(atan((length(float2(dx_1, dz_1)) / 3.0)));
}

float bin_float(uint index)
{
  uint _e3 = asuint(bins.Load(index*4));
  return asfloat(_e3);
}

float intrusion(uint base, float2 xz_11, float clearance_1)
{
  float t_3 = 0.0;

  const float _e3 = bin_float(base);
  const float _e6 = bin_float((base + 1u));
  float2 a_2 = float2(_e3, _e6);
  const float _e10 = bin_float((base + 2u));
  const float _e13 = bin_float((base + 3u));
  float2 b = float2(_e10, _e13);
  float2 d = (b - a_2);
  float length_squared = ((d.x * d.x) + (d.y * d.y));
  if ((length_squared > 0.0)) {
    t_3 = clamp(((((xz_11.x - a_2.x) * d.x) + ((xz_11.y - a_2.y) * d.y)) / length_squared), 0.0, 1.0);
  }
  float _e42 = t_3;
  float2 p_2 = ((a_2 + (d * _e42)) - xz_11);
  const float _e48 = bin_float((base + 4u));
  const float _e51 = bin_float((base + 5u));
  const float _e54 = bin_float((base + 4u));
  float _e56 = t_3;
  float half_ = (_e48 + ((_e51 - _e54) * _e56));
  const float _e61 = bin_float((base + 6u));
  return ((half_ + (_e61 * clearance_1)) - sqrt(((p_2.x * p_2.x) + (p_2.y * p_2.y))));
}

bool in_channel(float2 xz_12, float clearance_2)
{
  int row = (int)0;
  uint item = (uint)0;

  const float _e3 = bin_float(0u);
  const float _e5 = bin_float(1u);
  float2 origin = float2(_e3, _e5);
  const float _e8 = bin_float(2u);
  uint _e11 = asuint(bins.Load(12));
  int columns = int(_e11);
  uint _e15 = asuint(bins.Load(16));
  int rows = int(_e15);
  uint first_item = ((5u + uint(asint(asuint(columns) * asuint(rows)))) + 1u);
  int2 c_1 = naga_f2i32(floor(((xz_12 - origin) / (_e8).xx)));
  int x0_ = max(asint(asuint(c_1.x) - asuint(int(1))), int(0));
  int x1_ = min(asint(asuint(c_1.x) + asuint(int(1))), asint(asuint(columns) - asuint(int(1))));
  if ((x0_ > x1_)) {
    return false;
  }
  row = max(asint(asuint(c_1.y) - asuint(int(1))), int(0));
  uint2 loop_bound_2 = uint2(4294967295u, 4294967295u);
  bool loop_init_2 = true;
  while(true) {
    if (all(loop_bound_2 == uint2(0u, 0u))) { break; }
    loop_bound_2 -= uint2(loop_bound_2.y == 0u, 1u);
    if (!loop_init_2) {
      int _e87 = row;
      row = asint(asuint(_e87) + asuint(int(1)));
    }
    loop_init_2 = false;
    int _e47 = row;
    if ((_e47 <= min(asint(asuint(c_1.y) + asuint(int(1))), asint(asuint(rows) - asuint(int(1)))))) {
    } else {
      break;
    }
    {
      int _e56 = row;
      uint first = asuint(bins.Load(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e56) * asuint(columns))))) + asuint(x0_))*4));
      int _e64 = row;
      uint last_2 = asuint(bins.Load(asint(asuint(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e64) * asuint(columns))))) + asuint(x1_))) + asuint(int(1)))*4));
      item = first;
      uint2 loop_bound_3 = uint2(4294967295u, 4294967295u);
      bool loop_init_3 = true;
      while(true) {
        if (all(loop_bound_3 == uint2(0u, 0u))) { break; }
        loop_bound_3 -= uint2(loop_bound_3.y == 0u, 1u);
        if (!loop_init_3) {
          uint _e84 = item;
          item = (_e84 + 1u);
        }
        loop_init_3 = false;
        uint _e74 = item;
        if ((_e74 < last_2)) {
        } else {
          break;
        }
        {
          uint _e76 = item;
          const float _e80 = intrusion((first_item + (_e76 * BIN_WORDS)), xz_12, clearance_2);
          if ((_e80 > 0.0)) {
            return true;
          }
        }
      }
    }
  }
  return false;
}

NearChannel ConstructNearChannel(float arg0, uint arg1) {
  NearChannel ret = (NearChannel)0;
  ret.edge = arg0;
  ret.base = arg1;
  return ret;
}

NearChannel near_channel(float2 xz_13, float reach_1)
{
  NearChannel best = (NearChannel)0;
  int row_1 = (int)0;
  uint item_1 = (uint)0;
  bool local_27 = (bool)0;

  const float _e3 = bin_float(0u);
  const float _e5 = bin_float(1u);
  float2 origin_1 = float2(_e3, _e5);
  const float _e8 = bin_float(2u);
  uint _e11 = asuint(bins.Load(12));
  int columns_1 = int(_e11);
  uint _e15 = asuint(bins.Load(16));
  int rows_1 = int(_e15);
  uint first_item_1 = ((5u + uint(asint(asuint(columns_1) * asuint(rows_1)))) + 1u);
  int2 c_2 = naga_f2i32(floor(((xz_13 - origin_1) / (_e8).xx)));
  int x0_1 = max(asint(asuint(c_2.x) - asuint(int(1))), int(0));
  int x1_1 = min(asint(asuint(c_2.x) + asuint(int(1))), asint(asuint(columns_1) - asuint(int(1))));
  best = ConstructNearChannel((reach_1 + 1.0), 0u);
  if ((x0_1 > x1_1)) {
    NearChannel _e45 = best;
    const NearChannel nearchannel = _e45;
    return nearchannel;
  }
  row_1 = max(asint(asuint(c_2.y) - asuint(int(1))), int(0));
  uint2 loop_bound_4 = uint2(4294967295u, 4294967295u);
  bool loop_init_4 = true;
  while(true) {
    if (all(loop_bound_4 == uint2(0u, 0u))) { break; }
    loop_bound_4 -= uint2(loop_bound_4.y == 0u, 1u);
    if (!loop_init_4) {
      int _e100 = row_1;
      row_1 = asint(asuint(_e100) + asuint(int(1)));
    }
    loop_init_4 = false;
    int _e52 = row_1;
    if ((_e52 <= min(asint(asuint(c_2.y) + asuint(int(1))), asint(asuint(rows_1) - asuint(int(1)))))) {
    } else {
      break;
    }
    {
      int _e61 = row_1;
      uint first_1 = asuint(bins.Load(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e61) * asuint(columns_1))))) + asuint(x0_1))*4));
      int _e69 = row_1;
      uint last_3 = asuint(bins.Load(asint(asuint(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e69) * asuint(columns_1))))) + asuint(x1_1))) + asuint(int(1)))*4));
      item_1 = first_1;
      uint2 loop_bound_5 = uint2(4294967295u, 4294967295u);
      bool loop_init_5 = true;
      while(true) {
        if (all(loop_bound_5 == uint2(0u, 0u))) { break; }
        loop_bound_5 -= uint2(loop_bound_5.y == 0u, 1u);
        if (!loop_init_5) {
          uint _e97 = item_1;
          item_1 = (_e97 + 1u);
        }
        loop_init_5 = false;
        uint _e79 = item_1;
        if ((_e79 < last_3)) {
        } else {
          break;
        }
        {
          uint _e81 = item_1;
          uint base_3 = (first_item_1 + (_e81 * BIN_WORDS));
          const float _e86 = intrusion(base_3, xz_13, 0.0);
          float edge_1 = -(_e86);
          if ((edge_1 <= reach_1)) {
            float _e92 = best.edge;
            local_27 = (edge_1 < _e92);
          } else {
            local_27 = false;
          }
          bool _e95 = local_27;
          if (_e95) {
            best = ConstructNearChannel(edge_1, base_3);
          }
        }
      }
    }
  }
  NearChannel _e103 = best;
  const NearChannel nearchannel_1 = _e103;
  return nearchannel_1;
}

float boulder_size(float u_1, float position)
{
  float size_1 = (0.3 * pow((1.0 - (u_1 * (1.0 - 0.063095726))), -0.8333333));
  return clamp((size_1 * (0.75 + (0.6 * position))), 0.3, 3.0);
}

float4 boulder_candidate(Mapping m_7, int2 cell_2, uint seed_1)
{
  bool local_28 = (bool)0;
  bool local_29 = (bool)0;
  bool local_30 = (bool)0;

  const uint3 _e5 = pcg3d(uint3(asuint(cell_2), seed_1));
  const float2 _e7 = jittered(cell_2, _e5, BOULDER_PITCH);
  const bool _e8 = on_map(m_7, _e7);
  if (!(_e8)) {
    return float4(0.0, 0.0, -1.0, 0.0);
  }
  const int2 _e16 = nearest(m_7, _e7);
  const uint4 _e17 = bytes_at(banks_texture, _e16);
  uint talus = _e17.w;
  float p_3 = ((float((talus >> 4u)) / 15.0) * TALUS_PROBABILITY);
  const float _e27 = unit(_e5.z);
  if (!((_e27 >= p_3))) {
    const float _e32 = height_at(m_7, _e7);
    local_28 = (_e32 <= (m_7.terrain2_.w + BOULDER_WATER_LINE));
  } else {
    local_28 = true;
  }
  bool _e39 = local_28;
  if (!(_e39)) {
    const bool _e44 = in_water(m_7, _e7, BOULDER_WATER_CLEARANCE);
    local_29 = _e44;
  } else {
    local_29 = true;
  }
  bool _e46 = local_29;
  if (!(_e46)) {
    const bool _e51 = in_channel(_e7, 1.0);
    local_30 = _e51;
  } else {
    local_30 = true;
  }
  bool _e53 = local_30;
  if (_e53) {
    return float4(0.0, 0.0, -1.0, 0.0);
  }
  const uint3 _e63 = pcg3d(uint3(asuint(cell_2), (seed_1 ^ 625341585u)));
  const float _e65 = unit(_e63.x);
  const float _e71 = boulder_size(_e65, (float((talus & 15u)) / 15.0));
  return float4(_e7, _e71, (_e27 / p_3));
}

float stone_size(float u_2, float median)
{
  return clamp(((0.71 * median) / sqrt((1.0 - (u_2 * 0.944)))), 0.05, 3.0);
}

float4 stone_candidate(int2 cell_3, uint seed_2)
{
  float chance = (float)0;
  float scale_1 = 1.0;

  const uint3 _e4 = pcg3d(uint3(asuint(cell_3), seed_2));
  const float2 _e6 = jittered(cell_3, _e4, STONE_PITCH);
  const NearChannel _e8 = near_channel(_e6, STONE_REACH);
  if ((_e8.edge > STONE_REACH)) {
    return float4(0.0, 0.0, -1.0, 0.0);
  }
  const float _e20 = bin_float((_e8.base + 8u));
  chance = _e20;
  if ((_e8.edge > COBBLE_METRES)) {
    float _e27 = chance;
    chance = (_e27 / 3.0);
  } else {
    if ((_e8.edge > 0.0)) {
      float _e33 = chance;
      chance = min((1.5 * _e33), 0.5);
      scale_1 = 0.33;
    }
  }
  const float _e40 = unit(_e4.z);
  float _e41 = chance;
  if ((_e40 >= _e41)) {
    return float4(0.0, 0.0, -1.0, 0.0);
  }
  const uint3 _e52 = pcg3d(uint3(asuint(cell_3), (seed_2 ^ 625341585u)));
  const float _e54 = unit(_e52.x);
  const float _e58 = bin_float((_e8.base + 7u));
  const float _e59 = stone_size(_e54, _e58);
  float _e60 = scale_1;
  float _e64 = chance;
  return float4(_e6, max((_e59 * _e60), 0.05), (_e40 / _e64));
}

bool under_boulder(Mapping m_8, float2 xz_14, uint seed_3, float margin)
{
  int dz = int(-1);
  int dx = (int)0;
  bool local_31 = (bool)0;

  int2 c_3 = naga_f2i32(floor((xz_14 / (2.0).xx)));
  uint2 loop_bound_6 = uint2(4294967295u, 4294967295u);
  bool loop_init_6 = true;
  while(true) {
    if (all(loop_bound_6 == uint2(0u, 0u))) { break; }
    loop_bound_6 -= uint2(loop_bound_6.y == 0u, 1u);
    if (!loop_init_6) {
      int _e43 = dz;
      dz = asint(asuint(_e43) + asuint(int(1)));
    }
    loop_init_6 = false;
    int _e11 = dz;
    if ((_e11 <= int(1))) {
    } else {
      break;
    }
    {
      dx = int(-1);
      uint2 loop_bound_7 = uint2(4294967295u, 4294967295u);
      bool loop_init_7 = true;
      while(true) {
        if (all(loop_bound_7 == uint2(0u, 0u))) { break; }
        loop_bound_7 -= uint2(loop_bound_7.y == 0u, 1u);
        if (!loop_init_7) {
          int _e40 = dx;
          dx = asint(asuint(_e40) + asuint(int(1)));
        }
        loop_init_7 = false;
        int _e16 = dx;
        if ((_e16 <= int(1))) {
        } else {
          break;
        }
        {
          int _e19 = dx;
          int _e20 = dz;
          const float4 _e23 = boulder_candidate(m_8, asint(asuint(c_3) + asuint(int2(_e19, _e20))), seed_3);
          if ((_e23.z > 0.0)) {
            local_31 = (length((_e23.xy - xz_14)) < ((_e23.z * FOOTPRINT) + margin));
          } else {
            local_31 = false;
          }
          bool _e38 = local_31;
          if (_e38) {
            return true;
          }
        }
      }
    }
  }
  return false;
}

float2 channel_lean(float2 xz_15)
{
  float best_1 = 64.0;
  float2 towards = (0.0).xx;
  int row_2 = (int)0;
  uint item_2 = (uint)0;
  float t_4 = (float)0;
  bool local_32 = (bool)0;

  const float _e2 = bin_float(0u);
  const float _e4 = bin_float(1u);
  float2 origin_2 = float2(_e2, _e4);
  const float _e7 = bin_float(2u);
  uint _e10 = asuint(bins.Load(12));
  int columns_2 = int(_e10);
  uint _e14 = asuint(bins.Load(16));
  int rows_2 = int(_e14);
  uint first_item_2 = ((5u + uint(asint(asuint(columns_2) * asuint(rows_2)))) + 1u);
  int2 c_4 = naga_f2i32(floor(((xz_15 - origin_2) / (_e7).xx)));
  int x0_2 = max(asint(asuint(c_4.x) - asuint(int(1))), int(0));
  int x1_2 = min(asint(asuint(c_4.x) + asuint(int(1))), asint(asuint(columns_2) - asuint(int(1))));
  if ((x0_2 > x1_2)) {
    float2 _e44 = towards;
    return _e44;
  }
  row_2 = max(asint(asuint(c_4.y) - asuint(int(1))), int(0));
  uint2 loop_bound_8 = uint2(4294967295u, 4294967295u);
  bool loop_init_8 = true;
  while(true) {
    if (all(loop_bound_8 == uint2(0u, 0u))) { break; }
    loop_bound_8 -= uint2(loop_bound_8.y == 0u, 1u);
    if (!loop_init_8) {
      int _e148 = row_2;
      row_2 = asint(asuint(_e148) + asuint(int(1)));
    }
    loop_init_8 = false;
    int _e51 = row_2;
    if ((_e51 <= min(asint(asuint(c_4.y) + asuint(int(1))), asint(asuint(rows_2) - asuint(int(1)))))) {
    } else {
      break;
    }
    {
      int _e60 = row_2;
      uint first_2 = asuint(bins.Load(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e60) * asuint(columns_2))))) + asuint(x0_2))*4));
      int _e68 = row_2;
      uint last_4 = asuint(bins.Load(asint(asuint(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e68) * asuint(columns_2))))) + asuint(x1_2))) + asuint(int(1)))*4));
      item_2 = first_2;
      uint2 loop_bound_9 = uint2(4294967295u, 4294967295u);
      bool loop_init_9 = true;
      while(true) {
        if (all(loop_bound_9 == uint2(0u, 0u))) { break; }
        loop_bound_9 -= uint2(loop_bound_9.y == 0u, 1u);
        if (!loop_init_9) {
          uint _e145 = item_2;
          item_2 = (_e145 + 1u);
        }
        loop_init_9 = false;
        uint _e78 = item_2;
        if ((_e78 < last_4)) {
        } else {
          break;
        }
        {
          uint _e80 = item_2;
          uint base_4 = (first_item_2 + (_e80 * BIN_WORDS));
          const float _e84 = bin_float(base_4);
          const float _e87 = bin_float((base_4 + 1u));
          float2 a_3 = float2(_e84, _e87);
          const float _e91 = bin_float((base_4 + 2u));
          const float _e94 = bin_float((base_4 + 3u));
          float2 d_1 = (float2(_e91, _e94) - a_3);
          float length_squared_1 = ((d_1.x * d_1.x) + (d_1.y * d_1.y));
          t_4 = 0.0;
          if ((length_squared_1 > 0.0)) {
            t_4 = clamp(((((xz_15.x - a_3.x) * d_1.x) + ((xz_15.y - a_3.y) * d_1.y)) / length_squared_1), 0.0, 1.0);
          }
          float _e123 = t_4;
          float2 p_4 = ((a_3 + (d_1 * _e123)) - xz_15);
          float distance_2 = ((p_4.x * p_4.x) + (p_4.y * p_4.y));
          float _e134 = best_1;
          if ((distance_2 < _e134)) {
            local_32 = (distance_2 > 1e-6);
          } else {
            local_32 = false;
          }
          bool _e141 = local_32;
          if (_e141) {
            best_1 = distance_2;
            towards = (p_4 / (sqrt(distance_2)).xx);
          }
        }
      }
    }
  }
  float2 _e151 = towards;
  return _e151;
}

int naga_f2i32(float value) {
  return int(clamp(value, -2147483600.0, 2147483500.0));
}

uint shape_bits(Mapping m_9, uint hash_1, float2 xz_16, bool young_1, bool stunted)
{
  uint age = MATURE;
  bool local_33 = (bool)0;
  float2 lean = (float2)0;
  uint strength = (uint)0;

  const float2 _e5 = channel_lean(xz_16);
  bool by_water = any((_e5 != (0.0).xx));
  if (stunted) {
    age = KRUMMHOLZ;
  } else {
    if (young_1) {
      age = YOUNG;
    } else {
      if ((((hash_1 >> 2u) & 255u) < OLD_SHARE)) {
        local_33 = !(by_water);
      } else {
        local_33 = false;
      }
      bool _e24 = local_33;
      if (_e24) {
        age = OLD;
      }
    }
  }
  const float _e30 = height_at(m_9, (xz_16 + float2(1.5, 0.0)));
  const float _e35 = height_at(m_9, (xz_16 - float2(1.5, 0.0)));
  float dx_2 = (_e30 - _e35);
  const float _e41 = height_at(m_9, (xz_16 + float2(0.0, 1.5)));
  const float _e46 = height_at(m_9, (xz_16 - float2(0.0, 1.5)));
  float dz_2 = (_e41 - _e46);
  float rise = length(float2(dx_2, dz_2));
  float slope = degrees(atan((rise / 3.0)));
  float fall = min(((rise / 3.0) * 10.0), 2.0);
  lean = (((-(float2(dx_2, dz_2)) / (max(rise, 1e-6)).xx) * fall) + float2(0.4, 0.3));
  if (by_water) {
    lean = _e5;
  }
  float _e72 = lean.x;
  float _e74 = lean.y;
  uint sector = uint((naga_f2i32(round((atan2(_e72, _e74) / 0.3926991))) & int(15)));
  uint roll = ((hash_1 >> 10u) & 255u);
  strength = ((((slope >= 12.0) ? 1u : 0u) + ((slope >= 25.0) ? 1u : 0u)) + ((slope >= 35.0) ? 1u : 0u));
  uint _e105 = strength;
  strength = max(_e105, (((roll >= 128u) ? 1u : 0u) + ((roll >= 218u) ? 1u : 0u)));
  if (by_water) {
    uint _e118 = strength;
    strength = max(_e118, 2u);
  }
  uint _e125 = age;
  uint _e129 = strength;
  return ((((hash_1 & 3u) << VARIANT_SHIFT) | (_e125 << AGE_SHIFT)) | ((sector | (min(_e129, 3u) << 4u)) << LEAN_SHIFT));
}

uint naga_div(uint lhs, uint rhs) {
  return lhs / (rhs == 0u ? 1u : rhs);
}

uint naga_mod(uint lhs, uint rhs) {
  return lhs % (rhs == 0u ? 1u : rhs);
}

uint naga_f2u32(float value) {
  return uint(clamp(value, 0.0, 4294967000.0));
}

void riparian_scrub(Mapping m_10, int2 cell_4, Job job)
{
  uint table[19] = SCRUB_SPECIES;
  float outer = (float)0;
  bool local_34 = (bool)0;
  bool local_35 = (bool)0;
  bool local_36 = (bool)0;
  bool local_37 = (bool)0;
  bool local_38 = (bool)0;
  bool local_39 = (bool)0;
  bool local_40 = (bool)0;
  bool local_41 = (bool)0;
  bool local_42 = (bool)0;
  bool local_43 = (bool)0;
  bool local_44 = (bool)0;
  TreeInstance tree_1 = (TreeInstance)0;

  uint _e6 = params.shape.x;
  uint seed_4 = (_e6 ^ RIPARIAN_SALT);
  const uint3 _e11 = pcg3d(uint3(asuint(cell_4), seed_4));
  const float2 _e13 = jittered(cell_4, _e11, TREE_PITCH);
  const bool _e14 = on_map(m_10, _e13);
  if (!(_e14)) {
    return;
  }
  const NearChannel _e17 = near_channel(_e13, 1000000000.0);
  const int2 _e19 = nearest(m_10, _e13);
  const uint4 _e20 = bytes_at(surface_texture, _e19);
  uint mix = table[min(uint(min(_e20.w, 18u)), 18u)];
  const float _e31 = bin_float((_e17.base + 4u));
  const float _e35 = bin_float((_e17.base + 5u));
  outer = (4.0 + (0.5 * (_e31 + _e35)));
  if ((_e20.w == SAVANNAH)) {
    outer = SCRUB_DESERT;
  }
  if (!((mix == 0u))) {
    local_34 = (_e17.edge < SCRUB_FROM);
  } else {
    local_34 = true;
  }
  bool _e55 = local_34;
  if (!(_e55)) {
    float _e60 = outer;
    local_35 = (_e17.edge > _e60);
  } else {
    local_35 = true;
  }
  bool _e63 = local_35;
  if (!(_e63)) {
    local_36 = (_e20.z > 127u);
  } else {
    local_36 = true;
  }
  bool _e71 = local_36;
  if (_e71) {
    return;
  }
  const float _e72 = clump(cell_4, seed_4);
  float gaps = saturate(((_e72 - 0.15) / 0.5));
  const float _e78 = slope_degrees(m_10, _e13);
  float steep = saturate(((45.0 - _e78) / 10.0));
  const float _e88 = bin_float((_e17.base + 10u));
  float chance_1 = (((SCRUB_CHANCE * _e88) * gaps) * steep);
  const float _e93 = unit(_e11.z);
  if (!((chance_1 <= 0.0))) {
    float _e102 = params.rules.w;
    local_37 = (_e93 < (chance_1 * _e102));
  } else {
    local_37 = true;
  }
  bool _e106 = local_37;
  if (!(_e106)) {
    local_38 = (_e93 >= (chance_1 * job.keep));
  } else {
    local_38 = true;
  }
  bool _e114 = local_38;
  if (!(_e114)) {
    const float _e118 = height_at(m_10, _e13);
    float _e122 = params.terrain2_.w;
    local_39 = (_e118 <= (_e122 + TREE_WATER_LINE));
  } else {
    local_39 = true;
  }
  bool _e127 = local_39;
  if (!(_e127)) {
    const float _e131 = water_distance(m_10, _e13);
    local_40 = (_e131 <= 0.0);
  } else {
    local_40 = true;
  }
  bool _e135 = local_40;
  if (!(_e135)) {
    const bool _e140 = in_channel(_e13, 1.0);
    local_41 = _e140;
  } else {
    local_41 = true;
  }
  bool _e142 = local_41;
  if (!(_e142)) {
    uint _e149 = params.shape.w;
    if ((_e149 == 1u)) {
      uint _e157 = params.shape.z;
      const bool _e159 = under_boulder(m_10, _e13, _e157, TRUNK_CLEARANCE);
      local_43 = _e159;
    } else {
      local_43 = false;
    }
    bool _e161 = local_43;
    local_42 = _e161;
  } else {
    local_42 = true;
  }
  bool _e163 = local_42;
  if (_e163) {
    return;
  }
  const uint3 _e168 = pcg3d(uint3(asuint(cell_4), (seed_4 ^ TREE_TRAITS_SALT)));
  if (!((_e20.x < 97u))) {
    const float _e176 = unit(_e168.x);
    local_44 = ((_e176 * 15.0) < float(((mix >> 8u) & 15u)));
  } else {
    local_44 = true;
  }
  bool first_3 = local_44;
  uint species = (first_3 ? (mix & 15u) : ((mix >> 4u) & 15u));
  bool shrub = (species == SHRUB);
  const float _e197 = unit(_e168.y);
  float scale_2 = (shrub ? (1.0 + (1.3 * _e197)) : (0.15 + (0.15 * _e197)));
  const uint3 _e211 = pcg3d(uint3(asuint(cell_4), (seed_4 ^ TREE_SHAPE_SALT)));
  uint shape = _e211.x;
  uint rank_bits = min(naga_f2u32(((_e93 / chance_1) * RANK_LEVELS)), 2046u);
  float4 _e225 = params.terrain;
  float4 _e228 = params.terrain2_;
  float4 _e231 = params.mesh;
  float _e240 = params.roots[naga_div(species, 4u)][naga_mod(species, 4u)];
  const float _e242 = grounded_base(heights_4, _e225, _e228, _e231, _e13, (_e240 * scale_2));
  tree_1.position = float3(_e13.x, _e242, _e13.y);
  tree_1.scale = scale_2;
  tree_1.rotation = (float((_e168.z & 255u)) * 0.024543693);
  const float _e255 = unit(_e168.z);
  tree_1.tint = (0.35 + (0.3 * _e255));
  const uint _e267 = shape_bits(m_10, shape, _e13, !(shrub), false);
  tree_1.species = ((((species | GROUNDED) | LATTICE) | _e267) | (rank_bits << RANK_SHIFT));
  tree_1.dryness = 0.0;
  uint _e278; counts.InterlockedAdd(job.slot*4, 1u, _e278);
  if ((_e278 < job.capacity)) {
    TreeInstance _e285 = tree_1;
    {
      TreeInstance _value3 = _e285;
      trees.Store3((job.first + _e278)*32+0, asuint(_value3.position));
      trees.Store((job.first + _e278)*32+12, asuint(_value3.scale));
      trees.Store((job.first + _e278)*32+16, asuint(_value3.rotation));
      trees.Store((job.first + _e278)*32+20, asuint(_value3.tint));
      trees.Store((job.first + _e278)*32+24, asuint(_value3.species));
      trees.Store((job.first + _e278)*32+28, asuint(_value3.dryness));
    }
    return;
  } else {
    return;
  }
}

float krummholz_rotation(uint hash_2)
{
  return (2.4980917 + (((float(((hash_2 >> 18u) & 255u)) / 255.0) - 0.5) * 0.7));
}

Mapping ConstructMapping(float4 arg0, float4 arg1, float arg2) {
  Mapping ret = (Mapping)0;
  ret.terrain = arg0;
  ret.terrain2_ = arg1;
  ret.inverse = arg2;
  return ret;
}

Job ConstructJob(int2 arg0, uint arg1, uint arg2, uint arg3, float arg4, uint2 arg5) {
  Job ret = (Job)0;
  ret.tile = arg0;
  ret.first = arg1;
  ret.capacity = arg2;
  ret.slot = arg3;
  ret.keep = arg4;
  ret.unused = arg5;
  return ret;
}

[numthreads(8, 8, 1)]
void generate_main(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  bool local_1 = (bool)0;
  bool local_2 = (bool)0;
  bool local_3 = (bool)0;
  bool local_4 = (bool)0;
  bool local_5 = (bool)0;
  bool local_6 = (bool)0;
  float scale = (float)0;
  float tint = (float)0;
  float dryness = (float)0;
  bool young = (bool)0;
  bool local_7 = (bool)0;
  bool local_8 = (bool)0;
  bool local_9 = (bool)0;
  TreeInstance tree = (TreeInstance)0;

  Job job_1 = ConstructJob(asint(jobs.Load2(id.z*32+0)), asuint(jobs.Load(id.z*32+8)), asuint(jobs.Load(id.z*32+12)), asuint(jobs.Load(id.z*32+16)), asfloat(jobs.Load(id.z*32+20)), asuint(jobs.Load2(id.z*32+24)));
  const int _e9 = tile_first(job_1.tile.x, int(64), int(3));
  const int _e14 = tile_first(job_1.tile.y, int(64), int(3));
  int2 first_4 = int2(_e9, _e14);
  const int _e22 = tile_first(asint(asuint(job_1.tile.x) + asuint(int(1))), int(64), int(3));
  const int _e29 = tile_first(asint(asuint(job_1.tile.y) + asuint(int(1))), int(64), int(3));
  int2 next = int2(_e22, _e29);
  int2 cell_6 = asint(asuint(first_4) + asuint(int2(id.xy)));
  if (any((cell_6 >= next))) {
    return;
  }
  float4 _e38 = params.terrain;
  float4 _e41 = params.terrain2_;
  float _e45 = params.rules.x;
  Mapping m_11 = ConstructMapping(_e38, _e41, _e45);
  riparian_scrub(m_11, cell_6, job_1);
  uint seed_5 = params.shape.x;
  const uint3 _e53 = pcg3d(uint3(asuint(cell_6), seed_5));
  const float2 _e55 = jittered(cell_6, _e53, TREE_PITCH);
  const bool _e56 = on_map(m_11, _e55);
  if (!(_e56)) {
    return;
  }
  const int2 _e58 = nearest(m_11, _e55);
  const uint4 _e60 = bytes_at(cover_texture, _e58);
  float red = float(_e60.x);
  float _e67 = params.rules.y;
  const float _e69 = clump(cell_6, seed_5);
  float p_5 = (((red * red) * _e67) * _e69);
  const float _e72 = unit(_e53.z);
  if (!((_e60.x == 0u))) {
    float _e82 = params.rules.w;
    local = (_e72 < (p_5 * _e82));
  } else {
    local = true;
  }
  bool _e86 = local;
  if (!(_e86)) {
    local_1 = (_e72 >= (p_5 * job_1.keep));
  } else {
    local_1 = true;
  }
  bool _e94 = local_1;
  if (_e94) {
    return;
  }
  const uint3 _e99 = pcg3d(uint3(asuint(cell_6), (seed_5 ^ TREE_TRAITS_SALT)));
  const float _e101 = unit(_e99.x);
  bool second = (_e101 < (float((_e60.w & 127u)) / 127.0));
  uint species_1 = min((second ? _e60.z : _e60.y), 7u);
  const float _e114 = height_at(m_11, _e55);
  float _e118 = params.terrain2_.w;
  if (!((_e114 <= (_e118 + TREE_WATER_LINE)))) {
    const bool _e126 = in_water(m_11, _e55, TREE_WATER_CLEARANCE);
    local_2 = _e126;
  } else {
    local_2 = true;
  }
  bool _e128 = local_2;
  if (!(_e128)) {
    const float _e132 = slope_degrees(m_11, _e55);
    float _e141 = params.max_slopes[naga_div(species_1, 4u)][naga_mod(species_1, 4u)];
    local_3 = (_e132 >= _e141);
  } else {
    local_3 = true;
  }
  bool _e144 = local_3;
  if (!(_e144)) {
    const bool _e149 = in_channel(_e55, 1.0);
    local_4 = _e149;
  } else {
    local_4 = true;
  }
  bool _e151 = local_4;
  if (!(_e151)) {
    uint _e158 = params.shape.w;
    if ((_e158 == 1u)) {
      uint _e166 = params.shape.z;
      const bool _e168 = under_boulder(m_11, _e55, _e166, TRUNK_CLEARANCE);
      local_6 = _e168;
    } else {
      local_6 = false;
    }
    bool _e170 = local_6;
    local_5 = _e170;
  } else {
    local_5 = true;
  }
  bool _e172 = local_5;
  if (_e172) {
    return;
  }
  const uint4 _e174 = bytes_at(surface_texture, _e58);
  float temperature = (float(_e174.x) / 255.0);
  float moisture = (float(_e174.y) / 255.0);
  uint biome = _e174.w;
  const float _e185 = unit(_e99.y);
  const float _e187 = unit(_e99.z);
  float variation = params.rules.z;
  float share_1 = ((red * red) * 6.15148e-5);
  float vigour = (0.75 + (0.3 * min((share_1 * 3.0), 1.0)));
  scale = ((1.0 + (((_e185 - 0.5) * 0.55) * max(variation, 0.15))) * vigour);
  tint = (0.5 + ((_e187 - 0.5) * max(variation, 0.1)));
  dryness = clamp((((temperature - 0.45) * 1.5) + ((0.5 - moisture) * 1.5)), 0.0, 1.0);
  young = ((_e99.y & 255u) < YOUNG_SHARE);
  bool _e241 = young;
  if (_e241) {
    scale = (0.45 + (0.35 * _e185));
  }
  uint _e250 = params.shape.y;
  if (((_e72 / p_5) >= asfloat(_e250))) {
    scale = (0.25 + (0.25 * _e185));
    young = true;
  }
  bool shrub_1 = (species_1 == SHRUB);
  bool tundra = (biome == ICE_ARCTIC);
  if (!(shrub_1)) {
    local_7 = ((_e60.w & COVER_STUNTED) != 0u);
  } else {
    local_7 = false;
  }
  bool stunted_1 = local_7;
  if (shrub_1) {
    if (!(tundra)) {
      local_9 = (biome == ALPINE_TRANSITION);
    } else {
      local_9 = true;
    }
    bool _e280 = local_9;
    local_8 = _e280;
  } else {
    local_8 = false;
  }
  bool _e282 = local_8;
  if (_e282) {
    scale = (0.6 + (0.6 * _e185));
    young = true;
    if (tundra) {
      tint = (0.15 + (0.2 * _e187));
      dryness = 0.75;
    }
  } else {
    if (stunted_1) {
      float _e293 = scale;
      scale = (_e293 * 0.7);
    }
  }
  uint rank_bits_1 = min(naga_f2u32(((_e72 / p_5) * RANK_LEVELS)), 2046u);
  float _e310 = params.roots[naga_div(species_1, 4u)][naga_mod(species_1, 4u)];
  float _e311 = scale;
  float root_1 = (_e310 * _e311);
  float4 _e319 = params.terrain;
  float4 _e322 = params.terrain2_;
  float4 _e325 = params.mesh;
  const float _e326 = grounded_base(heights_4, _e319, _e322, _e325, _e55, root_1);
  tree.position = float3(_e55.x, _e326, _e55.y);
  float _e330 = scale;
  tree.scale = _e330;
  const uint3 _e335 = pcg3d(uint3(asuint(cell_6), (seed_5 ^ TREE_SHAPE_SALT)));
  uint shape_1 = _e335.x;
  const float _e344 = krummholz_rotation(shape_1);
  tree.rotation = (stunted_1 ? _e344 : (float((_e99.z & 255u)) * 0.024543693));
  float _e347 = tint;
  tree.tint = _e347;
  bool _e357 = young;
  const uint _e358 = shape_bits(m_11, shape_1, _e55, _e357, stunted_1);
  tree.species = (((((species_1 | GROUNDED) | LATTICE) | (stunted_1 ? STUNTED : 0u)) | _e358) | (rank_bits_1 << RANK_SHIFT));
  float _e364 = dryness;
  tree.dryness = _e364;
  uint _e369; counts.InterlockedAdd(job_1.slot*4, 1u, _e369);
  if ((_e369 < job_1.capacity)) {
    TreeInstance _e376 = tree;
    {
      TreeInstance _value3 = _e376;
      trees.Store3((job_1.first + _e369)*32+0, asuint(_value3.position));
      trees.Store((job_1.first + _e369)*32+12, asuint(_value3.scale));
      trees.Store((job_1.first + _e369)*32+16, asuint(_value3.rotation));
      trees.Store((job_1.first + _e369)*32+20, asuint(_value3.tint));
      trees.Store((job_1.first + _e369)*32+24, asuint(_value3.species));
      trees.Store((job_1.first + _e369)*32+28, asuint(_value3.dryness));
    }
    return;
  } else {
    return;
  }
}
