// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: normals (normals)
// Entry point: main, compile with /T cs_5_0 /E main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(1) normals -> u0  RWByteAddressBuffer

ByteAddressBuffer heights : register(t0);
RWByteAddressBuffer normals : register(u0);

uint NagaBufferLengthRW(RWByteAddressBuffer buffer)
{
  uint ret;
  buffer.GetDimensions(ret);
  return ret;
}

[numthreads(8, 8, 1)]
void main(uint3 id : SV_DispatchThreadID)
{
  uint index = ((id.y * 1024u) + id.x);
  if ((index < ((NagaBufferLengthRW(normals) - 0) / 16))) {
    normals.Store4(index*16, asuint(float4(0.0, 1.0, 0.0, 0.0)));
    return;
  } else {
    return;
  }
}
