// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: water (ground + common + lattice + water)
// Entry point: fragment_fall, compile with /T ps_5_0 /E fragment_fall
// override INLAND = true
// override SEA_ICE = false
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) frame -> b0  constant buffer
//   @group(1) @binding(0) linear_sampler -> s0  SamplerState
//   @group(1) @binding(5) noise_texture -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(6) cloud_texture -> t1  Texture3D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(8) height_texture -> t2  Texture2D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(9) world -> b1  constant buffer
//   @group(1) @binding(10) terrain_shadow_texture -> t3  Texture2D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(11) clamp_sampler -> s1  SamplerState
//   @group(1) @binding(12) ground_layers -> t4  Texture2DArray (Sampled { kind: Float, multi: false })
//   @group(1) @binding(13) regional_texture -> t5  Texture2D (Sampled { kind: Float, multi: false })
//   @group(2) @binding(0) tree_shadow_map -> t6  Texture2D (Depth { multi: false })
//   @group(2) @binding(1) shadow_sampler -> s2  SamplerComparisonState

struct FrameUniforms {
  row_major float4x4 view_proj;
  float4 camera_position;
  float4 camera_forward;
  float4 camera_right;
  float4 camera_up;
  float4 sun_direction;
  float4 atmosphere;
  float4 sky_tint;
  float4 mist_params;
  float4 mist_colour;
  float4 mist_wind;
  float4 cloud_params;
  float4 cloud_motion;
  float4 cloud_colour;
  float4 water_params;
  float4 water_shallow;
  float4 water_deep;
  float4 water_current;
  float4 wave_params;
  float4 wave_params2_;
  float4 water_origin;
  float4 vegetation;
  float4 vegetation2_;
  float4 viewport;
  row_major float4x4 shadow_view_proj;
  float4 shadow_params;
  float4 weather;
  float4 weather2_;
  float4 surface;
  float4 clouds2_;
  float4 clouds3_;
  float4 clouds4_;
  float4 weather3_;
  row_major float4x4 previous_view_proj;
  float4 temporal;
  float4 distances;
  float4 fades;
  float4 output;
  float4 cold;
  float4 sea_ice;
  float4 rivers;
  float4 ground;
  float4 vegetation3_;
  float4 rock;
  float4 regional;
  float4 air;
  float4 light;
  float4 gust;
  float4 weather4_;
  float4 clouds5_;
  float4 alto;
  float4 rivers2_;
  float4 waterside;
  float4 mouths[16];
};

struct WorldInfo {
  float4 species[8];
  float4 species_tint[8];
  float4 terrain;
  float4 terrain2_;
  float4 material_tints[12];
  float4 trees;
  float4 species_canopy[8];
};

struct Fog {
  float3 inscatter;
  float transmittance;
};

struct VertexOut {
  float4 clip_position : SV_Position;
  float3 world_position : LOC0;
  float2 flow : LOC1;
  nointerpolation int kind : LOC2;
  float across : LOC3;
  float spacing : LOC4;
  float2 rest_xz : LOC5;
  float4 extra : LOC6;
  float coverage : LOC7;
  float along : LOC8;
  float swirl : LOC9;
  float into_step : LOC10;
  float2 catchment : LOC11;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const int CLUMP_CELLS = int(4);
static const uint CLUMP_SALT = 1013904242u;
static const float JITTER = 0.45;
static const float FADE_BAND = 0.05;
static const float MAX_GROWTH = 1.8;
static const int KIND_OCEAN = int(0);
static const int KIND_RIVER = int(1);
static const int KIND_LAKE = int(2);
static const int KIND_FALL = int(3);
static const int KIND_SPRAY = int(4);
static const int KIND_POOL = int(5);
static const int WAVE_COUNT = int(8);

cbuffer frame : register(b0) { FrameUniforms frame; }
SamplerState linear_sampler : register(s0);
Texture2D<float4> noise_texture : register(t0);
Texture3D<float4> cloud_texture : register(t1);
Texture2D<float4> height_texture : register(t2);
cbuffer world : register(b1) { WorldInfo world; }
Texture2D<float4> terrain_shadow_texture : register(t3);
SamplerState clamp_sampler : register(s1);
Texture2DArray<float4> ground_layers : register(t4);
Texture2D<float4> regional_texture : register(t5);
Texture2D<float> tree_shadow_map : register(t6);
SamplerComparisonState shadow_sampler : register(s2);

struct FragmentInput_fragment_fall {
  float3 world_position_2 : LOC0;
  float2 flow : LOC1;
  nointerpolation int kind : LOC2;
  float across : LOC3;
  float spacing : LOC4;
  float2 rest_xz : LOC5;
  float4 extra : LOC6;
  float coverage_1 : LOC7;
  float along : LOC8;
  float swirl : LOC9;
  float into_step : LOC10;
  float2 catchment : LOC11;
  float4 clip_position : SV_Position;
};

float hash12_(float2 p)
{
  float3 p3_ = (float3)0;

  p3_ = frac((float3(p.x, p.y, p.x) * 0.1031));
  float3 _e9 = p3_;
  float3 _e10 = p3_;
  float3 _e11 = p3_;
  p3_ = (_e9 + (dot(_e10, (_e11.yzx + (33.33).xxx))).xxx);
  float _e20 = p3_.x;
  float _e22 = p3_.y;
  float _e25 = p3_.z;
  return frac(((_e20 + _e22) * _e25));
}

float skirt_height(float edge, float sea, float distance_, float noise_)
{
  float foot = min(edge, (sea - 60.0));
  if ((distance_ >= SKIRT_METRES)) {
    return (foot - ((distance_ - SKIRT_METRES) * 0.08));
  }
  float s = smoothstep(0.0, 1.0, (distance_ / SKIRT_METRES));
  return (lerp(edge, foot, s) + (((((edge - foot) * 0.6) * noise_) * s) * (1.0 - s)));
}

float skirt_noise(float2 xz)
{
  float2 p_1 = (xz / (700.0).xx);
  float2 cell = floor(p_1);
  float2 f = (p_1 - cell);
  float2 u = ((f * f) * ((3.0).xx - (2.0 * f)));
  const float _e13 = hash12_(cell);
  const float _e18 = hash12_((cell + float2(1.0, 0.0)));
  float top = lerp(_e13, _e18, u.x);
  const float _e25 = hash12_((cell + float2(0.0, 1.0)));
  const float _e30 = hash12_((cell + float2(1.0, 1.0)));
  float bottom = lerp(_e25, _e30, u.x);
  return ((lerp(top, bottom, u.y) * 2.0) - 1.0);
}

int2 naga_f2i32(float2 value) {
  return int2(clamp(value, -2147483600.0, 2147483500.0));
}

float texel_height(Texture2D<float4> heights, float4 terrain2_, float2 texel)
{
  float2 clamped = clamp(texel, (0.0).xx, (terrain2_.xy - (1.001).xx));
  float2 base_1 = floor(clamped);
  float2 f_1 = (clamped - base_1);
  int2 i_1 = naga_f2i32(base_1);
  float4 _e14 = heights.Load(int3(i_1, int(0)));
  float h00_ = _e14.x;
  float4 _e21 = heights.Load(int3(asint(asuint(i_1) + asuint(int2(int(1), int(0)))), int(0)));
  float h10_ = _e21.x;
  float4 _e28 = heights.Load(int3(asint(asuint(i_1) + asuint(int2(int(0), int(1)))), int(0)));
  float h01_ = _e28.x;
  float4 _e35 = heights.Load(int3(asint(asuint(i_1) + asuint(int2(int(1), int(1)))), int(0)));
  float h11_ = _e35.x;
  return lerp(lerp(h00_, h10_, f_1.x), lerp(h01_, h11_, f_1.x), f_1.y);
}

float ground_height(Texture2D<float4> heights_1, float4 terrain, float4 terrain2_1, float2 xz_1)
{
  if ((terrain2_1.z < 0.5)) {
    return -100000.0;
  }
  const float _e12 = texel_height(heights_1, terrain2_1, ((xz_1 + terrain.xy) / terrain.zw));
  float outside = length(max((abs(xz_1) - terrain.xy), (0.0).xx));
  if ((outside <= 0.0)) {
    return _e12;
  }
  const float _e23 = skirt_noise(xz_1);
  const float _e24 = skirt_height(_e12, terrain2_1.w, outside, _e23);
  return _e24;
}

float remap(float value, float old_min, float old_max, float new_min, float new_max)
{
  return (new_min + (((value - old_min) / max((old_max - old_min), 0.0001)) * (new_max - new_min)));
}

float time_seconds()
{
  float _e3 = frame.camera_position.w;
  return _e3;
}

float pixel_dither(float2 pixel)
{
  return frac((52.982918 * frac(dot(pixel, float2(0.06711056, 0.00583715)))));
}

float3 aces(float3 colour_1)
{
  float3 a = (colour_1 * ((colour_1 * 2.51) + (0.03).xxx));
  float3 b = ((colour_1 * ((colour_1 * 2.43) + (0.59).xxx)) + (0.14).xxx);
  return clamp((a / b), (0.0).xxx, (1.0).xxx);
}

float3 finish_colour(float3 linear_)
{
  float3 mapped = (float3)0;

  float _e7 = frame.atmosphere.w;
  const float3 _e9 = aces((max(linear_, (0.0).xxx) * _e7));
  mapped = _e9;
  float _e14 = frame.camera_up.w;
  if ((_e14 > 0.5)) {
    float3 _e17 = mapped;
    mapped = pow(_e17, (0.45454547).xxx);
  }
  float3 _e21 = mapped;
  return _e21;
}

float3 sun_dir()
{
  float4 _e2 = frame.sun_direction;
  return normalize(_e2.xyz);
}

float henyey_greenstein(float cos_theta, float g)
{
  float g2_ = (g * g);
  return ((1.0 - g2_) / (12.566371 * pow(max(((1.0 + g2_) - ((2.0 * g) * cos_theta)), 0.0001), 1.5)));
}

float air_mass(float cos_zenith)
{
  float c = clamp(cos_zenith, -0.2, 1.0);
  float zenith_degrees = degrees(acos(c));
  return (1.0 / max((c + (0.50572 * pow(max((96.07995 - zenith_degrees), 0.05), -1.6364))), 0.02));
}

float3 rayleigh_beta()
{
  float _e4 = frame.atmosphere.x;
  return (RAYLEIGH_BETA * max(_e4, 0.0));
}

float3 mie_beta()
{
  float _e4 = frame.atmosphere.y;
  float4 _e14 = frame.air;
  return ((MIE_BETA * (0.1 + (max(_e4, 0.0) * 0.45))) * _e14.xyz);
}

float3 sun_transmittance(float cos_zenith_1)
{
  const float _e1 = air_mass(cos_zenith_1);
  const float3 _e2 = rayleigh_beta();
  const float3 _e5 = mie_beta();
  float3 transmittance_1 = exp((-(((_e2 * RAYLEIGH_HEIGHT) + (_e5 * MIE_HEIGHT))) * _e1));
  return (transmittance_1 * smoothstep(-0.08, 0.02, cos_zenith_1));
}

float3 sun_light()
{
  const float3 _e0 = sun_dir();
  const float3 _e2 = sun_transmittance(_e0.y);
  float _e6 = frame.sun_direction.w;
  float _e13 = frame.light.x;
  return (((_e2 * _e6) * 2.35) * _e13);
}

float luminance(float3 colour_2)
{
  return dot(colour_2, float3(0.2126, 0.7152, 0.0722));
}

float3 sky_radiance(float3 direction)
{
  float3 sky = (float3)0;

  const float3 _e1 = sun_dir();
  float3 dir = normalize(float3(direction.x, max(direction.y, 0.0), direction.z));
  float mu = dot(dir, _e1);
  const float3 _e10 = rayleigh_beta();
  const float3 _e11 = mie_beta();
  const float _e13 = air_mass(dir.y);
  float3 depth_r = ((_e10 * RAYLEIGH_HEIGHT) * _e13);
  float3 depth_m = ((_e11 * MIE_HEIGHT) * _e13);
  float3 extinction = (depth_r + depth_m);
  float phase_r = (0.0596831 * (1.0 + (mu * mu)));
  float _e29 = frame.air.w;
  const float _e30 = henyey_greenstein(mu, _e29);
  const float3 _e32 = sun_transmittance(_e1.y);
  float3 sun_colour = (sqrt(_e32) * smoothstep(-0.08, 0.02, _e1.y));
  float3 inscatter_1 = ((((depth_r * phase_r) + (depth_m * _e30)) / max(extinction, (1e-6).xxx)) * ((1.0).xxx - exp(-(extinction))));
  float3 fill = (float3(0.004, 0.009, 0.022) * smoothstep(-0.3, 0.2, _e1.y));
  float3 night = float3(0.0012, 0.0018, 0.004);
  float _e71 = frame.sun_direction.w;
  float4 _e77 = frame.sky_tint;
  sky = ((((((inscatter_1 * sun_colour) * SUN_RADIANCE) * _e71) + fill) + night) * _e77.xyz);
  float overcast = frame.weather2_.y;
  if ((overcast > 0.001)) {
    float zenith_mu = _e1.y;
    float _e101 = frame.air.w;
    const float _e102 = henyey_greenstein(zenith_mu, _e101);
    float3 zenith_inscatter = ((((((_e10 * RAYLEIGH_HEIGHT) * 0.0596831) * (1.0 + (zenith_mu * zenith_mu))) + ((_e11 * MIE_HEIGHT) * _e102)) / ((_e10 * RAYLEIGH_HEIGHT) + (_e11 * MIE_HEIGHT))) * ((1.0).xxx - exp(-(((_e10 * RAYLEIGH_HEIGHT) + (_e11 * MIE_HEIGHT))))));
    float _e128 = frame.sun_direction.w;
    float4 _e134 = frame.sky_tint;
    const float _e137 = luminance(((((((zenith_inscatter * sun_colour) * SUN_RADIANCE) * _e128) + fill) + night) * _e134.xyz));
    float deck = ((((_e137 * 2.0) * (1.0 + (2.0 * dir.y))) / 3.0) * (1.0 - (overcast * 0.4)));
    float3 _e153 = sky;
    sky = lerp(_e153, ((deck).xxx * float3(0.92, 0.95, 1.0)), overcast);
  }
  float3 _e161 = sky;
  float _e169 = frame.weather2_.x;
  return (_e161 + ((float3(0.75, 0.8, 1.0) * _e169) * 1.6));
}

float3 sky_irradiance(float3 normal)
{
  const float3 _e5 = sky_radiance(float3(0.0, 1.0, 0.0));
  float towards_sky = saturate(((normal.y * 0.5) + 0.5));
  if ((towards_sky >= 0.9999)) {
    float _e19 = frame.light.z;
    return ((_e5 * 2.4) * _e19);
  }
  const float3 _e21 = sun_dir();
  const float3 _e24 = sun_dir();
  const float3 _e30 = sky_radiance(normalize(float3(-(_e21.x), 0.2, -(_e24.z))));
  float _e35 = frame.light.w;
  float3 sky_1 = lerp(lerp(_e30, _e5, towards_sky), _e5, _e35);
  const float3 _e37 = sun_light();
  float3 bounce = ((_e37 * 0.035) * saturate(((-(normal.y) * 0.5) + 0.5)));
  float _e65 = frame.light.z;
  return ((((sky_1 * (0.55 + (0.45 * saturate(((normal.y * 0.5) + 0.5))))) * 2.4) + bounce) * _e65);
}

float terrain_height_at(float2 xz_2)
{
  float4 _e4 = world.terrain;
  float4 _e7 = world.terrain2_;
  const float _e8 = ground_height(height_texture, _e4, _e7, xz_2);
  return _e8;
}

bool over_terrain(float2 xz_3)
{
  bool local = (bool)0;

  float _e4 = world.terrain2_.z;
  if ((_e4 > 0.5)) {
    float4 _e12 = world.terrain;
    local = all((abs(xz_3) <= _e12.xy));
  } else {
    local = false;
  }
  bool _e17 = local;
  return _e17;
}

float4 ground_layer_at(float2 xz_4, int layer)
{
  float4 _e4 = world.terrain2_;
  float2 size = max(_e4.xy, (1.0).xx);
  float4 _e11 = world.terrain;
  float4 _e16 = world.terrain;
  float2 uv = ((((xz_4 + _e11.xy) / _e16.zw) + (0.5).xx) / size);
  float4 _e26 = ground_layers.SampleLevel(clamp_sampler, float3(uv, layer), 0.0);
  return _e26;
}

float4 cover_at(float2 xz_5)
{
  const float4 _e2 = ground_layer_at(xz_5, int(2));
  return _e2;
}

float4 regional_weather_at(float2 xz_6)
{
  float4 _e3 = frame.regional;
  float _e9 = frame.regional.z;
  float2 uv_1 = ((xz_6 - _e3.xy) * _e9);
  float4 _e14 = regional_texture.SampleLevel(clamp_sampler, uv_1, 0.0);
  return _e14;
}

float canopy_at(float2 xz_7)
{
  bool local_1 = (bool)0;

  const bool _e1 = over_terrain(xz_7);
  if (!(!(_e1))) {
    float _e9 = frame.vegetation3_.x;
    local_1 = (_e9 <= 0.0);
  } else {
    local_1 = true;
  }
  bool _e13 = local_1;
  if (_e13) {
    return 0.0;
  }
  const float4 _e15 = cover_at(xz_7);
  float red = (_e15.x * 255.0);
  float _e22 = frame.vegetation3_.x;
  return (1.0 - exp((((-(_e22) * red) * red) * 6.15148e-5)));
}

float2 cloud_weather_level(float2 xz_8)
{
  float coverage = (float)0;

  float _e4 = frame.cloud_params.x;
  coverage = _e4;
  float _e9 = frame.regional.w;
  if ((_e9 > 0.5)) {
    const float4 _e12 = regional_weather_at(xz_8);
    coverage = _e12.x;
  }
  float4 _e16 = frame.cloud_motion;
  float2 uv_2 = ((xz_8 + _e16.xy) / (26000.0).xx);
  float4 large = noise_texture.SampleLevel(linear_sampler, uv_2, 0.0);
  float4 _e35 = noise_texture.SampleLevel(linear_sampler, ((uv_2 * 3.3) + float2(0.37, 0.71)), 0.0);
  float medium = _e35.y;
  float weather = ((large.x * 0.7) + (medium * 0.3));
  float _e43 = coverage;
  float _e50 = coverage;
  const float _e57 = remap(weather, ((1.0 - (_e43 * 0.95)) - 0.05), (1.0 - (_e50 * 0.35)), 0.0, 1.0);
  return float2(saturate(_e57), large.w);
}

float cloud_weather(float2 xz_9)
{
  const float2 _e1 = cloud_weather_level(xz_9);
  return _e1.x;
}

bool alto_on()
{
  float _e3 = frame.clouds5_.z;
  float _e7 = frame.clouds5_.w;
  return (max(_e3, _e7) > 0.001);
}

float2 alto_wind()
{
  float4 _e2 = frame.clouds2_;
  float2 wind = _e2.zw;
  return float2(((wind.x * 0.9396926) + (wind.y * 0.3420201)), ((wind.y * 0.9396926) - (wind.x * 0.3420201)));
}

float alto_ripple(float2 q, float warp)
{
  const float2 _e2 = alto_wind();
  return (0.5 + (0.5 * sin(((dot(q, float2(-(_e2.y), _e2.x)) * 0.0069813174) + warp))));
}

float3 alto_coarse(float2 xz_10)
{
  float scale = 1.0;

  float4 _e3 = frame.alto;
  float2 q_1 = (xz_10 + _e3.xy);
  const float2 _e6 = alto_wind();
  float2 across_1 = float2(-(_e6.y), _e6.x);
  float2 local_7 = float2((dot(q_1, _e6) / 2.5), dot(q_1, across_1));
  float4 n = noise_texture.SampleLevel(linear_sampler, ((local_7 / (48000.0).xx) + float2(0.29, 0.53)), 0.0);
  float _e32 = frame.regional.w;
  if ((_e32 > 0.5)) {
    const float4 _e35 = regional_weather_at(xz_10);
    float cover = _e35.x;
    float _e40 = frame.cloud_params.x;
    scale = (1.0 + (0.3 * clamp(((cover - _e40) / 0.2), -1.0, 1.0)));
  }
  float _e54 = frame.clouds5_.z;
  float _e55 = scale;
  float cumulus = saturate(((_e54 * _e55) * lerp(0.3, 1.7, n.x)));
  float _e66 = frame.clouds5_.w;
  float _e67 = scale;
  float stratus = ((_e66 * _e67) * (0.7 + (0.3 * n.y)));
  return float3(cumulus, stratus, ((n.w - 0.5) * 7.5));
}

float alto_shadow_depth(float2 xz_11)
{
  const float3 _e1 = alto_coarse(xz_11);
  float4 _e5 = frame.alto;
  const float _e9 = alto_ripple((xz_11 + _e5.xy), _e1.z);
  float cumulus_1 = (_e1.x * lerp(0.25, 0.45, _e9));
  return (ALTO_EXTINCTION * ((cumulus_1 * ALTOCUMULUS_THICKNESS) + (_e1.y * ALTOSTRATUS_THICKNESS)));
}

float alto_shadow(float3 position)
{
  bool local_2 = (bool)0;

  float _e4 = frame.alto.z;
  float rise = (_e4 - position.y);
  const bool _e7 = alto_on();
  if (!(!(_e7))) {
    local_2 = (rise <= 0.0);
  } else {
    local_2 = true;
  }
  bool _e15 = local_2;
  if (_e15) {
    return 1.0;
  }
  const float3 _e17 = sun_dir();
  float sun_y = max(_e17.y, 0.05);
  const float _e26 = alto_shadow_depth((position.xz + (_e17.xz * (rise / sun_y))));
  return exp((-(_e26) / sun_y));
}

float cloud_shadow(float3 position_1)
{
  float lit_ = 1.0;

  float _e4 = frame.cloud_colour.w;
  if ((_e4 < 0.5)) {
    return 1.0;
  }
  float _e13 = frame.cloud_params.x;
  if ((_e13 > 0.001)) {
    const float3 _e16 = sun_dir();
    float _e20 = frame.cloud_params.y;
    float _e24 = frame.cloud_params.z;
    float mid_height = (_e20 + (_e24 * 0.35));
    float travel = (max((mid_height - position_1.y), 0.0) / max(_e16.y, 0.08));
    float2 shadow_point = (position_1.xz + (_e16.xz * travel));
    const float _e40 = cloud_weather(shadow_point);
    float _e47 = frame.cloud_motion.w;
    float density = (smoothstep(0.05, 0.6, _e40) * saturate(((_e47 * 1.4) + 0.2)));
    float _e57 = frame.shadow_params.w;
    lit_ = (1.0 - (density * _e57));
  }
  const bool _e61 = alto_on();
  if (_e61) {
    float _e62 = lit_;
    const float _e63 = alto_shadow(position_1);
    float _e67 = frame.shadow_params.w;
    lit_ = (_e62 * lerp(1.0, _e63, _e67));
  }
  float _e71 = lit_;
  return _e71;
}

float terrain_shadow(float3 position_2)
{
  bool local_3 = (bool)0;
  bool local_4 = (bool)0;

  float strength = frame.shadow_params.z;
  if (!((strength <= 0.001))) {
    float _e13 = world.terrain2_.z;
    local_3 = (_e13 < 0.5);
  } else {
    local_3 = true;
  }
  bool _e17 = local_3;
  if (_e17) {
    return 1.0;
  }
  float4 _e22 = world.terrain;
  float4 _e27 = world.terrain;
  float2 uv_3 = ((position_2.xz + _e22.xy) / max((_e27.xy * 2.0), (1.0).xx));
  if (!(any((uv_3 < (0.0).xx)))) {
    local_4 = any((uv_3 > (1.0).xx));
  } else {
    local_4 = true;
  }
  bool _e47 = local_4;
  if (_e47) {
    return 1.0;
  }
  float4 _e52 = terrain_shadow_texture.SampleLevel(clamp_sampler, uv_3, 0.0);
  float lit_2 = _e52.x;
  return lerp(1.0, lit_2, strength);
}

uint2 NagaDepthDimensions2D(Texture2D<float> tex)
{
  uint4 ret;
  tex.GetDimensions(0, ret.x, ret.y, ret.z);
  return ret.xy;
}

float tree_shadow(float3 position_3, float3 normal_1)
{
  bool local_5 = (bool)0;
  bool local_6 = (bool)0;
  float lit_1 = 0.0;

  float strength_1 = frame.shadow_params.x;
  if ((strength_1 <= 0.001)) {
    return 1.0;
  }
  float4x4 _e11 = frame.shadow_view_proj;
  float4 clip_ = mul(float4((position_3 + (normal_1 * 0.25)), 1.0), _e11);
  float2 uv_4 = float2(((clip_.x * 0.5) + 0.5), (0.5 - (clip_.y * 0.5)));
  if (!(any((uv_4 <= (0.0).xx)))) {
    local_5 = any((uv_4 >= (1.0).xx));
  } else {
    local_5 = true;
  }
  bool _e41 = local_5;
  if (!(_e41)) {
    local_6 = (clip_.z >= 1.0);
  } else {
    local_6 = true;
  }
  bool _e49 = local_6;
  if (_e49) {
    return 1.0;
  }
  float _e54 = frame.shadow_params.y;
  float texel_1 = (_e54 / float(NagaDepthDimensions2D(tree_shadow_map).x));
  float depth = (clip_.z - 0.0008);
  float _e65 = lit_1;
  float _e73 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_4 + (float2(-0.7, -0.3) * texel_1)), depth);
  lit_1 = (_e65 + _e73);
  float _e75 = lit_1;
  float _e83 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_4 + (float2(0.3, -0.7) * texel_1)), depth);
  lit_1 = (_e75 + _e83);
  float _e85 = lit_1;
  float _e93 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_4 + (float2(0.7, 0.3) * texel_1)), depth);
  lit_1 = (_e85 + _e93);
  float _e95 = lit_1;
  float _e103 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_4 + (float2(-0.3, 0.7) * texel_1)), depth);
  lit_1 = (_e95 + _e103);
  float _e105 = lit_1;
  lit_1 = (_e105 * 0.25);
  float edge_1 = min(min(uv_4.x, uv_4.y), min((1.0 - uv_4.x), (1.0 - uv_4.y)));
  float _e119 = lit_1;
  lit_1 = lerp(1.0, _e119, smoothstep(0.0, 0.08, edge_1));
  float _e125 = lit_1;
  return lerp(1.0, _e125, strength_1);
}

float sun_visibility(float3 position_4, float3 normal_2)
{
  const float _e2 = cloud_shadow(position_4);
  const float _e3 = terrain_shadow(position_4);
  const float _e5 = tree_shadow(position_4, normal_2);
  return ((_e2 * _e3) * _e5);
}

float height_density_average(float h0_, float h1_, float base, float scale_1)
{
  float a_1 = exp(-(clamp(((h0_ - base) / scale_1), -30.0, 60.0)));
  float b_1 = exp(-(clamp(((h1_ - base) / scale_1), -30.0, 60.0)));
  float dh = ((h1_ - h0_) / scale_1);
  if ((abs(dh) < 0.001)) {
    return ((a_1 + b_1) * 0.5);
  }
  return ((a_1 - b_1) / dh);
}

float mist_noise(float3 position_5)
{
  float _e4 = frame.mist_wind.x;
  float _e8 = frame.mist_wind.y;
  float3 p_2 = ((position_5 + float3(_e4, 0.0, _e8)) / (420.0).xxx);
  float _e20 = frame.mist_wind.w;
  float4 n_1 = cloud_texture.SampleLevel(linear_sampler, (p_2 + (_e20).xxx), 0.0);
  return ((saturate(((n_1.x * 1.25) - 0.1)) * 0.75) + (n_1.y * 0.25));
}

Fog ConstructFog(float3 arg0, float arg1) {
  Fog ret = (Fog)0;
  ret.inscatter = arg0;
  ret.transmittance = arg1;
  return ret;
}

Fog atmospheric_fog(float3 ray, float distance_1, float2 pixel_1, bool include_haze)
{
  float3 transmittance = (1.0).xxx;
  float3 inscatter = (0.0).xxx;
  float average = (float)0;
  float noise_1 = 0.0;
  int i = int(0);

  float4 _e6 = frame.camera_position;
  float3 camera = _e6.xyz;
  float3 end_1 = (camera + (ray * distance_1));
  const float3 _e10 = sun_dir();
  float mu_1 = dot(ray, _e10);
  if (include_haze) {
    float _e21 = frame.atmosphere.z;
    float haze_extinction = (2.6 / max(_e21, 1.0));
    const float _e31 = height_density_average(camera.y, end_1.y, 0.0, MIE_HEIGHT);
    float haze_depth = ((haze_extinction * distance_1) * _e31);
    const float3 _e33 = rayleigh_beta();
    const float _e39 = height_density_average(camera.y, end_1.y, 0.0, RAYLEIGH_HEIGHT);
    float3 rayleigh_depth = ((_e33 * distance_1) * _e39);
    transmittance = exp(-(((haze_depth).xxx + rayleigh_depth)));
    float3 horizon_ray = normalize(float3(ray.x, max(ray.y, 0.015), ray.z));
    const float3 _e52 = sky_radiance(horizon_ray);
    const float3 _e55 = sun_light();
    const float _e57 = henyey_greenstein(mu_1, 0.7);
    float3 haze_light = ((_e52 * 0.85) + ((_e55 * _e57) * 0.35));
    float3 _e64 = transmittance;
    inscatter = (haze_light * ((1.0).xxx - _e64));
  }
  float mist_density = frame.mist_params.x;
  if ((mist_density > 0.0001)) {
    float base_2 = frame.mist_params.y;
    float _e80 = frame.mist_params.z;
    float falloff = max(_e80, 1.0);
    float march = min(distance_1, 9000.0);
    float3 mist_end = (camera + (ray * march));
    const float _e91 = height_density_average(max(camera.y, base_2), max(mist_end.y, base_2), base_2, falloff);
    average = _e91;
    float water_level = frame.mist_colour.w;
    float _e97 = average;
    const float _e102 = height_density_average(camera.y, mist_end.y, water_level, (falloff * 0.35));
    average = (_e97 + ((_e102 * 0.5) * step(camera.y, (water_level + (falloff * 12.0)))));
    float _e115 = frame.mist_params.w;
    if ((_e115 > 0.001)) {
      const float _e120 = pixel_dither(pixel_1);
      uint2 loop_bound = uint2(4294967295u, 4294967295u);
      bool loop_init = true;
      while(true) {
        if (all(loop_bound == uint2(0u, 0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
          int _e139 = i;
          i = asint(asuint(_e139) + asuint(int(1)));
        }
        loop_init = false;
        int _e123 = i;
        if ((_e123 < int(4))) {
        } else {
          break;
        }
        {
          int _e126 = i;
          float t = ((float(_e126) + _e120) / 4.0);
          float along_1 = (pow(t, 1.6) * march);
          float _e134 = noise_1;
          const float _e137 = mist_noise((camera + (ray * along_1)));
          noise_1 = (_e134 + _e137);
        }
      }
      float _e142 = average;
      float _e143 = noise_1;
      float _e151 = frame.mist_params.w;
      average = (_e142 * lerp(1.0, ((_e143 / 4.0) * 1.8), _e151));
    }
    if ((distance_1 < 3000.0)) {
      float _e157 = average;
      const float _e159 = canopy_at(end_1.xz);
      average = (_e157 * (1.0 + (0.2 * _e159)));
    }
    float _e167 = average;
    float mist_optical = (((mist_density * 0.0045) * _e167) * march);
    float mist_transmittance = exp(-(mist_optical));
    float scatter = frame.mist_wind.z;
    float4 _e178 = frame.mist_colour;
    const float3 _e184 = sky_irradiance(float3(0.0, 1.0, 0.0));
    const float3 _e187 = sun_light();
    const float _e189 = henyey_greenstein(mu_1, 0.55);
    float3 mist_light = (_e178.xyz * ((_e184 * 0.3) + (_e187 * (0.08 + ((_e189 * scatter) * 1.2)))));
    float3 _e198 = inscatter;
    inscatter = ((_e198 * mist_transmittance) + (mist_light * (1.0 - mist_transmittance)));
    float3 _e204 = transmittance;
    transmittance = (_e204 * mist_transmittance);
  }
  float3 _e206 = inscatter;
  float3 _e207 = transmittance;
  const Fog fog = ConstructFog(_e206, dot(_e207, (0.3333).xxx));
  return fog;
}

float3 render_distance_colour(float3 ray_1)
{
  const float3 _e6 = sky_radiance(normalize(float3(ray_1.x, 0.02, ray_1.z)));
  return _e6;
}

float fade_in_before(float end, float length_, float distance_2)
{
  float t_1 = saturate(((distance_2 - (end - length_)) / max(length_, 0.001)));
  return ((t_1 * t_1) * (3.0 - (2.0 * t_1)));
}

float render_distance_fog(float distance_3)
{
  float limit = frame.distances.x;
  if ((limit >= 100000000.0)) {
    return 0.0;
  }
  float _e11 = frame.fades.x;
  const float _e12 = fade_in_before(limit, _e11, distance_3);
  return _e12;
}

float3 apply_fog(float3 colour_3, float3 world_position, float2 pixel_2)
{
  float4 _e5 = frame.camera_position;
  float3 offset = (world_position - _e5.xyz);
  float distance_4 = length(offset);
  float3 ray_2 = (offset / (max(distance_4, 0.001)).xxx);
  const Fog _e14 = atmospheric_fog(ray_2, distance_4, pixel_2, true);
  const float3 _e19 = render_distance_colour(ray_2);
  const float _e20 = render_distance_fog(distance_4);
  return lerp(((colour_3 * _e14.transmittance) + _e14.inscatter), _e19, _e20);
}

float3 shade_surface(float3 albedo, float3 normal_3, float3 world_position_1, float occlusion, float specular, float roughness)
{
  float3 colour_4 = (float3)0;

  const float3 _e6 = sun_dir();
  float n_dot_l = saturate(dot(normal_3, _e6));
  const float _e9 = sun_visibility(world_position_1, normal_3);
  const float3 _e10 = sun_light();
  float3 direct = ((_e10 * n_dot_l) * _e9);
  const float3 _e13 = sky_irradiance(normal_3);
  float3 ambient = (_e13 * occlusion);
  colour_4 = (((albedo * (direct + (ambient * 0.75))) / (3.1415927).xxx) * 2.6);
  if ((specular > 0.001)) {
    float4 _e29 = frame.camera_position;
    float3 view = normalize((_e29.xyz - world_position_1));
    float3 half_vector = normalize((view + _e6));
    float n_dot_h = saturate(dot(normal_3, half_vector));
    float alpha_1 = max((roughness * roughness), 0.02);
    float d = ((alpha_1 * alpha_1) / (PI * pow((((n_dot_h * n_dot_h) * ((alpha_1 * alpha_1) - 1.0)) + 1.0), 2.0)));
    float fresnel = (0.04 + (0.96 * pow((1.0 - saturate(dot(view, half_vector))), 5.0)));
    float3 _e63 = colour_4;
    const float3 _e64 = sun_light();
    colour_4 = (_e63 + ((((((_e64 * _e9) * n_dot_l) * d) * fresnel) * specular) * 0.25));
  }
  float3 _e73 = colour_4;
  return _e73;
}

bool freezing_possible()
{
  float _e3 = frame.rivers.y;
  return (_e3 > 0.5);
}

float freeze_fraction(float celsius, float start)
{
  return saturate(((start - celsius) / 2.0));
}

float4 fragment_fall(FragmentInput_fragment_fall fragmentinput_fragment_fall) : SV_Target0
{
  VertexOut in_ = { fragmentinput_fragment_fall.clip_position, fragmentinput_fragment_fall.world_position_2, fragmentinput_fragment_fall.flow, fragmentinput_fragment_fall.kind, fragmentinput_fragment_fall.across, fragmentinput_fragment_fall.spacing, fragmentinput_fragment_fall.rest_xz, fragmentinput_fragment_fall.extra, fragmentinput_fragment_fall.coverage_1, fragmentinput_fragment_fall.along, fragmentinput_fragment_fall.swirl, fragmentinput_fragment_fall.into_step, fragmentinput_fragment_fall.catchment };
  float alpha = (float)0;
  float3 colour = (float3)0;

  float3 position_6 = in_.world_position;
  float4 _e4 = frame.camera_position;
  float3 view_offset = (_e4.xyz - position_6);
  float distance_5 = length(view_offset);
  float3 view_1 = (view_offset / (max(distance_5, 0.001)).xxx);
  const float3 _e12 = sun_dir();
  const float _e13 = time_seconds();
  float _e17 = frame.camera_forward.w;
  float _e24 = frame.viewport.w;
  float footprint = (((distance_5 * _e17) * 2.0) * _e24);
  if ((in_.kind == KIND_SPRAY)) {
    float r2_ = dot(in_.flow, in_.flow);
    if ((r2_ >= 1.0)) {
      return (0.0).xxxx;
    }
    float age = in_.extra.x;
    float size_1 = in_.extra.y;
    const float _e41 = terrain_height_at(position_6.xz);
    float soft = (saturate(((position_6.y - _e41) / max((size_1 * 0.25), 0.5))) * saturate(((distance_5 - 1.0) / 4.0)));
    float far = (1.0 - smoothstep(1200.0, 1500.0, in_.extra.w));
    float4 _e80 = noise_texture.SampleLevel(linear_sampler, (((position_6.xz + (position_6.y).xx) / (max((size_1 * 2.0), 1.0)).xx) + (in_.flow * 0.2)), 0.0);
    float billow = _e80.x;
    float puff = (((1.0 - r2_) * (1.0 - r2_)) * lerp(0.55, 1.0, billow));
    float density_1 = (((((puff * (1.0 - age)) * smoothstep(0.0, 0.15, age)) * saturate((in_.extra.z * 0.1))) * soft) * far);
    const float _e109 = henyey_greenstein(dot(-(view_1), _e12), 0.6);
    const float3 _e112 = sun_light();
    const float3 _e122 = sky_irradiance(float3(0.0, 1.0, 0.0));
    float3 colour_5 = ((((0.92).xxx * ((_e112 * (0.25 + (_e109 * 1.8))) + (_e122 * 0.4))) / (3.1415927).xxx) * 2.2);
    const float3 _e134 = apply_fog(colour_5, position_6, in_.clip_position.xy);
    const float3 _e135 = finish_colour(_e134);
    return float4(_e135, saturate((density_1 * 0.8)));
  }
  float travelled = in_.extra.x;
  float down = (travelled / max(in_.extra.y, 0.01));
  float celsius_1 = in_.extra.z;
  float2 direction_1 = normalize((in_.flow + float2(1e-5, 0.0)));
  float2 side = float2(-(direction_1.y), direction_1.x);
  float u_1 = dot(in_.rest_xz, side);
  float lod = max(log2(((footprint * 512.0) / 9.0)), 0.0);
  float2 streak_uv = float2((u_1 / 1.3), ((travelled - (_e13 * in_.spacing)) / 9.0));
  float4 _e178 = noise_texture.SampleLevel(linear_sampler, streak_uv, lod);
  float s1_ = _e178.x;
  float4 _e190 = noise_texture.SampleLevel(linear_sampler, ((streak_uv * float2(2.3, 1.7)) + float2(0.37, 0.61)), lod);
  float s2_ = _e190.y;
  float streak = ((s1_ * 0.6) + (s2_ * 0.4));
  float edge_2 = (1.0 - smoothstep(0.55, 1.0, abs(in_.across)));
  float aerated = smoothstep(0.15, 0.85, down);
  alpha = (saturate((lerp(0.45, 0.92, aerated) * (0.55 + ((streak - 0.35) * 1.4)))) * lerp(0.3, 1.0, edge_2));
  float3 normal_4 = normalize(float3(direction_1.x, 0.3, direction_1.y));
  float3 albedo_1 = lerp(float3(0.5, 0.64, 0.68), float3(0.92, 0.94, 0.95), max(aerated, (streak * 0.5)));
  const float _e240 = sun_visibility(position_6, normal_4);
  const float3 _e241 = sun_light();
  const float3 _e250 = sky_irradiance(normal_4);
  float3 lit_3 = (((_e241 * _e240) * ((saturate(dot(normal_4, _e12)) * 0.8) + 0.2)) + (_e250 * 0.6));
  float _e264 = alpha;
  float back = ((pow(saturate(dot(-(view_1), _e12)), 4.0) * (1.0 - (aerated * 0.6))) * (1.0 - (_e264 * 0.5)));
  const float3 _e276 = sun_light();
  colour = ((((albedo_1 * lit_3) / (3.1415927).xxx) * 2.4) + ((((_e276 * _e240) * float3(0.5, 0.75, 0.7)) * back) * 0.4));
  const bool _e288 = freezing_possible();
  if (_e288) {
    const float _e290 = freeze_fraction(celsius_1, -8.0);
    if ((_e290 > 0.001)) {
      float4 _e300 = noise_texture.SampleLevel(linear_sampler, float2((u_1 / 2.0), (travelled / 7.0)), lod);
      float grain = _e300.x;
      float rib = (0.5 + (0.5 * sin(((u_1 * 2.7) + (grain * 5.0)))));
      float3 ice_albedo = lerp(float3(0.5, 0.68, 0.82), float3(0.88, 0.93, 0.97), ((rib * 0.6) + (grain * 0.4)));
      float3 ice_normal = normalize((normal_4 + ((float3(side.x, 0.0, side.y) * (rib - 0.5)) * 0.8)));
      const float3 _e340 = shade_surface(ice_albedo, ice_normal, position_6, 1.0, 0.4, 0.35);
      float3 _e341 = colour;
      colour = lerp(_e341, _e340, _e290);
      float _e343 = alpha;
      alpha = lerp(_e343, (0.97 * lerp(0.5, 1.0, edge_2)), _e290);
    }
  }
  float3 _e350 = colour;
  const float3 _e353 = apply_fog(_e350, position_6, in_.clip_position.xy);
  const float3 _e354 = finish_colour(_e353);
  float _e355 = alpha;
  return float4(_e354, saturate(_e355));
}
