// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: water (ground + common + lattice + water)
// Entry point: vertex_main, compile with /T vs_5_0 /E vertex_main
// override INLAND = false
// override SEA_ICE = false
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) frame -> b0  constant buffer
//   @group(1) @binding(8) height_texture -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(9) world -> b1  constant buffer
//   @group(1) @binding(11) clamp_sampler -> s0  SamplerState
//   @group(1) @binding(12) ground_layers -> t1  Texture2DArray (Sampled { kind: Float, multi: false })

struct FrameUniforms {
  row_major float4x4 view_proj;
  float4 camera_position;
  float4 camera_forward;
  float4 camera_right;
  float4 camera_up;
  float4 sun_direction;
  float4 atmosphere;
  float4 sky_tint;
  float4 mist_params;
  float4 mist_colour;
  float4 mist_wind;
  float4 cloud_params;
  float4 cloud_motion;
  float4 cloud_colour;
  float4 water_params;
  float4 water_shallow;
  float4 water_deep;
  float4 water_current;
  float4 wave_params;
  float4 wave_params2_;
  float4 water_origin;
  float4 vegetation;
  float4 vegetation2_;
  float4 viewport;
  row_major float4x4 shadow_view_proj;
  float4 shadow_params;
  float4 weather;
  float4 weather2_;
  float4 surface;
  float4 clouds2_;
  float4 clouds3_;
  float4 clouds4_;
  float4 weather3_;
  row_major float4x4 previous_view_proj;
  float4 temporal;
  float4 distances;
  float4 fades;
  float4 output;
  float4 cold;
  float4 sea_ice;
  float4 rivers;
  float4 ground;
  float4 vegetation3_;
  float4 rock;
  float4 regional;
  float4 air;
  float4 light;
  float4 gust;
  float4 weather4_;
  float4 clouds5_;
  float4 alto;
  float4 rivers2_;
  float4 waterside;
  float4 mouths[16];
};

struct WorldInfo {
  float4 species[8];
  float4 species_tint[8];
  float4 terrain;
  float4 terrain2_;
  float4 material_tints[12];
  float4 trees;
  float4 species_canopy[8];
};

struct VertexIn {
  float3 position : LOC0;
  float2 flow : LOC1;
  float4 params : LOC2;
  float4 extra : LOC3;
  float swirl : LOC4;
};

struct VertexOut {
  float4 clip_position : SV_Position;
  float3 world_position : LOC0;
  float2 flow : LOC1;
  nointerpolation int kind : LOC2;
  float across : LOC3;
  float spacing : LOC4;
  float2 rest_xz : LOC5;
  float4 extra : LOC6;
  float coverage : LOC7;
  float along : LOC8;
  float swirl : LOC9;
  float into_step : LOC10;
  float2 catchment : LOC11;
};

struct Wave {
  float2 direction;
  float k;
  float amplitude;
  float omega;
  float steepness;
  float phase;
  float wavelength;
};

struct WaveSample {
  float3 displacement;
  int _pad1_0;
  float3 normal;
  float jacobian;
  float height;
  int _end_pad_0;
  int _end_pad_1;
  int _end_pad_2;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const int CLUMP_CELLS = int(4);
static const uint CLUMP_SALT = 1013904242u;
static const float JITTER = 0.45;
static const float FADE_BAND = 0.05;
static const float MAX_GROWTH = 1.8;
static const int KIND_OCEAN = int(0);
static const int KIND_RIVER = int(1);
static const int KIND_LAKE = int(2);
static const int KIND_FALL = int(3);
static const int KIND_SPRAY = int(4);
static const int KIND_POOL = int(5);
static const int WAVE_COUNT = int(8);
static const bool INLAND = false;
static const bool SEA_ICE = false;

cbuffer frame : register(b0) { FrameUniforms frame; }
Texture2D<float4> height_texture : register(t0);
cbuffer world : register(b1) { WorldInfo world; }
SamplerState clamp_sampler : register(s0);
Texture2DArray<float4> ground_layers : register(t1);

struct VertexOutput_vertex_main {
  float3 world_position : LOC0;
  float2 flow : LOC1;
  nointerpolation int kind : LOC2;
  float across : LOC3;
  float spacing_2 : LOC4;
  float2 rest_xz : LOC5;
  float4 extra : LOC6;
  float coverage : LOC7;
  float along : LOC8;
  float swirl : LOC9;
  float into_step : LOC10;
  float2 catchment : LOC11;
  float4 clip_position : SV_Position;
};

float hash12_(float2 p)
{
  float3 p3_ = (float3)0;

  p3_ = frac((float3(p.x, p.y, p.x) * 0.1031));
  float3 _e9 = p3_;
  float3 _e10 = p3_;
  float3 _e11 = p3_;
  p3_ = (_e9 + (dot(_e10, (_e11.yzx + (33.33).xxx))).xxx);
  float _e20 = p3_.x;
  float _e22 = p3_.y;
  float _e25 = p3_.z;
  return frac(((_e20 + _e22) * _e25));
}

float skirt_height(float edge, float sea, float distance_, float noise_)
{
  float foot = min(edge, (sea - 60.0));
  if ((distance_ >= SKIRT_METRES)) {
    return (foot - ((distance_ - SKIRT_METRES) * 0.08));
  }
  float s = smoothstep(0.0, 1.0, (distance_ / SKIRT_METRES));
  return (lerp(edge, foot, s) + (((((edge - foot) * 0.6) * noise_) * s) * (1.0 - s)));
}

float skirt_noise(float2 xz)
{
  float2 p_1 = (xz / (700.0).xx);
  float2 cell = floor(p_1);
  float2 f = (p_1 - cell);
  float2 u = ((f * f) * ((3.0).xx - (2.0 * f)));
  const float _e13 = hash12_(cell);
  const float _e18 = hash12_((cell + float2(1.0, 0.0)));
  float top = lerp(_e13, _e18, u.x);
  const float _e25 = hash12_((cell + float2(0.0, 1.0)));
  const float _e30 = hash12_((cell + float2(1.0, 1.0)));
  float bottom = lerp(_e25, _e30, u.x);
  return ((lerp(top, bottom, u.y) * 2.0) - 1.0);
}

int2 naga_f2i32(float2 value) {
  return int2(clamp(value, -2147483600.0, 2147483500.0));
}

float texel_height(Texture2D<float4> heights, float4 terrain2_, float2 texel)
{
  float2 clamped = clamp(texel, (0.0).xx, (terrain2_.xy - (1.001).xx));
  float2 base = floor(clamped);
  float2 f_1 = (clamped - base);
  int2 i_2 = naga_f2i32(base);
  float4 _e14 = heights.Load(int3(i_2, int(0)));
  float h00_ = _e14.x;
  float4 _e21 = heights.Load(int3(asint(asuint(i_2) + asuint(int2(int(1), int(0)))), int(0)));
  float h10_ = _e21.x;
  float4 _e28 = heights.Load(int3(asint(asuint(i_2) + asuint(int2(int(0), int(1)))), int(0)));
  float h01_ = _e28.x;
  float4 _e35 = heights.Load(int3(asint(asuint(i_2) + asuint(int2(int(1), int(1)))), int(0)));
  float h11_ = _e35.x;
  return lerp(lerp(h00_, h10_, f_1.x), lerp(h01_, h11_, f_1.x), f_1.y);
}

float ground_height(Texture2D<float4> heights_1, float4 terrain, float4 terrain2_1, float2 xz_1)
{
  if ((terrain2_1.z < 0.5)) {
    return -100000.0;
  }
  const float _e12 = texel_height(heights_1, terrain2_1, ((xz_1 + terrain.xy) / terrain.zw));
  float outside = length(max((abs(xz_1) - terrain.xy), (0.0).xx));
  if ((outside <= 0.0)) {
    return _e12;
  }
  const float _e23 = skirt_noise(xz_1);
  const float _e24 = skirt_height(_e12, terrain2_1.w, outside, _e23);
  return _e24;
}

float time_seconds()
{
  float _e3 = frame.camera_position.w;
  return _e3;
}

float terrain_height_at(float2 xz_2)
{
  float4 _e4 = world.terrain;
  float4 _e7 = world.terrain2_;
  const float _e8 = ground_height(height_texture, _e4, _e7, xz_2);
  return _e8;
}

bool over_terrain(float2 xz_3)
{
  bool local_6 = (bool)0;

  float _e4 = world.terrain2_.z;
  if ((_e4 > 0.5)) {
    float4 _e12 = world.terrain;
    local_6 = all((abs(xz_3) <= _e12.xy));
  } else {
    local_6 = false;
  }
  bool _e17 = local_6;
  return _e17;
}

float4 ground_layer_at(float2 xz_4, int layer)
{
  float4 _e4 = world.terrain2_;
  float2 size = max(_e4.xy, (1.0).xx);
  float4 _e11 = world.terrain;
  float4 _e16 = world.terrain;
  float2 uv = ((((xz_4 + _e11.xy) / _e16.zw) + (0.5).xx) / size);
  float4 _e26 = ground_layers.SampleLevel(clamp_sampler, float3(uv, layer), 0.0);
  return _e26;
}

float4 surface_at(float2 xz_5)
{
  const float4 _e2 = ground_layer_at(xz_5, int(0));
  return _e2;
}

bool falls_possible()
{
  float _e3 = frame.rivers.z;
  return (_e3 > 0.5);
}

bool freezing_possible()
{
  float _e3 = frame.rivers.y;
  return (_e3 > 0.5);
}

float freeze_fraction(float celsius, float start)
{
  return saturate(((start - celsius) / 2.0));
}

typedef float ret_Constructarray8_float_[8];
ret_Constructarray8_float_ Constructarray8_float_(float arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6, float arg7) {
  float ret[8] = { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 };
  return ret;
}

Wave ConstructWave(float2 arg0, float arg1, float arg2, float arg3, float arg4, float arg5, float arg6) {
  Wave ret = (Wave)0;
  ret.direction = arg0;
  ret.k = arg1;
  ret.amplitude = arg2;
  ret.omega = arg3;
  ret.steepness = arg4;
  ret.phase = arg5;
  ret.wavelength = arg6;
  return ret;
}

Wave wave(int i)
{
  float scales[8] = Constructarray8_float_(1.0, 0.61, 0.43, 0.29, 0.21, 0.14, 0.095, 0.061);
  float angles[8] = Constructarray8_float_(0.0, 0.55, -0.42, 1.05, -0.95, 0.28, -1.45, 1.6);
  float phases[8] = Constructarray8_float_(0.0, 1.7, 4.1, 2.3, 5.2, 0.9, 3.3, 5.9);

  float _e34 = frame.wave_params.y;
  float base_wavelength = max(_e34, 0.5);
  float _e40 = frame.wave_params.z;
  float _e42 = angles[min(uint(i), 7u)];
  float _e46 = frame.wave_params2_.y;
  float angle = (_e40 + (_e42 * _e46));
  float _e50 = scales[min(uint(i), 7u)];
  float wavelength = (base_wavelength * _e50);
  float k = (TAU / wavelength);
  float _e57 = frame.wave_params.x;
  float _e61 = scales[min(uint(i), 7u)];
  float amplitude = (((_e57 * 0.5) * pow(_e61, 1.1)) * ((i == int(0)) ? 1.0 : 0.55));
  float _e77 = frame.wave_params2_.x;
  float omega = (sqrt((9.81 * k)) * _e77);
  float _e82 = frame.wave_params.w;
  float steepness = (saturate(_e82) / max(((k * amplitude) * 8.0), 0.0001));
  float _e96 = phases[min(uint(i), 7u)];
  const Wave wave_1 = ConstructWave(float2(sin(angle), cos(angle)), k, amplitude, omega, min(steepness, 1.0), _e96, wavelength);
  return wave_1;
}

float wave_attenuation(Wave w, float depth, float spacing)
{
  float shoal = smoothstep(0.0, max((w.wavelength * 0.06), 0.6), depth);
  float resolvable = (1.0 - smoothstep((w.wavelength / 7.0), (w.wavelength / 3.5), spacing));
  return (shoal * resolvable);
}

WaveSample ConstructWaveSample(float3 arg0, float3 arg1, float arg2, float arg3) {
  WaveSample ret = (WaveSample)0;
  ret.displacement = arg0;
  ret.normal = arg1;
  ret.jacobian = arg2;
  ret.height = arg3;
  return ret;
}

WaveSample sample_waves(float2 xz_6, float depth_1, float spacing_1)
{
  WaveSample result = ConstructWaveSample((0.0).xxx, float3(0.0, 1.0, 0.0), 1.0, 0.0);
  bool local_7 = (bool)0;
  float nx = 0.0;
  float nz = 0.0;
  float ny = 1.0;
  int i_1 = int(0);

  float _e16 = frame.wave_params2_.z;
  if (!((_e16 < 0.5))) {
    float _e25 = frame.wave_params.x;
    local_7 = (_e25 <= 0.0001);
  } else {
    local_7 = true;
  }
  bool _e29 = local_7;
  if (_e29) {
    WaveSample _e30 = result;
    const WaveSample wavesample = _e30;
    return wavesample;
  }
  const float _e31 = time_seconds();
  bool loop_init = true;
  while(true) {
    if (!loop_init) {
      int _e105 = i_1;
      i_1 = asint(asuint(_e105) + asuint(int(1)));
    }
    loop_init = false;
    int _e40 = i_1;
    if ((_e40 < WAVE_COUNT)) {
    } else {
      break;
    }
    {
      int _e43 = i_1;
      const Wave _e44 = wave(_e43);
      const float _e46 = wave_attenuation(_e44, depth_1, spacing_1);
      float a = (_e44.amplitude * _e46);
      if ((a <= 0.0001)) {
        continue;
      }
      float phase = (((_e44.k * dot(_e44.direction, xz_6)) - (_e44.omega * _e31)) + _e44.phase);
      float c = cos(phase);
      float s_1 = sin(phase);
      float qa = (_e44.steepness * a);
      float3 _e65 = result.displacement;
      result.displacement = (_e65 + float3(((qa * _e44.direction.x) * c), (a * s_1), ((qa * _e44.direction.y) * c)));
      float _e77 = nx;
      nx = (_e77 - (((_e44.direction.x * _e44.k) * a) * c));
      float _e85 = nz;
      nz = (_e85 - (((_e44.direction.y * _e44.k) * a) * c));
      float _e93 = ny;
      ny = (_e93 - (((_e44.steepness * _e44.k) * a) * s_1));
      float _e102 = result.height;
      result.height = (_e102 + (s_1 * a));
    }
  }
  float _e109 = nx;
  float _e110 = ny;
  float _e113 = nz;
  result.normal = normalize(float3(_e109, max(_e110, 0.05), _e113));
  float _e117 = ny;
  result.jacobian = _e117;
  WaveSample _e118 = result;
  const WaveSample wavesample_1 = _e118;
  return wavesample_1;
}

bool sea_ice_possible()
{
  bool local_8 = (bool)0;

  if (SEA_ICE) {
    float _e6 = frame.sea_ice.x;
    local_8 = (_e6 > 0.5);
  } else {
    local_8 = false;
  }
  bool _e10 = local_8;
  return _e10;
}

float sea_ice_concentration(float2 xz_7)
{
  float unit = (float)0;
  float fast = 0.0;

  const bool _e1 = sea_ice_possible();
  if (!(_e1)) {
    return 0.0;
  }
  float _e7 = frame.sea_ice.y;
  unit = _e7;
  const bool _e11 = over_terrain(xz_7);
  if (_e11) {
    float4 _e14 = world.terrain;
    float2 margin = (_e14.xy - abs(xz_7));
    float inside = saturate((min(margin.x, margin.y) / 300.0));
    const float4 _e24 = surface_at(xz_7);
    float _e25 = unit;
    unit = lerp(_e25, _e24.x, inside);
    fast = (_e24.z * inside);
  }
  float _e30 = unit;
  float celsius_1 = ((_e30 * 65.0) - 30.0);
  float _e40 = fast;
  return max(saturate(((-1.5 - celsius_1) / 6.0)), _e40);
}

float naga_mod(float lhs, float rhs) {
  return lhs - rhs * trunc(lhs / rhs);
}

int naga_f2i32(float value) {
  return int(clamp(value, -2147483600.0, 2147483500.0));
}

VertexOutput_vertex_main vertex_main(VertexIn in_)
{
  float3 position = (float3)0;
  bool local = (bool)0;
  VertexOut out_ = (VertexOut)0;
  float3 displacement = (float3)0;
  bool local_1 = (bool)0;
  bool local_2 = (bool)0;
  bool local_3 = (bool)0;
  bool local_4 = (bool)0;
  bool local_5 = (bool)0;

  int kind_1 = naga_f2i32(floor((in_.params.x + 0.01)));
  position = in_.position;
  if (true) {
    local = (kind_1 == KIND_OCEAN);
  } else {
    local = false;
  }
  bool ocean = local;
  if (ocean) {
    float _e23 = frame.water_origin.x;
    float _e28 = frame.water_shallow.w;
    float _e34 = frame.water_origin.y;
    position = float3((in_.position.x + _e23), _e28, (in_.position.z + _e34));
  }
  float3 _e39 = position;
  out_.rest_xz = _e39.xz;
  out_.flow = in_.flow;
  out_.extra = in_.extra;
  if (ocean) {
    float _e46 = position.y;
    float3 _e47 = position;
    const float _e49 = terrain_height_at(_e47.xz);
    float depth_2 = (_e46 - _e49);
    float3 _e51 = position;
    const WaveSample _e55 = sample_waves(_e51.xz, depth_2, in_.params.z);
    displacement = _e55.displacement;
    const bool _e58 = sea_ice_possible();
    if (_e58) {
      float3 _e59 = displacement;
      float3 _e60 = position;
      const float _e62 = sea_ice_concentration(_e60.xz);
      displacement = (_e59 * (1.0 - _e62));
    }
    float3 _e66 = position;
    float3 _e67 = displacement;
    position = (_e66 + _e67);
  }
  out_.coverage = 1.0;
  if (INLAND) {
    local_1 = (kind_1 == KIND_RIVER);
  } else {
    local_1 = false;
  }
  bool _e77 = local_1;
  if (_e77) {
    float _e80 = position.y;
    float _e88 = frame.rivers.x;
    position.y = (_e80 + ((0.2 * in_.extra.z) * saturate(((_e88 - 1.0) / 0.4))));
    float3 _e96 = position;
    float4 _e99 = frame.camera_position;
    float _e105 = frame.camera_forward.w;
    float _e112 = frame.viewport.w;
    float footprint = (((distance(_e96, _e99.xyz) * _e105) * 2.0) * _e112);
    float drawn = max(in_.params.z, (0.75 * footprint));
    float2 side = normalize(float2(-(in_.flow.y), in_.flow.x));
    float3 _e126 = position;
    position = (_e126 + ((float3(side.x, 0.0, side.y) * (drawn - in_.params.z)) * in_.params.y));
    out_.coverage = (in_.params.z / drawn);
  }
  if (INLAND) {
    local_2 = (kind_1 == KIND_SPRAY);
  } else {
    local_2 = false;
  }
  bool _e149 = local_2;
  if (_e149) {
    const bool _e152 = falls_possible();
    local_3 = _e152;
  } else {
    local_3 = false;
  }
  bool _e154 = local_3;
  if (_e154) {
    float seed = in_.params.y;
    float size_1 = in_.params.z;
    float height = in_.extra.x;
    float life = (3.0 + (seed * 3.0));
    const float _e165 = time_seconds();
    float age = frac(((_e165 / life) + (seed * 7.13)));
    float rise = ((age * min((height * 0.6), (size_1 * 2.0))) + (size_1 * 0.3));
    float _e184 = frame.weather2_.z;
    float _e188 = frame.weather2_.w;
    float3 centre = ((in_.position + (((float3(_e184, 0.0, _e188) * age) * life) * 0.35)) + float3(0.0, rise, 0.0));
    float grown = (size_1 * (0.6 + (age * 0.8)));
    float4 _e207 = frame.camera_position;
    float distance_1 = length((centre - _e207.xyz));
    if (!((distance_1 > 1500.0))) {
      const bool _e216 = freezing_possible();
      if (_e216) {
        const float _e222 = freeze_fraction(in_.extra.z, -8.0);
        local_5 = (_e222 > 0.5);
      } else {
        local_5 = false;
      }
      bool _e226 = local_5;
      local_4 = _e226;
    } else {
      local_4 = true;
    }
    bool hidden = local_4;
    float2 corner = (hidden ? (0.0).xx : in_.flow);
    float4 _e235 = frame.camera_right;
    float4 _e241 = frame.camera_up;
    position = (centre + ((((_e235.xyz * corner.x) + (_e241.xyz * corner.y)) * grown) * 0.5));
    out_.extra = float4(age, grown, sqrt(max((in_.extra.x * in_.extra.y), 0.0)), distance_1);
  }
  float4x4 _e263 = frame.view_proj;
  float3 _e264 = position;
  out_.clip_position = mul(float4(_e264, 1.0), _e263);
  float3 _e269 = position;
  out_.world_position = _e269;
  out_.kind = kind_1;
  out_.across = in_.params.y;
  out_.spacing = in_.params.z;
  out_.along = in_.params.w;
  float code = floor(((in_.swirl + 2.0) * 0.25));
  out_.swirl = (in_.swirl - (4.0 * code));
  out_.catchment = (float2(naga_mod(code, 8.0), floor((code / 8.0))) / (7.0).xx);
  out_.into_step = (in_.params.x - float(kind_1));
  VertexOut _e306 = out_;
  const VertexOut vertexout = _e306;
  const VertexOutput_vertex_main vertexout_1 = { vertexout.world_position, vertexout.flow, vertexout.kind, vertexout.across, vertexout.spacing, vertexout.rest_xz, vertexout.extra, vertexout.coverage, vertexout.along, vertexout.swirl, vertexout.into_step, vertexout.catchment, vertexout.clip_position };
  return vertexout_1;
}
