//! Procedural texture baking on the GPU.
//!
//! Every surface texture — ten terrain materials, bark and foliage,
//! water ripples, and 2D/3D noise for clouds and mist — is generated by
//! compute shaders (`shaders/texture_gen.wgsl`) and mipmapped by
//! `shaders/mipgen.wgsl`: the water and 2D noise at engine start-up, each
//! terrain material when the ground first uses it, the flora layers of
//! each tree species when it first appears, and the 3D noise when clouds
//! or mist first need it. Nothing is
//! downloaded, the output is identical on every run, and the cost is GPU
//! time instead of megabytes of image assets.

use crate::maths::Portable;
#[cfg(not(target_arch = "wasm32"))]
use crate::render::recorder as wgpu;

/// Edge length of each terrain material layer.
pub const TERRAIN_TEXTURE_SIZE: u32 = 512;
/// Number of terrain material layers.
pub const TERRAIN_LAYERS: u32 = 12;
/// Edge length of each flora layer.
pub const FLORA_TEXTURE_SIZE: u32 = 512;
/// Edge length of the water ripple texture.
pub const WATER_TEXTURE_SIZE: u32 = 512;
/// Edge length of the general 2D noise texture.
pub const NOISE_TEXTURE_SIZE: u32 = 512;
/// Edge length of the 3D cloud noise volume.
pub const CLOUD_TEXTURE_SIZE: u32 = 64;

/// Mip generation mode, matching `mipgen.wgsl`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MipMode {
  /// sRGB-encoded opaque colour.
  Colour,
  /// sRGB-encoded colour with alpha-tested coverage, kept at each level.
  Coverage,
  /// Linear data such as normals and noise.
  Linear,
  /// The flora layers: opaque bark, alpha-tested foliage, then the leaf
  /// normal maps.
  Flora,
  /// The impostor atlas: colour with coverage, and normals, in turn.
  Impostors,
}

impl MipMode {
  /// `mode`, `opaque_below`, `linear_from` and `odd_linear` in
  /// `MipParams`.
  fn params(self) -> [u32; 4] {
    let bark = crate::render::tree_models::layers::FIRST_FOLIAGE as u32;
    let normals = crate::render::tree_models::layers::COUNT;

    match self {
      Self::Colour => [0, 0, u32::MAX, 0],
      Self::Coverage => [1, 0, u32::MAX, 0],
      Self::Linear => [2, 0, u32::MAX, 0],
      Self::Flora => [1, bark, normals, 0],
      Self::Impostors => [1, 0, u32::MAX, 1],
    }
  }
}

/// All baked world textures.
pub struct WorldTextures {
  /// Terrain albedo (rgb) and height (a).
  pub terrain_albedo: wgpu::TextureView,
  /// Terrain detail normal (rg), occlusion (b), and roughness (a).
  pub terrain_normal: wgpu::TextureView,
  /// Bark and foliage layers.
  pub flora: wgpu::TextureView,
  /// Water ripple normal (rg), foam (b), and height (a).
  pub water: wgpu::TextureView,
  /// General-purpose tiling 2D noise.
  pub noise: wgpu::TextureView,
  /// 3D cloud noise.
  pub cloud: wgpu::TextureView,
  /// Terrain albedo texture, for replacing layers.
  pub terrain_albedo_texture: wgpu::Texture,
  /// Terrain normal texture, for replacing layers.
  pub terrain_normal_texture: wgpu::Texture,
  /// Flora texture, for replacing layers.
  pub flora_texture: wgpu::Texture,
  /// Terrain material layers baked so far, one bit per layer. Layers are
  /// baked when the ground first uses their material.
  pub terrain_baked: u32,
  /// Flora layers baked or replaced so far, one bit per layer. Layers are
  /// baked when a species that samples them first appears.
  pub flora_baked: u32,
  /// Whether the 3D cloud noise has been baked.
  pub cloud_baked: bool,
  // Keep the remaining textures alive for as long as their views are used.
  _textures: Vec<wgpu::Texture>,
}

/// Number of mip levels for a square texture.
pub fn mip_count(size: u32) -> u32 {
  32 - size.max(1).leading_zeros()
}

/// An rgba8 texture that can be sampled and written by compute shaders.
pub fn create_texture(
  device: &wgpu::Device,
  label: &str,
  size: wgpu::Extent3d,
  dimension: wgpu::TextureDimension,
  mips: u32,
  extra_usage: wgpu::TextureUsages,
) -> wgpu::Texture {
  device.create_texture(&wgpu::TextureDescriptor {
    label: Some(label),
    size,
    mip_level_count: mips,
    sample_count: 1,
    dimension,
    format: wgpu::TextureFormat::Rgba8Unorm,
    usage: wgpu::TextureUsages::TEXTURE_BINDING
      | wgpu::TextureUsages::STORAGE_BINDING
      | extra_usage,
    view_formats: &[],
  })
}

/// Create an rgba8 2D array texture suitable for baking and mipmapping.
pub fn create_array_texture(
  device: &wgpu::Device,
  label: &str,
  width: u32,
  height: u32,
  layers: u32,
  extra_usage: wgpu::TextureUsages,
) -> wgpu::Texture {
  create_texture(
    device,
    label,
    wgpu::Extent3d {
      width,
      height,
      depth_or_array_layers: layers,
    },
    wgpu::TextureDimension::D2,
    mip_count(width.min(height)),
    extra_usage,
  )
}

/// A single-mip view of `texture` as a 2D array.
pub fn array_mip_view(texture: &wgpu::Texture, mip: u32) -> wgpu::TextureView {
  texture.create_view(&wgpu::TextureViewDescriptor {
    label: Some("VistaWASM mip view"),
    dimension: Some(wgpu::TextureViewDimension::D2Array),
    base_mip_level: mip,
    mip_level_count: Some(1),
    ..Default::default()
  })
}

/// Full view of `texture` as a 2D array.
pub fn array_view(texture: &wgpu::Texture) -> wgpu::TextureView {
  texture.create_view(&wgpu::TextureViewDescriptor {
    label: Some("VistaWASM array view"),
    dimension: Some(wgpu::TextureViewDimension::D2Array),
    ..Default::default()
  })
}

/// Builds mip chains with `mipgen.wgsl`.
pub struct MipGenerator {
  module: wgpu::ShaderModule,
  pipeline: wgpu::ComputePipeline,
  /// Counts coverage; made when an alpha-tested texture first needs it.
  count: std::cell::OnceCell<wgpu::ComputePipeline>,
}

fn mip_pipeline(
  device: &wgpu::Device,
  module: &wgpu::ShaderModule,
  entry: &str,
) -> wgpu::ComputePipeline {
  device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
    label: Some("VistaWASM mip pipeline"),
    layout: None,
    module,
    entry_point: Some(entry),
    compilation_options: wgpu::PipelineCompilationOptions::default(),
    cache: None,
  })
}

impl MipGenerator {
  /// Compile the mip pipeline.
  pub fn new(device: &wgpu::Device) -> Self {
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
      label: Some("VistaWASM mip shader"),
      source: wgpu::ShaderSource::Wgsl(crate::render::shaders::MIPGEN.into()),
    });
    let pipeline = mip_pipeline(device, &module, "downsample");

    Self {
      module,
      pipeline,
      count: std::cell::OnceCell::new(),
    }
  }

  /// A uniform `MipParams` for one level.
  fn params(
    device: &wgpu::Device,
    mode: MipMode,
    level: u32,
    reference: u32,
    layers: u64,
  ) -> wgpu::Buffer {
    let [mode, opaque_below, linear_from, odd_linear] = mode.params();
    let buffer = device.create_buffer(&wgpu::BufferDescriptor {
      label: Some("VistaWASM mip params"),
      size: 32,
      usage: wgpu::BufferUsages::UNIFORM,
      mapped_at_creation: true,
    });

    if let Ok(mut range) = buffer.slice(..).get_mapped_range_mut() {
      range.copy_from_slice(bytemuck::cast_slice(&[
        mode,
        opaque_below,
        linear_from,
        odd_linear,
        level,
        reference,
        layers as u32,
        (layers >> 32) as u32,
      ]));
    }

    buffer.unmap();
    buffer
  }

  /// Record every mip level of an rgba8 2D (array) texture. Alpha-tested
  /// layers keep mip 0's coverage at every level.
  pub fn generate(
    &self,
    device: &wgpu::Device,
    encoder: &mut wgpu::CommandEncoder,
    texture: &wgpu::Texture,
    mode: MipMode,
  ) {
    self.generate_layers(device, encoder, texture, mode, u64::MAX);
  }

  /// [`Self::generate`] for the layers in `layers` only (one bit each; a
  /// texture with more than 64 layers redoes the rest too).
  pub fn generate_layers(
    &self,
    device: &wgpu::Device,
    encoder: &mut wgpu::CommandEncoder,
    texture: &wgpu::Texture,
    mode: MipMode,
    layers_wanted: u64,
  ) {
    let layers = texture.depth_or_array_layers();
    let reference = texture.width() * texture.height();
    let coverage = !matches!(mode, MipMode::Colour | MipMode::Linear);
    // 16 levels of 17 counts per layer.
    let counts = coverage.then(|| {
      device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("VistaWASM coverage counts"),
        size: u64::from(layers) * 16 * 17 * 4,
        usage: wgpu::BufferUsages::STORAGE,
        mapped_at_creation: false,
      })
    });
    let count = counts.as_ref().map(|_| {
      self
        .count
        .get_or_init(|| mip_pipeline(device, &self.module, "count"))
    });
    let dispatch = |pipeline: &wgpu::ComputePipeline,
                    encoder: &mut wgpu::CommandEncoder,
                    entries: &[wgpu::BindGroupEntry<'_>],
                    size: [u32; 2]| {
      let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("VistaWASM mip bind group"),
        layout: &pipeline.get_bind_group_layout(0),
        entries,
      });
      let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
        label: Some("VistaWASM mip pass"),
        timestamp_writes: None,
      });
      pass.set_pipeline(pipeline);
      pass.set_bind_group(0, &bind_group, &[]);
      pass.dispatch_workgroups(size[0].div_ceil(8), size[1].div_ceil(8), layers);
    };

    for mip in 0..texture.mip_level_count() {
      let width = (texture.width() >> mip).max(1);
      let height = (texture.height() >> mip).max(1);
      let params = Self::params(device, mode, mip, reference, layers_wanted);

      if let (Some(counts), Some(count)) = (&counts, count) {
        // Mip 0's coverage, then each level's at every candidate scale.
        let source = array_mip_view(texture, mip.saturating_sub(1));
        dispatch(
          count,
          encoder,
          &[
            storage_entry(0, &source),
            buffer_entry(2, &params),
            buffer_entry(3, counts),
          ],
          [width, height],
        );
      }

      if mip == 0 {
        continue;
      }

      let source = array_mip_view(texture, mip - 1);
      let destination = array_mip_view(texture, mip);
      let placeholder;
      let counts = match &counts {
        Some(counts) => counts,
        None => {
          placeholder = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("VistaWASM no coverage counts"),
            size: 16 * 17 * 4,
            usage: wgpu::BufferUsages::STORAGE,
            mapped_at_creation: false,
          });
          &placeholder
        }
      };
      dispatch(
        &self.pipeline,
        encoder,
        &[
          storage_entry(0, &source),
          storage_entry(1, &destination),
          buffer_entry(2, &params),
          buffer_entry(3, counts),
        ],
        [width, height],
      );
    }
  }

  /// Average each species' impostors into its canopy colour, into
  /// `canopy` (a vec4 per species), from the impostor atlas's level
  /// `mip`.
  pub fn average_canopy(
    &self,
    device: &wgpu::Device,
    encoder: &mut wgpu::CommandEncoder,
    impostors: &wgpu::Texture,
    mip: u32,
    variants: u32,
    canopy: &wgpu::Buffer,
  ) {
    let pipeline = mip_pipeline(device, &self.module, "average_canopy");
    let source = array_mip_view(impostors, mip);
    let buffer = device.create_buffer(&wgpu::BufferDescriptor {
      label: Some("VistaWASM canopy params"),
      size: 32,
      usage: wgpu::BufferUsages::UNIFORM,
      mapped_at_creation: true,
    });

    if let Ok(mut range) = buffer.slice(..).get_mapped_range_mut() {
      range.copy_from_slice(bytemuck::cast_slice(&[variants, 0u32, 0, 0, 0, 0, 0, 0]));
    }

    buffer.unmap();
    let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
      label: Some("VistaWASM canopy bind group"),
      layout: &pipeline.get_bind_group_layout(0),
      entries: &[
        storage_entry(0, &source),
        buffer_entry(2, &buffer),
        buffer_entry(4, canopy),
      ],
    });
    let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
      label: Some("VistaWASM canopy colour pass"),
      timestamp_writes: None,
    });
    pass.set_pipeline(&pipeline);
    pass.set_bind_group(0, &bind_group, &[]);
    pass.dispatch_workgroups(crate::render::tree_models::SPECIES_COUNT as u32, 1, 1);
  }
}

fn buffer_entry(binding: u32, buffer: &wgpu::Buffer) -> wgpu::BindGroupEntry<'_> {
  wgpu::BindGroupEntry {
    binding,
    resource: buffer.as_entire_binding(),
  }
}

fn storage_entry(binding: u32, view: &wgpu::TextureView) -> wgpu::BindGroupEntry<'_> {
  wgpu::BindGroupEntry {
    binding,
    resource: wgpu::BindingResource::TextureView(view),
  }
}

/// A `texture_gen.wgsl` pipeline for one entry point. Each bake compiles
/// only the entries it runs.
fn gen_pipeline(device: &wgpu::Device, entry: &str) -> wgpu::ComputePipeline {
  let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
    label: Some("VistaWASM texture generation shader"),
    source: wgpu::ShaderSource::Wgsl(crate::render::shaders::TEXTURE_GEN.into()),
  });

  device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
    label: Some("VistaWASM texture generation pipeline"),
    layout: None,
    module: &module,
    entry_point: Some(entry),
    compilation_options: wgpu::PipelineCompilationOptions::default(),
    cache: None,
  })
}

/// Record one texture generation dispatch in its own pass.
fn dispatch_gen(
  device: &wgpu::Device,
  encoder: &mut wgpu::CommandEncoder,
  pipeline: &wgpu::ComputePipeline,
  entries: &[wgpu::BindGroupEntry<'_>],
  groups: [u32; 3],
) {
  let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
    label: Some("VistaWASM texture generation bind group"),
    layout: &pipeline.get_bind_group_layout(0),
    entries,
  });
  let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
    label: Some("VistaWASM texture generation pass"),
    timestamp_writes: None,
  });
  pass.set_pipeline(pipeline);
  pass.set_bind_group(0, &bind_group, &[]);
  pass.dispatch_workgroups(groups[0], groups[1], groups[2]);
}

/// The PCG hash of `texture_gen.wgsl`.
fn pcg(value: u32) -> u32 {
  let state = value.wrapping_mul(747_796_405).wrapping_add(2_891_336_453);
  let word = ((state >> ((state >> 28) + 4)) ^ state).wrapping_mul(277_803_737);
  (word >> 22) ^ word
}

fn unit(hash: u32) -> f32 {
  (hash & 0xff_ffff) as f32 / 16_777_215.0
}

/// The leaves of the three leaf-clump layers (broadleaf, tropical and
/// oak: `clump_of` in `texture_gen.wgsl`, in that order), placed along
/// their twig: per leaf its base and direction, then its size and where
/// its colour lies between the clump's two. Each clump's leaves alternate
/// sides, with one at the tip, and stay on the card.
fn leaf_placements() -> Vec<[f32; 4]> {
  let mut placements = Vec::with_capacity(120);

  for (count, length, seed) in [(26u32, 0.2f32, 181u32), (10, 0.4, 191), (24, 0.24, 241)] {
    let bend = (unit(pcg(seed)) - 0.5) * 0.25;

    for i in 0..count {
      let h = pcg(seed.wrapping_add(i.wrapping_mul(7919)));
      let t = (i as f32 + 0.5) / count as f32;
      let at = [
        0.5 + bend * t * t + (unit(pcg(h.wrapping_add(1))) - 0.5) * 0.3,
        0.05 + t * 0.62,
      ];
      let side = if i % 2 == 0 { 1.0 } else { -1.0 };
      let angle = if i == count - 1 {
        (unit(h) - 0.5) * 0.4
      } else {
        side * (0.55 + unit(h) * 0.75)
      };
      let direction = [angle.portable_sin(), angle.portable_cos()];
      let room_x = if direction[0] < 0.0 {
        (at[0] - 0.03) / (-direction[0]).max(1e-3)
      } else {
        (0.97 - at[0]) / direction[0].max(1e-3)
      };
      let room = room_x.min((0.97 - at[1]) / direction[1].max(1e-3));
      let size = (length * (0.75 + unit(pcg(h.wrapping_add(3))) * 0.5)).min(room);
      placements.push([at[0], at[1], direction[0], direction[1]]);
      placements.push([size, unit(pcg(h.wrapping_add(9))), 0.0, 0.0]);
    }
  }

  placements
}

/// A uniform holding which terrain (x) and flora (y) layers to bake, one
/// bit per layer.
fn layer_mask(
  device: &wgpu::Device,
  queue: &wgpu::Queue,
  terrain: u32,
  flora: u32,
) -> wgpu::Buffer {
  let buffer = device.create_buffer(&wgpu::BufferDescriptor {
    label: Some("VistaWASM layers to bake"),
    size: 16,
    usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
    mapped_at_creation: false,
  });
  queue.write_buffer(&buffer, 0, bytemuck::cast_slice(&[terrain, flora, 0u32, 0]));
  buffer
}

/// Bake the water ripples and the 2D noise, and create the terrain and
/// flora arrays and a cloud placeholder, all baked when first needed (see
/// [`WorldTextures::bake_terrain`], [`WorldTextures::bake_flora`] and
/// [`WorldTextures::bake_cloud_noise`]).
pub fn bake_world_textures(
  device: &wgpu::Device,
  queue: &wgpu::Queue,
  mips: &MipGenerator,
) -> WorldTextures {
  let terrain_albedo = create_array_texture(
    device,
    "VistaWASM terrain albedo",
    TERRAIN_TEXTURE_SIZE,
    TERRAIN_TEXTURE_SIZE,
    TERRAIN_LAYERS,
    wgpu::TextureUsages::empty(),
  );
  let terrain_normal = create_array_texture(
    device,
    "VistaWASM terrain normals",
    TERRAIN_TEXTURE_SIZE,
    TERRAIN_TEXTURE_SIZE,
    TERRAIN_LAYERS,
    wgpu::TextureUsages::empty(),
  );
  let flora = create_array_texture(
    device,
    "VistaWASM flora textures",
    FLORA_TEXTURE_SIZE,
    FLORA_TEXTURE_SIZE,
    crate::render::tree_models::layers::TOTAL,
    wgpu::TextureUsages::empty(),
  );
  let water = create_array_texture(
    device,
    "VistaWASM water texture",
    WATER_TEXTURE_SIZE,
    WATER_TEXTURE_SIZE,
    1,
    wgpu::TextureUsages::empty(),
  );
  let noise = create_array_texture(
    device,
    "VistaWASM noise texture",
    NOISE_TEXTURE_SIZE,
    NOISE_TEXTURE_SIZE,
    1,
    wgpu::TextureUsages::empty(),
  );
  let cloud = create_texture(
    device,
    "VistaWASM cloud noise placeholder",
    wgpu::Extent3d {
      width: 1,
      height: 1,
      depth_or_array_layers: 1,
    },
    wgpu::TextureDimension::D3,
    1,
    wgpu::TextureUsages::empty(),
  );
  let single_mip0 = |texture: &wgpu::Texture| {
    texture.create_view(&wgpu::TextureViewDescriptor {
      label: Some("VistaWASM mip 0"),
      dimension: Some(wgpu::TextureViewDimension::D2),
      base_mip_level: 0,
      mip_level_count: Some(1),
      ..Default::default()
    })
  };
  let water_mip0 = single_mip0(&water);
  let noise_mip0 = single_mip0(&noise);
  let cloud_view = cloud.create_view(&wgpu::TextureViewDescriptor::default());
  let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
    label: Some("VistaWASM texture bake"),
  });
  dispatch_gen(
    device,
    &mut encoder,
    &gen_pipeline(device, "gen_water"),
    &[storage_entry(3, &water_mip0)],
    [WATER_TEXTURE_SIZE / 8, WATER_TEXTURE_SIZE / 8, 1],
  );
  dispatch_gen(
    device,
    &mut encoder,
    &gen_pipeline(device, "gen_noise"),
    &[storage_entry(4, &noise_mip0)],
    [NOISE_TEXTURE_SIZE / 8, NOISE_TEXTURE_SIZE / 8, 1],
  );
  mips.generate(device, &mut encoder, &water, MipMode::Linear);
  mips.generate(device, &mut encoder, &noise, MipMode::Linear);
  queue.submit(Some(encoder.finish()));

  let view_2d = |texture: &wgpu::Texture| {
    texture.create_view(&wgpu::TextureViewDescriptor {
      label: Some("VistaWASM 2D view"),
      dimension: Some(wgpu::TextureViewDimension::D2),
      ..Default::default()
    })
  };

  WorldTextures {
    terrain_albedo: array_view(&terrain_albedo),
    terrain_normal: array_view(&terrain_normal),
    flora: array_view(&flora),
    water: view_2d(&water),
    noise: view_2d(&noise),
    cloud: cloud_view,
    terrain_albedo_texture: terrain_albedo,
    terrain_normal_texture: terrain_normal,
    flora_texture: flora,
    terrain_baked: 0,
    flora_baked: 0,
    cloud_baked: false,
    _textures: vec![water, noise, cloud],
  }
}

impl WorldTextures {
  /// Bake the terrain material layers in `layers` (one bit per layer) that
  /// are not baked yet: albedo and height first, then normal, occlusion
  /// and roughness from the heights. Then rebuild both arrays' mips.
  pub fn bake_terrain(
    &mut self,
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    mips: &MipGenerator,
    layers: u32,
  ) {
    let missing = layers & !self.terrain_baked & ((1 << TERRAIN_LAYERS) - 1);

    if missing == 0 {
      return;
    }

    self.terrain_baked |= missing;
    let mask = layer_mask(device, queue, missing, 0);
    let heights = device.create_buffer(&wgpu::BufferDescriptor {
      label: Some("VistaWASM terrain material heights"),
      size: (TERRAIN_TEXTURE_SIZE * TERRAIN_TEXTURE_SIZE * TERRAIN_LAYERS * 4) as u64,
      usage: wgpu::BufferUsages::STORAGE,
      mapped_at_creation: false,
    });
    let albedo_mip0 = array_mip_view(&self.terrain_albedo_texture, 0);
    let normal_mip0 = array_mip_view(&self.terrain_normal_texture, 0);
    let groups = [
      TERRAIN_TEXTURE_SIZE / 8,
      TERRAIN_TEXTURE_SIZE / 8,
      TERRAIN_LAYERS,
    ];
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
      label: Some("VistaWASM terrain texture bake"),
    });
    dispatch_gen(
      device,
      &mut encoder,
      &gen_pipeline(device, "gen_terrain"),
      &[
        storage_entry(0, &albedo_mip0),
        buffer_entry(6, &heights),
        buffer_entry(7, &mask),
      ],
      groups,
    );
    dispatch_gen(
      device,
      &mut encoder,
      &gen_pipeline(device, "gen_terrain_normals"),
      &[
        storage_entry(1, &normal_mip0),
        buffer_entry(6, &heights),
        buffer_entry(7, &mask),
      ],
      groups,
    );
    mips.generate(
      device,
      &mut encoder,
      &self.terrain_albedo_texture,
      MipMode::Colour,
    );
    mips.generate(
      device,
      &mut encoder,
      &self.terrain_normal_texture,
      MipMode::Linear,
    );
    queue.submit(Some(encoder.finish()));
  }

  /// Bake the flora layers in `layers` (one bit per layer) that are not
  /// baked yet, with the normal maps of the leaf layers among them, then
  /// rebuild the flora mips.
  pub fn bake_flora(
    &mut self,
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    mips: &MipGenerator,
    layers: u32,
  ) {
    let missing =
      layers & !self.flora_baked & ((1 << crate::render::tree_models::layers::COUNT) - 1);
    self.flora_baked |= missing;
    self.bake_flora_layers(device, queue, mips, missing);
  }

  /// A host replaced leaf layer `layer`: its normal map turns flat.
  pub fn replaced_flora(&mut self, queue: &wgpu::Queue, layer: u32) {
    self.flora_baked |= 1 << layer;

    if let Some(normals) = crate::render::tree_models::layers::normal_layer(layer) {
      let flat = [128u8, 128, 0, 255].repeat((FLORA_TEXTURE_SIZE * FLORA_TEXTURE_SIZE) as usize);
      queue.write_texture(
        wgpu::TexelCopyTextureInfo {
          texture: &self.flora_texture,
          mip_level: 0,
          origin: wgpu::Origin3d {
            x: 0,
            y: 0,
            z: normals,
          },
          aspect: wgpu::TextureAspect::All,
        },
        &flat,
        wgpu::TexelCopyBufferLayout {
          offset: 0,
          bytes_per_row: Some(FLORA_TEXTURE_SIZE * 4),
          rows_per_image: Some(FLORA_TEXTURE_SIZE),
        },
        wgpu::Extent3d {
          width: FLORA_TEXTURE_SIZE,
          height: FLORA_TEXTURE_SIZE,
          depth_or_array_layers: 1,
        },
      );
    }
  }

  fn bake_flora_layers(
    &mut self,
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    mips: &MipGenerator,
    layers: u32,
  ) {
    if layers == 0 {
      return;
    }

    let normals = (0..crate::render::tree_models::layers::COUNT)
      .filter(|layer| layers & 1 << layer != 0)
      .filter_map(crate::render::tree_models::layers::normal_layer)
      .fold(0u64, |mask, layer| mask | 1 << layer);
    let mask = layer_mask(device, queue, 0, layers);
    let leaves = device.create_buffer(&wgpu::BufferDescriptor {
      label: Some("VistaWASM leaf placements"),
      size: 120 * 16,
      usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
      mapped_at_creation: false,
    });
    queue.write_buffer(&leaves, 0, bytemuck::cast_slice(&leaf_placements()));
    let mip0 = array_mip_view(&self.flora_texture, 0);
    let pipeline = gen_pipeline(device, "gen_flora");
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
      label: Some("VistaWASM flora texture bake"),
    });
    dispatch_gen(
      device,
      &mut encoder,
      &pipeline,
      &[
        storage_entry(2, &mip0),
        buffer_entry(7, &mask),
        buffer_entry(8, &leaves),
      ],
      [
        FLORA_TEXTURE_SIZE / 8,
        FLORA_TEXTURE_SIZE / 8,
        crate::render::tree_models::layers::COUNT,
      ],
    );
    mips.generate_layers(
      device,
      &mut encoder,
      &self.flora_texture,
      MipMode::Flora,
      u64::from(layers) | normals,
    );
    queue.submit(Some(encoder.finish()));
  }

  /// Bake the 3D cloud noise in place of its placeholder, once.
  pub fn bake_cloud_noise(&mut self, device: &wgpu::Device, queue: &wgpu::Queue) {
    if self.cloud_baked {
      return;
    }

    self.cloud_baked = true;
    let cloud = create_texture(
      device,
      "VistaWASM cloud noise",
      wgpu::Extent3d {
        width: CLOUD_TEXTURE_SIZE,
        height: CLOUD_TEXTURE_SIZE,
        depth_or_array_layers: CLOUD_TEXTURE_SIZE,
      },
      wgpu::TextureDimension::D3,
      1,
      wgpu::TextureUsages::empty(),
    );
    let view = cloud.create_view(&wgpu::TextureViewDescriptor::default());
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
      label: Some("VistaWASM cloud noise bake"),
    });
    dispatch_gen(
      device,
      &mut encoder,
      &gen_pipeline(device, "gen_cloud"),
      &[storage_entry(5, &view)],
      [
        CLOUD_TEXTURE_SIZE / 4,
        CLOUD_TEXTURE_SIZE / 4,
        CLOUD_TEXTURE_SIZE / 4,
      ],
    );
    queue.submit(Some(encoder.finish()));
    self.cloud = view;
    self._textures.push(cloud);
  }
}
