// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: mipgen (mipgen)
// Entry point: downsample, compile with /T cs_5_0 /E downsample
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) source -> t0  Texture2DArray (Sampled { kind: Float, multi: false })
//   @group(0) @binding(1) destination -> u0  RWTexture2DArray (Rgba8Unorm)
//   @group(0) @binding(2) params -> b0  constant buffer
//   @group(0) @binding(3) counts -> u1  RWByteAddressBuffer

struct MipParams {
  uint mode;
  uint opaque_below;
  uint linear_from;
  uint odd_linear;
  uint level;
  uint reference_texels;
  uint mask_low;
  uint mask_high;
};

static const uint CANDIDATES = 16u;
static const uint SLOTS = 17u;
static const uint LEVELS = 16u;

Texture2DArray<float4> source : register(t0);
RWTexture2DArray<unorm float4> destination : register(u0);
cbuffer params : register(b0) { MipParams params; }
RWByteAddressBuffer counts : register(u1);

float candidate_scale(uint k_1)
{
  return (0.85 + (float(k_1) * 0.1));
}

uint naga_mod(uint lhs, uint rhs) {
  return lhs % (rhs == 0u ? 1u : rhs);
}

bool wanted(uint layer)
{
  bool local_2 = (bool)0;

  uint _e3 = params.mask_high;
  uint _e6 = params.mask_low;
  uint bits = ((layer < 32u) ? _e6 : _e3);
  if (!((layer >= 64u))) {
    local_2 = (((bits >> naga_mod(layer, 32u)) & 1u) != 0u);
  } else {
    local_2 = true;
  }
  bool _e23 = local_2;
  return _e23;
}

uint layer_mode(uint layer_1)
{
  bool local_3 = (bool)0;
  bool local_4 = (bool)0;

  uint _e3 = params.opaque_below;
  if ((layer_1 < _e3)) {
    return 0u;
  }
  uint _e8 = params.linear_from;
  if (!((layer_1 >= _e8))) {
    uint _e15 = params.odd_linear;
    if ((_e15 == 1u)) {
      local_4 = (naga_mod(layer_1, 2u) == 1u);
    } else {
      local_4 = false;
    }
    bool _e25 = local_4;
    local_3 = _e25;
  } else {
    local_3 = true;
  }
  bool _e27 = local_3;
  if (_e27) {
    return 2u;
  }
  uint _e31 = params.mode;
  return _e31;
}

uint slot(uint layer_2, uint level, uint k_2)
{
  return ((((layer_2 * LEVELS) + level) * SLOTS) + k_2);
}

float4 downsampled(int2 texel, int layer_3, uint mode)
{
  float3 colour = (0.0).xxx;
  float4 plain = (0.0).xxxx;
  float alpha = 0.0;
  int y = int(0);
  int x = (int)0;

  int2 base = asint(asuint(texel) * asuint(int(2)));
  uint2 loop_bound = uint2(4294967295u, 4294967295u);
  bool loop_init = true;
  while(true) {
    if (all(loop_bound == uint2(0u, 0u))) { break; }
    loop_bound -= uint2(loop_bound.y == 0u, 1u);
    if (!loop_init) {
      int _e52 = y;
      y = asint(asuint(_e52) + asuint(int(1)));
    }
    loop_init = false;
    int _e15 = y;
    if ((_e15 < int(2))) {
    } else {
      break;
    }
    {
      x = int(0);
      uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
      bool loop_init_1 = true;
      while(true) {
        if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
          int _e49 = x;
          x = asint(asuint(_e49) + asuint(int(1)));
        }
        loop_init_1 = false;
        int _e20 = x;
        if ((_e20 < int(2))) {
        } else {
          break;
        }
        {
          int _e24 = x;
          int _e25 = y;
          float4 value = source.Load(int4(asint(asuint(base) + asuint(int2(_e24, _e25))), layer_3, int(0)));
          float3 linear_ = ((mode == 2u) ? value.xyz : pow(value.xyz, (2.2).xxx));
          float3 _e38 = colour;
          colour = (_e38 + (linear_ * value.w));
          float4 _e42 = plain;
          plain = (_e42 + float4(linear_, value.w));
          float _e46 = alpha;
          alpha = (_e46 + value.w);
        }
      }
    }
  }
  if ((mode == 1u)) {
    float4 _e57 = plain;
    float3 _e62 = colour;
    float _e63 = alpha;
    float _e68 = alpha;
    float3 rgb = ((_e68 > 0.0001) ? (_e62 / (max(_e63, 0.0001)).xxx) : (_e57.xyz / (4.0).xxx));
    float _e75 = alpha;
    return float4(pow(rgb, (0.45454547).xxx), (_e75 / 4.0));
  }
  if ((mode == 2u)) {
    float4 _e81 = plain;
    return (_e81 / (4.0).xxxx);
  }
  float4 _e85 = plain;
  float _e94 = plain.w;
  return float4(pow((_e85.xyz / (4.0).xxx), (0.45454547).xxx), (_e94 / 4.0));
}

uint2 NagaRWDimensions2DArray(RWTexture2DArray<unorm float4> tex)
{
  uint4 ret;
  tex.GetDimensions(ret.x, ret.y, ret.z);
  return ret.xy;
}

[numthreads(8, 8, 1)]
void downsample(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  bool local_1 = (bool)0;
  float4 result = (float4)0;
  float best = 1.0;
  float error = 2.0;
  uint passing = 0u;
  uint k = 0u;

  uint2 size = NagaRWDimensions2DArray(destination);
  uint layer_4 = id.z;
  if (!((id.x >= size.x))) {
    local = (id.y >= size.y);
  } else {
    local = true;
  }
  bool _e14 = local;
  if (!(_e14)) {
    const bool _e18 = wanted(layer_4);
    local_1 = !(_e18);
  } else {
    local_1 = true;
  }
  bool _e21 = local_1;
  if (_e21) {
    return;
  }
  const uint _e22 = layer_mode(layer_4);
  const float4 _e26 = downsampled(int2(id.xy), int(layer_4), _e22);
  result = _e26;
  if ((_e22 == 1u)) {
    const uint _e33 = slot(layer_4, 0u, CANDIDATES);
    uint _e35; counts.InterlockedOr(_e33*4, 0, _e35);
    uint _e39 = params.reference_texels;
    float wanted_1 = (float(_e35) / float(max(_e39, 1u)));
    float texels = float((size.x * size.y));
    uint2 loop_bound_2 = uint2(4294967295u, 4294967295u);
    bool loop_init_2 = true;
    while(true) {
      if (all(loop_bound_2 == uint2(0u, 0u))) { break; }
      loop_bound_2 -= uint2(loop_bound_2.y == 0u, 1u);
      if (!loop_init_2) {
        uint _e80 = k;
        k = (_e80 + 1u);
      }
      loop_init_2 = false;
      uint _e56 = k;
      if ((_e56 < CANDIDATES)) {
      } else {
        break;
      }
      {
        uint _e59 = passing;
        uint _e63 = params.level;
        uint _e64 = k;
        const uint _e65 = slot(layer_4, _e63, _e64);
        uint _e67; counts.InterlockedOr(_e65*4, 0, _e67);
        passing = (_e59 + _e67);
        uint _e69 = passing;
        float share = (float(_e69) / texels);
        float _e74 = error;
        if ((abs((share - wanted_1)) < _e74)) {
          error = abs((share - wanted_1));
          uint _e78 = k;
          const float _e79 = candidate_scale(_e78);
          best = _e79;
        }
      }
    }
    float _e85 = result.w;
    float _e86 = best;
    result.w = min((_e85 * _e86), 1.0);
  }
  float4 _e94 = result;
  destination[int3(int2(id.xy), int(layer_4))] = _e94;
  return;
}
