// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: grass_generate (ground + lattice + generate_common + grass_generate)
// Entry point: cull_main, compile with /T cs_5_0 /E cull_main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(7) tufts -> u0  RWByteAddressBuffer
//   @group(0) @binding(8) counts -> u1  RWByteAddressBuffer
//   @group(0) @binding(10) drawn -> u2  RWByteAddressBuffer
//   @group(0) @binding(11) args -> u3  RWByteAddressBuffer

struct GrassParams {
  float4 terrain;
  float4 terrain2_;
  float4 mesh;
  float4 rules;
  uint4 shape;
  float4 camera;
  float4 view;
  float4 planes[6];
  uint4 classes[8];
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const int CLUMP_CELLS = int(4);
static const uint CLUMP_SALT = 1013904242u;
static const float JITTER = 0.45;
static const float FADE_BAND = 0.05;
static const float MAX_GROWTH = 1.8;
static const uint BIN_WORDS = 11u;
static const float SLOPE_SPAN = 1.5;
static const float BOULDER_PITCH = 2.0;
static const uint BOULDER_SALT = 2135587861u;
static const float BOULDER_WATER_LINE = 0.3;
static const float BOULDER_WATER_CLEARANCE = 1.0;
static const float SIZE_EXPONENT = 1.2;
static const float FOOTPRINT = 0.55;
static const float TALUS_PROBABILITY = 0.6;
static const float STONE_PITCH = 1.0;
static const float STONE_REACH = 1.5;
static const float COBBLE_METRES = 0.5;
static const float GRASS_PITCH = 0.35;
static const uint TRAITS_SALT = 625341585u;
static const float GRASS_WATER_LINE = 0.5;
static const float NEAR_WATER_METRES = 12.0;
static const float FLOOR_DENSITY = 0.35;
static const float TUNDRA_GRASS_HEIGHT = 0.4;
static const float FERN = 2.0;
static const float UNDERGROWTH = 3.0;
static const float MAX_PLANTING_SLOPE = 50.0;
static const float TUFT_METRES = 0.6;
static const float HERB_METRES = 3.0;
static const float RIPARIAN_TUFTS = 0.5;
static const float RIPARIAN_HERBS = 0.12;
static const uint ALPINE_TRANSITION = 15u;
static const uint NEAR_SLOTS = 8192u;
static const float CARD_METRES = 15.0;

cbuffer params : register(b0) { GrassParams params; }
RWByteAddressBuffer tufts : register(u0);
RWByteAddressBuffer counts : register(u1);
RWByteAddressBuffer drawn : register(u2);
RWByteAddressBuffer args : register(u3);

float4 thinning(float distance_, float radius, float floor_)
{
  float share = (float)0;

  float ratio = (radius / max(distance_, 0.001));
  float keep = clamp((ratio * ratio), floor_, 1.0);
  float band = min(FADE_BAND, (keep - floor_));
  float end = min((keep + band), 1.0);
  share = keep;
  if ((band > 0.0)) {
    float cut = (((keep + band) - end) / band);
    share = (keep + ((band / 3.0) * (1.0 - ((cut * cut) * cut))));
  }
  float _e29 = share;
  float growth = sqrt((1.0 / max(_e29, 0.001)));
  float height = min(growth, MAX_GROWTH);
  return float4(keep, band, height, (growth / height));
}

float thinning_fade(float4 t, float u)
{
  if ((u < t.x)) {
    return 1.0;
  }
  if ((t.y > 0.0)) {
    return clamp((((t.x + t.y) - u) / t.y), 0.0, 1.0);
  }
  return 0.0;
}

float smoothed(float t_1)
{
  float x = clamp(t_1, 0.0, 1.0);
  return ((x * x) * (3.0 - (2.0 * x)));
}

uint naga_div(uint lhs, uint rhs) {
  return lhs / (rhs == 0u ? 1u : rhs);
}

uint naga_mod(uint lhs, uint rhs) {
  return lhs % (rhs == 0u ? 1u : rhs);
}

[numthreads(64, 1, 1)]
void cull_main(uint3 id : SV_DispatchThreadID)
{
  uint group = 0u;
  uint c = 1u;
  bool local = (bool)0;
  bool local_1 = (bool)0;
  int p = int(0);
  uint place = NEAR_SLOTS;

  uint index = id.x;
  uint _e5 = params.shape.z;
  if ((index >= _e5)) {
    return;
  }
  uint2 loop_bound = uint2(4294967295u, 4294967295u);
  bool loop_init = true;
  while(true) {
    if (all(loop_bound == uint2(0u, 0u))) { break; }
    loop_bound -= uint2(loop_bound.y == 0u, 1u);
    if (!loop_init) {
      uint _e25 = c;
      c = (_e25 + 1u);
    }
    loop_init = false;
    uint _e11 = c;
    uint _e15 = params.shape.y;
    if ((_e11 < _e15)) {
    } else {
      break;
    }
    {
      uint _e19 = c;
      uint _e22 = params.classes[_e19].y;
      if ((index >= _e22)) {
        uint _e24 = c;
        group = _e24;
      }
    }
  }
  uint _e30 = group;
  uint4 spec = params.classes[_e30];
  uint offset = (index - spec.y);
  uint slot = (spec.x + naga_div(offset, spec.z));
  uint _e43; counts.InterlockedOr(slot*4, 0, _e43);
  if ((naga_mod(offset, spec.z) >= min(_e43, spec.z))) {
    return;
  }
  uint base = (index * 7u);
  float _e51 = asfloat(tufts.Load(base*4));
  float _e56 = asfloat(tufts.Load((base + 1u)*4));
  float _e61 = asfloat(tufts.Load((base + 2u)*4));
  float3 position = float3(_e51, _e56, _e61);
  float4 _e65 = params.camera;
  float distance_1 = length((position - _e65.xyz));
  float _e72 = params.view.x;
  if ((distance_1 > _e72)) {
    return;
  }
  float style = asfloat(tufts.Load((base + 6u)*4));
  float kind = floor(style);
  float _e83 = params.camera.w;
  const float4 _e85 = thinning(distance_1, _e83, 0.0);
  const float _e87 = thinning_fade(_e85, frac(style));
  float start = params.view.w;
  float _e96 = params.view.x;
  const float _e101 = smoothed(((distance_1 - start) / max((_e96 - start), 1.0)));
  float handover = (1.0 - _e101);
  if (!((_e87 <= 0.0))) {
    if ((handover < 1.0)) {
      local_1 = (frac(style) >= (handover * (_e85.x + _e85.y)));
    } else {
      local_1 = false;
    }
    bool _e120 = local_1;
    local = _e120;
  } else {
    local = true;
  }
  bool _e122 = local;
  if (_e122) {
    return;
  }
  float _e127 = asfloat(tufts.Load((base + 3u)*4));
  float scale = ((_e127 * _e87) * _e85.z);
  float3 centre = (position + float3(0.0, (scale * 0.5), 0.0));
  float radius_1 = (((scale * 1.5) * _e85.w) + 0.5);
  uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
  bool loop_init_1 = true;
  while(true) {
    if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
    loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
    if (!loop_init_1) {
      int _e159 = p;
      p = asint(asuint(_e159) + asuint(int(1)));
    }
    loop_init_1 = false;
    int _e145 = p;
    if ((_e145 < int(6))) {
    } else {
      break;
    }
    {
      int _e150 = p;
      float4 plane = params.planes[_e150];
      if (((dot(plane.xyz, centre) + plane.w) < -(radius_1))) {
        return;
      }
    }
  }
  if ((distance_1 < CARD_METRES)) {
    uint _e169; args.InterlockedAdd(4, 1u, _e169);
    place = _e169;
    uint _e170 = place;
    if ((_e170 >= NEAR_SLOTS)) {
      uint _e176; args.InterlockedAdd(4, -1u, _e176);
    }
  }
  uint _e177 = place;
  if ((_e177 >= NEAR_SLOTS)) {
    uint _e184; args.InterlockedAdd(20, 1u, _e184);
    place = (NEAR_SLOTS + _e184);
  }
  uint _e186 = place;
  uint out_ = (_e186 * 7u);
  drawn.Store(out_*4, asuint(position.x));
  drawn.Store((out_ + 1u)*4, asuint(position.y));
  drawn.Store((out_ + 2u)*4, asuint(position.z));
  drawn.Store((out_ + 3u)*4, asuint(scale));
  float _e214 = asfloat(tufts.Load((base + 4u)*4));
  drawn.Store((out_ + 4u)*4, asuint(_e214));
  float _e223 = asfloat(tufts.Load((base + 5u)*4));
  drawn.Store((out_ + 5u)*4, asuint(_e223));
  drawn.Store((out_ + 6u)*4, asuint((kind + min(((_e85.w - 1.0) * 0.25), 0.999))));
  return;
}
