// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: grass_generate (ground + lattice + generate_common + grass_generate)
// Entry point: generate_main, compile with /T cs_5_0 /E generate_main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(1) heights -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(2) surface_texture -> t1  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(3) banks_texture -> t2  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(4) cover_texture -> t3  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(5) bins -> t4  ByteAddressBuffer
//   @group(0) @binding(6) jobs -> t5  ByteAddressBuffer
//   @group(0) @binding(7) tufts -> u0  RWByteAddressBuffer
//   @group(0) @binding(8) counts -> u1  RWByteAddressBuffer
//   @group(0) @binding(9) grass_texture -> t6  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(12) grass_mask -> t7  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(13) mask_sampler -> s0  SamplerState

struct Job {
  int2 tile;
  uint first;
  uint capacity;
  uint slot;
  float keep;
  uint2 unused;
};

struct Mapping {
  float4 terrain;
  float4 terrain2_;
  float inverse;
  int _end_pad_0;
  int _end_pad_1;
  int _end_pad_2;
};

struct NearChannel {
  float edge;
  uint base;
};

struct GrassParams {
  float4 terrain;
  float4 terrain2_;
  float4 mesh;
  float4 rules;
  uint4 shape;
  float4 camera;
  float4 view;
  float4 planes[6];
  uint4 classes[8];
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const int CLUMP_CELLS = int(4);
static const uint CLUMP_SALT = 1013904242u;
static const float JITTER = 0.45;
static const float FADE_BAND = 0.05;
static const float MAX_GROWTH = 1.8;
static const uint BIN_WORDS = 11u;
static const float SLOPE_SPAN = 1.5;
static const float BOULDER_PITCH = 2.0;
static const uint BOULDER_SALT = 2135587861u;
static const float BOULDER_WATER_LINE = 0.3;
static const float BOULDER_WATER_CLEARANCE = 1.0;
static const float SIZE_EXPONENT = 1.2;
static const float FOOTPRINT = 0.55;
static const float TALUS_PROBABILITY = 0.6;
static const float STONE_PITCH = 1.0;
static const float STONE_REACH = 1.5;
static const float COBBLE_METRES = 0.5;
static const float GRASS_PITCH = 0.35;
static const uint TRAITS_SALT = 625341585u;
static const float GRASS_WATER_LINE = 0.5;
static const float NEAR_WATER_METRES = 12.0;
static const float FLOOR_DENSITY = 0.35;
static const float TUNDRA_GRASS_HEIGHT = 0.4;
static const float FERN = 2.0;
static const float UNDERGROWTH = 3.0;
static const float MAX_PLANTING_SLOPE = 50.0;
static const float TUFT_METRES = 0.6;
static const float HERB_METRES = 3.0;
static const float RIPARIAN_TUFTS = 0.5;
static const float RIPARIAN_HERBS = 0.12;
static const uint ALPINE_TRANSITION = 15u;
static const uint NEAR_SLOTS = 8192u;
static const float CARD_METRES = 15.0;

Texture2D<float4> heights_4 : register(t0);
Texture2D<float4> surface_texture : register(t1);
Texture2D<float4> banks_texture : register(t2);
Texture2D<float4> cover_texture : register(t3);
ByteAddressBuffer bins : register(t4);
ByteAddressBuffer jobs : register(t5);
cbuffer params : register(b0) { GrassParams params; }
RWByteAddressBuffer tufts : register(u0);
RWByteAddressBuffer counts : register(u1);
Texture2D<float4> grass_texture : register(t6);
Texture2D<float4> grass_mask : register(t7);
SamplerState mask_sampler : register(s0);

float density_multiplier(float value)
{
  float byte = round((value * 255.0));
  return ((byte > 128.0) ? (1.0 + ((byte - 128.0) / 127.0)) : (byte / 128.0));
}

float hash12_(float2 p)
{
  float3 p3_ = (float3)0;

  p3_ = frac((float3(p.x, p.y, p.x) * 0.1031));
  float3 _e9 = p3_;
  float3 _e10 = p3_;
  float3 _e11 = p3_;
  p3_ = (_e9 + (dot(_e10, (_e11.yzx + (33.33).xxx))).xxx);
  float _e20 = p3_.x;
  float _e22 = p3_.y;
  float _e25 = p3_.z;
  return frac(((_e20 + _e22) * _e25));
}

float skirt_height(float edge, float sea, float distance_, float noise_)
{
  float foot = min(edge, (sea - 60.0));
  if ((distance_ >= SKIRT_METRES)) {
    return (foot - ((distance_ - SKIRT_METRES) * 0.08));
  }
  float s = smoothstep(0.0, 1.0, (distance_ / SKIRT_METRES));
  return (lerp(edge, foot, s) + (((((edge - foot) * 0.6) * noise_) * s) * (1.0 - s)));
}

float skirt_noise(float2 xz)
{
  float2 p_1 = (xz / (700.0).xx);
  float2 cell_2 = floor(p_1);
  float2 f = (p_1 - cell_2);
  float2 u_1 = ((f * f) * ((3.0).xx - (2.0 * f)));
  const float _e13 = hash12_(cell_2);
  const float _e18 = hash12_((cell_2 + float2(1.0, 0.0)));
  float top = lerp(_e13, _e18, u_1.x);
  const float _e25 = hash12_((cell_2 + float2(0.0, 1.0)));
  const float _e30 = hash12_((cell_2 + float2(1.0, 1.0)));
  float bottom = lerp(_e25, _e30, u_1.x);
  return ((lerp(top, bottom, u_1.y) * 2.0) - 1.0);
}

int2 naga_f2i32(float2 value) {
  return int2(clamp(value, -2147483600.0, 2147483500.0));
}

float texel_height(Texture2D<float4> heights, float4 terrain2_, float2 texel)
{
  float2 clamped = clamp(texel, (0.0).xx, (terrain2_.xy - (1.001).xx));
  float2 base_1 = floor(clamped);
  float2 f_1 = (clamped - base_1);
  int2 i = naga_f2i32(base_1);
  float4 _e14 = heights.Load(int3(i, int(0)));
  float h00_ = _e14.x;
  float4 _e21 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(1), int(0)))), int(0)));
  float h10_ = _e21.x;
  float4 _e28 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(0), int(1)))), int(0)));
  float h01_ = _e28.x;
  float4 _e35 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(1), int(1)))), int(0)));
  float h11_ = _e35.x;
  return lerp(lerp(h00_, h10_, f_1.x), lerp(h01_, h11_, f_1.x), f_1.y);
}

float ground_height(Texture2D<float4> heights_1, float4 terrain, float4 terrain2_1, float2 xz_1)
{
  if ((terrain2_1.z < 0.5)) {
    return -100000.0;
  }
  const float _e12 = texel_height(heights_1, terrain2_1, ((xz_1 + terrain.xy) / terrain.zw));
  float outside = length(max((abs(xz_1) - terrain.xy), (0.0).xx));
  if ((outside <= 0.0)) {
    return _e12;
  }
  const float _e23 = skirt_noise(xz_1);
  const float _e24 = skirt_height(_e12, terrain2_1.w, outside, _e23);
  return _e24;
}

float band_offset(float grid)
{
  float g = abs(grid);
  float band_1 = floor((g / LOD_BAND_WIDTH));
  float step_ = exp2(band_1);
  return (sign(grid) * ((LOD_BAND_WIDTH * (step_ - 1.0)) + ((g - (LOD_BAND_WIDTH * band_1)) * step_)));
}

float band_grid(float offset)
{
  float band = (float)0;

  band = floor(log2(((offset / LOD_BAND_WIDTH) + 1.0)));
  float _e8 = band;
  float _e10 = band;
  band = (_e8 - ((offset < (LOD_BAND_WIDTH * (exp2(_e10) - 1.0))) ? 1.0 : 0.0));
  float _e20 = band;
  float _e22 = band;
  band = (_e20 + ((offset >= (LOD_BAND_WIDTH * (exp2((_e22 + 1.0)) - 1.0))) ? 1.0 : 0.0));
  float _e34 = band;
  float step_1 = exp2(_e34);
  float _e37 = band;
  return ((LOD_BAND_WIDTH * _e37) + floor(((offset - (LOD_BAND_WIDTH * (step_1 - 1.0))) / step_1)));
}

float2 mesh_cell(float sample_, float centre, float last, float reach)
{
  float grid_1 = (float)0;
  bool local_11 = (bool)0;
  bool local_12 = (bool)0;
  bool local_13 = (bool)0;
  bool local_14 = (bool)0;
  bool local_15 = (bool)0;
  bool local_16 = (bool)0;

  float offset_1 = (sample_ - centre);
  const float _e6 = band_grid(abs(offset_1));
  grid_1 = _e6;
  if ((offset_1 < 0.0)) {
    float _e10 = grid_1;
    grid_1 = (-(_e10) - 1.0);
  }
  float _e14 = grid_1;
  const float _e15 = band_offset(_e14);
  float low = clamp((centre + _e15), -(reach), (last + reach));
  float _e20 = grid_1;
  const float _e23 = band_offset((_e20 + 1.0));
  float high = clamp((centre + _e23), -(reach), (last + reach));
  if ((high > last)) {
    local_11 = (sample_ == low);
  } else {
    local_11 = false;
  }
  bool _e33 = local_11;
  if (_e33) {
    local_12 = (low == last);
  } else {
    local_12 = false;
  }
  bool _e38 = local_12;
  if (_e38) {
    local_13 = (last > 0.0);
  } else {
    local_13 = false;
  }
  bool _e44 = local_13;
  if (_e44) {
    float _e45 = grid_1;
    const float _e48 = band_offset((_e45 - 1.0));
    return float2(clamp((centre + _e48), -(reach), (last + reach)), low);
  }
  if ((low < 0.0)) {
    local_14 = (sample_ == high);
  } else {
    local_14 = false;
  }
  bool _e60 = local_14;
  if (_e60) {
    local_15 = (high == 0.0);
  } else {
    local_15 = false;
  }
  bool _e66 = local_15;
  if (_e66) {
    local_16 = (last > 0.0);
  } else {
    local_16 = false;
  }
  bool _e72 = local_16;
  if (_e72) {
    float _e73 = grid_1;
    const float _e76 = band_offset((_e73 + 2.0));
    return float2(high, clamp((centre + _e76), -(reach), (last + reach)));
  }
  return float2(low, high);
}

typedef float2 ret_Constructarray3_float2_[3];
ret_Constructarray3_float2_ Constructarray3_float2_(float2 arg0, float2 arg1, float2 arg2) {
  float2 ret[3] = { arg0, arg1, arg2 };
  return ret;
}

typedef float ret_Constructarray3_float_[3];
ret_Constructarray3_float_ Constructarray3_float_(float arg0, float arg1, float arg2) {
  float ret[3] = { arg0, arg1, arg2 };
  return ret;
}

float mesh_height(Texture2D<float4> heights_2, float4 terrain_1, float4 terrain2_2, float4 mesh, float2 xz_2)
{
  bool local_17 = (bool)0;
  bool local_18 = (bool)0;
  bool local_19 = (bool)0;
  bool local_20 = (bool)0;
  bool local_21 = (bool)0;
  bool local_22 = (bool)0;
  bool local_23 = (bool)0;
  float2 t = (float2)0;
  float2 corners[3] = (float2[3])0;
  float h[3] = Constructarray3_float_(0.0, 0.0, 0.0);
  int k = int(0);
  bool local_24 = (bool)0;
  bool local_25 = (bool)0;
  bool local_26 = (bool)0;

  if ((mesh.z > 0.0)) {
    local_17 = (terrain2_2.z > 0.5);
  } else {
    local_17 = false;
  }
  bool drawn = local_17;
  float metres = (drawn ? mesh.z : max(terrain_1.z, 0.001));
  float2 last_1 = round(((terrain_1.xy * 2.0) / (metres).xx));
  float2 sample_1 = ((xz_2 / (metres).xx) + (last_1 * 0.5));
  const float2 _e35 = mesh_cell(sample_1.x, mesh.x, last_1.x, mesh.w);
  const float2 _e40 = mesh_cell(sample_1.y, mesh.y, last_1.y, mesh.w);
  if (drawn) {
    local_18 = (_e35.x < _e35.y);
  } else {
    local_18 = false;
  }
  bool _e47 = local_18;
  if (_e47) {
    local_19 = (_e40.x < _e40.y);
  } else {
    local_19 = false;
  }
  bool _e54 = local_19;
  if (_e54) {
    local_20 = (sample_1.x >= _e35.x);
  } else {
    local_20 = false;
  }
  bool _e61 = local_20;
  if (_e61) {
    local_21 = (sample_1.x <= _e35.y);
  } else {
    local_21 = false;
  }
  bool _e68 = local_21;
  if (_e68) {
    local_22 = (sample_1.y >= _e40.x);
  } else {
    local_22 = false;
  }
  bool _e75 = local_22;
  if (_e75) {
    local_23 = (sample_1.y <= _e40.y);
  } else {
    local_23 = false;
  }
  bool inside = local_23;
  t = ((sample_1 - float2(_e35.x, _e40.x)) / max(float2((_e35.y - _e35.x), (_e40.y - _e40.x)), (1.0).xx));
  float2 _e101 = t;
  t = (inside ? _e101 : (0.0).xx);
  float _e104 = t.x;
  float _e106 = t.y;
  bool upper = ((_e104 + _e106) > 1.0);
  corners = Constructarray3_float2_(float2(_e35.x, _e40.y), float2(_e35.y, _e40.x), (upper ? float2(_e35.y, _e40.y) : float2(_e35.x, _e40.x)));
  float stride = (terrain_1.z / metres);
  uint2 loop_bound = uint2(4294967295u, 4294967295u);
  bool loop_init = true;
  while(true) {
    if (all(loop_bound == uint2(0u, 0u))) { break; }
    loop_bound -= uint2(loop_bound.y == 0u, 1u);
    if (!loop_init) {
      int _e180 = k;
      k = asint(asuint(_e180) + asuint(int(1)));
    }
    loop_init = false;
    int _e134 = k;
    if ((_e134 < int(3))) {
    } else {
      break;
    }
    {
      int _e137 = k;
      float2 _e139 = corners[min(uint(_e137), 2u)];
      float2 corner = (inside ? _e139 : sample_1);
      if (inside) {
        local_24 = all((corner >= (0.0).xx));
      } else {
        local_24 = false;
      }
      bool _e148 = local_24;
      if (_e148) {
        local_25 = all((corner <= last_1));
      } else {
        local_25 = false;
      }
      bool on_map_1 = local_25;
      if (on_map_1) {
        local_26 = (stride < 1.5);
      } else {
        local_26 = false;
      }
      bool _e160 = local_26;
      if (_e160) {
        int _e161 = k;
        float4 _e166 = heights_2.Load(int3(naga_f2i32(round(corner)), int(0)));
        h[min(uint(_e161), 2u)] = _e166.x;
      } else {
        if (on_map_1) {
          int _e168 = k;
          const float _e172 = texel_height(heights_2, terrain2_2, (corner / (stride).xx));
          h[min(uint(_e168), 2u)] = _e172;
        } else {
          int _e173 = k;
          const float _e179 = ground_height(heights_2, terrain_1, terrain2_2, ((corner - (last_1 * 0.5)) * metres));
          h[min(uint(_e173), 2u)] = _e179;
        }
      }
    }
  }
  float bottom_left = h[0];
  float top_right = h[1];
  if (!(upper)) {
    float top_left = h[2];
    float _e192 = t.x;
    float _e197 = t.y;
    return ((top_left + ((top_right - top_left) * _e192)) + ((bottom_left - top_left) * _e197));
  }
  float bottom_right = h[2];
  float _e204 = t.x;
  float _e211 = t.y;
  return ((bottom_right + ((bottom_left - bottom_right) * (1.0 - _e204))) + ((top_right - bottom_right) * (1.0 - _e211)));
}

float grounded_base(Texture2D<float4> heights_3, float4 terrain_2, float4 terrain2_3, float4 mesh_1, float2 xz_3, float root)
{
  float lowest = 1e30;
  int point_ = int(0);
  bool local_27 = (bool)0;

  int points = ((root <= 0.0) ? int(1) : int(5));
  uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
  bool loop_init_1 = true;
  while(true) {
    if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
    loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
    if (!loop_init_1) {
      int _e43 = point_;
      point_ = asint(asuint(_e43) + asuint(int(1)));
    }
    loop_init_1 = false;
    int _e15 = point_;
    if ((_e15 < points)) {
    } else {
      break;
    }
    {
      int _e17 = point_;
      float angle = (float(_e17) * 1.5707964);
      int _e27 = point_;
      if (!((_e27 == int(4)))) {
        local_27 = (points == int(1));
      } else {
        local_27 = true;
      }
      bool _e36 = local_27;
      float2 out_ = (_e36 ? (0.0).xx : round(float2(cos(angle), sin(angle))));
      float _e38 = lowest;
      const float _e41 = mesh_height(heights_3, terrain_2, terrain2_3, mesh_1, (xz_3 + (out_ * root)));
      lowest = min(_e38, _e41);
    }
  }
  float _e46 = lowest;
  return (_e46 - (0.05 * root));
}

uint3 pcg3d(uint3 input)
{
  uint3 v = (uint3)0;

  v = input;
  uint3 _e2 = v;
  v = ((_e2 * 1664525u) + (1013904223u).xxx);
  uint _e9 = v.x;
  uint _e11 = v.y;
  uint _e13 = v.z;
  v.x = (_e9 + (_e11 * _e13));
  uint _e17 = v.y;
  uint _e19 = v.z;
  uint _e21 = v.x;
  v.y = (_e17 + (_e19 * _e21));
  uint _e25 = v.z;
  uint _e27 = v.x;
  uint _e29 = v.y;
  v.z = (_e25 + (_e27 * _e29));
  uint3 _e32 = v;
  uint3 _e33 = v;
  v = (_e32 ^ (_e33 >> (16u).xxx));
  uint _e39 = v.x;
  uint _e41 = v.y;
  uint _e43 = v.z;
  v.x = (_e39 + (_e41 * _e43));
  uint _e47 = v.y;
  uint _e49 = v.z;
  uint _e51 = v.x;
  v.y = (_e47 + (_e49 * _e51));
  uint _e55 = v.z;
  uint _e57 = v.x;
  uint _e59 = v.y;
  v.z = (_e55 + (_e57 * _e59));
  uint3 _e62 = v;
  return _e62;
}

float unit(uint word)
{
  return (float((word >> 8u)) * 5.9604645e-8);
}

float2 jittered(int2 cell, uint3 hash, float pitch)
{
  const float _e4 = unit(hash.x);
  const float _e6 = unit(hash.y);
  float2 jitter = ((float2(_e4, _e6) - (0.5).xx) * 0.9);
  return (((float2(cell) + (0.5).xx) + jitter) * pitch);
}

int naga_div(int lhs, int rhs) {
  return lhs / (((lhs == int(-2147483647 - 1) & rhs == -1) | (rhs == 0)) ? 1 : rhs);
}

int naga_mod(int lhs, int rhs) {
  int divisor = ((lhs == int(-2147483647 - 1) & rhs == -1) | (rhs == 0)) ? 1 : rhs;
  return lhs - (lhs / divisor) * divisor;
}

int tile_first(int tile, int size, int pitch_1)
{
  int a = asint(asuint(tile) * asuint(size));
  return asint(asuint(naga_div(a, pitch_1)) + asuint(((naga_mod(a, pitch_1) > int(0)) ? int(1) : int(0))));
}

bool on_map(Mapping m, float2 xz_4)
{
  return all((abs(xz_4) <= m.terrain.xy));
}

float2 texel_position(Mapping m_1, float2 xz_5)
{
  return ((xz_5 + m_1.terrain.xy) * m_1.inverse);
}

int2 nearest(Mapping m_2, float2 xz_6)
{
  const float2 _e2 = texel_position(m_2, xz_6);
  float2 t_5 = floor((_e2 + (0.5).xx));
  return clamp(naga_f2i32(t_5), (int(0)).xx, asint(asuint(naga_f2i32(m_2.terrain2_.xy)) - asuint((int(1)).xx)));
}

uint4 naga_f2u32(float4 value) {
  return uint4(clamp(value, 0.0, 4294967000.0));
}

uint4 bytes_at(Texture2D<float4> t_1, int2 texel_1)
{
  float4 _e3 = t_1.Load(int3(texel_1, int(0)));
  return naga_f2u32(round((_e3 * 255.0)));
}

float height_at(Mapping m_3, float2 xz_7)
{
  const float2 _e4 = texel_position(m_3, xz_7);
  const float _e5 = texel_height(heights_4, m_3.terrain2_, _e4);
  return _e5;
}

float water_distance(Mapping m_4, float2 xz_8)
{
  const float2 _e2 = texel_position(m_4, xz_8);
  float2 t_6 = clamp(_e2, (0.0).xx, (m_4.terrain2_.xy - (1.001).xx));
  float2 base_2 = floor(t_6);
  float2 f_2 = (t_6 - base_2);
  int2 i_1 = naga_f2i32(base_2);
  float4 _e16 = banks_texture.Load(int3(i_1, int(0)));
  float d00_ = _e16.x;
  float4 _e24 = banks_texture.Load(int3(asint(asuint(i_1) + asuint(int2(int(1), int(0)))), int(0)));
  float d10_ = _e24.x;
  float4 _e32 = banks_texture.Load(int3(asint(asuint(i_1) + asuint(int2(int(0), int(1)))), int(0)));
  float d01_ = _e32.x;
  float4 _e40 = banks_texture.Load(int3(asint(asuint(i_1) + asuint(int2(int(1), int(1)))), int(0)));
  float d11_ = _e40.x;
  return (lerp(lerp(d00_, d10_, f_2.x), lerp(d01_, d11_, f_2.x), f_2.y) * 40.0);
}

bool in_water(Mapping m_5, float2 xz_9, float clearance)
{
  const float _e3 = water_distance(m_5, xz_9);
  return (_e3 < ((0.25 * m_5.terrain.z) + clearance));
}

float slope_degrees(Mapping m_6, float2 xz_10)
{
  const float _e6 = height_at(m_6, (xz_10 + float2(1.5, 0.0)));
  const float _e11 = height_at(m_6, (xz_10 - float2(1.5, 0.0)));
  float dx_1 = (_e6 - _e11);
  const float _e17 = height_at(m_6, (xz_10 + float2(0.0, 1.5)));
  const float _e22 = height_at(m_6, (xz_10 - float2(0.0, 1.5)));
  float dz_1 = (_e17 - _e22);
  return degrees(atan((length(float2(dx_1, dz_1)) / 3.0)));
}

float bin_float(uint index)
{
  uint _e3 = asuint(bins.Load(index*4));
  return asfloat(_e3);
}

float intrusion(uint base, float2 xz_11, float clearance_1)
{
  float t_2 = 0.0;

  const float _e3 = bin_float(base);
  const float _e6 = bin_float((base + 1u));
  float2 a_1 = float2(_e3, _e6);
  const float _e10 = bin_float((base + 2u));
  const float _e13 = bin_float((base + 3u));
  float2 b = float2(_e10, _e13);
  float2 d = (b - a_1);
  float length_squared = ((d.x * d.x) + (d.y * d.y));
  if ((length_squared > 0.0)) {
    t_2 = clamp(((((xz_11.x - a_1.x) * d.x) + ((xz_11.y - a_1.y) * d.y)) / length_squared), 0.0, 1.0);
  }
  float _e42 = t_2;
  float2 p_2 = ((a_1 + (d * _e42)) - xz_11);
  const float _e48 = bin_float((base + 4u));
  const float _e51 = bin_float((base + 5u));
  const float _e54 = bin_float((base + 4u));
  float _e56 = t_2;
  float half_ = (_e48 + ((_e51 - _e54) * _e56));
  const float _e61 = bin_float((base + 6u));
  return ((half_ + (_e61 * clearance_1)) - sqrt(((p_2.x * p_2.x) + (p_2.y * p_2.y))));
}

bool in_channel(float2 xz_12, float clearance_2)
{
  int row = (int)0;
  uint item = (uint)0;

  const float _e3 = bin_float(0u);
  const float _e5 = bin_float(1u);
  float2 origin = float2(_e3, _e5);
  const float _e8 = bin_float(2u);
  uint _e11 = asuint(bins.Load(12));
  int columns = int(_e11);
  uint _e15 = asuint(bins.Load(16));
  int rows = int(_e15);
  uint first_item = ((5u + uint(asint(asuint(columns) * asuint(rows)))) + 1u);
  int2 c = naga_f2i32(floor(((xz_12 - origin) / (_e8).xx)));
  int x0_ = max(asint(asuint(c.x) - asuint(int(1))), int(0));
  int x1_ = min(asint(asuint(c.x) + asuint(int(1))), asint(asuint(columns) - asuint(int(1))));
  if ((x0_ > x1_)) {
    return false;
  }
  row = max(asint(asuint(c.y) - asuint(int(1))), int(0));
  uint2 loop_bound_2 = uint2(4294967295u, 4294967295u);
  bool loop_init_2 = true;
  while(true) {
    if (all(loop_bound_2 == uint2(0u, 0u))) { break; }
    loop_bound_2 -= uint2(loop_bound_2.y == 0u, 1u);
    if (!loop_init_2) {
      int _e87 = row;
      row = asint(asuint(_e87) + asuint(int(1)));
    }
    loop_init_2 = false;
    int _e47 = row;
    if ((_e47 <= min(asint(asuint(c.y) + asuint(int(1))), asint(asuint(rows) - asuint(int(1)))))) {
    } else {
      break;
    }
    {
      int _e56 = row;
      uint first = asuint(bins.Load(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e56) * asuint(columns))))) + asuint(x0_))*4));
      int _e64 = row;
      uint last_2 = asuint(bins.Load(asint(asuint(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e64) * asuint(columns))))) + asuint(x1_))) + asuint(int(1)))*4));
      item = first;
      uint2 loop_bound_3 = uint2(4294967295u, 4294967295u);
      bool loop_init_3 = true;
      while(true) {
        if (all(loop_bound_3 == uint2(0u, 0u))) { break; }
        loop_bound_3 -= uint2(loop_bound_3.y == 0u, 1u);
        if (!loop_init_3) {
          uint _e84 = item;
          item = (_e84 + 1u);
        }
        loop_init_3 = false;
        uint _e74 = item;
        if ((_e74 < last_2)) {
        } else {
          break;
        }
        {
          uint _e76 = item;
          const float _e80 = intrusion((first_item + (_e76 * BIN_WORDS)), xz_12, clearance_2);
          if ((_e80 > 0.0)) {
            return true;
          }
        }
      }
    }
  }
  return false;
}

NearChannel ConstructNearChannel(float arg0, uint arg1) {
  NearChannel ret = (NearChannel)0;
  ret.edge = arg0;
  ret.base = arg1;
  return ret;
}

NearChannel near_channel(float2 xz_13, float reach_1)
{
  NearChannel best = (NearChannel)0;
  int row_1 = (int)0;
  uint item_1 = (uint)0;
  bool local_28 = (bool)0;

  const float _e3 = bin_float(0u);
  const float _e5 = bin_float(1u);
  float2 origin_1 = float2(_e3, _e5);
  const float _e8 = bin_float(2u);
  uint _e11 = asuint(bins.Load(12));
  int columns_1 = int(_e11);
  uint _e15 = asuint(bins.Load(16));
  int rows_1 = int(_e15);
  uint first_item_1 = ((5u + uint(asint(asuint(columns_1) * asuint(rows_1)))) + 1u);
  int2 c_1 = naga_f2i32(floor(((xz_13 - origin_1) / (_e8).xx)));
  int x0_1 = max(asint(asuint(c_1.x) - asuint(int(1))), int(0));
  int x1_1 = min(asint(asuint(c_1.x) + asuint(int(1))), asint(asuint(columns_1) - asuint(int(1))));
  best = ConstructNearChannel((reach_1 + 1.0), 0u);
  if ((x0_1 > x1_1)) {
    NearChannel _e45 = best;
    const NearChannel nearchannel = _e45;
    return nearchannel;
  }
  row_1 = max(asint(asuint(c_1.y) - asuint(int(1))), int(0));
  uint2 loop_bound_4 = uint2(4294967295u, 4294967295u);
  bool loop_init_4 = true;
  while(true) {
    if (all(loop_bound_4 == uint2(0u, 0u))) { break; }
    loop_bound_4 -= uint2(loop_bound_4.y == 0u, 1u);
    if (!loop_init_4) {
      int _e100 = row_1;
      row_1 = asint(asuint(_e100) + asuint(int(1)));
    }
    loop_init_4 = false;
    int _e52 = row_1;
    if ((_e52 <= min(asint(asuint(c_1.y) + asuint(int(1))), asint(asuint(rows_1) - asuint(int(1)))))) {
    } else {
      break;
    }
    {
      int _e61 = row_1;
      uint first_1 = asuint(bins.Load(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e61) * asuint(columns_1))))) + asuint(x0_1))*4));
      int _e69 = row_1;
      uint last_3 = asuint(bins.Load(asint(asuint(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e69) * asuint(columns_1))))) + asuint(x1_1))) + asuint(int(1)))*4));
      item_1 = first_1;
      uint2 loop_bound_5 = uint2(4294967295u, 4294967295u);
      bool loop_init_5 = true;
      while(true) {
        if (all(loop_bound_5 == uint2(0u, 0u))) { break; }
        loop_bound_5 -= uint2(loop_bound_5.y == 0u, 1u);
        if (!loop_init_5) {
          uint _e97 = item_1;
          item_1 = (_e97 + 1u);
        }
        loop_init_5 = false;
        uint _e79 = item_1;
        if ((_e79 < last_3)) {
        } else {
          break;
        }
        {
          uint _e81 = item_1;
          uint base_3 = (first_item_1 + (_e81 * BIN_WORDS));
          const float _e86 = intrusion(base_3, xz_13, 0.0);
          float edge_1 = -(_e86);
          if ((edge_1 <= reach_1)) {
            float _e92 = best.edge;
            local_28 = (edge_1 < _e92);
          } else {
            local_28 = false;
          }
          bool _e95 = local_28;
          if (_e95) {
            best = ConstructNearChannel(edge_1, base_3);
          }
        }
      }
    }
  }
  NearChannel _e103 = best;
  const NearChannel nearchannel_1 = _e103;
  return nearchannel_1;
}

float boulder_size(float u, float position)
{
  float size_1 = (0.3 * pow((1.0 - (u * (1.0 - 0.063095726))), -0.8333333));
  return clamp((size_1 * (0.75 + (0.6 * position))), 0.3, 3.0);
}

float4 boulder_candidate(Mapping m_7, int2 cell_1, uint seed)
{
  bool local_29 = (bool)0;
  bool local_30 = (bool)0;
  bool local_31 = (bool)0;

  const uint3 _e5 = pcg3d(uint3(asuint(cell_1), seed));
  const float2 _e7 = jittered(cell_1, _e5, BOULDER_PITCH);
  const bool _e8 = on_map(m_7, _e7);
  if (!(_e8)) {
    return float4(0.0, 0.0, -1.0, 0.0);
  }
  const int2 _e16 = nearest(m_7, _e7);
  const uint4 _e17 = bytes_at(banks_texture, _e16);
  uint talus = _e17.w;
  float p_3 = ((float((talus >> 4u)) / 15.0) * TALUS_PROBABILITY);
  const float _e27 = unit(_e5.z);
  if (!((_e27 >= p_3))) {
    const float _e32 = height_at(m_7, _e7);
    local_29 = (_e32 <= (m_7.terrain2_.w + BOULDER_WATER_LINE));
  } else {
    local_29 = true;
  }
  bool _e39 = local_29;
  if (!(_e39)) {
    const bool _e44 = in_water(m_7, _e7, BOULDER_WATER_CLEARANCE);
    local_30 = _e44;
  } else {
    local_30 = true;
  }
  bool _e46 = local_30;
  if (!(_e46)) {
    const bool _e51 = in_channel(_e7, 1.0);
    local_31 = _e51;
  } else {
    local_31 = true;
  }
  bool _e53 = local_31;
  if (_e53) {
    return float4(0.0, 0.0, -1.0, 0.0);
  }
  const uint3 _e63 = pcg3d(uint3(asuint(cell_1), (seed ^ 625341585u)));
  const float _e65 = unit(_e63.x);
  const float _e71 = boulder_size(_e65, (float((talus & 15u)) / 15.0));
  return float4(_e7, _e71, (_e27 / p_3));
}

bool under_boulder(Mapping m_8, float2 xz_14, uint seed_1, float margin)
{
  int dz = int(-1);
  int dx = (int)0;
  bool local_32 = (bool)0;

  int2 c_2 = naga_f2i32(floor((xz_14 / (2.0).xx)));
  uint2 loop_bound_6 = uint2(4294967295u, 4294967295u);
  bool loop_init_6 = true;
  while(true) {
    if (all(loop_bound_6 == uint2(0u, 0u))) { break; }
    loop_bound_6 -= uint2(loop_bound_6.y == 0u, 1u);
    if (!loop_init_6) {
      int _e43 = dz;
      dz = asint(asuint(_e43) + asuint(int(1)));
    }
    loop_init_6 = false;
    int _e11 = dz;
    if ((_e11 <= int(1))) {
    } else {
      break;
    }
    {
      dx = int(-1);
      uint2 loop_bound_7 = uint2(4294967295u, 4294967295u);
      bool loop_init_7 = true;
      while(true) {
        if (all(loop_bound_7 == uint2(0u, 0u))) { break; }
        loop_bound_7 -= uint2(loop_bound_7.y == 0u, 1u);
        if (!loop_init_7) {
          int _e40 = dx;
          dx = asint(asuint(_e40) + asuint(int(1)));
        }
        loop_init_7 = false;
        int _e16 = dx;
        if ((_e16 <= int(1))) {
        } else {
          break;
        }
        {
          int _e19 = dx;
          int _e20 = dz;
          const float4 _e23 = boulder_candidate(m_8, asint(asuint(c_2) + asuint(int2(_e19, _e20))), seed_1);
          if ((_e23.z > 0.0)) {
            local_32 = (length((_e23.xy - xz_14)) < ((_e23.z * FOOTPRINT) + margin));
          } else {
            local_32 = false;
          }
          bool _e38 = local_32;
          if (_e38) {
            return true;
          }
        }
      }
    }
  }
  return false;
}

float smoothed(float t_3)
{
  float x = clamp(t_3, 0.0, 1.0);
  return ((x * x) * (3.0 - (2.0 * x)));
}

float4 riparian_grass(Mapping m_9, float2 xz_15, uint4 banks, uint snow, float mask_1, float shade)
{
  bool local_33 = (bool)0;
  bool local_34 = (bool)0;
  float t_4 = 0.0;

  if (!((banks.z == 0u))) {
    local_33 = (snow > 127u);
  } else {
    local_33 = true;
  }
  bool _e15 = local_33;
  if (!(_e15)) {
    const float _e19 = water_distance(m_9, xz_15);
    local_34 = (_e19 > (HERB_METRES + (0.75 / m_9.inverse)));
  } else {
    local_34 = true;
  }
  bool _e27 = local_34;
  if (_e27) {
    return (0.0).xxxx;
  }
  const NearChannel _e31 = near_channel(xz_15, HERB_METRES);
  if ((_e31.edge > HERB_METRES)) {
    return (0.0).xxxx;
  }
  const float _e40 = bin_float((_e31.base + 9u));
  float band_2 = (_e40 * mask_1);
  const float _e49 = smoothed(((_e31.edge - 0.4) / 0.2));
  float tufts_1 = ((_e31.edge >= 0.0) ? ((band_2 * RIPARIAN_TUFTS) * (1.0 - _e49)) : 0.0);
  const float _e65 = smoothed(((_e31.edge - 0.3) / 0.2));
  const float _e72 = smoothed(((_e31.edge - 2.5) / 0.5));
  float herbs = ((((band_2 * RIPARIAN_HERBS) * _e65) * (1.0 - _e72)) * (1.0 + shade));
  const float _e80 = bin_float(_e31.base);
  const float _e84 = bin_float((_e31.base + 1u));
  float2 a_2 = float2(_e80, _e84);
  const float _e89 = bin_float((_e31.base + 2u));
  const float _e93 = bin_float((_e31.base + 3u));
  float2 d_1 = (float2(_e89, _e93) - a_2);
  float length_squared_1 = ((d_1.x * d_1.x) + (d_1.y * d_1.y));
  if ((length_squared_1 > 0.0)) {
    t_4 = clamp(((((xz_15.x - a_2.x) * d_1.x) + ((xz_15.y - a_2.y) * d_1.y)) / length_squared_1), 0.0, 1.0);
  }
  float _e122 = t_4;
  float2 to = ((a_2 + (d_1 * _e122)) - xz_15);
  return float4(tufts_1, herbs, (to / (max(length(to), 1e-6)).xx));
}

float slope_fade(float slope_1)
{
  const float _e5 = smoothed(((slope_1 - 30.000002) / 20.0));
  return (1.0 - _e5);
}

float grass_accept(Mapping m_10, float2 xz_16)
{
  const float2 _e2 = texel_position(m_10, xz_16);
  float2 t_7 = clamp(_e2, (0.0).xx, (m_10.terrain2_.xy - (1.001).xx));
  float2 base_4 = floor(t_7);
  float2 f_3 = (t_7 - base_4);
  int2 i_2 = naga_f2i32(base_4);
  float4 _e16 = grass_texture.Load(int3(i_2, int(0)));
  float a00_ = _e16.x;
  float4 _e24 = grass_texture.Load(int3(asint(asuint(i_2) + asuint(int2(int(1), int(0)))), int(0)));
  float a10_ = _e24.x;
  float4 _e32 = grass_texture.Load(int3(asint(asuint(i_2) + asuint(int2(int(0), int(1)))), int(0)));
  float a01_ = _e32.x;
  float4 _e40 = grass_texture.Load(int3(asint(asuint(i_2) + asuint(int2(int(1), int(1)))), int(0)));
  float a11_ = _e40.x;
  return lerp(lerp(a00_, a10_, f_3.x), lerp(a01_, a11_, f_3.x), f_3.y);
}

float grass_mask_at(Mapping m_11, float2 xz_17)
{
  const float2 _e2 = texel_position(m_11, xz_17);
  float2 uv = ((_e2 + (0.5).xx) / m_11.terrain2_.xy);
  float4 _e12 = grass_mask.SampleLevel(mask_sampler, uv, 0.0);
  const float _e14 = density_multiplier(_e12.x);
  return _e14;
}

float grass_rock(Mapping m_12, float2 xz_18)
{
  float4 r = (float4)0;

  const float2 _e2 = texel_position(m_12, xz_18);
  float2 t_8 = clamp(_e2, (0.0).xx, (m_12.terrain2_.xy - (1.001).xx));
  float2 base_5 = floor(t_8);
  float2 f_4 = (t_8 - base_5);
  int2 i_3 = naga_f2i32(base_5);
  float4 _e16 = grass_texture.Load(int3(i_3, int(0)));
  float4 _e24 = grass_texture.Load(int3(asint(asuint(i_3) + asuint(int2(int(1), int(0)))), int(0)));
  float4 _e32 = grass_texture.Load(int3(asint(asuint(i_3) + asuint(int2(int(0), int(1)))), int(0)));
  float4 _e40 = grass_texture.Load(int3(asint(asuint(i_3) + asuint(int2(int(1), int(1)))), int(0)));
  r = float4(_e16.z, _e24.z, _e32.z, _e40.z);
  float4 _e44 = r;
  float4 _e53 = r;
  r = (((_e53 * 255.0) > (127.5).xxxx) ? (0.0).xxxx : (round((_e44 * 255.0)) / (127.0).xxxx));
  float _e61 = r.x;
  float _e63 = r.y;
  float _e67 = r.z;
  float _e69 = r.w;
  return lerp(lerp(_e61, _e63, f_4.x), lerp(_e67, _e69, f_4.x), f_4.y);
}

float edge_turf(float rock)
{
  const float _e5 = smoothed(((rock - 0.2) / 0.2));
  const float _e12 = smoothed(((rock - 0.45) / 0.1));
  return ((1.2 * _e5) * (1.0 - _e12));
}

Mapping ConstructMapping(float4 arg0, float4 arg1, float arg2) {
  Mapping ret = (Mapping)0;
  ret.terrain = arg0;
  ret.terrain2_ = arg1;
  ret.inverse = arg2;
  return ret;
}

int naga_f2i32(float value) {
  return int(clamp(value, -2147483600.0, 2147483500.0));
}

Job ConstructJob(int2 arg0, uint arg1, uint arg2, uint arg3, float arg4, uint2 arg5) {
  Job ret = (Job)0;
  ret.tile = arg0;
  ret.first = arg1;
  ret.capacity = arg2;
  ret.slot = arg3;
  ret.keep = arg4;
  ret.unused = arg5;
  return ret;
}

[numthreads(8, 8, 1)]
void generate_main(uint3 id : SV_DispatchThreadID)
{
  float mask = 1.0;
  float slope = 0.0;
  bool local = (bool)0;
  bool local_1 = (bool)0;
  bool local_2 = (bool)0;
  bool local_3 = (bool)0;
  bool local_4 = (bool)0;
  float style = 0.0;
  float scale = (float)0;
  float dryness = (float)0;
  bool local_5 = (bool)0;
  bool local_6 = (bool)0;
  bool local_7 = (bool)0;
  bool local_8 = (bool)0;
  bool local_9 = (bool)0;
  bool local_10 = (bool)0;

  Job job = ConstructJob(asint(jobs.Load2(id.z*32+0)), asuint(jobs.Load(id.z*32+8)), asuint(jobs.Load(id.z*32+12)), asuint(jobs.Load(id.z*32+16)), asfloat(jobs.Load(id.z*32+20)), asuint(jobs.Load2(id.z*32+24)));
  const int _e9 = tile_first(job.tile.x, int(1600), int(35));
  const int _e14 = tile_first(job.tile.y, int(1600), int(35));
  int2 first_2 = int2(_e9, _e14);
  const int _e22 = tile_first(asint(asuint(job.tile.x) + asuint(int(1))), int(1600), int(35));
  const int _e29 = tile_first(asint(asuint(job.tile.y) + asuint(int(1))), int(1600), int(35));
  int2 next = int2(_e22, _e29);
  int2 cell_3 = asint(asuint(first_2) + asuint(int2(id.xy)));
  if (any((cell_3 >= next))) {
    return;
  }
  float4 _e38 = params.terrain;
  float4 _e41 = params.terrain2_;
  float _e45 = params.rules.x;
  Mapping m_13 = ConstructMapping(_e38, _e41, _e45);
  uint seed_2 = params.shape.x;
  const uint3 _e53 = pcg3d(uint3(asuint(cell_3), seed_2));
  const float2 _e55 = jittered(cell_3, _e53, GRASS_PITCH);
  const bool _e56 = on_map(m_13, _e55);
  if (!(_e56)) {
    return;
  }
  const int2 _e58 = nearest(m_13, _e55);
  const uint4 _e60 = bytes_at(grass_texture, _e58);
  const float _e62 = unit(_e53.z);
  const float _e63 = water_distance(m_13, _e55);
  const uint4 _e65 = bytes_at(banks_texture, _e58);
  const float _e68 = smoothed((_e63 / NEAR_WATER_METRES));
  float near = max((1.0 - _e68), (float(_e65.z) / 255.0));
  const uint4 _e77 = bytes_at(cover_texture, _e58);
  float red = float(_e77.x);
  float _e83 = params.rules.z;
  float shade_1 = (1.0 - exp((((-(_e83) * red) * red) * 6.15148e-5)));
  float _e97 = params.view.z;
  if ((_e97 > 0.5)) {
    const float _e100 = grass_mask_at(m_13, _e55);
    mask = _e100;
  }
  float _e106 = params.rules.y;
  float _e107 = mask;
  if ((_e62 < ((_e106 * _e107) * job.keep))) {
    const float _e112 = slope_degrees(m_13, _e55);
    const float _e113 = slope_fade(_e112);
    slope = _e113;
  }
  float _e117 = params.rules.y;
  const float _e118 = grass_accept(m_13, _e55);
  float _e130 = slope;
  const float _e132 = grass_rock(m_13, _e55);
  const float _e133 = edge_turf(_e132);
  float _e137 = mask;
  float meadow = (((((_e117 * min((_e118 * (1.0 + (0.6 * near))), 1.0)) * (1.0 - shade_1)) * _e130) * (1.0 + _e133)) * _e137);
  float _e142 = params.rules.y;
  float _e151 = slope;
  float _e153 = mask;
  float floor_plants = ((((((_e142 * FLOOR_DENSITY) * shade_1) * float(_e60.w)) / 255.0) * _e151) * _e153);
  const uint4 _e156 = bytes_at(surface_texture, _e58);
  float _e158 = mask;
  const float4 _e159 = riparian_grass(m_13, _e55, _e65, _e156.z, _e158, shade_1);
  float p_4 = (((meadow + floor_plants) + _e159.x) + _e159.y);
  if (!((p_4 <= 0.0))) {
    local = (_e62 >= (p_4 * job.keep));
  } else {
    local = true;
  }
  bool _e174 = local;
  if (_e174) {
    return;
  }
  const bool _e176 = in_water(m_13, _e55, 0.0);
  bool wet = ((_e62 < (_e159.x + _e159.y)) ? (_e63 <= 0.0) : _e176);
  const float _e184 = height_at(m_13, _e55);
  float _e188 = params.terrain2_.w;
  if (!((_e184 <= (_e188 + GRASS_WATER_LINE)))) {
    local_1 = wet;
  } else {
    local_1 = true;
  }
  bool _e196 = local_1;
  if (!(_e196)) {
    const bool _e201 = in_channel(_e55, 0.0);
    local_2 = _e201;
  } else {
    local_2 = true;
  }
  bool _e203 = local_2;
  if (!(_e203)) {
    float _e210 = params.view.y;
    if ((_e210 > 0.5)) {
      uint _e218 = params.shape.w;
      const bool _e220 = under_boulder(m_13, _e55, _e218, 0.0);
      local_4 = _e220;
    } else {
      local_4 = false;
    }
    bool _e222 = local_4;
    local_3 = _e222;
  } else {
    local_3 = true;
  }
  bool _e224 = local_3;
  if (_e224) {
    return;
  }
  const uint3 _e229 = pcg3d(uint3(asuint(cell_3), (seed_2 ^ TRAITS_SALT)));
  const float _e231 = unit(_e229.x);
  float relative = (_e62 / p_4);
  scale = (0.5 + (_e231 * 0.6));
  dryness = ((float(_e60.y) / 255.0) * (1.0 - (0.7 * near)));
  bool tundra = (_e60.z > 127u);
  float band_3 = (_e159.x + _e159.y);
  if ((_e62 < _e159.x)) {
    int sector = (naga_f2i32(round((atan2(_e159.w, _e159.z) / 0.7853982))) & int(7));
    float _e267 = scale;
    float _e273 = params.rules.w;
    scale = ((_e267 * 1.3) * (tundra ? TUNDRA_GRASS_HEIGHT : _e273));
    float _e277 = dryness;
    dryness = (_e277 + (2.0 * float(asint(asuint(sector) + asuint(int(1))))));
  } else {
    if ((_e62 < band_3)) {
      if (!(tundra)) {
        local_6 = (_e156.w >= ALPINE_TRANSITION);
      } else {
        local_6 = true;
      }
      bool _e294 = local_6;
      local_5 = _e294;
    } else {
      local_5 = false;
    }
    bool _e296 = local_5;
    if (_e296) {
      float _e297 = scale;
      scale = (_e297 * 1.2);
      dryness = 0.3;
    } else {
      if ((_e62 < band_3)) {
        if ((_e156.y > 140u)) {
          local_7 = (_e156.x >= 100u);
        } else {
          local_7 = false;
        }
        bool _e311 = local_7;
        if (_e311) {
          local_8 = (_e156.x < 200u);
        } else {
          local_8 = false;
        }
        bool fern = local_8;
        style = (fern ? FERN : UNDERGROWTH);
        scale = (0.7 + ((1.3 * _e231) * (fern ? 1.0 : 0.6)));
        dryness = 0.0;
      } else {
        if ((_e62 >= (band_3 + meadow))) {
          if ((_e156.y > 140u)) {
            local_9 = (_e156.x >= 100u);
          } else {
            local_9 = false;
          }
          bool _e342 = local_9;
          if (_e342) {
            local_10 = (_e156.x < 200u);
          } else {
            local_10 = false;
          }
          bool fern_1 = local_10;
          style = (fern_1 ? FERN : UNDERGROWTH);
          scale = (fern_1 ? (0.4 + (_e231 * 0.5)) : (0.3 + (_e231 * 0.3)));
          dryness = 0.0;
        } else {
          if (tundra) {
            float _e363 = scale;
            scale = (_e363 * TUNDRA_GRASS_HEIGHT);
            dryness = 0.5;
          } else {
            float _e367 = scale;
            float _e371 = params.rules.w;
            scale = (_e367 * _e371);
          }
        }
      }
    }
  }
  uint _e377; counts.InterlockedAdd(job.slot*4, 1u, _e377);
  if ((_e377 < job.capacity)) {
    uint base_6 = ((job.first + _e377) * 7u);
    tufts.Store(base_6*4, asuint(_e55.x));
    float4 _e394 = params.terrain;
    float4 _e397 = params.terrain2_;
    float4 _e400 = params.mesh;
    const float _e402 = grounded_base(heights_4, _e394, _e397, _e400, _e55, 0.0);
    tufts.Store((base_6 + 1u)*4, asuint(_e402));
    tufts.Store((base_6 + 2u)*4, asuint(_e55.y));
    float _e412 = scale;
    tufts.Store((base_6 + 3u)*4, asuint(_e412));
    const float _e418 = unit(_e229.y);
    tufts.Store((base_6 + 4u)*4, asuint(_e418));
    float _e423 = dryness;
    tufts.Store((base_6 + 5u)*4, asuint(_e423));
    float _e428 = style;
    tufts.Store((base_6 + 6u)*4, asuint((_e428 + min(relative, 0.999))));
    return;
  } else {
    return;
  }
}
