// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: boulder_generate (ground + lattice + generate_common + boulder_generate)
// Entry point: cull_main, compile with /T cs_5_0 /E cull_main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(7) pool -> u0  RWByteAddressBuffer
//   @group(0) @binding(8) counts -> u1  RWByteAddressBuffer
//   @group(0) @binding(10) drawn -> u2  RWByteAddressBuffer
//   @group(0) @binding(11) args -> u3  RWByteAddressBuffer

struct BoulderParams {
  float4 terrain;
  float4 terrain2_;
  float4 mesh;
  float4 rules;
  uint4 shape;
  float4 camera;
  float4 tall[2];
  float4 planes[6];
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const int CLUMP_CELLS = int(4);
static const uint CLUMP_SALT = 1013904242u;
static const float JITTER = 0.45;
static const float FADE_BAND = 0.05;
static const float MAX_GROWTH = 1.8;
static const uint BIN_WORDS = 11u;
static const float SLOPE_SPAN = 1.5;
static const float BOULDER_PITCH = 2.0;
static const uint BOULDER_SALT = 2135587861u;
static const float BOULDER_WATER_LINE = 0.3;
static const float BOULDER_WATER_CLEARANCE = 1.0;
static const float SIZE_EXPONENT = 1.2;
static const float FOOTPRINT = 0.55;
static const float TALUS_PROBABILITY = 0.6;
static const float STONE_PITCH = 1.0;
static const float STONE_REACH = 1.5;
static const float COBBLE_METRES = 0.5;
static const uint VARIANTS = 6u;
static const uint MAX_BOULDERS = 20000u;
static const uint VARIANT_ENTRIES = 7168u;
static const uint SHADOW_CAPACITY = 2048u;
static const uint TOTAL = 120u;

cbuffer params : register(b0) { BoulderParams params; }
RWByteAddressBuffer pool : register(u0);
RWByteAddressBuffer counts : register(u1);
RWByteAddressBuffer drawn : register(u2);
RWByteAddressBuffer args : register(u3);

void append(uint list, uint start, uint capacity, uint source, float scale)
{
  uint k = 0u;

  uint _e12; args.InterlockedAdd(((list * 5u) + 1u)*4, 1u, _e12);
  if ((_e12 >= capacity)) {
    uint _e21; args.InterlockedAdd(((list * 5u) + 1u)*4, -1u, _e21);
    return;
  }
  uint out_ = ((start + _e12) * 8u);
  uint2 loop_bound = uint2(4294967295u, 4294967295u);
  bool loop_init = true;
  while(true) {
    if (all(loop_bound == uint2(0u, 0u))) { break; }
    loop_bound -= uint2(loop_bound.y == 0u, 1u);
    if (!loop_init) {
      uint _e39 = k;
      k = (_e39 + 1u);
    }
    loop_init = false;
    uint _e27 = k;
    if ((_e27 < 8u)) {
    } else {
      break;
    }
    {
      uint _e31 = k;
      uint _e35 = k;
      float _e38 = asfloat(pool.Load((source + _e35)*4));
      drawn.Store((out_ + _e31)*4, asuint(_e38));
    }
  }
  drawn.Store((out_ + 3u)*4, asuint(scale));
  return;
}

uint naga_mod(uint lhs, uint rhs) {
  return lhs % (rhs == 0u ? 1u : rhs);
}

uint naga_div(uint lhs, uint rhs) {
  return lhs / (rhs == 0u ? 1u : rhs);
}

typedef uint ret_Constructarray3_uint_[3];
ret_Constructarray3_uint_ Constructarray3_uint_(uint arg0, uint arg1, uint arg2) {
  uint ret[3] = { arg0, arg1, arg2 };
  return ret;
}

uint naga_f2u32(float value) {
  return uint(clamp(value, 0.0, 4294967000.0));
}

[numthreads(64, 1, 1)]
void cull_main(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  int p = int(0);
  uint starts[3] = Constructarray3_uint_(0u, 1024u, 3072u);
  uint capacities[3] = Constructarray3_uint_(1024u, 2048u, 4096u);

  uint index = id.x;
  uint capacity_1 = params.shape.z;
  uint _e9 = params.shape.y;
  if (!((index >= _e9))) {
    uint _e18; counts.InterlockedOr(naga_div(index, capacity_1)*4, 0, _e18);
    local = (naga_mod(index, capacity_1) >= min(_e18, capacity_1));
  } else {
    local = true;
  }
  bool _e22 = local;
  if (_e22) {
    return;
  }
  uint base = (index * 8u);
  float _e27 = asfloat(pool.Load(base*4));
  float _e32 = asfloat(pool.Load((base + 1u)*4));
  float _e37 = asfloat(pool.Load((base + 2u)*4));
  float3 position = float3(_e27, _e32, _e37);
  float4 _e41 = params.camera;
  float distance_ = length((position - _e41.xyz));
  float reach = params.rules.y;
  float code = asfloat(pool.Load((base + 7u)*4));
  float keep = (saturate(((reach - distance_) / (0.2 * reach))) * 1.05);
  float fade = saturate(((keep - frac(code)) / 0.05));
  if ((fade <= 0.0)) {
    return;
  }
  float _e72 = asfloat(pool.Load((base + 3u)*4));
  float scale_1 = (_e72 * fade);
  float3 centre = (position + float3(0.0, (scale_1 * 0.4), 0.0));
  float _e86 = params.rules.w;
  if ((((scale_1 / max(distance_, 0.01)) * _e86) < 0.75)) {
    return;
  }
  uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
  bool loop_init_1 = true;
  while(true) {
    if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
    loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
    if (!loop_init_1) {
      int _e106 = p;
      p = asint(asuint(_e106) + asuint(int(1)));
    }
    loop_init_1 = false;
    int _e92 = p;
    if ((_e92 < int(6))) {
    } else {
      break;
    }
    {
      int _e97 = p;
      float4 plane = params.planes[_e97];
      if (((dot(plane.xyz, centre) + plane.w) < -(scale_1))) {
        return;
      }
    }
  }
  uint _e112; args.InterlockedAdd(480, 1u, _e112);
  if ((_e112 >= MAX_BOULDERS)) {
    return;
  }
  uint variant = min(naga_f2u32(code), 5u);
  float looks = (scale_1 / max(distance_, 0.01));
  uint lod = ((looks > 0.04) ? 0u : ((looks > 0.012) ? 1u : 2u));
  uint _e146 = starts[min(uint(lod), 2u)];
  uint _e149 = capacities[min(uint(lod), 2u)];
  append(((variant * 3u) + lod), ((variant * VARIANT_ENTRIES) + _e146), _e149, base, scale_1);
  float _e153 = params.rules.z;
  if ((distance_ < _e153)) {
    append((18u + variant), (43008u + (variant * SHADOW_CAPACITY)), SHADOW_CAPACITY, base, scale_1);
    return;
  } else {
    return;
  }
}
