// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: boulder_generate (ground + lattice + generate_common + boulder_generate)
// Entry point: generate_main, compile with /T cs_5_0 /E generate_main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(1) heights -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(3) banks_texture -> t1  Texture2D (Sampled { kind: Float, multi: false })
//   @group(0) @binding(5) bins -> t2  ByteAddressBuffer
//   @group(0) @binding(6) jobs -> t3  ByteAddressBuffer
//   @group(0) @binding(7) pool -> u0  RWByteAddressBuffer
//   @group(0) @binding(8) counts -> u1  RWByteAddressBuffer

struct Job {
  int2 tile;
  uint first;
  uint capacity;
  uint slot;
  float keep;
  uint2 unused;
};

struct Mapping {
  float4 terrain;
  float4 terrain2_;
  float inverse;
  int _end_pad_0;
  int _end_pad_1;
  int _end_pad_2;
};

struct NearChannel {
  float edge;
  uint base;
};

struct BoulderParams {
  float4 terrain;
  float4 terrain2_;
  float4 mesh;
  float4 rules;
  uint4 shape;
  float4 camera;
  float4 tall[2];
  float4 planes[6];
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const int CLUMP_CELLS = int(4);
static const uint CLUMP_SALT = 1013904242u;
static const float JITTER = 0.45;
static const float FADE_BAND = 0.05;
static const float MAX_GROWTH = 1.8;
static const uint BIN_WORDS = 11u;
static const float SLOPE_SPAN = 1.5;
static const float BOULDER_PITCH = 2.0;
static const uint BOULDER_SALT = 2135587861u;
static const float BOULDER_WATER_LINE = 0.3;
static const float BOULDER_WATER_CLEARANCE = 1.0;
static const float SIZE_EXPONENT = 1.2;
static const float FOOTPRINT = 0.55;
static const float TALUS_PROBABILITY = 0.6;
static const float STONE_PITCH = 1.0;
static const float STONE_REACH = 1.5;
static const float COBBLE_METRES = 0.5;
static const uint VARIANTS = 6u;
static const uint MAX_BOULDERS = 20000u;
static const uint VARIANT_ENTRIES = 7168u;
static const uint SHADOW_CAPACITY = 2048u;
static const uint TOTAL = 120u;

Texture2D<float4> heights_4 : register(t0);
Texture2D<float4> banks_texture : register(t1);
ByteAddressBuffer bins : register(t2);
ByteAddressBuffer jobs : register(t3);
cbuffer params : register(b0) { BoulderParams params; }
RWByteAddressBuffer pool : register(u0);
RWByteAddressBuffer counts : register(u1);

float hash12_(float2 p)
{
  float3 p3_ = (float3)0;

  p3_ = frac((float3(p.x, p.y, p.x) * 0.1031));
  float3 _e9 = p3_;
  float3 _e10 = p3_;
  float3 _e11 = p3_;
  p3_ = (_e9 + (dot(_e10, (_e11.yzx + (33.33).xxx))).xxx);
  float _e20 = p3_.x;
  float _e22 = p3_.y;
  float _e25 = p3_.z;
  return frac(((_e20 + _e22) * _e25));
}

float skirt_height(float edge, float sea, float distance_, float noise_)
{
  float foot = min(edge, (sea - 60.0));
  if ((distance_ >= SKIRT_METRES)) {
    return (foot - ((distance_ - SKIRT_METRES) * 0.08));
  }
  float s = smoothstep(0.0, 1.0, (distance_ / SKIRT_METRES));
  return (lerp(edge, foot, s) + (((((edge - foot) * 0.6) * noise_) * s) * (1.0 - s)));
}

float skirt_noise(float2 xz)
{
  float2 p_1 = (xz / (700.0).xx);
  float2 cell_3 = floor(p_1);
  float2 f = (p_1 - cell_3);
  float2 u_2 = ((f * f) * ((3.0).xx - (2.0 * f)));
  const float _e13 = hash12_(cell_3);
  const float _e18 = hash12_((cell_3 + float2(1.0, 0.0)));
  float top = lerp(_e13, _e18, u_2.x);
  const float _e25 = hash12_((cell_3 + float2(0.0, 1.0)));
  const float _e30 = hash12_((cell_3 + float2(1.0, 1.0)));
  float bottom = lerp(_e25, _e30, u_2.x);
  return ((lerp(top, bottom, u_2.y) * 2.0) - 1.0);
}

int2 naga_f2i32(float2 value) {
  return int2(clamp(value, -2147483600.0, 2147483500.0));
}

float texel_height(Texture2D<float4> heights, float4 terrain2_, float2 texel)
{
  float2 clamped = clamp(texel, (0.0).xx, (terrain2_.xy - (1.001).xx));
  float2 base_1 = floor(clamped);
  float2 f_1 = (clamped - base_1);
  int2 i = naga_f2i32(base_1);
  float4 _e14 = heights.Load(int3(i, int(0)));
  float h00_ = _e14.x;
  float4 _e21 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(1), int(0)))), int(0)));
  float h10_ = _e21.x;
  float4 _e28 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(0), int(1)))), int(0)));
  float h01_ = _e28.x;
  float4 _e35 = heights.Load(int3(asint(asuint(i) + asuint(int2(int(1), int(1)))), int(0)));
  float h11_ = _e35.x;
  return lerp(lerp(h00_, h10_, f_1.x), lerp(h01_, h11_, f_1.x), f_1.y);
}

float ground_height(Texture2D<float4> heights_1, float4 terrain, float4 terrain2_1, float2 xz_1)
{
  if ((terrain2_1.z < 0.5)) {
    return -100000.0;
  }
  const float _e12 = texel_height(heights_1, terrain2_1, ((xz_1 + terrain.xy) / terrain.zw));
  float outside = length(max((abs(xz_1) - terrain.xy), (0.0).xx));
  if ((outside <= 0.0)) {
    return _e12;
  }
  const float _e23 = skirt_noise(xz_1);
  const float _e24 = skirt_height(_e12, terrain2_1.w, outside, _e23);
  return _e24;
}

float band_offset(float grid)
{
  float g = abs(grid);
  float band_1 = floor((g / LOD_BAND_WIDTH));
  float step_ = exp2(band_1);
  return (sign(grid) * ((LOD_BAND_WIDTH * (step_ - 1.0)) + ((g - (LOD_BAND_WIDTH * band_1)) * step_)));
}

float band_grid(float offset)
{
  float band = (float)0;

  band = floor(log2(((offset / LOD_BAND_WIDTH) + 1.0)));
  float _e8 = band;
  float _e10 = band;
  band = (_e8 - ((offset < (LOD_BAND_WIDTH * (exp2(_e10) - 1.0))) ? 1.0 : 0.0));
  float _e20 = band;
  float _e22 = band;
  band = (_e20 + ((offset >= (LOD_BAND_WIDTH * (exp2((_e22 + 1.0)) - 1.0))) ? 1.0 : 0.0));
  float _e34 = band;
  float step_1 = exp2(_e34);
  float _e37 = band;
  return ((LOD_BAND_WIDTH * _e37) + floor(((offset - (LOD_BAND_WIDTH * (step_1 - 1.0))) / step_1)));
}

float2 mesh_cell(float sample_, float centre, float last, float reach)
{
  float grid_1 = (float)0;
  bool local = (bool)0;
  bool local_1 = (bool)0;
  bool local_2 = (bool)0;
  bool local_3 = (bool)0;
  bool local_4 = (bool)0;
  bool local_5 = (bool)0;

  float offset_1 = (sample_ - centre);
  const float _e6 = band_grid(abs(offset_1));
  grid_1 = _e6;
  if ((offset_1 < 0.0)) {
    float _e10 = grid_1;
    grid_1 = (-(_e10) - 1.0);
  }
  float _e14 = grid_1;
  const float _e15 = band_offset(_e14);
  float low = clamp((centre + _e15), -(reach), (last + reach));
  float _e20 = grid_1;
  const float _e23 = band_offset((_e20 + 1.0));
  float high = clamp((centre + _e23), -(reach), (last + reach));
  if ((high > last)) {
    local = (sample_ == low);
  } else {
    local = false;
  }
  bool _e33 = local;
  if (_e33) {
    local_1 = (low == last);
  } else {
    local_1 = false;
  }
  bool _e38 = local_1;
  if (_e38) {
    local_2 = (last > 0.0);
  } else {
    local_2 = false;
  }
  bool _e44 = local_2;
  if (_e44) {
    float _e45 = grid_1;
    const float _e48 = band_offset((_e45 - 1.0));
    return float2(clamp((centre + _e48), -(reach), (last + reach)), low);
  }
  if ((low < 0.0)) {
    local_3 = (sample_ == high);
  } else {
    local_3 = false;
  }
  bool _e60 = local_3;
  if (_e60) {
    local_4 = (high == 0.0);
  } else {
    local_4 = false;
  }
  bool _e66 = local_4;
  if (_e66) {
    local_5 = (last > 0.0);
  } else {
    local_5 = false;
  }
  bool _e72 = local_5;
  if (_e72) {
    float _e73 = grid_1;
    const float _e76 = band_offset((_e73 + 2.0));
    return float2(high, clamp((centre + _e76), -(reach), (last + reach)));
  }
  return float2(low, high);
}

typedef float2 ret_Constructarray3_float2_[3];
ret_Constructarray3_float2_ Constructarray3_float2_(float2 arg0, float2 arg1, float2 arg2) {
  float2 ret[3] = { arg0, arg1, arg2 };
  return ret;
}

typedef float ret_Constructarray3_float_[3];
ret_Constructarray3_float_ Constructarray3_float_(float arg0, float arg1, float arg2) {
  float ret[3] = { arg0, arg1, arg2 };
  return ret;
}

float mesh_height(Texture2D<float4> heights_2, float4 terrain_1, float4 terrain2_2, float4 mesh, float2 xz_2)
{
  bool local_6 = (bool)0;
  bool local_7 = (bool)0;
  bool local_8 = (bool)0;
  bool local_9 = (bool)0;
  bool local_10 = (bool)0;
  bool local_11 = (bool)0;
  bool local_12 = (bool)0;
  float2 t = (float2)0;
  float2 corners[3] = (float2[3])0;
  float h[3] = Constructarray3_float_(0.0, 0.0, 0.0);
  int k_1 = int(0);
  bool local_13 = (bool)0;
  bool local_14 = (bool)0;
  bool local_15 = (bool)0;

  if ((mesh.z > 0.0)) {
    local_6 = (terrain2_2.z > 0.5);
  } else {
    local_6 = false;
  }
  bool drawn = local_6;
  float metres = (drawn ? mesh.z : max(terrain_1.z, 0.001));
  float2 last_1 = round(((terrain_1.xy * 2.0) / (metres).xx));
  float2 sample_1 = ((xz_2 / (metres).xx) + (last_1 * 0.5));
  const float2 _e35 = mesh_cell(sample_1.x, mesh.x, last_1.x, mesh.w);
  const float2 _e40 = mesh_cell(sample_1.y, mesh.y, last_1.y, mesh.w);
  if (drawn) {
    local_7 = (_e35.x < _e35.y);
  } else {
    local_7 = false;
  }
  bool _e47 = local_7;
  if (_e47) {
    local_8 = (_e40.x < _e40.y);
  } else {
    local_8 = false;
  }
  bool _e54 = local_8;
  if (_e54) {
    local_9 = (sample_1.x >= _e35.x);
  } else {
    local_9 = false;
  }
  bool _e61 = local_9;
  if (_e61) {
    local_10 = (sample_1.x <= _e35.y);
  } else {
    local_10 = false;
  }
  bool _e68 = local_10;
  if (_e68) {
    local_11 = (sample_1.y >= _e40.x);
  } else {
    local_11 = false;
  }
  bool _e75 = local_11;
  if (_e75) {
    local_12 = (sample_1.y <= _e40.y);
  } else {
    local_12 = false;
  }
  bool inside = local_12;
  t = ((sample_1 - float2(_e35.x, _e40.x)) / max(float2((_e35.y - _e35.x), (_e40.y - _e40.x)), (1.0).xx));
  float2 _e101 = t;
  t = (inside ? _e101 : (0.0).xx);
  float _e104 = t.x;
  float _e106 = t.y;
  bool upper = ((_e104 + _e106) > 1.0);
  corners = Constructarray3_float2_(float2(_e35.x, _e40.y), float2(_e35.y, _e40.x), (upper ? float2(_e35.y, _e40.y) : float2(_e35.x, _e40.x)));
  float stride = (terrain_1.z / metres);
  bool loop_init = true;
  [allow_uav_condition] while(true) {
    if (!loop_init) {
      int _e180 = k_1;
      k_1 = asint(asuint(_e180) + asuint(int(1)));
    }
    loop_init = false;
    int _e134 = k_1;
    if ((_e134 < int(3))) {
    } else {
      break;
    }
    {
      int _e137 = k_1;
      float2 _e139 = corners[min(uint(_e137), 2u)];
      float2 corner = (inside ? _e139 : sample_1);
      if (inside) {
        local_13 = all((corner >= (0.0).xx));
      } else {
        local_13 = false;
      }
      bool _e148 = local_13;
      if (_e148) {
        local_14 = all((corner <= last_1));
      } else {
        local_14 = false;
      }
      bool on_map_1 = local_14;
      if (on_map_1) {
        local_15 = (stride < 1.5);
      } else {
        local_15 = false;
      }
      bool _e160 = local_15;
      if (_e160) {
        int _e161 = k_1;
        float4 _e166 = heights_2.Load(int3(naga_f2i32(round(corner)), int(0)));
        h[min(uint(_e161), 2u)] = _e166.x;
      } else {
        if (on_map_1) {
          int _e168 = k_1;
          const float _e172 = texel_height(heights_2, terrain2_2, (corner / (stride).xx));
          h[min(uint(_e168), 2u)] = _e172;
        } else {
          int _e173 = k_1;
          const float _e179 = ground_height(heights_2, terrain_1, terrain2_2, ((corner - (last_1 * 0.5)) * metres));
          h[min(uint(_e173), 2u)] = _e179;
        }
      }
    }
  }
  float bottom_left = h[0];
  float top_right = h[1];
  if (!(upper)) {
    float top_left = h[2];
    float _e192 = t.x;
    float _e197 = t.y;
    return ((top_left + ((top_right - top_left) * _e192)) + ((bottom_left - top_left) * _e197));
  }
  float bottom_right = h[2];
  float _e204 = t.x;
  float _e211 = t.y;
  return ((bottom_right + ((bottom_left - bottom_right) * (1.0 - _e204))) + ((top_right - bottom_right) * (1.0 - _e211)));
}

float grounded_base(Texture2D<float4> heights_3, float4 terrain_2, float4 terrain2_3, float4 mesh_1, float2 xz_3, float root)
{
  float lowest = 1e30;
  int point_ = int(0);
  bool local_16 = (bool)0;

  int points = ((root <= 0.0) ? int(1) : int(5));
  bool loop_init_1 = true;
  [allow_uav_condition] while(true) {
    if (!loop_init_1) {
      int _e43 = point_;
      point_ = asint(asuint(_e43) + asuint(int(1)));
    }
    loop_init_1 = false;
    int _e15 = point_;
    if ((_e15 < points)) {
    } else {
      break;
    }
    {
      int _e17 = point_;
      float angle = (float(_e17) * 1.5707964);
      int _e27 = point_;
      if (!((_e27 == int(4)))) {
        local_16 = (points == int(1));
      } else {
        local_16 = true;
      }
      bool _e36 = local_16;
      float2 out_ = (_e36 ? (0.0).xx : round(float2(cos(angle), sin(angle))));
      float _e38 = lowest;
      const float _e41 = mesh_height(heights_3, terrain_2, terrain2_3, mesh_1, (xz_3 + (out_ * root)));
      lowest = min(_e38, _e41);
    }
  }
  float _e46 = lowest;
  return (_e46 - (0.05 * root));
}

uint3 pcg3d(uint3 input)
{
  uint3 v = (uint3)0;

  v = input;
  uint3 _e2 = v;
  v = ((_e2 * 1664525u) + (1013904223u).xxx);
  uint _e9 = v.x;
  uint _e11 = v.y;
  uint _e13 = v.z;
  v.x = (_e9 + (_e11 * _e13));
  uint _e17 = v.y;
  uint _e19 = v.z;
  uint _e21 = v.x;
  v.y = (_e17 + (_e19 * _e21));
  uint _e25 = v.z;
  uint _e27 = v.x;
  uint _e29 = v.y;
  v.z = (_e25 + (_e27 * _e29));
  uint3 _e32 = v;
  uint3 _e33 = v;
  v = (_e32 ^ (_e33 >> (16u).xxx));
  uint _e39 = v.x;
  uint _e41 = v.y;
  uint _e43 = v.z;
  v.x = (_e39 + (_e41 * _e43));
  uint _e47 = v.y;
  uint _e49 = v.z;
  uint _e51 = v.x;
  v.y = (_e47 + (_e49 * _e51));
  uint _e55 = v.z;
  uint _e57 = v.x;
  uint _e59 = v.y;
  v.z = (_e55 + (_e57 * _e59));
  uint3 _e62 = v;
  return _e62;
}

float unit(uint word)
{
  return (float((word >> 8u)) * 5.9604645e-8);
}

float2 jittered(int2 cell, uint3 hash, float pitch)
{
  const float _e4 = unit(hash.x);
  const float _e6 = unit(hash.y);
  float2 jitter = ((float2(_e4, _e6) - (0.5).xx) * 0.9);
  return (((float2(cell) + (0.5).xx) + jitter) * pitch);
}

int naga_div(int lhs, int rhs) {
  return lhs / (((lhs == int(-2147483647 - 1) & rhs == -1) | (rhs == 0)) ? 1 : rhs);
}

int naga_mod(int lhs, int rhs) {
  int divisor = ((lhs == int(-2147483647 - 1) & rhs == -1) | (rhs == 0)) ? 1 : rhs;
  return lhs - (lhs / divisor) * divisor;
}

int tile_first(int tile, int size, int pitch_1)
{
  int a = asint(asuint(tile) * asuint(size));
  return asint(asuint(naga_div(a, pitch_1)) + asuint(((naga_mod(a, pitch_1) > int(0)) ? int(1) : int(0))));
}

bool on_map(Mapping m, float2 xz_4)
{
  return all((abs(xz_4) <= m.terrain.xy));
}

float2 texel_position(Mapping m_1, float2 xz_5)
{
  return ((xz_5 + m_1.terrain.xy) * m_1.inverse);
}

int2 nearest(Mapping m_2, float2 xz_6)
{
  const float2 _e2 = texel_position(m_2, xz_6);
  float2 t_3 = floor((_e2 + (0.5).xx));
  return clamp(naga_f2i32(t_3), (int(0)).xx, asint(asuint(naga_f2i32(m_2.terrain2_.xy)) - asuint((int(1)).xx)));
}

uint4 naga_f2u32(float4 value) {
  return uint4(clamp(value, 0.0, 4294967000.0));
}

uint4 bytes_at(Texture2D<float4> t_1, int2 texel_1)
{
  float4 _e3 = t_1.Load(int3(texel_1, int(0)));
  return naga_f2u32(round((_e3 * 255.0)));
}

float height_at(Mapping m_3, float2 xz_7)
{
  const float2 _e4 = texel_position(m_3, xz_7);
  const float _e5 = texel_height(heights_4, m_3.terrain2_, _e4);
  return _e5;
}

float water_distance(Mapping m_4, float2 xz_8)
{
  const float2 _e2 = texel_position(m_4, xz_8);
  float2 t_4 = clamp(_e2, (0.0).xx, (m_4.terrain2_.xy - (1.001).xx));
  float2 base_2 = floor(t_4);
  float2 f_2 = (t_4 - base_2);
  int2 i_1 = naga_f2i32(base_2);
  float4 _e16 = banks_texture.Load(int3(i_1, int(0)));
  float d00_ = _e16.x;
  float4 _e24 = banks_texture.Load(int3(asint(asuint(i_1) + asuint(int2(int(1), int(0)))), int(0)));
  float d10_ = _e24.x;
  float4 _e32 = banks_texture.Load(int3(asint(asuint(i_1) + asuint(int2(int(0), int(1)))), int(0)));
  float d01_ = _e32.x;
  float4 _e40 = banks_texture.Load(int3(asint(asuint(i_1) + asuint(int2(int(1), int(1)))), int(0)));
  float d11_ = _e40.x;
  return (lerp(lerp(d00_, d10_, f_2.x), lerp(d01_, d11_, f_2.x), f_2.y) * 40.0);
}

bool in_water(Mapping m_5, float2 xz_9, float clearance)
{
  const float _e3 = water_distance(m_5, xz_9);
  return (_e3 < ((0.25 * m_5.terrain.z) + clearance));
}

float bin_float(uint index)
{
  uint _e3 = asuint(bins.Load(index*4));
  return asfloat(_e3);
}

float intrusion(uint base, float2 xz_10, float clearance_1)
{
  float t_2 = 0.0;

  const float _e3 = bin_float(base);
  const float _e6 = bin_float((base + 1u));
  float2 a_1 = float2(_e3, _e6);
  const float _e10 = bin_float((base + 2u));
  const float _e13 = bin_float((base + 3u));
  float2 b_1 = float2(_e10, _e13);
  float2 d = (b_1 - a_1);
  float length_squared = ((d.x * d.x) + (d.y * d.y));
  if ((length_squared > 0.0)) {
    t_2 = clamp(((((xz_10.x - a_1.x) * d.x) + ((xz_10.y - a_1.y) * d.y)) / length_squared), 0.0, 1.0);
  }
  float _e42 = t_2;
  float2 p_2 = ((a_1 + (d * _e42)) - xz_10);
  const float _e48 = bin_float((base + 4u));
  const float _e51 = bin_float((base + 5u));
  const float _e54 = bin_float((base + 4u));
  float _e56 = t_2;
  float half_ = (_e48 + ((_e51 - _e54) * _e56));
  const float _e61 = bin_float((base + 6u));
  return ((half_ + (_e61 * clearance_1)) - sqrt(((p_2.x * p_2.x) + (p_2.y * p_2.y))));
}

bool in_channel(float2 xz_11, float clearance_2)
{
  int row = (int)0;
  uint item = (uint)0;

  const float _e3 = bin_float(0u);
  const float _e5 = bin_float(1u);
  float2 origin = float2(_e3, _e5);
  const float _e8 = bin_float(2u);
  uint _e11 = asuint(bins.Load(12));
  int columns = int(_e11);
  uint _e15 = asuint(bins.Load(16));
  int rows = int(_e15);
  uint first_item = ((5u + uint(asint(asuint(columns) * asuint(rows)))) + 1u);
  int2 c = naga_f2i32(floor(((xz_11 - origin) / (_e8).xx)));
  int x0_ = max(asint(asuint(c.x) - asuint(int(1))), int(0));
  int x1_ = min(asint(asuint(c.x) + asuint(int(1))), asint(asuint(columns) - asuint(int(1))));
  if ((x0_ > x1_)) {
    return false;
  }
  row = max(asint(asuint(c.y) - asuint(int(1))), int(0));
  bool loop_init_2 = true;
  [allow_uav_condition] while(true) {
    if (!loop_init_2) {
      int _e87 = row;
      row = asint(asuint(_e87) + asuint(int(1)));
    }
    loop_init_2 = false;
    int _e47 = row;
    if ((_e47 <= min(asint(asuint(c.y) + asuint(int(1))), asint(asuint(rows) - asuint(int(1)))))) {
    } else {
      break;
    }
    {
      int _e56 = row;
      uint first = asuint(bins.Load(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e56) * asuint(columns))))) + asuint(x0_))*4));
      int _e64 = row;
      uint last_2 = asuint(bins.Load(asint(asuint(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e64) * asuint(columns))))) + asuint(x1_))) + asuint(int(1)))*4));
      item = first;
      bool loop_init_3 = true;
      [allow_uav_condition] while(true) {
        if (!loop_init_3) {
          uint _e84 = item;
          item = (_e84 + 1u);
        }
        loop_init_3 = false;
        uint _e74 = item;
        if ((_e74 < last_2)) {
        } else {
          break;
        }
        {
          uint _e76 = item;
          const float _e80 = intrusion((first_item + (_e76 * BIN_WORDS)), xz_11, clearance_2);
          if ((_e80 > 0.0)) {
            return true;
          }
        }
      }
    }
  }
  return false;
}

NearChannel ConstructNearChannel(float arg0, uint arg1) {
  NearChannel ret = (NearChannel)0;
  ret.edge = arg0;
  ret.base = arg1;
  return ret;
}

NearChannel near_channel(float2 xz_12, float reach_1)
{
  NearChannel best = (NearChannel)0;
  int row_1 = (int)0;
  uint item_1 = (uint)0;
  bool local_17 = (bool)0;

  const float _e3 = bin_float(0u);
  const float _e5 = bin_float(1u);
  float2 origin_1 = float2(_e3, _e5);
  const float _e8 = bin_float(2u);
  uint _e11 = asuint(bins.Load(12));
  int columns_1 = int(_e11);
  uint _e15 = asuint(bins.Load(16));
  int rows_1 = int(_e15);
  uint first_item_1 = ((5u + uint(asint(asuint(columns_1) * asuint(rows_1)))) + 1u);
  int2 c_1 = naga_f2i32(floor(((xz_12 - origin_1) / (_e8).xx)));
  int x0_1 = max(asint(asuint(c_1.x) - asuint(int(1))), int(0));
  int x1_1 = min(asint(asuint(c_1.x) + asuint(int(1))), asint(asuint(columns_1) - asuint(int(1))));
  best = ConstructNearChannel((reach_1 + 1.0), 0u);
  if ((x0_1 > x1_1)) {
    NearChannel _e45 = best;
    const NearChannel nearchannel = _e45;
    return nearchannel;
  }
  row_1 = max(asint(asuint(c_1.y) - asuint(int(1))), int(0));
  bool loop_init_4 = true;
  [allow_uav_condition] while(true) {
    if (!loop_init_4) {
      int _e100 = row_1;
      row_1 = asint(asuint(_e100) + asuint(int(1)));
    }
    loop_init_4 = false;
    int _e52 = row_1;
    if ((_e52 <= min(asint(asuint(c_1.y) + asuint(int(1))), asint(asuint(rows_1) - asuint(int(1)))))) {
    } else {
      break;
    }
    {
      int _e61 = row_1;
      uint first_1 = asuint(bins.Load(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e61) * asuint(columns_1))))) + asuint(x0_1))*4));
      int _e69 = row_1;
      uint last_3 = asuint(bins.Load(asint(asuint(asint(asuint(asint(asuint(int(5)) + asuint(asint(asuint(_e69) * asuint(columns_1))))) + asuint(x1_1))) + asuint(int(1)))*4));
      item_1 = first_1;
      bool loop_init_5 = true;
      [allow_uav_condition] while(true) {
        if (!loop_init_5) {
          uint _e97 = item_1;
          item_1 = (_e97 + 1u);
        }
        loop_init_5 = false;
        uint _e79 = item_1;
        if ((_e79 < last_3)) {
        } else {
          break;
        }
        {
          uint _e81 = item_1;
          uint base_3 = (first_item_1 + (_e81 * BIN_WORDS));
          const float _e86 = intrusion(base_3, xz_12, 0.0);
          float edge_1 = -(_e86);
          if ((edge_1 <= reach_1)) {
            float _e92 = best.edge;
            local_17 = (edge_1 < _e92);
          } else {
            local_17 = false;
          }
          bool _e95 = local_17;
          if (_e95) {
            best = ConstructNearChannel(edge_1, base_3);
          }
        }
      }
    }
  }
  NearChannel _e103 = best;
  const NearChannel nearchannel_1 = _e103;
  return nearchannel_1;
}

float boulder_size(float u, float position)
{
  float size_1 = (0.3 * pow((1.0 - (u * (1.0 - 0.063095726))), -0.8333333));
  return clamp((size_1 * (0.75 + (0.6 * position))), 0.3, 3.0);
}

float4 boulder_candidate(Mapping m_6, int2 cell_1, uint seed)
{
  bool local_18 = (bool)0;
  bool local_19 = (bool)0;
  bool local_20 = (bool)0;

  const uint3 _e5 = pcg3d(uint3(asuint(cell_1), seed));
  const float2 _e7 = jittered(cell_1, _e5, BOULDER_PITCH);
  const bool _e8 = on_map(m_6, _e7);
  if (!(_e8)) {
    return float4(0.0, 0.0, -1.0, 0.0);
  }
  const int2 _e16 = nearest(m_6, _e7);
  const uint4 _e17 = bytes_at(banks_texture, _e16);
  uint talus = _e17.w;
  float p_3 = ((float((talus >> 4u)) / 15.0) * TALUS_PROBABILITY);
  const float _e27 = unit(_e5.z);
  if (!((_e27 >= p_3))) {
    const float _e32 = height_at(m_6, _e7);
    local_18 = (_e32 <= (m_6.terrain2_.w + BOULDER_WATER_LINE));
  } else {
    local_18 = true;
  }
  bool _e39 = local_18;
  if (!(_e39)) {
    const bool _e44 = in_water(m_6, _e7, BOULDER_WATER_CLEARANCE);
    local_19 = _e44;
  } else {
    local_19 = true;
  }
  bool _e46 = local_19;
  if (!(_e46)) {
    const bool _e51 = in_channel(_e7, 1.0);
    local_20 = _e51;
  } else {
    local_20 = true;
  }
  bool _e53 = local_20;
  if (_e53) {
    return float4(0.0, 0.0, -1.0, 0.0);
  }
  const uint3 _e63 = pcg3d(uint3(asuint(cell_1), (seed ^ 625341585u)));
  const float _e65 = unit(_e63.x);
  const float _e71 = boulder_size(_e65, (float((talus & 15u)) / 15.0));
  return float4(_e7, _e71, (_e27 / p_3));
}

float stone_size(float u_1, float median)
{
  return clamp(((0.71 * median) / sqrt((1.0 - (u_1 * 0.944)))), 0.05, 3.0);
}

float4 stone_candidate(int2 cell_2, uint seed_1)
{
  float chance = (float)0;
  float scale = 1.0;

  const uint3 _e4 = pcg3d(uint3(asuint(cell_2), seed_1));
  const float2 _e6 = jittered(cell_2, _e4, STONE_PITCH);
  const NearChannel _e8 = near_channel(_e6, STONE_REACH);
  if ((_e8.edge > STONE_REACH)) {
    return float4(0.0, 0.0, -1.0, 0.0);
  }
  const float _e20 = bin_float((_e8.base + 8u));
  chance = _e20;
  if ((_e8.edge > COBBLE_METRES)) {
    float _e27 = chance;
    chance = (_e27 / 3.0);
  } else {
    if ((_e8.edge > 0.0)) {
      float _e33 = chance;
      chance = min((1.5 * _e33), 0.5);
      scale = 0.33;
    }
  }
  const float _e40 = unit(_e4.z);
  float _e41 = chance;
  if ((_e40 >= _e41)) {
    return float4(0.0, 0.0, -1.0, 0.0);
  }
  const uint3 _e52 = pcg3d(uint3(asuint(cell_2), (seed_1 ^ 625341585u)));
  const float _e54 = unit(_e52.x);
  const float _e58 = bin_float((_e8.base + 7u));
  const float _e59 = stone_size(_e54, _e58);
  float _e60 = scale;
  float _e64 = chance;
  return float4(_e6, max((_e59 * _e60), 0.05), (_e40 / _e64));
}

void store(Job job, float4 b, float sink, float2 lean, uint variant)
{
  uint _e9; counts.InterlockedAdd(job.slot*4, 1u, _e9);
  if ((_e9 < job.capacity)) {
    uint base_4 = ((job.first + _e9) * 8u);
    pool.Store(base_4*4, asuint(b.x));
    float4 _e26 = params.terrain;
    float4 _e29 = params.terrain2_;
    float4 _e32 = params.mesh;
    const float _e35 = grounded_base(heights_4, _e26, _e29, _e32, b.xy, 0.0);
    pool.Store((base_4 + 1u)*4, asuint((_e35 - sink)));
    pool.Store((base_4 + 2u)*4, asuint(b.y));
    pool.Store((base_4 + 3u)*4, asuint(b.z));
    pool.Store((base_4 + 4u)*4, asuint(sink));
    pool.Store((base_4 + 5u)*4, asuint(lean.x));
    pool.Store((base_4 + 6u)*4, asuint(lean.y));
    pool.Store((base_4 + 7u)*4, asuint((float(variant) + min(b.w, 0.999))));
    return;
  } else {
    return;
  }
}

uint naga_mod(uint lhs, uint rhs) {
  return lhs % (rhs == 0u ? 1u : rhs);
}

uint naga_div(uint lhs, uint rhs) {
  return lhs / (rhs == 0u ? 1u : rhs);
}

Mapping ConstructMapping(float4 arg0, float4 arg1, float arg2) {
  Mapping ret = (Mapping)0;
  ret.terrain = arg0;
  ret.terrain2_ = arg1;
  ret.inverse = arg2;
  return ret;
}

Job ConstructJob(int2 arg0, uint arg1, uint arg2, uint arg3, float arg4, uint2 arg5) {
  Job ret = (Job)0;
  ret.tile = arg0;
  ret.first = arg1;
  ret.capacity = arg2;
  ret.slot = arg3;
  ret.keep = arg4;
  ret.unused = arg5;
  return ret;
}

[numthreads(8, 8, 1)]
void generate_main(uint3 id : SV_DispatchThreadID)
{
  int k = int(0);

  Job job_1 = ConstructJob(asint(jobs.Load2(id.z*32+0)), asuint(jobs.Load(id.z*32+8)), asuint(jobs.Load(id.z*32+12)), asuint(jobs.Load(id.z*32+16)), asfloat(jobs.Load(id.z*32+20)), asuint(jobs.Load2(id.z*32+24)));
  const int _e9 = tile_first(job_1.tile.x, int(32), int(2));
  const int _e14 = tile_first(job_1.tile.y, int(32), int(2));
  int2 first_2 = int2(_e9, _e14);
  const int _e22 = tile_first(asint(asuint(job_1.tile.x) + asuint(int(1))), int(32), int(2));
  const int _e29 = tile_first(asint(asuint(job_1.tile.y) + asuint(int(1))), int(32), int(2));
  int2 next = int2(_e22, _e29);
  int2 cell_4 = asint(asuint(first_2) + asuint(int2(id.xy)));
  if (any((cell_4 >= next))) {
    return;
  }
  float4 _e38 = params.terrain;
  float4 _e41 = params.terrain2_;
  float _e45 = params.rules.x;
  Mapping m_7 = ConstructMapping(_e38, _e41, _e45);
  uint _e50 = params.shape.x;
  const float4 _e51 = boulder_candidate(m_7, cell_4, _e50);
  if ((_e51.z > 0.0)) {
    uint _e59 = params.shape.x;
    const uint3 _e63 = pcg3d(uint3(asuint(cell_4), (_e59 ^ 625341585u)));
    uint variant_1 = naga_mod(_e63.z, VARIANTS);
    const float _e68 = unit(_e63.y);
    float _e83 = params.tall[naga_div(variant_1, 4u)][naga_mod(variant_1, 4u)];
    float sink_1 = (((0.25 + (0.15 * _e68)) * _e51.z) * _e83);
    float2 span = float2(1.5, 0.0);
    const float _e91 = height_at(m_7, (_e51.xy + span.xy));
    const float _e95 = height_at(m_7, (_e51.xy - span.xy));
    const float _e100 = height_at(m_7, (_e51.xy + span.yx));
    const float _e104 = height_at(m_7, (_e51.xy - span.yx));
    float2 lean_1 = (float2((_e91 - _e95), (_e100 - _e104)) / (3.0).xx);
    store(job_1, _e51, sink_1, lean_1, variant_1);
  }
  bool loop_init_6 = true;
  [allow_uav_condition] while(true) {
    if (!loop_init_6) {
      int _e165 = k;
      k = asint(asuint(_e165) + asuint(int(1)));
    }
    loop_init_6 = false;
    int _e112 = k;
    if ((_e112 < int(4))) {
    } else {
      break;
    }
    {
      int _e117 = k;
      int _e120 = k;
      int2 stone_cell = asint(asuint(asint(asuint(int(2)) * asuint(cell_4))) + asuint(int2(naga_mod(_e117, int(2)), naga_div(_e120, int(2)))));
      uint _e128 = params.shape.w;
      const float4 _e129 = stone_candidate(stone_cell, _e128);
      if ((_e129.z > 0.0)) {
        uint _e137 = params.shape.w;
        const uint3 _e141 = pcg3d(uint3(asuint(stone_cell), (_e137 ^ 625341585u)));
        uint variant_2 = naga_mod(_e141.z, VARIANTS);
        const float _e146 = unit(_e141.y);
        float _e161 = params.tall[naga_div(variant_2, 4u)][naga_mod(variant_2, 4u)];
        float sink_2 = (((0.3 + (0.3 * _e146)) * _e129.z) * _e161);
        store(job_1, _e129, sink_2, (0.0).xx, variant_2);
      }
    }
  }
  return;
}
