// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: trees (ground + common + trees)
// Entry point: fragment_mesh, compile with /T ps_5_0 /E fragment_mesh
// override LIGHT = false
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) frame -> b0  constant buffer
//   @group(1) @binding(0) linear_sampler -> s0  SamplerState
//   @group(1) @binding(3) flora_texture -> t0  Texture2DArray (Sampled { kind: Float, multi: false })
//   @group(1) @binding(9) world -> b1  constant buffer
//   @group(2) @binding(0) tree_shadow_map -> t1  Texture2D (Depth { multi: false })
//   @group(2) @binding(1) shadow_sampler -> s1  SamplerComparisonState

struct FrameUniforms {
  row_major float4x4 view_proj;
  float4 camera_position;
  float4 camera_forward;
  float4 camera_right;
  float4 camera_up;
  float4 sun_direction;
  float4 atmosphere;
  float4 sky_tint;
  float4 mist_params;
  float4 mist_colour;
  float4 mist_wind;
  float4 cloud_params;
  float4 cloud_motion;
  float4 cloud_colour;
  float4 water_params;
  float4 water_shallow;
  float4 water_deep;
  float4 water_current;
  float4 wave_params;
  float4 wave_params2_;
  float4 water_origin;
  float4 vegetation;
  float4 vegetation2_;
  float4 viewport;
  row_major float4x4 shadow_view_proj;
  float4 shadow_params;
  float4 weather;
  float4 weather2_;
  float4 surface;
  float4 clouds2_;
  float4 clouds3_;
  float4 clouds4_;
  float4 weather3_;
  row_major float4x4 previous_view_proj;
  float4 temporal;
  float4 distances;
  float4 fades;
  float4 output;
  float4 cold;
  float4 sea_ice;
  float4 rivers;
  float4 ground;
  float4 vegetation3_;
  float4 rock;
  float4 regional;
  float4 air;
  float4 light;
  float4 gust;
  float4 weather4_;
  float4 clouds5_;
  float4 alto;
  float4 rivers2_;
  float4 waterside;
  float4 mouths[16];
};

struct WorldInfo {
  float4 species[8];
  float4 species_tint[8];
  float4 terrain;
  float4 terrain2_;
  float4 material_tints[12];
  float4 trees;
  float4 species_canopy[8];
};

struct MeshOut {
  float4 clip_position : SV_Position;
  float3 world_position : LOC0;
  float3 normal : LOC1;
  float2 uv : LOC2;
  nointerpolation int layer : LOC3;
  float ao : LOC4;
  nointerpolation uint species : LOC5;
  nointerpolation float fade : LOC6;
  nointerpolation float tint : LOC7;
  nointerpolation float dryness : LOC8;
  float3 sun : LOC9;
  float3 sky : LOC10;
  nointerpolation float snow : LOC11;
  float colour : LOC12;
  nointerpolation float wet : LOC13;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const float2 PREVAILING_WIND = float2(0.8, 0.6);
static const float WIND_BOUND = 0.08;
static const float ATLAS_MARGIN = 0.085;
static const float TOP_TAN = 0.8390996;
static const bool LIGHT = false;

cbuffer frame : register(b0) { FrameUniforms frame; }
SamplerState linear_sampler : register(s0);
Texture2DArray<float4> flora_texture : register(t0);
cbuffer world : register(b1) { WorldInfo world; }
Texture2D<float> tree_shadow_map : register(t1);
SamplerComparisonState shadow_sampler : register(s1);

struct FragmentInput_fragment_mesh {
  float3 world_position_1 : LOC0;
  float3 normal_5 : LOC1;
  float2 uv : LOC2;
  nointerpolation int layer_1 : LOC3;
  float ao : LOC4;
  nointerpolation uint species_1 : LOC5;
  nointerpolation float fade_1 : LOC6;
  nointerpolation float tint_2 : LOC7;
  nointerpolation float dryness_2 : LOC8;
  float3 sun : LOC9;
  float3 sky_1 : LOC10;
  nointerpolation float snow : LOC11;
  float colour_4 : LOC12;
  nointerpolation float wet_1 : LOC13;
  float4 clip_position : SV_Position;
  bool front_1 : SV_IsFrontFace;
};

float pixel_dither(float2 pixel)
{
  return frac((52.982918 * frac(dot(pixel, float2(0.06711056, 0.00583715)))));
}

float3 srgb_to_linear(float3 colour)
{
  return pow(max(colour, (0.0).xxx), (2.2).xxx);
}

float3 sun_dir()
{
  float4 _e2 = frame.sun_direction;
  return normalize(_e2.xyz);
}

float luminance(float3 colour_1)
{
  return dot(colour_1, float3(0.2126, 0.7152, 0.0722));
}

uint2 NagaDepthDimensions2D(Texture2D<float> tex)
{
  uint4 ret;
  tex.GetDimensions(0, ret.x, ret.y, ret.z);
  return ret.xy;
}

float tree_shadow(float3 position, float3 normal_2)
{
  bool local = (bool)0;
  bool local_1 = (bool)0;
  float lit_ = 0.0;

  float strength = frame.shadow_params.x;
  if ((strength <= 0.001)) {
    return 1.0;
  }
  float4x4 _e11 = frame.shadow_view_proj;
  float4 clip_ = mul(float4((position + (normal_2 * 0.25)), 1.0), _e11);
  float2 uv_1 = float2(((clip_.x * 0.5) + 0.5), (0.5 - (clip_.y * 0.5)));
  if (!(any((uv_1 <= (0.0).xx)))) {
    local = any((uv_1 >= (1.0).xx));
  } else {
    local = true;
  }
  bool _e41 = local;
  if (!(_e41)) {
    local_1 = (clip_.z >= 1.0);
  } else {
    local_1 = true;
  }
  bool _e49 = local_1;
  if (_e49) {
    return 1.0;
  }
  float _e54 = frame.shadow_params.y;
  float texel = (_e54 / float(NagaDepthDimensions2D(tree_shadow_map).x));
  float depth = (clip_.z - 0.0008);
  float _e65 = lit_;
  float _e73 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_1 + (float2(-0.7, -0.3) * texel)), depth);
  lit_ = (_e65 + _e73);
  float _e75 = lit_;
  float _e83 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_1 + (float2(0.3, -0.7) * texel)), depth);
  lit_ = (_e75 + _e83);
  float _e85 = lit_;
  float _e93 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_1 + (float2(0.7, 0.3) * texel)), depth);
  lit_ = (_e85 + _e93);
  float _e95 = lit_;
  float _e103 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_1 + (float2(-0.3, 0.7) * texel)), depth);
  lit_ = (_e95 + _e103);
  float _e105 = lit_;
  lit_ = (_e105 * 0.25);
  float edge = min(min(uv_1.x, uv_1.y), min((1.0 - uv_1.x), (1.0 - uv_1.y)));
  float _e119 = lit_;
  lit_ = lerp(1.0, _e119, smoothstep(0.0, 0.08, edge));
  float _e125 = lit_;
  return lerp(1.0, _e125, strength);
}

bool dithered_out(float dither, float fade)
{
  return ((fade < 0.0) ? (dither <= -(fade)) : (dither > fade));
}

float3 weather_surface(float3 albedo_1, float up, float cover, float wet)
{
  float3 colour_2 = (float3)0;

  colour_2 = (albedo_1 * (1.0 - (wet * 0.25)));
  float snow_1 = (cover * smoothstep(0.1, 0.7, up));
  float3 _e14 = colour_2;
  return lerp(_e14, float3(0.78, 0.82, 0.88), (snow_1 * 0.85));
}

float3 foliage_colour(float3 albedo_2, uint species, float tint, float dryness, float clump)
{
  float3 colour_3 = (float3)0;

  float t = (tint - 0.5);
  float4 _e10 = world.species_tint[species];
  colour_3 = (albedo_2 * _e10.xyz);
  float3 _e14 = colour_3;
  const float _e15 = luminance(_e14);
  float3 _e17 = colour_3;
  colour_3 = lerp((_e15).xxx, _e17, (1.0 + (0.2 * t)));
  float3 _e23 = colour_3;
  colour_3 = (_e23 * float3((1.0 + (0.08 * t)), 1.0, (1.0 - (0.08 * t))));
  float3 _e35 = colour_3;
  colour_3 = ((_e35 * (1.0 + (0.16 * t))) * (0.9 + (0.2 * clump)));
  float3 _e46 = colour_3;
  float3 _e47 = colour_3;
  colour_3 = lerp(_e46, (_e47 * float3(1.25, 1.05, 0.55)), (dryness * 0.35));
  float3 _e56 = colour_3;
  return _e56;
}

float3 shade_foliage(float3 albedo_3, float3 normal_3, float3 world_position, float occlusion, float3 sun_lit, float3 sky)
{
  const float3 _e6 = sun_dir();
  float4 _e9 = frame.camera_position;
  float3 view = normalize((_e9.xyz - world_position));
  float wrap = saturate(((dot(normal_3, _e6) + 0.45) / 1.45));
  float back = (pow(saturate(dot(-(view), _e6)), 3.0) * 0.6);
  float3 direct = (sun_lit * (((wrap * 0.85)).xxx + (back * float3(0.9, 1.1, 0.55))));
  return (((albedo_3 * ((direct * occlusion) + ((sky * occlusion) * 0.75))) / (3.1415927).xxx) * 2.6);
}

int leaf_normal_layer(int layer)
{
  return ((layer >= int(12)) ? asint(asuint(layer) + asuint(int(8))) : asint(asuint(layer) + asuint(int(11))));
}

float3 bark_colour(float3 albedo_4, float3 normal_4, float tint_1, float dryness_1)
{
  float damp = saturate((1.0 - (dryness_1 * 1.6)));
  const float3 _e9 = sun_dir();
  float shaded = saturate((0.5 - (dot(normal_4, _e9) * 0.8)));
  float moss = ((damp * shaded) * (0.35 + (0.3 * tint_1)));
  float3 green = ((albedo_4 * float3(0.75, 1.1, 0.6)) + float3(0.0, 0.012, 0.0));
  return lerp((albedo_4 * (0.9 + (tint_1 * 0.2))), green, moss);
}

float4 fragment_mesh(FragmentInput_fragment_mesh fragmentinput_fragment_mesh) : SV_Target0
{
  MeshOut in_ = { fragmentinput_fragment_mesh.clip_position, fragmentinput_fragment_mesh.world_position_1, fragmentinput_fragment_mesh.normal_5, fragmentinput_fragment_mesh.uv, fragmentinput_fragment_mesh.layer_1, fragmentinput_fragment_mesh.ao, fragmentinput_fragment_mesh.species_1, fragmentinput_fragment_mesh.fade_1, fragmentinput_fragment_mesh.tint_2, fragmentinput_fragment_mesh.dryness_2, fragmentinput_fragment_mesh.sun, fragmentinput_fragment_mesh.sky_1, fragmentinput_fragment_mesh.snow, fragmentinput_fragment_mesh.colour_4, fragmentinput_fragment_mesh.wet_1 };
  bool front = fragmentinput_fragment_mesh.front_1;
  float2 bump = (0.0).xx;
  float3 geometric = (float3)0;
  float3 normal = (float3)0;
  float3 albedo = (float3)0;
  float3 normal_1 = (float3)0;

  float3 dx = ddx(in_.world_position);
  float3 dy = ddy(in_.world_position);
  float2 du = ddx(in_.uv);
  float2 dv = ddy(in_.uv);
  float4 texel_1 = flora_texture.Sample(linear_sampler, float3(in_.uv, in_.layer));
  bool leaf = (in_.layer >= int(4));
  if (true) {
    const int _e30 = leaf_normal_layer((leaf ? in_.layer : int(4)));
    float4 _e31 = flora_texture.Sample(linear_sampler, float3(in_.uv, _e30));
    bump = ((_e31.xy * 2.0) - (1.0).xx);
  }
  geometric = normalize(cross(dx, dy));
  float3 _e41 = geometric;
  float3 _e43 = geometric;
  float3 _e44 = geometric;
  float4 _e47 = frame.camera_position;
  geometric = ((dot(_e44, (_e47.xyz - in_.world_position)) > 0.0) ? _e43 : -(_e41));
  const float _e57 = pixel_dither(in_.clip_position.xy);
  const bool _e59 = dithered_out(_e57, in_.fade);
  if (_e59) {
    discard;
  }
  if (leaf) {
    if ((texel_1.w < 0.45)) {
      discard;
    }
    normal = normalize(in_.normal);
    if (true) {
      float determinant_ = ((du.x * dv.y) - (du.y * dv.x));
      float inverse = ((abs(determinant_) > 1e-12) ? (1.0 / determinant_) : 0.0);
      float3 tangent = (((dx * dv.y) - (dy * du.y)) * inverse);
      float3 bitangent = (((dy * du.x) - (dx * dv.x)) * inverse);
      float scale = (0.5 / max(max(length(tangent), length(bitangent)), 0.0001));
      float3 _e102 = normal;
      float _e104 = bump.x;
      float _e107 = bump.y;
      normal = normalize((_e102 + ((((tangent * _e104) + (bitangent * _e107)) * scale) * 0.6)));
    }
    const float3 _e116 = srgb_to_linear(texel_1.xyz);
    const float3 _e121 = foliage_colour(_e116, in_.species, in_.tint, in_.dryness, in_.colour);
    albedo = _e121;
    float3 _e123 = albedo;
    float _e125 = geometric.y;
    const float3 _e128 = weather_surface(_e123, _e125, in_.snow, in_.wet);
    albedo = _e128;
    float3 _e129 = albedo;
    float3 _e130 = normal;
    const float3 _e135 = shade_foliage(_e129, _e130, in_.world_position, in_.ao, in_.sun, in_.sky);
    return float4(_e135, 1.0);
  }
  normal_1 = normalize(in_.normal);
  if (!(front)) {
    float3 _e142 = normal_1;
    normal_1 = -(_e142);
  }
  const float3 _e145 = srgb_to_linear(texel_1.xyz);
  float3 _e146 = normal_1;
  const float3 _e149 = bark_colour(_e145, _e146, in_.tint, in_.dryness);
  float _e151 = normal_1.y;
  const float3 _e158 = weather_surface(_e149, _e151, in_.snow, min((in_.wet * 1.4), 1.0));
  float3 _e160 = normal_1;
  const float3 _e161 = sun_dir();
  float3 _e166 = normal_1;
  const float _e167 = tree_shadow(in_.world_position, _e166);
  float3 direct_1 = ((in_.sun * saturate(dot(_e160, _e161))) * _e167);
  float3 colour_5 = (((_e158 * (direct_1 + (((in_.sky * in_.ao) * (0.6 + (texel_1.w * 0.4))) * 0.75))) / (3.1415927).xxx) * 2.6);
  return float4(colour_5, 1.0);
}
