// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: trees (ground + common + trees)
// Entry point: fragment_shadow, compile with /T ps_5_0 /E fragment_shadow
// override LIGHT = true
//
// Resources (WGSL group/binding -> register):
//   @group(1) @binding(0) linear_sampler -> s0  SamplerState
//   @group(1) @binding(4) impostor_texture -> t0  Texture2DArray (Sampled { kind: Float, multi: false })

struct ShadowOut {
  float4 clip_position : SV_Position;
  float2 uv : LOC0;
  nointerpolation int layer : LOC1;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const float2 PREVAILING_WIND = float2(0.8, 0.6);
static const float WIND_BOUND = 0.08;
static const float ATLAS_MARGIN = 0.085;
static const float TOP_TAN = 0.8390996;

SamplerState linear_sampler : register(s0);
Texture2DArray<float4> impostor_texture : register(t0);

struct FragmentInput_fragment_shadow {
  float2 uv : LOC0;
  nointerpolation int layer : LOC1;
  float4 clip_position : SV_Position;
};

void fragment_shadow(FragmentInput_fragment_shadow fragmentinput_fragment_shadow)
{
  ShadowOut in_ = { fragmentinput_fragment_shadow.clip_position, fragmentinput_fragment_shadow.uv, fragmentinput_fragment_shadow.layer };
  float4 _e6 = impostor_texture.SampleLevel(linear_sampler, float3(in_.uv, in_.layer), 1.0);
  if ((_e6.w < 0.5)) {
    discard;
  } else {
    return;
  }
}
