// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: trees (ground + common + trees)
// Entry point: fragment_impostor, compile with /T ps_5_0 /E fragment_impostor
// override LIGHT = false
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) frame -> b0  constant buffer
//   @group(1) @binding(0) linear_sampler -> s0  SamplerState
//   @group(1) @binding(4) impostor_texture -> t0  Texture2DArray (Sampled { kind: Float, multi: false })
//   @group(2) @binding(0) tree_shadow_map -> t1  Texture2D (Depth { multi: false })
//   @group(2) @binding(1) shadow_sampler -> s1  SamplerComparisonState

struct FrameUniforms {
  row_major float4x4 view_proj;
  float4 camera_position;
  float4 camera_forward;
  float4 camera_right;
  float4 camera_up;
  float4 sun_direction;
  float4 atmosphere;
  float4 sky_tint;
  float4 mist_params;
  float4 mist_colour;
  float4 mist_wind;
  float4 cloud_params;
  float4 cloud_motion;
  float4 cloud_colour;
  float4 water_params;
  float4 water_shallow;
  float4 water_deep;
  float4 water_current;
  float4 wave_params;
  float4 wave_params2_;
  float4 water_origin;
  float4 vegetation;
  float4 vegetation2_;
  float4 viewport;
  row_major float4x4 shadow_view_proj;
  float4 shadow_params;
  float4 weather;
  float4 weather2_;
  float4 surface;
  float4 clouds2_;
  float4 clouds3_;
  float4 clouds4_;
  float4 weather3_;
  row_major float4x4 previous_view_proj;
  float4 temporal;
  float4 distances;
  float4 fades;
  float4 output;
  float4 cold;
  float4 sea_ice;
  float4 rivers;
  float4 ground;
  float4 vegetation3_;
  float4 rock;
  float4 regional;
  float4 air;
  float4 light;
  float4 gust;
  float4 weather4_;
  float4 clouds5_;
  float4 alto;
  float4 rivers2_;
  float4 waterside;
  float4 mouths[16];
};

struct ImpostorOut {
  float4 clip_position : SV_Position;
  float3 world_position : LOC0;
  float2 at : LOC1;
  float3 right : LOC3;
  float3 facing : LOC4;
  nointerpolation float fade : LOC5;
  nointerpolation float tint : LOC6;
  nointerpolation float dryness : LOC7;
  float3 sun : LOC8;
  float3 sky : LOC9;
  nointerpolation float snow : LOC10;
  nointerpolation float2 view : LOC11;
  nointerpolation float level : LOC12;
  nointerpolation float wet : LOC13;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const float2 PREVAILING_WIND = float2(0.8, 0.6);
static const float WIND_BOUND = 0.08;
static const float ATLAS_MARGIN = 0.085;
static const float TOP_TAN = 0.8390996;

cbuffer frame : register(b0) { FrameUniforms frame; }
SamplerState linear_sampler : register(s0);
Texture2DArray<float4> impostor_texture : register(t0);
Texture2D<float> tree_shadow_map : register(t1);
SamplerComparisonState shadow_sampler : register(s1);

struct FragmentInput_fragment_impostor {
  float3 world_position_1 : LOC0;
  float2 at : LOC1;
  float3 right : LOC3;
  float3 facing : LOC4;
  nointerpolation float fade_1 : LOC5;
  nointerpolation float tint : LOC6;
  nointerpolation float dryness : LOC7;
  float3 sun : LOC8;
  float3 sky_1 : LOC9;
  nointerpolation float snow : LOC10;
  nointerpolation float2 view : LOC11;
  nointerpolation float level : LOC12;
  nointerpolation float wet_1 : LOC13;
  float4 clip_position : SV_Position;
};

float pixel_dither(float2 pixel)
{
  return frac((52.982918 * frac(dot(pixel, float2(0.06711056, 0.00583715)))));
}

float3 srgb_to_linear(float3 colour)
{
  return pow(max(colour, (0.0).xxx), (2.2).xxx);
}

float3 sun_dir()
{
  float4 _e2 = frame.sun_direction;
  return normalize(_e2.xyz);
}

uint2 NagaDepthDimensions2D(Texture2D<float> tex)
{
  uint4 ret;
  tex.GetDimensions(0, ret.x, ret.y, ret.z);
  return ret.xy;
}

float tree_shadow(float3 position, float3 normal)
{
  bool local_1 = (bool)0;
  bool local_2 = (bool)0;
  float lit_ = 0.0;

  float strength = frame.shadow_params.x;
  if ((strength <= 0.001)) {
    return 1.0;
  }
  float4x4 _e11 = frame.shadow_view_proj;
  float4 clip_ = mul(float4((position + (normal * 0.25)), 1.0), _e11);
  float2 uv_1 = float2(((clip_.x * 0.5) + 0.5), (0.5 - (clip_.y * 0.5)));
  if (!(any((uv_1 <= (0.0).xx)))) {
    local_1 = any((uv_1 >= (1.0).xx));
  } else {
    local_1 = true;
  }
  bool _e41 = local_1;
  if (!(_e41)) {
    local_2 = (clip_.z >= 1.0);
  } else {
    local_2 = true;
  }
  bool _e49 = local_2;
  if (_e49) {
    return 1.0;
  }
  float _e54 = frame.shadow_params.y;
  float texel = (_e54 / float(NagaDepthDimensions2D(tree_shadow_map).x));
  float depth = (clip_.z - 0.0008);
  float _e65 = lit_;
  float _e73 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_1 + (float2(-0.7, -0.3) * texel)), depth);
  lit_ = (_e65 + _e73);
  float _e75 = lit_;
  float _e83 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_1 + (float2(0.3, -0.7) * texel)), depth);
  lit_ = (_e75 + _e83);
  float _e85 = lit_;
  float _e93 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_1 + (float2(0.7, 0.3) * texel)), depth);
  lit_ = (_e85 + _e93);
  float _e95 = lit_;
  float _e103 = tree_shadow_map.SampleCmpLevelZero(shadow_sampler, (uv_1 + (float2(-0.3, 0.7) * texel)), depth);
  lit_ = (_e95 + _e103);
  float _e105 = lit_;
  lit_ = (_e105 * 0.25);
  float edge = min(min(uv_1.x, uv_1.y), min((1.0 - uv_1.x), (1.0 - uv_1.y)));
  float _e119 = lit_;
  lit_ = lerp(1.0, _e119, smoothstep(0.0, 0.08, edge));
  float _e125 = lit_;
  return lerp(1.0, _e125, strength);
}

bool dithered_out(float dither, float fade)
{
  return ((fade < 0.0) ? (dither <= -(fade)) : (dither > fade));
}

float3 weather_surface(float3 albedo_1, float up, float cover, float wet)
{
  float3 colour_1 = (float3)0;

  colour_1 = (albedo_1 * (1.0 - (wet * 0.25)));
  float snow_1 = (cover * smoothstep(0.1, 0.7, up));
  float3 _e14 = colour_1;
  return lerp(_e14, float3(0.78, 0.82, 0.88), (snow_1 * 0.85));
}

float3 shade_foliage(float3 albedo_2, float3 normal_1, float3 world_position, float occlusion, float3 sun_lit, float3 sky)
{
  const float3 _e6 = sun_dir();
  float4 _e9 = frame.camera_position;
  float3 view_1 = normalize((_e9.xyz - world_position));
  float wrap = saturate(((dot(normal_1, _e6) + 0.45) / 1.45));
  float back = (pow(saturate(dot(-(view_1), _e6)), 3.0) * 0.6);
  float3 direct = (sun_lit * (((wrap * 0.85)).xxx + (back * float3(0.9, 1.1, 0.55))));
  return (((albedo_2 * ((direct * occlusion) + ((sky * occlusion) * 0.75))) / (3.1415927).xxx) * 2.6);
}

float naga_mod(float lhs, float rhs) {
  return lhs - rhs * trunc(lhs / rhs);
}

float2 atlas_uv(float cell, float2 uv)
{
  float column = naga_mod(cell, 3.0);
  float row = floor((cell / 3.0));
  float2 inner = ((0.085).xx + (saturate(uv) * 0.83));
  return ((float2(column, row) + inner) / (3.0).xx);
}

int naga_f2i32(float value) {
  return int(clamp(value, -2147483600.0, 2147483500.0));
}

float4 fragment_impostor(FragmentInput_fragment_impostor fragmentinput_fragment_impostor) : SV_Target0
{
  ImpostorOut in_ = { fragmentinput_fragment_impostor.clip_position, fragmentinput_fragment_impostor.world_position_1, fragmentinput_fragment_impostor.at, fragmentinput_fragment_impostor.right, fragmentinput_fragment_impostor.facing, fragmentinput_fragment_impostor.fade_1, fragmentinput_fragment_impostor.tint, fragmentinput_fragment_impostor.dryness, fragmentinput_fragment_impostor.sun, fragmentinput_fragment_impostor.sky_1, fragmentinput_fragment_impostor.snow, fragmentinput_fragment_impostor.view, fragmentinput_fragment_impostor.level, fragmentinput_fragment_impostor.wet_1 };
  bool local = (bool)0;
  float3 albedo = (float3)0;

  const float _e3 = pixel_dither(in_.clip_position.xy);
  const float2 _e7 = atlas_uv(in_.view.x, in_.at);
  int layer = naga_f2i32(in_.view.y);
  float4 texel_1 = impostor_texture.SampleLevel(linear_sampler, float3(_e7, layer), in_.level);
  if (!((texel_1.w < 0.5))) {
    const bool _e22 = dithered_out(_e3, in_.fade);
    local = _e22;
  } else {
    local = true;
  }
  bool _e24 = local;
  if (_e24) {
    discard;
  }
  float4 _e30 = impostor_texture.SampleLevel(linear_sampler, float3(_e7, asint(asuint(layer) + asuint(int(1)))), in_.level);
  float3 packed = ((_e30.xyz * 2.0) - (1.0).xxx);
  float3 up_1 = float3(0.0, 1.0, 0.0);
  float3 normal_2 = normalize((((in_.right * packed.x) + (up_1 * packed.y)) + (in_.facing * packed.z)));
  const float3 _e53 = srgb_to_linear(texel_1.xyz);
  albedo = (_e53 * (0.82 + (in_.tint * 0.36)));
  float3 _e61 = albedo;
  float3 _e62 = albedo;
  albedo = lerp(_e61, (_e62 * float3(1.25, 1.05, 0.55)), (in_.dryness * 0.35));
  float3 _e72 = albedo;
  const float3 _e78 = weather_surface(_e72, (normal_2.y + 0.3), in_.snow, in_.wet);
  albedo = _e78;
  const float _e81 = tree_shadow(in_.world_position, normal_2);
  float3 sun_lit_1 = (in_.sun * _e81);
  float3 _e83 = albedo;
  const float3 _e87 = shade_foliage(_e83, normal_2, in_.world_position, 0.9, sun_lit_1, in_.sky);
  return float4(_e87, 1.0);
}
