// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: trees (ground + common + trees)
// Entry point: vertex_impostor, compile with /T vs_5_0 /E vertex_impostor
// override LIGHT = true
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) frame -> b0  constant buffer
//   @group(1) @binding(0) linear_sampler -> s0  SamplerState
//   @group(1) @binding(5) noise_texture -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(9) world -> b1  constant buffer
//   @group(1) @binding(10) terrain_shadow_texture -> t1  Texture2D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(11) clamp_sampler -> s1  SamplerState
//   @group(1) @binding(12) ground_layers -> t2  Texture2DArray (Sampled { kind: Float, multi: false })
//   @group(1) @binding(13) regional_texture -> t3  Texture2D (Sampled { kind: Float, multi: false })
//   @group(1) @binding(14) surface_weather_texture -> t4  Texture2D (Sampled { kind: Float, multi: false })
// D3D11: reads vertex_index or instance_index: bind { int first_vertex; int first_instance; uint other; } at b2 for each draw, with the draw's first vertex (base vertex when indexed) and first instance. Indirect draws take 0 and 0.

struct NagaConstants {
  int first_vertex;
  int first_instance;
  uint other;
};
cbuffer NagaConstantsBlock : register(b2) { NagaConstants _NagaConstants; }

struct FrameUniforms {
  row_major float4x4 view_proj;
  float4 camera_position;
  float4 camera_forward;
  float4 camera_right;
  float4 camera_up;
  float4 sun_direction;
  float4 atmosphere;
  float4 sky_tint;
  float4 mist_params;
  float4 mist_colour;
  float4 mist_wind;
  float4 cloud_params;
  float4 cloud_motion;
  float4 cloud_colour;
  float4 water_params;
  float4 water_shallow;
  float4 water_deep;
  float4 water_current;
  float4 wave_params;
  float4 wave_params2_;
  float4 water_origin;
  float4 vegetation;
  float4 vegetation2_;
  float4 viewport;
  row_major float4x4 shadow_view_proj;
  float4 shadow_params;
  float4 weather;
  float4 weather2_;
  float4 surface;
  float4 clouds2_;
  float4 clouds3_;
  float4 clouds4_;
  float4 weather3_;
  row_major float4x4 previous_view_proj;
  float4 temporal;
  float4 distances;
  float4 fades;
  float4 output;
  float4 cold;
  float4 sea_ice;
  float4 rivers;
  float4 ground;
  float4 vegetation3_;
  float4 rock;
  float4 regional;
  float4 air;
  float4 light;
  float4 gust;
  float4 weather4_;
  float4 clouds5_;
  float4 alto;
  float4 rivers2_;
  float4 waterside;
  float4 mouths[16];
};

struct WorldInfo {
  float4 species[8];
  float4 species_tint[8];
  float4 terrain;
  float4 terrain2_;
  float4 material_tints[12];
  float4 trees;
  float4 species_canopy[8];
};

struct ImpostorIn {
  uint vertex_index : SV_VertexID;
  float3 instance_position : LOC4;
  float instance_scale : LOC5;
  float instance_rotation : LOC6;
  float instance_tint : LOC7;
  float instance_species_fade : LOC8;
  float instance_dryness : LOC9;
  float instance_width : LOC10;
};

struct ImpostorOut {
  float4 clip_position : SV_Position;
  float3 world_position : LOC0;
  float2 at : LOC1;
  float3 right : LOC3;
  float3 facing : LOC4;
  nointerpolation float fade : LOC5;
  nointerpolation float tint : LOC6;
  nointerpolation float dryness : LOC7;
  float3 sun : LOC8;
  float3 sky : LOC9;
  nointerpolation float snow : LOC10;
  nointerpolation float2 view : LOC11;
  nointerpolation float level : LOC12;
  nointerpolation float wet : LOC13;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const float2 PREVAILING_WIND = float2(0.8, 0.6);
static const float WIND_BOUND = 0.08;
static const float ATLAS_MARGIN = 0.085;
static const float TOP_TAN = 0.8390996;

cbuffer frame : register(b0) { FrameUniforms frame; }
SamplerState linear_sampler : register(s0);
Texture2D<float4> noise_texture : register(t0);
cbuffer world : register(b1) { WorldInfo world; }
Texture2D<float4> terrain_shadow_texture : register(t1);
SamplerState clamp_sampler : register(s1);
Texture2DArray<float4> ground_layers : register(t2);
Texture2D<float4> regional_texture : register(t3);
Texture2D<float4> surface_weather_texture : register(t4);

struct VertexOutput_vertex_impostor {
  float3 world_position_1 : LOC0;
  float2 at : LOC1;
  float3 right_1 : LOC3;
  float3 facing_1 : LOC4;
  nointerpolation float fade : LOC5;
  nointerpolation float tint : LOC6;
  nointerpolation float dryness : LOC7;
  float3 sun : LOC8;
  float3 sky_1 : LOC9;
  nointerpolation float snow : LOC10;
  nointerpolation float2 view : LOC11;
  nointerpolation float level : LOC12;
  nointerpolation float wet : LOC13;
  float4 clip_position : SV_Position;
};

float remap(float value, float old_min, float old_max, float new_min, float new_max)
{
  return (new_min + (((value - old_min) / max((old_max - old_min), 0.0001)) * (new_max - new_min)));
}

float time_seconds()
{
  float _e3 = frame.camera_position.w;
  return _e3;
}

float hash11_(float value_1)
{
  float x = (float)0;

  x = frac((value_1 * 0.1031));
  float _e5 = x;
  float _e6 = x;
  x = (_e5 * (_e6 + 33.33));
  float _e10 = x;
  float _e11 = x;
  float _e12 = x;
  return frac((_e10 * (_e11 + _e12)));
}

float3 sun_dir()
{
  float4 _e2 = frame.sun_direction;
  return normalize(_e2.xyz);
}

float henyey_greenstein(float cos_theta, float g)
{
  float g2_ = (g * g);
  return ((1.0 - g2_) / (12.566371 * pow(max(((1.0 + g2_) - ((2.0 * g) * cos_theta)), 0.0001), 1.5)));
}

float air_mass(float cos_zenith)
{
  float c = clamp(cos_zenith, -0.2, 1.0);
  float zenith_degrees = degrees(acos(c));
  return (1.0 / max((c + (0.50572 * pow(max((96.07995 - zenith_degrees), 0.05), -1.6364))), 0.02));
}

float3 rayleigh_beta()
{
  float _e4 = frame.atmosphere.x;
  return (RAYLEIGH_BETA * max(_e4, 0.0));
}

float3 mie_beta()
{
  float _e4 = frame.atmosphere.y;
  float4 _e14 = frame.air;
  return ((MIE_BETA * (0.1 + (max(_e4, 0.0) * 0.45))) * _e14.xyz);
}

float3 sun_transmittance(float cos_zenith_1)
{
  const float _e1 = air_mass(cos_zenith_1);
  const float3 _e2 = rayleigh_beta();
  const float3 _e5 = mie_beta();
  float3 transmittance = exp((-(((_e2 * RAYLEIGH_HEIGHT) + (_e5 * MIE_HEIGHT))) * _e1));
  return (transmittance * smoothstep(-0.08, 0.02, cos_zenith_1));
}

float3 sun_light()
{
  const float3 _e0 = sun_dir();
  const float3 _e2 = sun_transmittance(_e0.y);
  float _e6 = frame.sun_direction.w;
  float _e13 = frame.light.x;
  return (((_e2 * _e6) * 2.35) * _e13);
}

float luminance(float3 colour)
{
  return dot(colour, float3(0.2126, 0.7152, 0.0722));
}

float3 sky_radiance(float3 direction)
{
  float3 sky = (float3)0;

  const float3 _e1 = sun_dir();
  float3 dir = normalize(float3(direction.x, max(direction.y, 0.0), direction.z));
  float mu = dot(dir, _e1);
  const float3 _e10 = rayleigh_beta();
  const float3 _e11 = mie_beta();
  const float _e13 = air_mass(dir.y);
  float3 depth_r = ((_e10 * RAYLEIGH_HEIGHT) * _e13);
  float3 depth_m = ((_e11 * MIE_HEIGHT) * _e13);
  float3 extinction = (depth_r + depth_m);
  float phase_r = (0.0596831 * (1.0 + (mu * mu)));
  float _e29 = frame.air.w;
  const float _e30 = henyey_greenstein(mu, _e29);
  const float3 _e32 = sun_transmittance(_e1.y);
  float3 sun_colour = (sqrt(_e32) * smoothstep(-0.08, 0.02, _e1.y));
  float3 inscatter = ((((depth_r * phase_r) + (depth_m * _e30)) / max(extinction, (1e-6).xxx)) * ((1.0).xxx - exp(-(extinction))));
  float3 fill = (float3(0.004, 0.009, 0.022) * smoothstep(-0.3, 0.2, _e1.y));
  float3 night = float3(0.0012, 0.0018, 0.004);
  float _e71 = frame.sun_direction.w;
  float4 _e77 = frame.sky_tint;
  sky = ((((((inscatter * sun_colour) * SUN_RADIANCE) * _e71) + fill) + night) * _e77.xyz);
  float overcast = frame.weather2_.y;
  if ((overcast > 0.001)) {
    float zenith_mu = _e1.y;
    float _e101 = frame.air.w;
    const float _e102 = henyey_greenstein(zenith_mu, _e101);
    float3 zenith_inscatter = ((((((_e10 * RAYLEIGH_HEIGHT) * 0.0596831) * (1.0 + (zenith_mu * zenith_mu))) + ((_e11 * MIE_HEIGHT) * _e102)) / ((_e10 * RAYLEIGH_HEIGHT) + (_e11 * MIE_HEIGHT))) * ((1.0).xxx - exp(-(((_e10 * RAYLEIGH_HEIGHT) + (_e11 * MIE_HEIGHT))))));
    float _e128 = frame.sun_direction.w;
    float4 _e134 = frame.sky_tint;
    const float _e137 = luminance(((((((zenith_inscatter * sun_colour) * SUN_RADIANCE) * _e128) + fill) + night) * _e134.xyz));
    float deck = ((((_e137 * 2.0) * (1.0 + (2.0 * dir.y))) / 3.0) * (1.0 - (overcast * 0.4)));
    float3 _e153 = sky;
    sky = lerp(_e153, ((deck).xxx * float3(0.92, 0.95, 1.0)), overcast);
  }
  float3 _e161 = sky;
  float _e169 = frame.weather2_.x;
  return (_e161 + ((float3(0.75, 0.8, 1.0) * _e169) * 1.6));
}

float3 sky_irradiance(float3 normal)
{
  const float3 _e5 = sky_radiance(float3(0.0, 1.0, 0.0));
  float towards_sky = saturate(((normal.y * 0.5) + 0.5));
  if ((towards_sky >= 0.9999)) {
    float _e19 = frame.light.z;
    return ((_e5 * 2.4) * _e19);
  }
  const float3 _e21 = sun_dir();
  const float3 _e24 = sun_dir();
  const float3 _e30 = sky_radiance(normalize(float3(-(_e21.x), 0.2, -(_e24.z))));
  float _e35 = frame.light.w;
  float3 sky_2 = lerp(lerp(_e30, _e5, towards_sky), _e5, _e35);
  const float3 _e37 = sun_light();
  float3 bounce = ((_e37 * 0.035) * saturate(((-(normal.y) * 0.5) + 0.5)));
  float _e65 = frame.light.z;
  return ((((sky_2 * (0.55 + (0.45 * saturate(((normal.y * 0.5) + 0.5))))) * 2.4) + bounce) * _e65);
}

bool over_terrain(float2 xz)
{
  bool local_1 = (bool)0;

  float _e4 = world.terrain2_.z;
  if ((_e4 > 0.5)) {
    float4 _e12 = world.terrain;
    local_1 = all((abs(xz) <= _e12.xy));
  } else {
    local_1 = false;
  }
  bool _e17 = local_1;
  return _e17;
}

float4 ground_layer_at(float2 xz_1, int layer)
{
  float4 _e4 = world.terrain2_;
  float2 size = max(_e4.xy, (1.0).xx);
  float4 _e11 = world.terrain;
  float4 _e16 = world.terrain;
  float2 uv = ((((xz_1 + _e11.xy) / _e16.zw) + (0.5).xx) / size);
  float4 _e26 = ground_layers.SampleLevel(clamp_sampler, float3(uv, layer), 0.0);
  return _e26;
}

float4 surface_at(float2 xz_2)
{
  const float4 _e2 = ground_layer_at(xz_2, int(0));
  return _e2;
}

float4 regional_weather_at(float2 xz_3)
{
  float4 _e3 = frame.regional;
  float _e9 = frame.regional.z;
  float2 uv_1 = ((xz_3 - _e3.xy) * _e9);
  float4 _e14 = regional_texture.SampleLevel(clamp_sampler, uv_1, 0.0);
  return _e14;
}

float4 surface_weather_at(float2 xz_4)
{
  bool local_2 = (bool)0;

  float _e4 = frame.weather4_.x;
  if (!((_e4 < 0.5))) {
    const bool _e10 = over_terrain(xz_4);
    local_2 = !(_e10);
  } else {
    local_2 = true;
  }
  bool _e13 = local_2;
  if (_e13) {
    float _e17 = frame.weather.z;
    float _e21 = frame.weather.w;
    return float4(_e17, 0.0, _e21, 0.0);
  }
  float4 _e27 = world.terrain;
  float4 _e32 = world.terrain;
  float2 uv_2 = ((xz_4 + _e27.xy) / max((_e32.xy * 2.0), (1.0).xx));
  float4 texel = surface_weather_texture.SampleLevel(clamp_sampler, uv_2, 0.0);
  return float4(texel.xyz, 1.0);
}

float gust_noise(float s)
{
  float cell_1 = floor(s);
  float t_1 = (s - cell_1);
  float fade_1 = ((t_1 * t_1) * (3.0 - (2.0 * t_1)));
  const float _e9 = hash11_(cell_1);
  const float _e12 = hash11_((cell_1 + 1.0));
  return ((lerp(_e9, _e12, fade_1) * 2.0) - 1.0);
}

float gust_front(float2 xz_5)
{
  float4 _e3 = frame.weather2_;
  float2 direction_2 = normalize((_e3.zw + float2(1e-5, 0.0)));
  float _e14 = frame.gust.x;
  float s_1 = (dot(xz_5, direction_2) - _e14);
  const float _e18 = gust_noise((s_1 / 220.0));
  const float _e25 = gust_noise(((s_1 / 70.0) + 17.0));
  return ((_e18 * 0.65) + (_e25 * 0.35));
}

float permanent_snow_at(float2 xz_6)
{
  const bool _e1 = over_terrain(xz_6);
  if (!(_e1)) {
    return 0.0;
  }
  const float4 _e4 = surface_at(xz_6);
  return _e4.z;
}

float2 cloud_weather_level(float2 xz_7)
{
  float coverage = (float)0;

  float _e4 = frame.cloud_params.x;
  coverage = _e4;
  float _e9 = frame.regional.w;
  if ((_e9 > 0.5)) {
    const float4 _e12 = regional_weather_at(xz_7);
    coverage = _e12.x;
  }
  float4 _e16 = frame.cloud_motion;
  float2 uv_3 = ((xz_7 + _e16.xy) / (26000.0).xx);
  float4 large = noise_texture.SampleLevel(linear_sampler, uv_3, 0.0);
  float4 _e35 = noise_texture.SampleLevel(linear_sampler, ((uv_3 * 3.3) + float2(0.37, 0.71)), 0.0);
  float medium = _e35.y;
  float weather = ((large.x * 0.7) + (medium * 0.3));
  float _e43 = coverage;
  float _e50 = coverage;
  const float _e57 = remap(weather, ((1.0 - (_e43 * 0.95)) - 0.05), (1.0 - (_e50 * 0.35)), 0.0, 1.0);
  return float2(saturate(_e57), large.w);
}

float cloud_weather(float2 xz_8)
{
  const float2 _e1 = cloud_weather_level(xz_8);
  return _e1.x;
}

bool alto_on()
{
  float _e3 = frame.clouds5_.z;
  float _e7 = frame.clouds5_.w;
  return (max(_e3, _e7) > 0.001);
}

float2 alto_wind()
{
  float4 _e2 = frame.clouds2_;
  float2 wind = _e2.zw;
  return float2(((wind.x * 0.9396926) + (wind.y * 0.3420201)), ((wind.y * 0.9396926) - (wind.x * 0.3420201)));
}

float alto_ripple(float2 q, float warp)
{
  const float2 _e2 = alto_wind();
  return (0.5 + (0.5 * sin(((dot(q, float2(-(_e2.y), _e2.x)) * 0.0069813174) + warp))));
}

float3 alto_coarse(float2 xz_9)
{
  float scale = 1.0;

  float4 _e3 = frame.alto;
  float2 q_1 = (xz_9 + _e3.xy);
  const float2 _e6 = alto_wind();
  float2 across = float2(-(_e6.y), _e6.x);
  float2 local_6 = float2((dot(q_1, _e6) / 2.5), dot(q_1, across));
  float4 n = noise_texture.SampleLevel(linear_sampler, ((local_6 / (48000.0).xx) + float2(0.29, 0.53)), 0.0);
  float _e32 = frame.regional.w;
  if ((_e32 > 0.5)) {
    const float4 _e35 = regional_weather_at(xz_9);
    float cover = _e35.x;
    float _e40 = frame.cloud_params.x;
    scale = (1.0 + (0.3 * clamp(((cover - _e40) / 0.2), -1.0, 1.0)));
  }
  float _e54 = frame.clouds5_.z;
  float _e55 = scale;
  float cumulus = saturate(((_e54 * _e55) * lerp(0.3, 1.7, n.x)));
  float _e66 = frame.clouds5_.w;
  float _e67 = scale;
  float stratus = ((_e66 * _e67) * (0.7 + (0.3 * n.y)));
  return float3(cumulus, stratus, ((n.w - 0.5) * 7.5));
}

float alto_shadow_depth(float2 xz_10)
{
  const float3 _e1 = alto_coarse(xz_10);
  float4 _e5 = frame.alto;
  const float _e9 = alto_ripple((xz_10 + _e5.xy), _e1.z);
  float cumulus_1 = (_e1.x * lerp(0.25, 0.45, _e9));
  return (ALTO_EXTINCTION * ((cumulus_1 * ALTOCUMULUS_THICKNESS) + (_e1.y * ALTOSTRATUS_THICKNESS)));
}

float alto_shadow(float3 position)
{
  bool local_3 = (bool)0;

  float _e4 = frame.alto.z;
  float rise = (_e4 - position.y);
  const bool _e7 = alto_on();
  if (!(!(_e7))) {
    local_3 = (rise <= 0.0);
  } else {
    local_3 = true;
  }
  bool _e15 = local_3;
  if (_e15) {
    return 1.0;
  }
  const float3 _e17 = sun_dir();
  float sun_y = max(_e17.y, 0.05);
  const float _e26 = alto_shadow_depth((position.xz + (_e17.xz * (rise / sun_y))));
  return exp((-(_e26) / sun_y));
}

float cloud_shadow(float3 position_1)
{
  float lit_ = 1.0;

  float _e4 = frame.cloud_colour.w;
  if ((_e4 < 0.5)) {
    return 1.0;
  }
  float _e13 = frame.cloud_params.x;
  if ((_e13 > 0.001)) {
    const float3 _e16 = sun_dir();
    float _e20 = frame.cloud_params.y;
    float _e24 = frame.cloud_params.z;
    float mid_height = (_e20 + (_e24 * 0.35));
    float travel = (max((mid_height - position_1.y), 0.0) / max(_e16.y, 0.08));
    float2 shadow_point = (position_1.xz + (_e16.xz * travel));
    const float _e40 = cloud_weather(shadow_point);
    float _e47 = frame.cloud_motion.w;
    float density = (smoothstep(0.05, 0.6, _e40) * saturate(((_e47 * 1.4) + 0.2)));
    float _e57 = frame.shadow_params.w;
    lit_ = (1.0 - (density * _e57));
  }
  const bool _e61 = alto_on();
  if (_e61) {
    float _e62 = lit_;
    const float _e63 = alto_shadow(position_1);
    float _e67 = frame.shadow_params.w;
    lit_ = (_e62 * lerp(1.0, _e63, _e67));
  }
  float _e71 = lit_;
  return _e71;
}

float terrain_shadow(float3 position_2)
{
  bool local_4 = (bool)0;
  bool local_5 = (bool)0;

  float strength = frame.shadow_params.z;
  if (!((strength <= 0.001))) {
    float _e13 = world.terrain2_.z;
    local_4 = (_e13 < 0.5);
  } else {
    local_4 = true;
  }
  bool _e17 = local_4;
  if (_e17) {
    return 1.0;
  }
  float4 _e22 = world.terrain;
  float4 _e27 = world.terrain;
  float2 uv_4 = ((position_2.xz + _e22.xy) / max((_e27.xy * 2.0), (1.0).xx));
  if (!(any((uv_4 < (0.0).xx)))) {
    local_5 = any((uv_4 > (1.0).xx));
  } else {
    local_5 = true;
  }
  bool _e47 = local_5;
  if (_e47) {
    return 1.0;
  }
  float4 _e52 = terrain_shadow_texture.SampleLevel(clamp_sampler, uv_4, 0.0);
  float lit_1 = _e52.x;
  return lerp(1.0, lit_1, strength);
}

float3 rotate_y(float3 v, float angle)
{
  float c_1 = cos(angle);
  float s_2 = sin(angle);
  return float3(((v.x * c_1) + (v.z * s_2)), v.y, ((-(v.x) * s_2) + (v.z * c_1)));
}

uint naga_f2u32(float value) {
  return uint(clamp(value, 0.0, 4294967000.0));
}

uint unpack_code(float value_2)
{
  return naga_f2u32(floor((abs(value_2) + 0.0001)));
}

float unpack_fade(float value_3)
{
  float fade_2 = saturate((frac((abs(value_3) + 0.0001)) * 2.0));
  return ((value_3 < 0.0) ? -(fade_2) : fade_2);
}

float2 wind_direction()
{
  float4 _e2 = frame.weather2_;
  float2 wind_1 = _e2.zw;
  float speed = length(wind_1);
  return ((speed > 0.1) ? (wind_1 / (max(speed, 0.001)).xx) : float2(0.8, 0.6));
}

float gust_at(float2 instance_xz, float2 direction_1, float t)
{
  float _e6 = frame.gust.w;
  if ((_e6 > 0.5)) {
    const float _e9 = gust_front(instance_xz);
    float _e13 = frame.gust.y;
    return (0.55 * (1.0 + ((_e9 * _e13) * 0.8)));
  }
  float phase = ((dot(instance_xz, direction_1) * 0.012) - (t * 0.9));
  return (0.55 + ((0.45 * sin(phase)) * sin(((phase * 0.37) + 1.3))));
}

float3 trunk_sway(float2 instance_xz_1, float y, float h, float bend)
{
  float _e7 = frame.vegetation.x;
  float w = (saturate(_e7) * 1.6);
  const float2 _e11 = wind_direction();
  const float _e12 = time_seconds();
  float frequency = clamp((1.6 / sqrt(h)), 0.2, 0.5);
  float sway = (0.7 + (0.3 * sin(((((TAU * frequency) * _e12) + (instance_xz_1.x * 0.13)) + (instance_xz_1.y * 0.11)))));
  const float _e41 = gust_at(instance_xz_1, _e11, _e12);
  float amount = (((((((((bend * w) * w) * h) * h) * 0.0025) * _e41) * sway) * (y / h)) * (y / h));
  return (float3(_e11.x, -0.08, _e11.y) * amount);
}

float3 lean_offset(uint code, float y_1, float h_1)
{
  uint lean = (code >> 5u);
  float angle_1 = (float((lean & 15u)) * 0.3926991);
  float strength_1 = float(((lean >> 4u) & 3u));
  float2 direction_3 = float2(sin(angle_1), cos(angle_1));
  float low = (0.2 * h_1);
  float y0_ = clamp(y_1, 0.0, low);
  float butt = (tan(radians((max((strength_1 - 1.0), 0.0) * 8.0))) * (y0_ - ((y0_ * y0_) / (2.0 * low))));
  float amount_1 = ((max(y_1, 0.0) * tan(radians((strength_1 * 2.0)))) + butt);
  return (float3(direction_3.x, 0.0, direction_3.y) * amount_1);
}

float2 view_uv(float cell, float2 card, float2 top_1)
{
  bool above = (cell > 7.5);
  float span = (above ? (1.0 + (2.0 * top_1.x)) : 1.0);
  float y_2 = (card.y + (above ? (top_1.x * (1.0 - top_1.y)) : 0.0));
  return float2(((card.x * 0.5) + 0.5), (1.0 - (y_2 / span)));
}

uint naga_mod(uint lhs, uint rhs) {
  return lhs % (rhs == 0u ? 1u : rhs);
}

float naga_mod(float lhs, float rhs) {
  return lhs - rhs * trunc(lhs / rhs);
}

typedef float2 ret_Constructarray6_float2_[6];
ret_Constructarray6_float2_ Constructarray6_float2_(float2 arg0, float2 arg1, float2 arg2, float2 arg3, float2 arg4, float2 arg5) {
  float2 ret[6] = { arg0, arg1, arg2, arg3, arg4, arg5 };
  return ret;
}

VertexOutput_vertex_impostor vertex_impostor(ImpostorIn in_)
{
  float2 corners[6] = Constructarray6_float2_(float2(-1.0, 0.0), float2(1.0, 0.0), float2(-1.0, 1.0), float2(1.0, 0.0), float2(1.0, 1.0), float2(-1.0, 1.0));
  float3 facing = (float3)0;
  float3 right = (float3)0;
  float top = (float)0;
  bool local = (bool)0;
  float3 world_position = (float3)0;
  float4 views = (float4)0;
  ImpostorOut out_ = (ImpostorOut)0;

  float2 corner = corners[min(uint(naga_mod((_NagaConstants.first_vertex + in_.vertex_index), 6u)), 5u)];
  const uint _e27 = unpack_code(in_.instance_species_fade);
  uint species = (_e27 & 7u);
  uint variant = ((_e27 >> 3u) & 3u);
  float4 bounds = world.species[species];
  float height = (bounds.x * in_.instance_scale);
  float radius = ((bounds.y * in_.instance_scale) * in_.instance_width);
  float3 up = float3(0.0, 1.0, 0.0);
  float4 _e52 = frame.camera_position;
  float3 to_camera = (_e52.xyz - in_.instance_position);
  float flat_length = max(length(to_camera.xz), 0.0001);
  facing = float3((to_camera.x / flat_length), 0.0, (to_camera.z / flat_length));
  top = saturate((atan2(to_camera.y, flat_length) / 0.6981317));
  float _e77 = frame.vegetation.z;
  if ((_e77 > 0.5)) {
    float _e85 = frame.vegetation.z;
    local = (_e85 < 1.5);
  } else {
    local = false;
  }
  bool _e89 = local;
  if (_e89) {
    float angle_2 = (in_.instance_rotation + (((_NagaConstants.first_vertex + in_.vertex_index) >= 6u) ? 1.5707963 : 0.0));
    right = float3(cos(angle_2), 0.0, -(sin(angle_2)));
    float3 _e103 = right;
    facing = cross(_e103, up);
    top = 0.0;
  } else {
    float3 _e106 = facing;
    right = normalize(cross(up, _e106));
  }
  float _e113 = top;
  float reach = (height + (((2.0 * radius) * TOP_TAN) * _e113));
  float lift = (corner.y * reach);
  float3 _e119 = facing;
  float _e121 = top;
  float3 _e124 = right;
  world_position = (((in_.instance_position + ((_e119 * radius) * _e121)) + ((_e124 * corner.x) * radius)) + (up * lift));
  float3 _e132 = world_position;
  const float3 _e133 = lean_offset(_e27, lift, height);
  const float3 _e141 = trunk_sway(in_.instance_position.xz, min(lift, height), max(height, 0.1), bounds.z);
  world_position = ((_e132 + _e133) + _e141);
  float3 _e143 = facing;
  const float3 _e146 = rotate_y(_e143, -(in_.instance_rotation));
  float around = (frac(((atan2(_e146.x, _e146.z) / TAU) + 1.0)) * 8.0);
  float first = floor(around);
  float t_2 = (around - first);
  float _e166 = world.trees.x;
  views = float4(first, naga_mod((first + 1.0), 8.0), t_2, float((((species * naga_f2u32(_e166)) + variant) * 2u)));
  float _e177 = top;
  float _e181 = top;
  float _e185 = top;
  float3 weights = float3(((1.0 - t_2) * (1.0 - _e177)), (t_2 * (1.0 - _e181)), _e185);
  if ((weights.z > min(weights.x, weights.y))) {
    float _e193 = views.y;
    float side = ((weights.y > weights.x) ? _e193 : first);
    float kept = max(weights.x, weights.y);
    float _e208 = views.w;
    views = float4(side, 8.0, (weights.z / max((kept + weights.z), 0.0001)), _e208);
  }
  float3 _e211 = world_position;
  float4 _e214 = frame.camera_position;
  float4 _e219 = frame.camera_forward;
  float depth = max(dot((_e211 - _e214.xyz), _e219.xyz), 0.1);
  float _e227 = frame.camera_forward.w;
  float _e235 = frame.viewport.y;
  float pixels = ((reach / ((2.0 * _e227) * depth)) * _e235);
  float2 card_1 = float2(corner.x, (lift / max(height, 0.001)));
  float _e247 = top;
  float2 rise_1 = float2(((radius / max(height, 0.001)) * TOP_TAN), _e247);
  float4x4 _e253 = frame.view_proj;
  float3 _e254 = world_position;
  out_.clip_position = mul(float4(_e254, 1.0), _e253);
  float3 _e259 = world_position;
  out_.world_position = _e259;
  const float _e269 = hash11_(((in_.instance_position.x * 0.7137) + (in_.instance_position.z * 1.3713)));
  float _e271 = views.z;
  bool second = (_e269 < _e271);
  float _e274 = views.x;
  float _e276 = views.y;
  float cell_2 = (second ? _e276 : _e274);
  const float2 _e279 = view_uv(cell_2, card_1, rise_1);
  out_.at = _e279;
  float3 _e281 = right;
  out_.right = _e281;
  float3 _e283 = facing;
  out_.facing = _e283;
  const float _e286 = unpack_fade(in_.instance_species_fade);
  out_.fade = _e286;
  out_.tint = in_.instance_tint;
  out_.dryness = in_.instance_dryness;
  const float3 _e292 = sun_light();
  float3 _e293 = world_position;
  const float _e294 = cloud_shadow(_e293);
  float3 _e296 = world_position;
  const float _e297 = terrain_shadow(_e296);
  out_.sun = ((_e292 * _e294) * _e297);
  float3 _e300 = facing;
  const float3 _e303 = sky_irradiance(normalize((_e300 + up)));
  out_.sky = _e303;
  const float4 _e306 = surface_weather_at(in_.instance_position.xz);
  const float _e311 = permanent_snow_at(in_.instance_position.xz);
  out_.snow = max(_e306.z, _e311);
  out_.wet = _e306.x;
  float _e317 = views.w;
  out_.view = float2(cell_2, _e317);
  out_.level = clamp(log2((160.0 / max(pixels, 0.001))), 0.0, 4.0);
  ImpostorOut _e328 = out_;
  const ImpostorOut impostorout = _e328;
  const VertexOutput_vertex_impostor impostorout_1 = { impostorout.world_position, impostorout.at, impostorout.right, impostorout.facing, impostorout.fade, impostorout.tint, impostorout.dryness, impostorout.sun, impostorout.sky, impostorout.snow, impostorout.view, impostorout.level, impostorout.wet, impostorout.clip_position };
  return impostorout_1;
}
