// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: trees (ground + common + trees)
// Entry point: vertex_bake, compile with /T vs_5_0 /E vertex_bake
// override LIGHT = false
//
// Resources (WGSL group/binding -> register):
//   @group(1) @binding(9) world -> b0  constant buffer
// D3D11: reads vertex_index or instance_index: bind { int first_vertex; int first_instance; uint other; } at b1 for each draw, with the draw's first vertex (base vertex when indexed) and first instance. Indirect draws take 0 and 0.

struct NagaConstants {
  int first_vertex;
  int first_instance;
  uint other;
};
cbuffer NagaConstantsBlock : register(b1) { NagaConstants _NagaConstants; }

struct WorldInfo {
  float4 species[8];
  float4 species_tint[8];
  float4 terrain;
  float4 terrain2_;
  float4 material_tints[12];
  float4 trees;
  float4 species_canopy[8];
};

struct BakeIn {
  uint view : SV_InstanceID;
  float3 position : LOC0;
  float4 normal : LOC1;
  float2 uv : LOC2;
  float4 params : LOC3;
};

struct BakeOut {
  float4 clip_position : SV_Position;
  float2 uv : LOC0;
  nointerpolation int layer : LOC1;
  float ao : LOC2;
  float3 normal : LOC3;
  nointerpolation uint species : LOC4;
  float colour : LOC5;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const float2 PREVAILING_WIND = float2(0.8, 0.6);
static const float WIND_BOUND = 0.08;
static const float ATLAS_MARGIN = 0.085;
static const float TOP_TAN = 0.8390996;

cbuffer world : register(b0) { WorldInfo world; }

struct VertexOutput_vertex_bake {
  float2 uv : LOC0;
  nointerpolation int layer : LOC1;
  float ao : LOC2;
  float3 normal : LOC3;
  nointerpolation uint species : LOC4;
  float colour : LOC5;
  float4 clip_position : SV_Position;
};

float3 rotate_y(float3 v, float angle)
{
  float c = cos(angle);
  float s = sin(angle);
  return float3(((v.x * c) + (v.z * s)), v.y, ((-(v.x) * s) + (v.z * c)));
}

uint naga_div(uint lhs, uint rhs) {
  return lhs / (rhs == 0u ? 1u : rhs);
}

uint naga_mod(uint lhs, uint rhs) {
  return lhs % (rhs == 0u ? 1u : rhs);
}

int naga_f2i32(float value) {
  return int(clamp(value, -2147483600.0, 2147483500.0));
}

VertexOutput_vertex_bake vertex_bake(BakeIn in_)
{
  float y = (float)0;
  float depth = (float)0;
  BakeOut out_ = (BakeOut)0;

  uint species_1 = naga_div((_NagaConstants.first_instance + in_.view), 16u);
  uint view = naga_mod((_NagaConstants.first_instance + in_.view), 16u);
  float4 bounds = world.species[species_1];
  float yaw = (float(naga_mod(min(view, 8u), 8u)) * 0.7853982);
  const float3 _e20 = rotate_y(in_.position, -(yaw));
  const float3 _e24 = rotate_y(in_.normal.xyz, -(yaw));
  float radius = bounds.y;
  y = (_e20.y / bounds.x);
  depth = (0.5 - (_e20.z / (4.0 * radius)));
  if ((view == 8u)) {
    y = ((_e20.y + ((radius - _e20.z) * TOP_TAN)) / (bounds.x + ((2.0 * radius) * TOP_TAN)));
    depth = (0.5 - (((_e20.z * 0.766) + (_e20.y * 0.643)) / (4.0 * max(radius, bounds.x))));
  }
  float _e72 = y;
  float _e78 = depth;
  out_.clip_position = float4(((_e20.x / radius) * 0.83), (((_e72 * 2.0) - 1.0) * 0.83), clamp(_e78, 0.0, 1.0), 1.0);
  out_.uv = in_.uv;
  out_.layer = naga_f2i32((in_.params.x + 0.5));
  out_.ao = in_.params.z;
  out_.normal = _e24;
  out_.species = species_1;
  out_.colour = saturate((((in_.normal.w * 4.0) - floor(((in_.normal.w * 4.0) + 0.01))) / 0.8));
  BakeOut _e113 = out_;
  const BakeOut bakeout = _e113;
  const VertexOutput_vertex_bake bakeout_1 = { bakeout.uv, bakeout.layer, bakeout.ao, bakeout.normal, bakeout.species, bakeout.colour, bakeout.clip_position };
  return bakeout_1;
}
