// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: hydraulic_erosion (hydraulic_erosion)
// Entry point: advect, compile with /T cs_5_0 /E advect
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(3) sediment -> u0  RWByteAddressBuffer
//   @group(0) @binding(4) scratch -> u1  RWByteAddressBuffer
//   @group(0) @binding(6) velocity -> u2  RWByteAddressBuffer

struct ErosionParams {
  uint size;
  float pipe_gain;
  float min_tilt;
  float level_sine;
  float dissolve_rate;
  float deposit_rate;
  float thermal_rate;
  float rain;
  float evaporation;
  float capacity;
  float full_depth;
  float talus;
  float creep_rate;
  float _pad0_;
  float _pad1_;
  float _pad2_;
};

cbuffer params : register(b0) { ErosionParams params; }
RWByteAddressBuffer sediment : register(u0);
RWByteAddressBuffer scratch : register(u1);
RWByteAddressBuffer velocity : register(u2);

[numthreads(8, 8, 1)]
void advect(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  float gathered = 0.0;
  int oy = int(-1);
  int ox = (int)0;
  bool local_1 = (bool)0;
  bool local_2 = (bool)0;
  bool local_3 = (bool)0;

  uint _e3 = params.size;
  int n = int(_e3);
  int x = int(id.x);
  int y = int(id.y);
  if (!((x >= n))) {
    local = (y >= n);
  } else {
    local = true;
  }
  bool _e15 = local;
  if (_e15) {
    return;
  }
  float limit = float(asint(asuint(n) - asuint(int(1))));
  uint2 loop_bound = uint2(4294967295u, 4294967295u);
  bool loop_init = true;
  while(true) {
    if (all(loop_bound == uint2(0u, 0u))) { break; }
    loop_bound -= uint2(loop_bound.y == 0u, 1u);
    if (!loop_init) {
      int _e96 = oy;
      oy = asint(asuint(_e96) + asuint(int(1)));
    }
    loop_init = false;
    int _e23 = oy;
    if ((_e23 <= int(1))) {
    } else {
      break;
    }
    {
      ox = int(-1);
      uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
      bool loop_init_1 = true;
      while(true) {
        if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
          int _e93 = ox;
          ox = asint(asuint(_e93) + asuint(int(1)));
        }
        loop_init_1 = false;
        int _e28 = ox;
        if ((_e28 <= int(1))) {
        } else {
          break;
        }
        {
          int _e31 = ox;
          int sx = asint(asuint(x) + asuint(_e31));
          int _e33 = oy;
          int sy = asint(asuint(y) + asuint(_e33));
          if (!((sx < int(0)))) {
            local_1 = (sy < int(0));
          } else {
            local_1 = true;
          }
          bool _e43 = local_1;
          if (!(_e43)) {
            local_2 = (sx >= n);
          } else {
            local_2 = true;
          }
          bool _e49 = local_2;
          if (!(_e49)) {
            local_3 = (sy >= n);
          } else {
            local_3 = true;
          }
          bool _e55 = local_3;
          if (_e55) {
            continue;
          }
          uint j = uint(asint(asuint(asint(asuint(sy) * asuint(n))) + asuint(sx)));
          float4 v = asfloat(velocity.Load4(j*16));
          float tx = clamp((float(sx) + v.x), 0.0, limit);
          float ty = clamp((float(sy) + v.y), 0.0, limit);
          float wx = max((1.0 - abs((tx - float(x)))), 0.0);
          float wy = max((1.0 - abs((ty - float(y)))), 0.0);
          float _e86 = gathered;
          float _e89 = asfloat(sediment.Load(j*4));
          gathered = (_e86 + ((_e89 * wx) * wy));
        }
      }
    }
  }
  float _e104 = gathered;
  scratch.Store(uint(asint(asuint(asint(asuint(y) * asuint(n))) + asuint(x)))*4, asuint(_e104));
  return;
}
