// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: hydraulic_erosion (hydraulic_erosion)
// Entry point: erode, compile with /T cs_5_0 /E erode
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(1) terrain -> u0  RWByteAddressBuffer
//   @group(0) @binding(2) water -> u1  RWByteAddressBuffer
//   @group(0) @binding(3) sediment -> u2  RWByteAddressBuffer
//   @group(0) @binding(6) velocity -> u3  RWByteAddressBuffer

struct ErosionParams {
  uint size;
  float pipe_gain;
  float min_tilt;
  float level_sine;
  float dissolve_rate;
  float deposit_rate;
  float thermal_rate;
  float rain;
  float evaporation;
  float capacity;
  float full_depth;
  float talus;
  float creep_rate;
  float _pad0_;
  float _pad1_;
  float _pad2_;
};

cbuffer params : register(b0) { ErosionParams params; }
RWByteAddressBuffer terrain : register(u0);
RWByteAddressBuffer water : register(u1);
RWByteAddressBuffer sediment : register(u2);
RWByteAddressBuffer velocity : register(u3);

bool is_edge(uint x, uint y)
{
  bool local_2 = (bool)0;
  bool local_3 = (bool)0;
  bool local_4 = (bool)0;

  uint _e4 = params.size;
  uint last = (_e4 - 1u);
  if (!((x == 0u))) {
    local_2 = (y == 0u);
  } else {
    local_2 = true;
  }
  bool _e15 = local_2;
  if (!(_e15)) {
    local_3 = (x == last);
  } else {
    local_3 = true;
  }
  bool _e21 = local_3;
  if (!(_e21)) {
    local_4 = (y == last);
  } else {
    local_4 = true;
  }
  bool _e27 = local_4;
  return _e27;
}

[numthreads(8, 8, 1)]
void erode(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  bool local_1 = (bool)0;

  uint _e4 = params.size;
  if (!((id.x >= _e4))) {
    uint _e12 = params.size;
    local = (id.y >= _e12);
  } else {
    local = true;
  }
  bool _e15 = local;
  if (_e15) {
    return;
  }
  uint _e19 = params.size;
  uint i = ((id.y * _e19) + id.x);
  float4 v = asfloat(velocity.Load4(i*16));
  if (!((v.w < 0.0))) {
    const bool _e34 = is_edge(id.x, id.y);
    local_1 = _e34;
  } else {
    local_1 = true;
  }
  bool _e36 = local_1;
  if (_e36) {
    sediment.Store(i*4, asuint(0.0));
    return;
  }
  float speed = length(v.xy);
  float _e44 = asfloat(water.Load(i*4));
  float _e47 = params.full_depth;
  float depth = clamp((_e44 / _e47), 0.0, 1.0);
  float _e54 = params.capacity;
  float _e58 = params.min_tilt;
  float capacity = (((_e54 * max(v.z, _e58)) * speed) * depth);
  float load = asfloat(sediment.Load(i*4));
  if ((capacity > load)) {
    float _e70 = params.level_sine;
    float _e74 = params.level_sine;
    float cutting = clamp(((v.z - _e70) / _e74), 0.0, 1.0);
    float _e81 = params.dissolve_rate;
    float amount = ((_e81 * (capacity - load)) * cutting);
    float _e89 = asfloat(terrain.Load(i*4));
    terrain.Store(i*4, asuint((_e89 - amount)));
    sediment.Store(i*4, asuint((load + amount)));
    return;
  } else {
    float _e96 = params.deposit_rate;
    float amount_1 = (_e96 * (load - capacity));
    float _e103 = asfloat(terrain.Load(i*4));
    terrain.Store(i*4, asuint((_e103 + amount_1)));
    sediment.Store(i*4, asuint((load - amount_1)));
    return;
  }
}
