// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: hydraulic_erosion (hydraulic_erosion)
// Entry point: evaporate, compile with /T cs_5_0 /E evaporate
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(2) water -> u0  RWByteAddressBuffer
//   @group(0) @binding(3) sediment -> u1  RWByteAddressBuffer
//   @group(0) @binding(4) scratch -> u2  RWByteAddressBuffer

struct ErosionParams {
  uint size;
  float pipe_gain;
  float min_tilt;
  float level_sine;
  float dissolve_rate;
  float deposit_rate;
  float thermal_rate;
  float rain;
  float evaporation;
  float capacity;
  float full_depth;
  float talus;
  float creep_rate;
  float _pad0_;
  float _pad1_;
  float _pad2_;
};

cbuffer params : register(b0) { ErosionParams params; }
RWByteAddressBuffer water : register(u0);
RWByteAddressBuffer sediment : register(u1);
RWByteAddressBuffer scratch : register(u2);

[numthreads(8, 8, 1)]
void evaporate(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;

  uint _e4 = params.size;
  if (!((id.x >= _e4))) {
    uint _e12 = params.size;
    local = (id.y >= _e12);
  } else {
    local = true;
  }
  bool _e15 = local;
  if (_e15) {
    return;
  }
  uint _e19 = params.size;
  uint i = ((id.y * _e19) + id.x);
  float _e27 = asfloat(water.Load(i*4));
  float _e30 = params.evaporation;
  water.Store(i*4, asuint((_e27 * (1.0 - _e30))));
  float _e38 = asfloat(scratch.Load(i*4));
  sediment.Store(i*4, asuint(_e38));
  return;
}
