// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: hydraulic_erosion (hydraulic_erosion)
// Entry point: outflow, compile with /T cs_5_0 /E outflow
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(1) terrain -> u0  RWByteAddressBuffer
//   @group(0) @binding(2) water -> u1  RWByteAddressBuffer
//   @group(0) @binding(5) flux -> u2  RWByteAddressBuffer

struct ErosionParams {
  uint size;
  float pipe_gain;
  float min_tilt;
  float level_sine;
  float dissolve_rate;
  float deposit_rate;
  float thermal_rate;
  float rain;
  float evaporation;
  float capacity;
  float full_depth;
  float talus;
  float creep_rate;
  float _pad0_;
  float _pad1_;
  float _pad2_;
};

cbuffer params : register(b0) { ErosionParams params; }
RWByteAddressBuffer terrain : register(u0);
RWByteAddressBuffer water : register(u1);
RWByteAddressBuffer flux : register(u2);

float pipe(float surface, float current, uint j)
{
  float _e5 = params.pipe_gain;
  float _e8 = asfloat(terrain.Load(j*4));
  float _e12 = asfloat(water.Load(j*4));
  return max((current + (_e5 * ((surface - _e8) - _e12))), 0.0);
}

[numthreads(8, 8, 1)]
void outflow(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  float4 out_ = (0.0).xxxx;
  bool local_1 = (bool)0;

  uint n = params.size;
  if (!((id.x >= n))) {
    local = (id.y >= n);
  } else {
    local = true;
  }
  bool _e12 = local;
  if (_e12) {
    return;
  }
  uint i = ((id.y * n) + id.x);
  float _e19 = asfloat(terrain.Load(i*4));
  float _e22 = asfloat(water.Load(i*4));
  float surface_1 = (_e19 + _e22);
  float4 current_1 = asfloat(flux.Load4(i*16));
  if ((id.x > 0u)) {
    const float _e37 = pipe(surface_1, current_1.x, (i - 1u));
    out_.x = _e37;
  }
  if (((id.x + 1u) < n)) {
    const float _e46 = pipe(surface_1, current_1.y, (i + 1u));
    out_.y = _e46;
  }
  if ((id.y > 0u)) {
    const float _e53 = pipe(surface_1, current_1.z, (i - n));
    out_.z = _e53;
  }
  if (((id.y + 1u) < n)) {
    const float _e61 = pipe(surface_1, current_1.w, (i + n));
    out_.w = _e61;
  }
  float _e63 = out_.x;
  float _e65 = out_.y;
  float _e68 = out_.z;
  float _e71 = out_.w;
  float total = (((_e63 + _e65) + _e68) + _e71);
  float _e75 = asfloat(water.Load(i*4));
  if ((total > _e75)) {
    local_1 = (total > 0.0);
  } else {
    local_1 = false;
  }
  bool _e82 = local_1;
  if (_e82) {
    float4 _e83 = out_;
    float _e86 = asfloat(water.Load(i*4));
    out_ = (_e83 * (_e86 / total));
  }
  float4 _e91 = out_;
  flux.Store4(i*16, asuint(_e91));
  return;
}
