// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: hydraulic_erosion (hydraulic_erosion)
// Entry point: update_water, compile with /T cs_5_0 /E update_water
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(1) terrain -> u0  RWByteAddressBuffer
//   @group(0) @binding(2) water -> u1  RWByteAddressBuffer
//   @group(0) @binding(5) flux -> u2  RWByteAddressBuffer
//   @group(0) @binding(6) velocity -> u3  RWByteAddressBuffer

struct ErosionParams {
  uint size;
  float pipe_gain;
  float min_tilt;
  float level_sine;
  float dissolve_rate;
  float deposit_rate;
  float thermal_rate;
  float rain;
  float evaporation;
  float capacity;
  float full_depth;
  float talus;
  float creep_rate;
  float _pad0_;
  float _pad1_;
  float _pad2_;
};

cbuffer params : register(b0) { ErosionParams params; }
RWByteAddressBuffer terrain : register(u0);
RWByteAddressBuffer water : register(u1);
RWByteAddressBuffer flux : register(u2);
RWByteAddressBuffer velocity : register(u3);

bool is_edge(uint x, uint y)
{
  bool local_2 = (bool)0;
  bool local_3 = (bool)0;
  bool local_4 = (bool)0;

  uint _e4 = params.size;
  uint last = (_e4 - 1u);
  if (!((x == 0u))) {
    local_2 = (y == 0u);
  } else {
    local_2 = true;
  }
  bool _e15 = local_2;
  if (!(_e15)) {
    local_3 = (x == last);
  } else {
    local_3 = true;
  }
  bool _e21 = local_3;
  if (!(_e21)) {
    local_4 = (y == last);
  } else {
    local_4 = true;
  }
  bool _e27 = local_4;
  return _e27;
}

[numthreads(8, 8, 1)]
void update_water(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  float4 inflow = (0.0).xxxx;
  float after = (float)0;
  bool local_1 = (bool)0;

  uint n = params.size;
  if (!((id.x >= n))) {
    local = (id.y >= n);
  } else {
    local = true;
  }
  bool _e12 = local;
  if (_e12) {
    return;
  }
  uint x_1 = id.x;
  uint y_1 = id.y;
  uint i = ((y_1 * n) + x_1);
  float4 out_ = asfloat(flux.Load4(i*16));
  if ((x_1 > 0u)) {
    float _e31 = asfloat(flux.Load(4+(i - 1u)*16));
    inflow.x = _e31;
  }
  if (((x_1 + 1u) < n)) {
    float _e41 = asfloat(flux.Load(0+(i + 1u)*16));
    inflow.y = _e41;
  }
  if ((y_1 > 0u)) {
    float _e49 = asfloat(flux.Load(12+(i - n)*16));
    inflow.z = _e49;
  }
  if (((y_1 + 1u) < n)) {
    float _e58 = asfloat(flux.Load(8+(i + n)*16));
    inflow.w = _e58;
  }
  float weight = asfloat(velocity.Load(12+i*16));
  float before = asfloat(water.Load(i*4));
  float _e67 = inflow.x;
  float _e70 = inflow.y;
  float _e73 = inflow.z;
  float _e76 = inflow.w;
  after = max(((((((((before + _e67) + _e70) + _e73) + _e76) - out_.x) - out_.y) - out_.z) - out_.w), 0.0);
  if (!((weight < 0.0))) {
    const bool _e94 = is_edge(x_1, y_1);
    local_1 = _e94;
  } else {
    local_1 = true;
  }
  bool _e96 = local_1;
  if (_e96) {
    after = 0.0;
  }
  float _e98 = after;
  float depth = max(((before + _e98) * 0.5), 0.0001);
  float _e105 = inflow.x;
  float _e111 = inflow.y;
  float flow_x = ((((_e105 - out_.x) + out_.y) - _e111) * 0.5);
  float _e116 = inflow.z;
  float _e122 = inflow.w;
  float flow_y = ((((_e116 - out_.z) + out_.w) - _e122) * 0.5);
  float left = asfloat(terrain.Load(((y_1 * n) + ((x_1 == 0u) ? x_1 : (x_1 - 1u)))*4));
  float right = asfloat(terrain.Load(((y_1 * n) + min((x_1 + 1u), (n - 1u)))*4));
  float up = asfloat(terrain.Load(((((y_1 == 0u) ? y_1 : (y_1 - 1u)) * n) + x_1)*4));
  float down = asfloat(terrain.Load(((min((y_1 + 1u), (n - 1u)) * n) + x_1)*4));
  float dx = ((right - left) * 0.5);
  float dy = ((down - up) * 0.5);
  float tangent_squared = ((dx * dx) + (dy * dy));
  float _e177 = after;
  water.Store(i*4, asuint(_e177));
  velocity.Store4(i*16, asuint(float4(clamp((flow_x / depth), -1.0, 1.0), clamp((flow_y / depth), -1.0, 1.0), sqrt((tangent_squared / (1.0 + tangent_squared))), weight)));
  return;
}
