// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: thermal_erosion (thermal_erosion)
// Entry point: apply, compile with /T cs_5_0 /E apply
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(1) terrain -> u0  RWByteAddressBuffer
//   @group(0) @binding(4) scratch -> u1  RWByteAddressBuffer

struct ErosionParams {
  uint size;
  float pipe_gain;
  float min_tilt;
  float level_sine;
  float dissolve_rate;
  float deposit_rate;
  float thermal_rate;
  float rain;
  float evaporation;
  float capacity;
  float full_depth;
  float talus;
  float creep_rate;
  float _pad0_;
  float _pad1_;
  float _pad2_;
};

cbuffer params : register(b0) { ErosionParams params; }
RWByteAddressBuffer terrain : register(u0);
RWByteAddressBuffer scratch : register(u1);

[numthreads(8, 8, 1)]
void apply(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;

  uint _e4 = params.size;
  if (!((id.x >= _e4))) {
    uint _e12 = params.size;
    local = (id.y >= _e12);
  } else {
    local = true;
  }
  bool _e15 = local;
  if (_e15) {
    return;
  }
  uint _e19 = params.size;
  uint i = ((id.y * _e19) + id.x);
  float _e27 = asfloat(terrain.Load(i*4));
  float _e30 = asfloat(scratch.Load(i*4));
  terrain.Store(i*4, asuint((_e27 + _e30)));
  return;
}
