// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: thermal_erosion (thermal_erosion)
// Entry point: exchange, compile with /T cs_5_0 /E exchange
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) params -> b0  constant buffer
//   @group(0) @binding(1) terrain -> u0  RWByteAddressBuffer
//   @group(0) @binding(4) scratch -> u1  RWByteAddressBuffer

struct ErosionParams {
  uint size;
  float pipe_gain;
  float min_tilt;
  float level_sine;
  float dissolve_rate;
  float deposit_rate;
  float thermal_rate;
  float rain;
  float evaporation;
  float capacity;
  float full_depth;
  float talus;
  float creep_rate;
  float _pad0_;
  float _pad1_;
  float _pad2_;
};

cbuffer params : register(b0) { ErosionParams params; }
RWByteAddressBuffer terrain : register(u0);
RWByteAddressBuffer scratch : register(u1);

[numthreads(8, 8, 1)]
void exchange(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  float change = 0.0;
  int oy = int(-1);
  int ox = (int)0;
  bool local_1 = (bool)0;
  bool local_2 = (bool)0;
  bool local_3 = (bool)0;
  bool local_4 = (bool)0;
  bool local_5 = (bool)0;
  float critical = (float)0;
  bool local_6 = (bool)0;
  bool local_7 = (bool)0;

  uint _e3 = params.size;
  int n = int(_e3);
  int x = int(id.x);
  int y = int(id.y);
  if (!((x >= n))) {
    local = (y >= n);
  } else {
    local = true;
  }
  bool _e15 = local;
  if (_e15) {
    return;
  }
  float here = asfloat(terrain.Load(uint(asint(asuint(asint(asuint(y) * asuint(n))) + asuint(x)))*4));
  uint2 loop_bound = uint2(4294967295u, 4294967295u);
  bool loop_init = true;
  while(true) {
    if (all(loop_bound == uint2(0u, 0u))) { break; }
    loop_bound -= uint2(loop_bound.y == 0u, 1u);
    if (!loop_init) {
      int _e134 = oy;
      oy = asint(asuint(_e134) + asuint(int(1)));
    }
    loop_init = false;
    int _e26 = oy;
    if ((_e26 <= int(1))) {
    } else {
      break;
    }
    {
      ox = int(-1);
      uint2 loop_bound_1 = uint2(4294967295u, 4294967295u);
      bool loop_init_1 = true;
      while(true) {
        if (all(loop_bound_1 == uint2(0u, 0u))) { break; }
        loop_bound_1 -= uint2(loop_bound_1.y == 0u, 1u);
        if (!loop_init_1) {
          int _e131 = ox;
          ox = asint(asuint(_e131) + asuint(int(1)));
        }
        loop_init_1 = false;
        int _e31 = ox;
        if ((_e31 <= int(1))) {
        } else {
          break;
        }
        {
          int _e34 = ox;
          int nx = asint(asuint(x) + asuint(_e34));
          int _e36 = oy;
          int ny = asint(asuint(y) + asuint(_e36));
          int _e38 = ox;
          if ((_e38 == int(0))) {
            int _e43 = oy;
            local_1 = (_e43 == int(0));
          } else {
            local_1 = false;
          }
          bool _e47 = local_1;
          if (!(_e47)) {
            local_2 = (nx < int(0));
          } else {
            local_2 = true;
          }
          bool _e54 = local_2;
          if (!(_e54)) {
            local_3 = (ny < int(0));
          } else {
            local_3 = true;
          }
          bool _e61 = local_3;
          if (!(_e61)) {
            local_4 = (nx >= n);
          } else {
            local_4 = true;
          }
          bool _e67 = local_4;
          if (!(_e67)) {
            local_5 = (ny >= n);
          } else {
            local_5 = true;
          }
          bool _e73 = local_5;
          if (_e73) {
            continue;
          }
          float _e76 = params.talus;
          critical = _e76;
          int _e78 = ox;
          if ((_e78 != int(0))) {
            int _e83 = oy;
            local_6 = (_e83 != int(0));
          } else {
            local_6 = false;
          }
          bool _e87 = local_6;
          if (_e87) {
            float _e88 = critical;
            critical = (_e88 * 1.4142135);
          }
          float _e96 = asfloat(terrain.Load(uint(asint(asuint(asint(asuint(ny) * asuint(n))) + asuint(nx)))*4));
          float difference = (_e96 - here);
          float _e98 = change;
          float _e101 = params.thermal_rate;
          float _e102 = critical;
          float _e107 = critical;
          change = (_e98 + (_e101 * (max((difference - _e102), 0.0) - max((-(difference) - _e107), 0.0))));
          int _e114 = ox;
          if (!((_e114 == int(0)))) {
            int _e120 = oy;
            local_7 = (_e120 == int(0));
          } else {
            local_7 = true;
          }
          bool _e124 = local_7;
          if (_e124) {
            float _e125 = change;
            float _e128 = params.creep_rate;
            change = (_e125 + (_e128 * difference));
          }
        }
      }
    }
  }
  float _e142 = change;
  scratch.Store(uint(asint(asuint(asint(asuint(y) * asuint(n))) + asuint(x)))*4, asuint(_e142));
  return;
}
