// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: texture_gen (texture_gen)
// Entry point: gen_flora, compile with /T cs_5_0 /E gen_flora
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(2) flora_out -> u0  RWTexture2DArray (Rgba8Unorm)
//   @group(0) @binding(7) bake_layers -> b0  constant buffer
//   @group(0) @binding(8) leaf_placements -> b1  constant buffer

struct Leaf {
  float4 colour;
  float height;
  int _end_pad_0;
  int _end_pad_1;
  int _end_pad_2;
};

struct Clump {
  int first;
  int count;
  float leaf_length;
  float leaf_width;
  float3 base;
  int _pad5_0;
  float3 tip;
  uint seed;
  int shape;
  float gloss;
  int _end_pad_0;
  int _end_pad_1;
};

static const float TAU = 6.2831855;

RWTexture2DArray<unorm float4> flora_out : register(u0);
cbuffer bake_layers : register(b0) { uint4 bake_layers; }
cbuffer leaf_placements : register(b1) { float4 leaf_placements[120]; }

uint pcg(uint value)
{
  uint state = ((value * 747796405u) + 2891336453u);
  uint word = (((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u);
  return ((word >> 22u) ^ word);
}

int naga_mod(int lhs, int rhs) {
  int divisor = ((lhs == int(-2147483647 - 1) & rhs == -1) | (rhs == 0)) ? 1 : rhs;
  return lhs - (lhs / divisor) * divisor;
}

int wrap(int value_1, int period)
{
  return naga_mod(asint(asuint(naga_mod(value_1, period)) + asuint(period)), period);
}

uint hash2a(int2 cell, int2 period_1, uint seed)
{
  const int _e5 = wrap(cell.x, period_1.x);
  uint x_1 = uint(_e5);
  const int _e9 = wrap(cell.y, period_1.y);
  uint y_1 = uint(_e9);
  const uint _e11 = pcg(seed);
  const uint _e13 = pcg((y_1 + _e11));
  const uint _e15 = pcg((x_1 + _e13));
  return _e15;
}

uint hash2_(int2 cell_1, int period_2, uint seed_1)
{
  const uint _e4 = hash2a(cell_1, int2(period_2, period_2), seed_1);
  return _e4;
}

float unit(uint h)
{
  return (float((h & 16777215u)) / 16777215.0);
}

float2 gradient2_(int2 cell_2, int2 period_3, uint seed_2)
{
  const uint _e3 = hash2a(cell_2, period_3, seed_2);
  const float _e4 = unit(_e3);
  float angle = (_e4 * TAU);
  return float2(cos(angle), sin(angle));
}

int2 naga_f2i32(float2 value) {
  return int2(clamp(value, -2147483600.0, 2147483500.0));
}

float perlin2a(float2 p, int2 period_4, uint seed_3)
{
  int2 i_10 = naga_f2i32(floor(p));
  float2 f = frac(p);
  float2 u = (((f * f) * f) * ((f * ((f * 6.0) - (15.0).xx)) + (10.0).xx));
  const float2 _e18 = gradient2_(i_10, period_4, seed_3);
  float a_1 = dot(_e18, f);
  const float2 _e24 = gradient2_(asint(asuint(i_10) + asuint(int2(int(1), int(0)))), period_4, seed_3);
  float b_1 = dot(_e24, (f - float2(1.0, 0.0)));
  const float2 _e34 = gradient2_(asint(asuint(i_10) + asuint(int2(int(0), int(1)))), period_4, seed_3);
  float c_1 = dot(_e34, (f - float2(0.0, 1.0)));
  const float2 _e44 = gradient2_(asint(asuint(i_10) + asuint(int2(int(1), int(1)))), period_4, seed_3);
  float d = dot(_e44, (f - float2(1.0, 1.0)));
  return (lerp(lerp(a_1, b_1, u.x), lerp(c_1, d, u.x), u.y) * 1.414);
}

float perlin2_(float2 p_1, int period_5, uint seed_4)
{
  const float _e4 = perlin2a(p_1, int2(period_5, period_5), seed_4);
  return _e4;
}

float fbm2_(float2 uv, int period_6, int octaves, uint seed_5)
{
  float value_2 = 0.0;
  float amplitude = 0.5;
  float total = 0.0;
  int frequency = (int)0;
  int i = int(0);

  frequency = period_6;
  bool loop_init = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init) {
      int _e38 = i;
      i = asint(asuint(_e38) + asuint(int(1)));
    }
    loop_init = false;
    int _e13 = i;
    if ((_e13 < octaves)) {
    } else {
      break;
    }
    {
      float _e15 = value_2;
      int _e16 = frequency;
      int _e19 = frequency;
      int _e20 = i;
      const float _e25 = perlin2_((uv * float(_e16)), _e19, (seed_5 + (uint(_e20) * 101u)));
      float _e26 = amplitude;
      value_2 = (_e15 + (_e25 * _e26));
      float _e29 = total;
      float _e30 = amplitude;
      total = (_e29 + _e30);
      float _e32 = amplitude;
      amplitude = (_e32 * 0.5);
      int _e35 = frequency;
      frequency = asint(asuint(_e35) * asuint(int(2)));
    }
  }
  float _e41 = value_2;
  float _e42 = total;
  return (((_e41 / _e42) * 0.5) + 0.5);
}

float3 worley2_(float2 p_2, int period_7, uint seed_6)
{
  float f1_ = 8.0;
  float f2_ = 8.0;
  float id_1 = 0.0;
  int y = int(-1);
  int x = (int)0;

  int2 i_11 = naga_f2i32(floor(p_2));
  float2 f_1 = frac(p_2);
  bool loop_init_1 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_1) {
      int _e51 = y;
      y = asint(asuint(_e51) + asuint(int(1)));
    }
    loop_init_1 = false;
    int _e14 = y;
    if ((_e14 <= int(1))) {
    } else {
      break;
    }
    {
      x = int(-1);
      bool loop_init_2 = true;
      [allow_uav_condition] [loop] while(true) {
        if (!loop_init_2) {
          int _e48 = x;
          x = asint(asuint(_e48) + asuint(int(1)));
        }
        loop_init_2 = false;
        int _e19 = x;
        if ((_e19 <= int(1))) {
        } else {
          break;
        }
        {
          int _e22 = x;
          int _e23 = y;
          int2 cell_3 = asint(asuint(i_11) + asuint(int2(_e22, _e23)));
          const uint _e26 = hash2_(cell_3, period_7, seed_6);
          int _e27 = x;
          int _e29 = y;
          const float _e32 = unit(_e26);
          const uint _e33 = pcg(_e26);
          const float _e34 = unit(_e33);
          float2 point_ = ((float2(float(_e27), float(_e29)) + float2(_e32, _e34)) - f_1);
          float d_1 = length(point_);
          float _e39 = f1_;
          if ((d_1 < _e39)) {
            float _e41 = f1_;
            f2_ = _e41;
            f1_ = d_1;
            const uint _e44 = pcg((_e26 + 17u));
            const float _e45 = unit(_e44);
            id_1 = _e45;
          } else {
            float _e46 = f2_;
            if ((d_1 < _e46)) {
              f2_ = d_1;
            }
          }
        }
      }
    }
  }
  float _e54 = f1_;
  float _e55 = f2_;
  float _e56 = id_1;
  return float3(_e54, _e55, _e56);
}

int naga_abs(int val) {
  return val >= 0 ? val : asint(-asuint(val));
}

int naga_div(int lhs, int rhs) {
  return lhs / (((lhs == int(-2147483647 - 1) & rhs == -1) | (rhs == 0)) ? 1 : rhs);
}

int naga_f2i32(float value) {
  return int(clamp(value, -2147483600.0, 2147483500.0));
}

float strokes(float2 uv_1, int2 skew, int period_8, float stretch, uint seed_7)
{
  int2 frequency_1 = (int2)0;
  float value_3 = 0.0;
  float amplitude_1 = 0.5;
  float total_1 = 0.0;
  int i_1 = int(0);

  float2 q = float2(((uv_1.x * float(skew.x)) + (uv_1.y * float(skew.y))), ((uv_1.y * float(skew.x)) - (uv_1.x * float(skew.y))));
  int span = max(asint(asuint(naga_abs(skew.x)) + asuint(naga_abs(skew.y))), int(1));
  frequency_1 = int2(max(naga_div(period_8, span), int(1)), max(naga_f2i32((float(naga_div(period_8, span)) / stretch)), int(1)));
  bool loop_init_3 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_3) {
      int _e76 = i_1;
      i_1 = asint(asuint(_e76) + asuint(int(1)));
    }
    loop_init_3 = false;
    int _e50 = i_1;
    if ((_e50 < int(3))) {
    } else {
      break;
    }
    {
      float _e53 = value_3;
      int2 _e54 = frequency_1;
      int2 _e57 = frequency_1;
      int _e58 = i_1;
      const float _e63 = perlin2a((q * float2(_e54)), _e57, (seed_7 + (uint(_e58) * 101u)));
      float _e64 = amplitude_1;
      value_3 = (_e53 + (_e63 * _e64));
      float _e67 = total_1;
      float _e68 = amplitude_1;
      total_1 = (_e67 + _e68);
      float _e70 = amplitude_1;
      amplitude_1 = (_e70 * 0.5);
      int2 _e73 = frequency_1;
      frequency_1 = asint(asuint(_e73) * asuint(int(2)));
    }
  }
  float _e79 = value_3;
  float _e80 = total_1;
  return (((_e79 / _e80) * 0.5) + 0.5);
}

float2 segment_distance(float2 p_3, float2 a, float2 b)
{
  float2 ab = (b - a);
  float t = saturate((dot((p_3 - a), ab) / max(dot(ab, ab), 1e-6)));
  return float2(length((p_3 - (a + (ab * t)))), t);
}

float4 bark_oak(float2 uv_2)
{
  float3 colour = (float3)0;

  const float _e4 = fbm2_(uv_2, int(3), int(3), 101u);
  const float3 _e17 = worley2_(float2((uv_2.x * 7.0), ((uv_2.y * 2.0) + (_e4 * 0.8))), int(7), 102u);
  float fissure = smoothstep(0.0, 0.18, (_e17.y - _e17.x));
  const float _e32 = fbm2_(float2(uv_2.x, (uv_2.y * 0.25)), int(24), int(3), 103u);
  colour = lerp(float3(0.14, 0.11, 0.09), float3(0.44, 0.38, 0.31), fissure);
  float3 _e43 = colour;
  colour = (_e43 * (0.85 + (_e32 * 0.3)));
  const float _e52 = fbm2_(uv_2, int(6), int(3), 104u);
  float lichen = (smoothstep(0.66, 0.72, _e52) * fissure);
  float3 _e57 = colour;
  colour = lerp(_e57, float3(0.55, 0.6, 0.45), (lichen * 0.5));
  float3 _e65 = colour;
  return float4(_e65, fissure);
}

float4 bark_pine(float2 uv_3)
{
  float3 colour_1 = (float3)0;

  const float _e4 = fbm2_(uv_3, int(4), int(3), 111u);
  const float3 _e17 = worley2_(float2(((uv_3.x * 8.0) + (_e4 * 0.5)), (uv_3.y * 6.0)), int(8), 112u);
  float gap = smoothstep(0.0, 0.07, (_e17.y - _e17.x));
  const float _e27 = fbm2_(uv_3, int(32), int(3), 113u);
  colour_1 = lerp(float3(0.5, 0.33, 0.22), float3(0.64, 0.45, 0.32), _e17.z);
  float3 _e39 = colour_1;
  colour_1 = ((_e39 * (0.85 + (_e27 * 0.3))) * (0.85 + (smoothstep(0.0, 0.3, (_e17.y - _e17.x)) * 0.2)));
  float3 _e60 = colour_1;
  colour_1 = lerp(float3(0.2, 0.14, 0.1), _e60, gap);
  float3 _e62 = colour_1;
  return float4(_e62, gap);
}

float4 bark_palm(float2 uv_4)
{
  float3 colour_2 = (float3)0;

  const float _e4 = fbm2_(uv_4, int(4), int(3), 121u);
  float ring_warp = (_e4 * 0.25);
  float rings = frac(((uv_4.y * 10.0) + ring_warp));
  float ring = (smoothstep(0.0, 0.12, rings) * smoothstep(1.0, 0.8, rings));
  const float _e29 = fbm2_(float2((uv_4.x * 4.0), (uv_4.y * 0.5)), int(12), int(3), 122u);
  colour_2 = lerp(float3(0.28, 0.24, 0.19), float3(0.58, 0.52, 0.43), ring);
  float3 _e40 = colour_2;
  colour_2 = (_e40 * (0.85 + (_e29 * 0.3)));
  float3 _e46 = colour_2;
  return float4(_e46, ring);
}

float4 bark_smooth(float2 uv_5)
{
  float3 colour_3 = (float3)0;

  const float _e4 = fbm2_(uv_5, int(4), int(5), 131u);
  const float _e11 = strokes(uv_5, int2(int(0), int(1)), int(24), 0.2, 132u);
  float lenticels = smoothstep(0.8, 0.9, _e11);
  colour_3 = lerp(float3(0.3, 0.28, 0.24), float3(0.5, 0.47, 0.41), _e4);
  const float _e28 = fbm2_(uv_5, int(3), int(4), 133u);
  float algae = smoothstep(0.6, 0.75, _e28);
  float3 _e32 = colour_3;
  colour_3 = lerp(_e32, float3(0.36, 0.44, 0.28), (algae * 0.5));
  float3 _e40 = colour_3;
  colour_3 = (_e40 * (1.0 - (lenticels * 0.35)));
  float3 _e46 = colour_3;
  return float4(_e46, saturate(((0.7 + (_e4 * 0.3)) - (lenticels * 0.4))));
}

Clump ConstructClump(int arg0, int arg1, float arg2, float arg3, float3 arg4, float3 arg5, uint arg6, int arg7, float arg8) {
  Clump ret = (Clump)0;
  ret.first = arg0;
  ret.count = arg1;
  ret.leaf_length = arg2;
  ret.leaf_width = arg3;
  ret.base = arg4;
  ret.tip = arg5;
  ret.seed = arg6;
  ret.shape = arg7;
  ret.gloss = arg8;
  return ret;
}

Clump clump_of(int layer)
{
  switch(layer) {
    case 4: {
      const Clump clump = ConstructClump(int(0), int(26), 0.2, 0.5, float3(0.1, 0.2, 0.04), float3(0.24, 0.36, 0.08), 181u, int(1), 0.0);
      return clump;
    }
    case 5: {
      const Clump clump_1 = ConstructClump(int(26), int(10), 0.4, 0.4, float3(0.05, 0.16, 0.035), float3(0.14, 0.3, 0.06), 191u, int(0), 1.0);
      return clump_1;
    }
    case 12: {
      const Clump clump_2 = ConstructClump(int(36), int(24), 0.24, 0.6, float3(0.09, 0.19, 0.04), float3(0.22, 0.33, 0.07), 241u, int(2), 0.2);
      return clump_2;
    }
    default: {
      const Clump clump_3 = ConstructClump(int(0), int(0), 0.0, 0.0, (0.0).xxx, (0.0).xxx, 0u, int(0), 0.0);
      return clump_3;
    }
  }
}

Leaf ConstructLeaf(float4 arg0, float arg1) {
  Leaf ret = (Leaf)0;
  ret.colour = arg0;
  ret.height = arg1;
  return ret;
}

typedef Leaf ret_ZeroValuearray4_Leaf_[4];
ret_ZeroValuearray4_Leaf_ ZeroValuearray4_Leaf_() {
  return (Leaf[4])0;
}

typedef Leaf ret_leaf_cluster[4];
ret_leaf_cluster leaf_cluster(float2 uvs_1[4], Clump c)
{
  Leaf result[4] = ZeroValuearray4_Leaf_();
  int i_2 = int(0);
  int s_2 = (int)0;
  bool local_2 = (bool)0;
  float half_width = (float)0;
  float3 colour_4 = (float3)0;
  int s_3 = int(0);

  const uint _e5 = pcg(c.seed);
  const float _e6 = unit(_e5);
  float bend = ((_e6 - 0.5) * 0.25);
  uint _e14 = bake_layers.w;
  int count_1 = asint(asuint(c.count) + asuint(int(_e14)));
  bool loop_init_4 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_4) {
      int _e209 = i_2;
      i_2 = asint(asuint(_e209) + asuint(int(1)));
    }
    loop_init_4 = false;
    int _e19 = i_2;
    if ((_e19 < count_1)) {
    } else {
      break;
    }
    {
      int _e23 = i_2;
      float4 place = leaf_placements[asint(asuint(asint(asuint(c.first) + asuint(_e23))) * asuint(int(2)))];
      int _e31 = i_2;
      float4 look = leaf_placements[asint(asuint(asint(asuint(asint(asuint(c.first) + asuint(_e31))) * asuint(int(2)))) + asuint(int(1)))];
      float2 at = place.xy;
      float2 direction = place.zw;
      float size = look.x;
      float3 leaf_colour = lerp(c.base, c.tip, look.y);
      int _e46 = i_2;
      float t_1 = ((float(_e46) + 0.5) / float(c.count));
      s_2 = int(0);
      bool loop_init_5 = true;
      [allow_uav_condition] [loop] while(true) {
        if (!loop_init_5) {
          int _e206 = s_2;
          s_2 = asint(asuint(_e206) + asuint(int(1)));
        }
        loop_init_5 = false;
        int _e55 = s_2;
        if ((_e55 < int(4))) {
        } else {
          break;
        }
        {
          int _e58 = s_2;
          float2 local_27 = (uvs_1[min(uint(_e58), 3u)] - at);
          float along = (dot(local_27, direction) / size);
          float across = (dot(local_27, float2(-(direction.y), direction.x)) / (size * c.leaf_width));
          if (!((along < 0.0))) {
            local_2 = (along > 1.0);
          } else {
            local_2 = true;
          }
          bool _e79 = local_2;
          if (_e79) {
            continue;
          }
          half_width = (sin((pow(along, 0.75) * 3.14159)) * 0.5);
          if ((c.shape == int(1))) {
            float _e91 = half_width;
            half_width = (_e91 * (1.0 - (0.14 * frac((along * 16.0)))));
          } else {
            if ((c.shape == int(2))) {
              float _e103 = half_width;
              half_width = (_e103 * (0.62 + (0.38 * abs(cos(((along * 4.5) * 3.14159))))));
            }
          }
          float _e116 = half_width;
          float edge = (1.0 - (abs(across) / max(_e116, 0.001)));
          if ((edge > 0.0)) {
            float midrib = (1.0 - smoothstep(0.0, 0.06, abs(across)));
            float veins = smoothstep(0.8, 1.0, sin((((along * 9.0) - (abs(across) * 3.0)) * 3.14159)));
            colour_4 = (leaf_colour * (0.75 + (0.25 * edge)));
            float3 _e148 = colour_4;
            float3 _e149 = colour_4;
            colour_4 = (lerp(_e148, (_e149 * 1.3), (midrib * 0.5)) * (1.0 - (veins * 0.1)));
            float3 _e160 = colour_4;
            colour_4 = (_e160 + (((c.gloss * pow(edge, 3.0)) * (1.0 - along)) * float3(0.06, 0.08, 0.05)));
            float3 _e174 = colour_4;
            colour_4 = (_e174 * (0.78 + (0.22 * t_1)));
            float relief = ((size * c.leaf_width) * ((0.12 * (1.0 - ((1.0 - edge) * (1.0 - edge)))) - (0.03 * midrib)));
            int _e195 = s_2;
            float3 _e197 = colour_4;
            int _e200 = i_2;
            result[min(uint(_e195), 3u)] = ConstructLeaf(float4(_e197, 1.0), (relief + (float(_e200) * 0.0001)));
          }
        }
      }
    }
  }
  bool loop_init_6 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_6) {
      int _e245 = s_3;
      s_3 = asint(asuint(_e245) + asuint(int(1)));
    }
    loop_init_6 = false;
    int _e214 = s_3;
    if ((_e214 < int(4))) {
    } else {
      break;
    }
    {
      int _e217 = s_3;
      const float2 _e226 = segment_distance(uvs_1[min(uint(_e217), 3u)], float2(0.5, 0.0), float2((0.5 + bend), 0.66));
      if ((_e226.x < (0.006 * (1.0 - (_e226.y * 0.5))))) {
        int _e236 = s_3;
        result[min(uint(_e236), 3u)] = ConstructLeaf(float4(0.22, 0.16, 0.1, 1.0), 0.004);
      }
    }
  }
  Leaf _e248[4] = result;
  return _e248;
}

typedef Leaf ret_radial_cluster[4];
ret_radial_cluster radial_cluster(float2 uvs_2[4], int count, float leaf_length, float leaf_width, float3 base, float3 tip, uint seed_8)
{
  Leaf result_1[4] = ZeroValuearray4_Leaf_();
  int i_3 = int(0);
  int s_4 = (int)0;
  bool local_3 = (bool)0;
  float3 colour_5 = (float3)0;

  float2 centre = float2(0.5, 0.5);
  bool loop_init_7 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_7) {
      int _e175 = i_3;
      i_3 = asint(asuint(_e175) + asuint(int(1)));
    }
    loop_init_7 = false;
    int _e14 = i_3;
    if ((_e14 < count)) {
    } else {
      break;
    }
    {
      int _e16 = i_3;
      const uint _e21 = pcg((seed_8 + (uint(_e16) * 7919u)));
      const float _e22 = unit(_e21);
      float angle_1 = (_e22 * TAU);
      const uint _e25 = pcg(_e21);
      const float _e26 = unit(_e25);
      float reach = (sqrt(_e26) * (0.46 - (leaf_length * 0.5)));
      const uint _e35 = pcg((_e21 + 3u));
      const float _e36 = unit(_e35);
      float size_1 = (leaf_length * (0.75 + (_e36 * 0.5)));
      const uint _e44 = pcg((_e21 + 5u));
      const float _e45 = unit(_e44);
      const uint _e54 = pcg((_e21 + 5u));
      const float _e55 = unit(_e54);
      float2 direction_1 = float2(cos((angle_1 + ((_e45 - 0.5) * 0.9))), sin((angle_1 + ((_e55 - 0.5) * 0.9))));
      float2 leaf_base = (centre + (float2(cos(angle_1), sin(angle_1)) * reach));
      const uint _e70 = pcg((_e21 + 9u));
      const float _e71 = unit(_e70);
      float3 leaf_colour_1 = lerp(base, tip, _e71);
      s_4 = int(0);
      bool loop_init_8 = true;
      [allow_uav_condition] [loop] while(true) {
        if (!loop_init_8) {
          int _e172 = s_4;
          s_4 = asint(asuint(_e172) + asuint(int(1)));
        }
        loop_init_8 = false;
        int _e75 = s_4;
        if ((_e75 < int(4))) {
        } else {
          break;
        }
        {
          int _e78 = s_4;
          float2 local_28 = (uvs_2[min(uint(_e78), 3u)] - leaf_base);
          float along_1 = (dot(local_28, direction_1) / size_1);
          float across_1 = (dot(local_28, float2(-(direction_1.y), direction_1.x)) / (size_1 * leaf_width));
          if (!((along_1 < 0.0))) {
            local_3 = (along_1 > 1.0);
          } else {
            local_3 = true;
          }
          bool _e98 = local_3;
          if (_e98) {
            continue;
          }
          float half_width_1 = (sin((pow(along_1, 0.75) * 3.14159)) * 0.5);
          if ((abs(across_1) < half_width_1)) {
            float shade = (0.75 + (0.25 * (1.0 - (abs(across_1) / max(half_width_1, 0.001)))));
            colour_5 = (leaf_colour_1 * shade);
            float midrib_1 = (1.0 - smoothstep(0.0, 0.05, abs(across_1)));
            float3 _e126 = colour_5;
            float3 _e127 = colour_5;
            colour_5 = lerp(_e126, (_e127 * 1.35), (midrib_1 * 0.6));
            float veins_1 = smoothstep(0.75, 1.0, sin(((((along_1 * 9.0) - (abs(across_1) * 3.0)) * TAU) * 0.5)));
            float3 _e147 = colour_5;
            colour_5 = (_e147 * (1.0 - (veins_1 * 0.12)));
            float3 _e153 = colour_5;
            colour_5 = (_e153 * (0.75 + (0.25 * saturate(((reach / 0.3) + (along_1 * 0.5))))));
            int _e165 = s_4;
            float3 _e167 = colour_5;
            result_1[min(uint(_e165), 3u)] = ConstructLeaf(float4(_e167, 1.0), 0.0);
          }
        }
      }
    }
  }
  Leaf _e178[4] = result_1;
  return _e178;
}

Leaf leaf(float3 colour_6, float height)
{
  const Leaf leaf_1 = ConstructLeaf(float4(colour_6, 1.0), height);
  return leaf_1;
}

Leaf needle_bundles(float2 uv_6)
{
  Leaf result_2 = ConstructLeaf((0.0).xxxx, 0.0);
  int i_4 = int(0);
  bool local_4 = (bool)0;
  bool local_5 = (bool)0;

  const float _e9 = fbm2_(uv_6, int(32), int(2), 144u);
  bool loop_init_9 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_9) {
      int _e181 = i_4;
      i_4 = asint(asuint(_e181) + asuint(int(1)));
    }
    loop_init_9 = false;
    int _e12 = i_4;
    if ((_e12 < int(11))) {
    } else {
      break;
    }
    {
      int _e16 = i_4;
      const uint _e21 = pcg((141u + (uint(_e16) * 977u)));
      int _e22 = i_4;
      float t_2 = ((float(_e22) + 0.5) / 11.0);
      int _e28 = i_4;
      float side = ((naga_mod(_e28, int(2)) == int(0)) ? 1.0 : -1.0);
      const float _e36 = unit(_e21);
      float2 centre_1 = float2((0.5 + ((side * (0.08 + (_e36 * 0.22))) * sqrt(t_2))), (0.12 + (t_2 * 0.66)));
      const uint _e51 = pcg(_e21);
      const float _e52 = unit(_e51);
      float axis = (side * (0.5 + (_e52 * 0.7)));
      const uint _e60 = pcg((_e21 + 1u));
      const float _e61 = unit(_e60);
      float reach_1 = (0.2 + (_e61 * 0.08));
      float2 rel = (uv_6 - centre_1);
      float r = length(rel);
      const float2 _e72 = segment_distance(uv_6, float2(0.5, (t_2 * 0.7)), centre_1);
      if ((_e72.x < 0.005)) {
        const Leaf _e81 = leaf(float3(0.24, 0.16, 0.1), 0.003);
        result_2 = _e81;
      }
      if ((r > reach_1)) {
        continue;
      }
      float angle_2 = (atan2(rel.x, rel.y) - axis);
      float wrapped = (angle_2 - (TAU * round((angle_2 / TAU))));
      if ((abs(wrapped) > 1.3)) {
        continue;
      }
      if ((r < (reach_1 * (0.35 + (0.2 * _e9))))) {
        float _e106 = result_2.colour.w;
        local_4 = (_e106 < 0.5);
      } else {
        local_4 = false;
      }
      bool _e110 = local_4;
      if (_e110) {
        const Leaf _e121 = leaf((float3(0.05, 0.1, 0.05) * (0.8 + (_e9 * 0.4))), 0.001);
        result_2 = _e121;
      }
      float k = round((wrapped / 0.05));
      int _e126 = i_4;
      const uint _e130 = hash2_(int2(naga_f2i32(k), _e126), int(4096), 141u);
      const float _e131 = unit(_e130);
      float needle = ((k * 0.05) + ((_e131 - 0.5) * 0.02));
      float distance_ = (r * abs(sin((wrapped - needle))));
      float length_ = (reach_1 * (0.7 + (0.3 * _e131)));
      float width = (0.0036 * (1.0 - (r / length_)));
      if ((r < length_)) {
        local_5 = (distance_ < width);
      } else {
        local_5 = false;
      }
      bool _e157 = local_5;
      if (_e157) {
        float3 colour_8 = lerp(float3(0.1, 0.2, 0.08), float3(0.22, 0.34, 0.14), (((r / length_) * 0.7) + (_e131 * 0.3)));
        const Leaf _e180 = leaf(colour_8, ((width * sqrt((1.0 - (distance_ / width)))) * 0.5));
        result_2 = _e180;
      }
    }
  }
  Leaf _e184 = result_2;
  const Leaf leaf_2 = _e184;
  return leaf_2;
}

typedef float4 ret_Constructarray9_float4_[9];
ret_Constructarray9_float4_ Constructarray9_float4_(float4 arg0, float4 arg1, float4 arg2, float4 arg3, float4 arg4, float4 arg5, float4 arg6, float4 arg7, float4 arg8) {
  float4 ret[9] = { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 };
  return ret;
}

Leaf needle_sprays(float2 uv_7)
{
  Leaf result_3 = ConstructLeaf((0.0).xxxx, 0.0);
  float4 twigs[9] = Constructarray9_float4_(float4(0.5, 0.0, 0.5, 1.0), float4(0.5, 0.15, 0.2, 0.42), float4(0.5, 0.25, 0.8, 0.55), float4(0.5, 0.36, 0.22, 0.64), float4(0.5, 0.46, 0.78, 0.74), float4(0.5, 0.56, 0.26, 0.8), float4(0.5, 0.66, 0.74, 0.86), float4(0.5, 0.75, 0.32, 0.92), float4(0.5, 0.83, 0.68, 0.96));
  int i_5 = int(0);
  bool local_6 = (bool)0;
  bool local_7 = (bool)0;
  bool local_8 = (bool)0;
  bool local_9 = (bool)0;
  bool local_10 = (bool)0;
  bool local_11 = (bool)0;
  bool local_12 = (bool)0;
  bool local_13 = (bool)0;

  bool loop_init_10 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_10) {
      int _e263 = i_5;
      i_5 = asint(asuint(_e263) + asuint(int(1)));
    }
    loop_init_10 = false;
    int _e55 = i_5;
    if ((_e55 < int(9))) {
    } else {
      break;
    }
    {
      int _e58 = i_5;
      float4 _e60 = twigs[min(uint(_e58), 8u)];
      float2 a_2 = _e60.xy;
      int _e62 = i_5;
      float4 _e64 = twigs[min(uint(_e62), 8u)];
      float2 b_2 = _e64.zw;
      float2 axis_1 = normalize((b_2 - a_2));
      float2 local_29 = (uv_7 - a_2);
      float along_2 = dot(local_29, axis_1);
      float across_2 = dot(local_29, float2(-(axis_1.y), axis_1.x));
      float twig_length = length((b_2 - a_2));
      int _e77 = i_5;
      float needle_length = (((_e77 > int(0)) ? 0.075 : 0.1) * (1.0 - (saturate((along_2 / twig_length)) * 0.4)));
      if (!((along_2 < -0.02))) {
        local_6 = (along_2 > (twig_length + needle_length));
      } else {
        local_6 = true;
      }
      bool _e98 = local_6;
      if (!(_e98)) {
        local_7 = (abs(across_2) > needle_length);
      } else {
        local_7 = true;
      }
      bool _e105 = local_7;
      if (_e105) {
        continue;
      }
      const float2 _e106 = segment_distance(uv_7, a_2, b_2);
      int _e110 = i_5;
      const float _e113 = fbm2_(uv_7, int(32), int(3), (142u + uint(_e110)));
      float mass_edge = (needle_length * (0.2 + (_e113 * 0.55)));
      if ((_e106.x < mass_edge)) {
        local_8 = (along_2 > 0.0);
      } else {
        local_8 = false;
      }
      bool _e126 = local_8;
      if (_e126) {
        local_9 = (along_2 < (twig_length + (needle_length * 0.5)));
      } else {
        local_9 = false;
      }
      bool _e134 = local_9;
      if (_e134) {
        float _e139 = result_3.colour.w;
        local_10 = (_e139 < 0.5);
      } else {
        local_10 = false;
      }
      bool _e143 = local_10;
      if (_e143) {
        const float _e151 = fbm2_(uv_7, int(64), int(2), 143u);
        const Leaf _e158 = leaf((float3(0.04, 0.09, 0.045) * (0.8 + (_e151 * 0.4))), 0.001);
        result_3 = _e158;
      }
      if ((_e106.x < (0.006 * (1.0 - (_e106.y * 0.6))))) {
        const Leaf _e173 = leaf(float3(0.2, 0.13, 0.08), 0.004);
        result_3 = _e173;
      }
      float start = (along_2 - (abs(across_2) * 0.7));
      float k_1 = round((start / 0.011));
      float needle_base = (k_1 * 0.011);
      if ((needle_base >= -0.005)) {
        local_11 = (needle_base <= twig_length);
      } else {
        local_11 = false;
      }
      bool _e188 = local_11;
      if (_e188) {
        float side_1 = sign(across_2);
        float2 direction_2 = normalize(float2(0.7, 1.0));
        float2 rel_1 = float2((along_2 - needle_base), abs(across_2));
        float t_3 = dot(rel_1, direction_2);
        float distance_1 = abs(((rel_1.x * direction_2.y) - (rel_1.y * direction_2.x)));
        int _e207 = i_5;
        const uint _e214 = hash2_(int2(naga_f2i32(k_1), asint(asuint(naga_f2i32(side_1)) + asuint(asint(asuint(_e207) * asuint(int(3)))))), int(4096), 141u);
        const float _e215 = unit(_e214);
        float width_1 = (0.0034 * (1.0 - ((t_3 / needle_length) * 0.6)));
        if ((t_3 > 0.0)) {
          local_12 = (t_3 < (needle_length * (0.55 + (_e215 * 0.45))));
        } else {
          local_12 = false;
        }
        bool _e234 = local_12;
        if (_e234) {
          local_13 = (distance_1 < width_1);
        } else {
          local_13 = false;
        }
        bool _e239 = local_13;
        if (_e239) {
          float3 colour_9 = lerp(float3(0.05, 0.12, 0.06), float3(0.16, 0.28, 0.12), (((t_3 / needle_length) * 0.7) + (_e215 * 0.3)));
          const Leaf _e262 = leaf(colour_9, ((width_1 * sqrt((1.0 - (distance_1 / width_1)))) * 0.5));
          result_3 = _e262;
        }
      }
    }
  }
  Leaf _e266 = result_3;
  const Leaf leaf_3 = _e266;
  return leaf_3;
}

Leaf scale_sprays(float2 uv_8)
{
  Leaf result_4 = ConstructLeaf((0.0).xxxx, 0.0);
  int i_6 = int(0);
  int j = (int)0;

  bool loop_init_11 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_11) {
      int _e174 = i_6;
      i_6 = asint(asuint(_e174) + asuint(int(1)));
    }
    loop_init_11 = false;
    int _e8 = i_6;
    if ((_e8 < int(7))) {
    } else {
      break;
    }
    {
      int _e11 = i_6;
      float side_2 = ((naga_mod(_e11, int(2)) == int(0)) ? 1.0 : -1.0);
      int _e19 = i_6;
      float2 a_3 = float2(0.5, (0.06 + (float(_e19) * 0.115)));
      int _e27 = i_6;
      float2 b_3 = (a_3 + float2((side_2 * (0.34 - (float(_e27) * 0.03))), 0.12));
      float2 axis_2 = normalize((b_3 - a_3));
      const float2 _e39 = segment_distance(uv_8, a_3, b_3);
      float spray_length = length((b_3 - a_3));
      j = int(0);
      bool loop_init_12 = true;
      [allow_uav_condition] [loop] while(true) {
        if (!loop_init_12) {
          int _e139 = j;
          j = asint(asuint(_e139) + asuint(int(1)));
        }
        loop_init_12 = false;
        int _e44 = j;
        if ((_e44 < int(7))) {
        } else {
          break;
        }
        {
          int _e47 = j;
          float t_4 = ((float(_e47) + 0.6) / 7.0);
          float2 origin = (a_3 + ((b_3 - a_3) * t_4));
          int _e56 = j;
          float turn = ((naga_mod(_e56, int(2)) == int(0)) ? 0.8 : -0.8);
          float2 direction_3 = float2(((axis_2.x * cos(turn)) - (axis_2.y * sin(turn))), ((axis_2.x * sin(turn)) + (axis_2.y * cos(turn))));
          const float2 _e88 = segment_distance(uv_8, origin, (origin + (((direction_3 * spray_length) * 0.45) * (1.0 - (t_4 * 0.4)))));
          float width_2 = ((0.018 * (0.75 + (0.25 * abs(sin((_e88.y * 18.0)))))) * (1.0 - (_e88.y * 0.5)));
          if ((_e88.x < width_2)) {
            int _e108 = i_6;
            int _e109 = j;
            const uint _e113 = hash2_(int2(_e108, _e109), int(64), 251u);
            const float _e114 = unit(_e113);
            float3 colour_10 = lerp(float3(0.06, 0.14, 0.08), float3(0.2, 0.3, 0.12), ((_e88.y * 0.6) + (_e114 * 0.4)));
            const Leaf _e138 = leaf(colour_10, ((width_2 * sqrt((1.0 - (_e88.x / width_2)))) * 0.5));
            result_4 = _e138;
          }
        }
      }
      float width_3 = ((0.014 * (0.75 + (0.25 * abs(sin((_e39.y * 24.0)))))) * (1.0 - (_e39.y * 0.4)));
      if ((_e39.x < width_3)) {
        const Leaf _e173 = leaf(lerp(float3(0.08, 0.16, 0.08), float3(0.16, 0.26, 0.1), _e39.y), (width_3 * 0.4));
        result_4 = _e173;
      }
    }
  }
  const float2 _e183 = segment_distance(uv_8, float2(0.5, 0.0), float2(0.5, 0.74));
  if ((_e183.x < 0.006)) {
    const Leaf _e192 = leaf(float3(0.24, 0.15, 0.09), 0.004);
    result_4 = _e192;
  }
  Leaf _e193 = result_4;
  const Leaf leaf_4 = _e193;
  return leaf_4;
}

Leaf palm_frond(float2 uv_9)
{
  bool local_14 = (bool)0;
  bool local_15 = (bool)0;
  bool local_16 = (bool)0;
  bool local_17 = (bool)0;
  float3 colour_7 = (float3)0;

  float rib_width = (0.018 * (1.0 - (uv_9.y * 0.7)));
  float rib_distance = abs((uv_9.x - 0.5));
  if ((rib_distance < rib_width)) {
    const Leaf _e24 = leaf(lerp(float3(0.45, 0.42, 0.22), float3(0.3, 0.36, 0.12), uv_9.y), 0.004);
    const Leaf leaf_5 = _e24;
    return leaf_5;
  }
  if ((uv_9.y < 0.08)) {
    const Leaf leaf_6 = ConstructLeaf((0.0).xxxx, 0.0);
    return leaf_6;
  }
  float across_3 = (rib_distance - rib_width);
  float start_1 = (uv_9.y - (across_3 * 0.55));
  float k_2 = round((start_1 / 0.03));
  float leaflet_base = (k_2 * 0.03);
  float rel_2 = (uv_9.y - (leaflet_base + (across_3 * 0.55)));
  float length_along = (across_3 / 0.48);
  float width_4 = ((0.011 * (1.0 - (length_along * 0.8))) * (1.0 - (uv_9.y * 0.3)));
  if (!((leaflet_base < 0.06))) {
    local_14 = (abs(rel_2) > width_4);
  } else {
    local_14 = true;
  }
  bool _e67 = local_14;
  if (!(_e67)) {
    local_15 = (length_along > (1.0 - (uv_9.y * 0.35)));
  } else {
    local_15 = true;
  }
  bool _e78 = local_15;
  if (_e78) {
    const Leaf leaf_7 = ConstructLeaf((0.0).xxxx, 0.0);
    return leaf_7;
  }
  const uint _e93 = hash2_(int2(naga_f2i32(k_2), ((uv_9.x > 0.5) ? int(1) : int(0))), int(4096), 151u);
  const float _e94 = unit(_e93);
  if (!((_e94 < 0.08))) {
    if ((_e94 > 0.92)) {
      local_17 = (length_along > 0.5);
    } else {
      local_17 = false;
    }
    bool _e107 = local_17;
    local_16 = _e107;
  } else {
    local_16 = true;
  }
  bool _e109 = local_16;
  if (_e109) {
    const Leaf leaf_8 = ConstructLeaf((0.0).xxxx, 0.0);
    return leaf_8;
  }
  colour_7 = lerp(float3(0.14, 0.3, 0.06), float3(0.3, 0.42, 0.1), _e94);
  float3 _e124 = colour_7;
  colour_7 = lerp(_e124, float3(0.55, 0.5, 0.2), (smoothstep(0.7, 1.0, length_along) * 0.5));
  float3 _e135 = colour_7;
  colour_7 = (_e135 * (0.8 + (0.2 * (1.0 - (abs(rel_2) / width_4)))));
  float3 _e145 = colour_7;
  const Leaf _e153 = leaf(_e145, (width_4 * (0.6 - ((abs(rel_2) / width_4) * 0.5))));
  const Leaf leaf_9 = _e153;
  return leaf_9;
}

Leaf fine_leaves(float2 uv_10)
{
  Leaf result_5 = ConstructLeaf((0.0).xxxx, 0.0);
  int i_7 = int(0);
  bool local_18 = (bool)0;
  bool local_19 = (bool)0;
  bool local_20 = (bool)0;

  bool loop_init_13 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_13) {
      int _e150 = i_7;
      i_7 = asint(asuint(_e150) + asuint(int(1)));
    }
    loop_init_13 = false;
    int _e8 = i_7;
    if ((_e8 < int(7))) {
    } else {
      break;
    }
    {
      int _e12 = i_7;
      const uint _e17 = pcg((161u + (uint(_e12) * 131u)));
      int _e18 = i_7;
      const float _e24 = unit(_e17);
      float angle_3 = (((float(_e18) / 7.0) * TAU) + (_e24 * 0.5));
      float2 a_4 = (float2(0.5, 0.5) + (float2(cos(angle_3), sin(angle_3)) * 0.04));
      const uint _e43 = pcg(_e17);
      const float _e44 = unit(_e43);
      float2 b_4 = (float2(0.5, 0.5) + (float2(cos(angle_3), sin(angle_3)) * (0.36 + (_e44 * 0.1))));
      float2 axis_3 = normalize((b_4 - a_4));
      float2 local_30 = (uv_10 - a_4);
      float along_3 = dot(local_30, axis_3);
      float across_4 = dot(local_30, float2(-(axis_3.y), axis_3.x));
      float spray_length_1 = length((b_4 - a_4));
      if (!((along_3 < 0.0))) {
        local_18 = (along_3 > (spray_length_1 + 0.05));
      } else {
        local_18 = true;
      }
      bool _e71 = local_18;
      if (!(_e71)) {
        local_19 = (abs(across_4) > 0.09);
      } else {
        local_19 = true;
      }
      bool _e79 = local_19;
      if (_e79) {
        continue;
      }
      const float2 _e80 = segment_distance(uv_10, a_4, b_4);
      if ((_e80.x < 0.004)) {
        const Leaf _e89 = leaf(float3(0.25, 0.22, 0.1), 0.003);
        result_5 = _e89;
      }
      float k_3 = round((along_3 / 0.016));
      float2 leaflet_centre = float2((k_3 * 0.016), ((sign(across_4) * 0.035) * (1.0 - (((k_3 * 0.016) / spray_length_1) * 0.5))));
      float2 d_2 = ((float2(along_3, across_4) - leaflet_centre) / float2(0.007, 0.03));
      if (((k_3 * 0.016) <= spray_length_1)) {
        local_20 = (dot(d_2, d_2) < 1.0);
      } else {
        local_20 = false;
      }
      bool _e119 = local_20;
      if (_e119) {
        int _e121 = i_7;
        const uint _e125 = hash2_(int2(naga_f2i32(k_3), _e121), int(4096), 162u);
        const float _e126 = unit(_e125);
        float3 colour_11 = (lerp(float3(0.15, 0.26, 0.06), float3(0.3, 0.4, 0.12), _e126) * (0.8 + ((1.0 - dot(d_2, d_2)) * 0.3)));
        const Leaf _e149 = leaf(colour_11, (0.004 * (1.0 - dot(d_2, d_2))));
        result_5 = _e149;
      }
    }
  }
  const float2 _e159 = segment_distance(uv_10, float2(0.5, 0.0), float2(0.5, 0.5));
  if ((_e159.x < 0.005)) {
    const Leaf _e168 = leaf(float3(0.25, 0.2, 0.12), 0.003);
    result_5 = _e168;
  }
  Leaf _e169 = result_5;
  const Leaf leaf_10 = _e169;
  return leaf_10;
}

float4 moss(float2 uv_11)
{
  float4 result_6 = (0.0).xxxx;
  int i_8 = int(0);

  bool loop_init_14 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_14) {
      int _e86 = i_8;
      i_8 = asint(asuint(_e86) + asuint(int(1)));
    }
    loop_init_14 = false;
    int _e6 = i_8;
    if ((_e6 < int(14))) {
    } else {
      break;
    }
    {
      int _e10 = i_8;
      const uint _e15 = pcg((171u + (uint(_e10) * 53u)));
      const float _e16 = unit(_e15);
      float x_2 = (0.08 + (_e16 * 0.84));
      const uint _e21 = pcg(_e15);
      const float _e22 = unit(_e21);
      float strand_length = (0.45 + (_e22 * 0.55));
      float hang = (1.0 - uv_11.y);
      if ((hang > strand_length)) {
        continue;
      }
      int _e33 = i_8;
      int _e42 = i_8;
      float sway = (((sin(((hang * 9.0) + float(_e33))) * 0.03) * hang) + (sin(((hang * 23.0) + (float(_e42) * 2.0))) * 0.01));
      float width_5 = (0.013 * (1.0 - ((hang / strand_length) * 0.7)));
      float distance_2 = abs(((uv_11.x - x_2) - sway));
      if ((distance_2 < width_5)) {
        const uint _e65 = pcg((_e15 + 11u));
        const float _e66 = unit(_e65);
        float3 colour_12 = (lerp(float3(0.4, 0.44, 0.34), float3(0.6, 0.63, 0.5), _e66) * (0.8 + (0.2 * (1.0 - (distance_2 / width_5)))));
        result_6 = float4(colour_12, 1.0);
      }
    }
  }
  float4 _e89 = result_6;
  return _e89;
}

float4 fern(float2 uv_12)
{
  float4 result_7 = (0.0).xxxx;
  int i_9 = int(0);
  bool local_21 = (bool)0;
  bool local_22 = (bool)0;
  bool local_23 = (bool)0;
  bool local_24 = (bool)0;
  bool local_25 = (bool)0;

  bool loop_init_15 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_15) {
      int _e147 = i_9;
      i_9 = asint(asuint(_e147) + asuint(int(1)));
    }
    loop_init_15 = false;
    int _e6 = i_9;
    if ((_e6 < int(2))) {
    } else {
      break;
    }
    {
      int _e9 = i_9;
      float side_3 = ((_e9 == int(1)) ? 1.0 : -1.0);
      float2 a_5 = float2(0.5, 0.97);
      float2 b_5 = float2((0.5 + (side_3 * 0.34)), 0.06);
      float2 axis_4 = normalize((b_5 - a_5));
      float2 local_31 = (uv_12 - a_5);
      float frond_length = length((b_5 - a_5));
      float along_4 = (dot(local_31, axis_4) / frond_length);
      if (!((along_4 < 0.0))) {
        local_21 = (along_4 > 1.0);
      } else {
        local_21 = true;
      }
      bool _e39 = local_21;
      if (_e39) {
        continue;
      }
      float across_5 = (dot(local_31, float2(-(axis_4.y), axis_4.x)) + ((side_3 * 0.06) * sin((along_4 * 3.14159))));
      float rachis_width = (0.007 * (1.0 - (along_4 * 0.6)));
      if ((abs(across_5) < rachis_width)) {
        result_7 = float4(lerp(float3(0.2, 0.17, 0.07), float3(0.12, 0.22, 0.05), along_4), 1.0);
        continue;
      }
      float pinna_length = ((0.12 * (1.0 - pow(along_4, 1.5))) + 0.015);
      float reach_2 = (abs(across_5) - rachis_width);
      float spacing = (0.03 / frond_length);
      float start_2 = (along_4 - ((reach_2 * 0.5) / frond_length));
      float k_4 = round((start_2 / spacing));
      float rel_3 = ((start_2 - (k_4 * spacing)) * frond_length);
      float width_6 = ((0.011 * (1.0 - (reach_2 / pinna_length))) * (1.0 - (along_4 * 0.4)));
      if ((k_4 >= 1.0)) {
        local_22 = (reach_2 < pinna_length);
      } else {
        local_22 = false;
      }
      bool _e108 = local_22;
      if (_e108) {
        local_23 = (abs(rel_3) < width_6);
      } else {
        local_23 = false;
      }
      bool _e114 = local_23;
      if (_e114) {
        int _e116 = i_9;
        const uint _e120 = hash2_(int2(naga_f2i32(k_4), _e116), int(4096), 221u);
        const float _e121 = unit(_e120);
        float3 colour_13 = lerp(float3(0.05, 0.16, 0.03), float3(0.16, 0.32, 0.07), ((_e121 * 0.6) + (along_4 * 0.4)));
        result_7 = float4((colour_13 * (0.8 + (0.2 * (1.0 - (abs(rel_3) / width_6))))), 1.0);
      }
    }
  }
  float stem = abs((uv_12.x - 0.5));
  if ((uv_12.y > 0.8)) {
    local_24 = (stem < 0.006);
  } else {
    local_24 = false;
  }
  bool _e162 = local_24;
  if (_e162) {
    result_7 = float4(0.14, 0.2, 0.06, 1.0);
  }
  float coil = length((uv_12 - float2(0.5, 0.77)));
  if ((coil < 0.035)) {
    local_25 = (coil > (0.012 + (0.01 * frac(((atan2((uv_12.y - 0.77), (uv_12.x - 0.5)) / TAU) + (coil * 12.0))))));
  } else {
    local_25 = false;
  }
  bool _e196 = local_25;
  if (_e196) {
    result_7 = float4(0.18, 0.26, 0.08, 1.0);
  }
  float4 _e202 = result_7;
  return _e202;
}

typedef Leaf ret_flora[4];
ret_flora flora(int layer_1, float2 uvs_3[4])
{
  Leaf result_8[4] = ZeroValuearray4_Leaf_();
  float4 bark = (float4)0;
  int s_5 = int(0);
  int s_6 = int(0);

  const Clump _e2 = clump_of(layer_1);
  if ((_e2.count > int(0))) {
    const Leaf _e6[4] = leaf_cluster(uvs_3, _e2);
    return _e6;
  }
  if ((layer_1 == int(11))) {
    const Leaf _e21[4] = radial_cluster(uvs_3, int(64), 0.13, 0.55, float3(0.03, 0.1, 0.025), float3(0.1, 0.22, 0.05), 231u);
    return _e21;
  }
  if ((layer_1 < int(4))) {
    float2 uv_13 = ((uvs_3[0] + uvs_3[3]) * 0.5);
    switch(layer_1) {
      case 0: {
        const float4 _e32 = bark_oak(uv_13);
        bark = _e32;
        break;
      }
      case 1: {
        const float4 _e33 = bark_pine(uv_13);
        bark = _e33;
        break;
      }
      case 2: {
        const float4 _e34 = bark_palm(uv_13);
        bark = _e34;
        break;
      }
      default: {
        const float4 _e35 = bark_smooth(uv_13);
        bark = _e35;
        break;
      }
    }
    bool loop_init_16 = true;
    [allow_uav_condition] [loop] while(true) {
      if (!loop_init_16) {
        int _e46 = s_5;
        s_5 = asint(asuint(_e46) + asuint(int(1)));
      }
      loop_init_16 = false;
      int _e38 = s_5;
      if ((_e38 < int(4))) {
      } else {
        break;
      }
      {
        int _e41 = s_5;
        float4 _e43 = bark;
        result_8[min(uint(_e41), 3u)] = ConstructLeaf(_e43, 0.0);
      }
    }
    Leaf _e49[4] = result_8;
    return _e49;
  }
  bool loop_init_17 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_17) {
      int _e82 = s_6;
      s_6 = asint(asuint(_e82) + asuint(int(1)));
    }
    loop_init_17 = false;
    int _e52 = s_6;
    if ((_e52 < int(4))) {
    } else {
      break;
    }
    {
      int _e55 = s_6;
      float2 uv_14 = uvs_3[min(uint(_e55), 3u)];
      bool should_continue = false;
      switch(layer_1) {
        case 6: {
          int _e57 = s_6;
          const Leaf _e59 = needle_bundles(uv_14);
          result_8[min(uint(_e57), 3u)] = _e59;
          break;
        }
        case 7: {
          int _e60 = s_6;
          const Leaf _e62 = palm_frond(uv_14);
          result_8[min(uint(_e60), 3u)] = _e62;
          break;
        }
        case 8: {
          int _e63 = s_6;
          const Leaf _e65 = fine_leaves(uv_14);
          result_8[min(uint(_e63), 3u)] = _e65;
          break;
        }
        case 10: {
          int _e66 = s_6;
          const float4 _e68 = fern(uv_14);
          result_8[min(uint(_e66), 3u)] = ConstructLeaf(_e68, 0.0);
          break;
        }
        case 13: {
          int _e71 = s_6;
          const Leaf _e73 = needle_sprays(uv_14);
          result_8[min(uint(_e71), 3u)] = _e73;
          break;
        }
        case 14: {
          int _e74 = s_6;
          const Leaf _e76 = scale_sprays(uv_14);
          result_8[min(uint(_e74), 3u)] = _e76;
          break;
        }
        default: {
          int _e77 = s_6;
          const float4 _e79 = moss(uv_14);
          result_8[min(uint(_e77), 3u)] = ConstructLeaf(_e79, 0.0);
          break;
        }
      }
    }
  }
  Leaf _e85[4] = result_8;
  return _e85;
}

int leaf_normal_layer(int layer_2)
{
  bool local_26 = (bool)0;

  if ((layer_2 >= int(4))) {
    local_26 = (layer_2 <= int(8));
  } else {
    local_26 = false;
  }
  bool _e8 = local_26;
  if (_e8) {
    return asint(asuint(layer_2) + asuint(int(11)));
  }
  return ((layer_2 >= int(12)) ? asint(asuint(layer_2) + asuint(int(8))) : int(-1));
}

typedef float2 ret_ZeroValuearray4_float2_[4];
ret_ZeroValuearray4_float2_ ZeroValuearray4_float2_() {
  return (float2[4])0;
}

uint2 NagaRWDimensions2DArray(RWTexture2DArray<unorm float4> tex)
{
  uint4 ret;
  tex.GetDimensions(ret.x, ret.y, ret.z);
  return ret.xy;
}

[numthreads(8, 8, 1)]
void gen_flora(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  bool local_1 = (bool)0;
  float2 uvs[4] = ZeroValuearray4_float2_();
  int s = int(0);
  float4 sum = (0.0).xxxx;
  float3 colour_sum = (0.0).xxx;
  int s_1 = int(0);

  uint2 size_2 = NagaRWDimensions2DArray(flora_out);
  if (!((id.x >= size_2.x))) {
    local = (id.y >= size_2.y);
  } else {
    local = true;
  }
  bool _e13 = local;
  if (!(_e13)) {
    uint _e19 = bake_layers.y;
    local_1 = ((_e19 & (1u << id.z)) == 0u);
  } else {
    local_1 = true;
  }
  bool _e27 = local_1;
  if (_e27) {
    return;
  }
  int layer_3 = int(id.z);
  bool loop_init_18 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_18) {
      int _e61 = s;
      s = asint(asuint(_e61) + asuint(int(1)));
    }
    loop_init_18 = false;
    int _e34 = s;
    if ((_e34 < int(4))) {
    } else {
      break;
    }
    {
      int _e37 = s;
      int _e45 = s;
      float2 offset = float2((0.25 + (float(naga_mod(_e37, int(2))) * 0.5)), (0.25 + (float(naga_div(_e45, int(2))) * 0.5)));
      int _e54 = s;
      uvs[min(uint(_e54), 3u)] = ((float2(id.xy) + offset) / float2(size_2));
    }
  }
  float2 _e64[4] = uvs;
  const Leaf _e65[4] = flora(layer_3, _e64);
  bool loop_init_19 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_19) {
      int _e91 = s_1;
      s_1 = asint(asuint(_e91) + asuint(int(1)));
    }
    loop_init_19 = false;
    int _e74 = s_1;
    if ((_e74 < int(4))) {
    } else {
      break;
    }
    {
      int _e77 = s_1;
      float4 sample_ = _e65[min(uint(_e77), 3u)].colour;
      float3 _e80 = colour_sum;
      colour_sum = (_e80 + (sample_.xyz * ((layer_3 < int(4)) ? 1.0 : sample_.w)));
      float4 _e89 = sum;
      sum = (_e89 + sample_);
    }
  }
  float _e95 = sum.w;
  float alpha = (_e95 / 4.0);
  float3 _e98 = colour_sum;
  float _e100 = sum.w;
  float3 colour_14 = (_e98 / (max(((layer_3 < int(4)) ? 4.0 : _e100), 0.0001)).xxx);
  flora_out[int3(int2(id.xy), layer_3)] = float4(saturate(colour_14), alpha);
  const int _e114 = leaf_normal_layer(layer_3);
  if ((_e114 >= int(0))) {
    float step_ = (0.5 / float(size_2.x));
    float2 slope = (float2((((_e65[1].height - _e65[0].height) + _e65[3].height) - _e65[2].height), (((_e65[2].height - _e65[0].height) + _e65[3].height) - _e65[1].height)) / ((2.0 * step_)).xx);
    float3 normal = normalize(float3(-(slope), 1.0));
    flora_out[int3(int2(id.xy), _e114)] = float4(((normal.xy * 0.5) + (0.5).xx), 0.0, 1.0);
    return;
  } else {
    return;
  }
}
