// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: texture_gen (texture_gen)
// Entry point: gen_terrain_normals, compile with /T cs_5_0 /E gen_terrain_normals
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(1) terrain_normal_out -> u0  RWTexture2DArray (Rgba8Unorm)
//   @group(0) @binding(6) terrain_heights -> u1  RWByteAddressBuffer
//   @group(0) @binding(7) bake_layers -> b0  constant buffer

static const float TAU = 6.2831855;

RWTexture2DArray<unorm float4> terrain_normal_out : register(u0);
RWByteAddressBuffer terrain_heights : register(u1);
cbuffer bake_layers : register(b0) { uint4 bake_layers; }

float material_roughness(int layer, float height)
{
  switch(layer) {
    case 3: {
      return 0.85;
    }
    case 4: {
      return (0.75 - (height * 0.15));
    }
    case 5: {
      return 0.45;
    }
    case 6: {
      return lerp(0.2, 0.7, saturate((height * 2.0)));
    }
    case 7: {
      return 0.6;
    }
    case 8: {
      return lerp(0.15, 0.35, smoothstep(0.35, 0.75, height));
    }
    case 9: {
      return 0.85;
    }
    case 10: {
      return lerp(0.95, 0.7, height);
    }
    case 11: {
      return lerp(0.95, 0.72, height);
    }
    default: {
      return 0.9;
    }
  }
}

float material_bump(int layer_1)
{
  switch(layer_1) {
    case 4: {
      return 5.5;
    }
    case 7: {
      return 5.0;
    }
    case 2: {
      return 3.5;
    }
    case 5: {
      return 1.5;
    }
    case 3: {
      return 1.6;
    }
    case 8: {
      return 1.2;
    }
    case 10: {
      return 4.0;
    }
    case 11: {
      return 5.0;
    }
    default: {
      return 3.0;
    }
  }
}

uint terrain_texel(uint x, uint y, uint layer_2, uint2 size)
{
  return ((((layer_2 * size.y) + y) * size.x) + x);
}

uint naga_mod(uint lhs, uint rhs) {
  return lhs % (rhs == 0u ? 1u : rhs);
}

uint2 NagaRWDimensions2DArray(RWTexture2DArray<unorm float4> tex)
{
  uint4 ret;
  tex.GetDimensions(ret.x, ret.y, ret.z);
  return ret.xy;
}

[numthreads(8, 8, 1)]
void gen_terrain_normals(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;
  bool local_1 = (bool)0;

  uint2 size_1 = NagaRWDimensions2DArray(terrain_normal_out);
  if (!((id.x >= size_1.x))) {
    local = (id.y >= size_1.y);
  } else {
    local = true;
  }
  bool _e13 = local;
  if (!(_e13)) {
    uint _e19 = bake_layers.x;
    local_1 = ((_e19 & (1u << id.z)) == 0u);
  } else {
    local_1 = true;
  }
  bool _e27 = local_1;
  if (_e27) {
    return;
  }
  int layer_3 = int(id.z);
  const uint _e34 = terrain_texel(id.x, id.y, id.z, size_1);
  float height_1 = asfloat(terrain_heights.Load(_e34*4));
  const uint _e45 = terrain_texel(naga_mod((id.x + 1u), size_1.x), id.y, id.z, size_1);
  float right = asfloat(terrain_heights.Load(_e45*4));
  const uint _e56 = terrain_texel(id.x, naga_mod((id.y + 1u), size_1.y), id.z, size_1);
  float up = asfloat(terrain_heights.Load(_e56*4));
  const float _e59 = material_bump(layer_3);
  float3 normal = normalize(float3(((height_1 - right) * _e59), 1.0, ((height_1 - up) * _e59)));
  float occlusion = saturate((0.55 + (height_1 * 0.6)));
  const float _e85 = material_roughness(layer_3, height_1);
  terrain_normal_out[int3(int2(id.xy), layer_3)] = float4(((normal.x * 0.5) + 0.5), ((normal.z * 0.5) + 0.5), occlusion, _e85);
  return;
}
