// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: texture_gen (texture_gen)
// Entry point: gen_noise, compile with /T cs_5_0 /E gen_noise
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(4) noise_out -> u0  RWTexture2D (Rgba8Unorm)

static const float TAU = 6.2831855;

RWTexture2D<unorm float4> noise_out : register(u0);

uint pcg(uint value)
{
  uint state = ((value * 747796405u) + 2891336453u);
  uint word = (((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u);
  return ((word >> 22u) ^ word);
}

int naga_mod(int lhs, int rhs) {
  int divisor = ((lhs == int(-2147483647 - 1) & rhs == -1) | (rhs == 0)) ? 1 : rhs;
  return lhs - (lhs / divisor) * divisor;
}

int wrap(int value_1, int period)
{
  return naga_mod(asint(asuint(naga_mod(value_1, period)) + asuint(period)), period);
}

uint hash2a(int2 cell, int2 period_1, uint seed)
{
  const int _e5 = wrap(cell.x, period_1.x);
  uint x_1 = uint(_e5);
  const int _e9 = wrap(cell.y, period_1.y);
  uint y_1 = uint(_e9);
  const uint _e11 = pcg(seed);
  const uint _e13 = pcg((y_1 + _e11));
  const uint _e15 = pcg((x_1 + _e13));
  return _e15;
}

uint hash2_(int2 cell_1, int period_2, uint seed_1)
{
  const uint _e4 = hash2a(cell_1, int2(period_2, period_2), seed_1);
  return _e4;
}

float unit(uint h)
{
  return (float((h & 16777215u)) / 16777215.0);
}

float2 gradient2_(int2 cell_2, int2 period_3, uint seed_2)
{
  const uint _e3 = hash2a(cell_2, period_3, seed_2);
  const float _e4 = unit(_e3);
  float angle = (_e4 * TAU);
  return float2(cos(angle), sin(angle));
}

int2 naga_f2i32(float2 value) {
  return int2(clamp(value, -2147483600.0, 2147483500.0));
}

float perlin2a(float2 p, int2 period_4, uint seed_3)
{
  int2 i_1 = naga_f2i32(floor(p));
  float2 f = frac(p);
  float2 u = (((f * f) * f) * ((f * ((f * 6.0) - (15.0).xx)) + (10.0).xx));
  const float2 _e18 = gradient2_(i_1, period_4, seed_3);
  float a = dot(_e18, f);
  const float2 _e24 = gradient2_(asint(asuint(i_1) + asuint(int2(int(1), int(0)))), period_4, seed_3);
  float b = dot(_e24, (f - float2(1.0, 0.0)));
  const float2 _e34 = gradient2_(asint(asuint(i_1) + asuint(int2(int(0), int(1)))), period_4, seed_3);
  float c = dot(_e34, (f - float2(0.0, 1.0)));
  const float2 _e44 = gradient2_(asint(asuint(i_1) + asuint(int2(int(1), int(1)))), period_4, seed_3);
  float d = dot(_e44, (f - float2(1.0, 1.0)));
  return (lerp(lerp(a, b, u.x), lerp(c, d, u.x), u.y) * 1.414);
}

float perlin2_(float2 p_1, int period_5, uint seed_4)
{
  const float _e4 = perlin2a(p_1, int2(period_5, period_5), seed_4);
  return _e4;
}

float fbm2_(float2 uv, int period_6, int octaves, uint seed_5)
{
  float value_2 = 0.0;
  float amplitude = 0.5;
  float total = 0.0;
  int frequency = (int)0;
  int i = int(0);

  frequency = period_6;
  bool loop_init = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init) {
      int _e38 = i;
      i = asint(asuint(_e38) + asuint(int(1)));
    }
    loop_init = false;
    int _e13 = i;
    if ((_e13 < octaves)) {
    } else {
      break;
    }
    {
      float _e15 = value_2;
      int _e16 = frequency;
      int _e19 = frequency;
      int _e20 = i;
      const float _e25 = perlin2_((uv * float(_e16)), _e19, (seed_5 + (uint(_e20) * 101u)));
      float _e26 = amplitude;
      value_2 = (_e15 + (_e25 * _e26));
      float _e29 = total;
      float _e30 = amplitude;
      total = (_e29 + _e30);
      float _e32 = amplitude;
      amplitude = (_e32 * 0.5);
      int _e35 = frequency;
      frequency = asint(asuint(_e35) * asuint(int(2)));
    }
  }
  float _e41 = value_2;
  float _e42 = total;
  return (((_e41 / _e42) * 0.5) + 0.5);
}

float3 worley2_(float2 p_2, int period_7, uint seed_6)
{
  float f1_ = 8.0;
  float f2_ = 8.0;
  float id_1 = 0.0;
  int y = int(-1);
  int x = (int)0;

  int2 i_2 = naga_f2i32(floor(p_2));
  float2 f_1 = frac(p_2);
  bool loop_init_1 = true;
  [allow_uav_condition] [loop] while(true) {
    if (!loop_init_1) {
      int _e51 = y;
      y = asint(asuint(_e51) + asuint(int(1)));
    }
    loop_init_1 = false;
    int _e14 = y;
    if ((_e14 <= int(1))) {
    } else {
      break;
    }
    {
      x = int(-1);
      bool loop_init_2 = true;
      [allow_uav_condition] [loop] while(true) {
        if (!loop_init_2) {
          int _e48 = x;
          x = asint(asuint(_e48) + asuint(int(1)));
        }
        loop_init_2 = false;
        int _e19 = x;
        if ((_e19 <= int(1))) {
        } else {
          break;
        }
        {
          int _e22 = x;
          int _e23 = y;
          int2 cell_3 = asint(asuint(i_2) + asuint(int2(_e22, _e23)));
          const uint _e26 = hash2_(cell_3, period_7, seed_6);
          int _e27 = x;
          int _e29 = y;
          const float _e32 = unit(_e26);
          const uint _e33 = pcg(_e26);
          const float _e34 = unit(_e33);
          float2 point_ = ((float2(float(_e27), float(_e29)) + float2(_e32, _e34)) - f_1);
          float d_1 = length(point_);
          float _e39 = f1_;
          if ((d_1 < _e39)) {
            float _e41 = f1_;
            f2_ = _e41;
            f1_ = d_1;
            const uint _e44 = pcg((_e26 + 17u));
            const float _e45 = unit(_e44);
            id_1 = _e45;
          } else {
            float _e46 = f2_;
            if ((d_1 < _e46)) {
              f2_ = d_1;
            }
          }
        }
      }
    }
  }
  float _e54 = f1_;
  float _e55 = f2_;
  float _e56 = id_1;
  return float3(_e54, _e55, _e56);
}

float remap(float value_3, float old_min, float old_max, float new_min, float new_max)
{
  return (new_min + (((value_3 - old_min) / max((old_max - old_min), 0.0001)) * (new_max - new_min)));
}

uint2 NagaRWDimensions2D(RWTexture2D<unorm float4> tex)
{
  uint4 ret;
  tex.GetDimensions(ret.x, ret.y);
  return ret.xy;
}

[numthreads(8, 8, 1)]
void gen_noise(uint3 id : SV_DispatchThreadID)
{
  bool local = (bool)0;

  uint2 size = NagaRWDimensions2D(noise_out);
  if (!((id.x >= size.x))) {
    local = (id.y >= size.y);
  } else {
    local = true;
  }
  bool _e13 = local;
  if (_e13) {
    return;
  }
  float2 uv_1 = ((float2(id.xy) + (0.5).xx) / float2(size));
  const float _e24 = fbm2_(uv_1, int(4), int(6), 301u);
  const float _e29 = remap(_e24, 0.22, 0.78, 0.0, 1.0);
  float r = saturate(_e29);
  const float _e34 = fbm2_(uv_1, int(8), int(5), 302u);
  const float _e39 = remap(_e34, 0.25, 0.75, 0.0, 1.0);
  float g = saturate(_e39);
  const float3 _e45 = worley2_((uv_1 * 6.0), int(6), 303u);
  float b_1 = (1.0 - saturate(_e45.x));
  const float _e53 = fbm2_(uv_1, int(16), int(4), 304u);
  const float _e58 = remap(_e53, 0.25, 0.75, 0.0, 1.0);
  float a_1 = saturate(_e58);
  noise_out[int2(id.xy)] = float4(r, g, b_1, a_1);
  return;
}
