# Generated by vista_hlsl. Compiles every translated shader with fxc
# (from the Windows SDK) and stops at the first failure.
# Run from this directory: powershell -File compile-fxc.ps1
$ErrorActionPreference = "Stop"
New-Item -ItemType Directory -Force -Path cso | Out-Null
fxc /nologo /O3 /T vs_5_0 /E vertex_main /Fo "cso/clipmap_render__vertex_main.cso" "clipmap_render/vertex_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "clipmap_render/vertex_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_main /Fo "cso/clipmap_render__fragment_main.cso" "clipmap_render/fragment_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "clipmap_render/fragment_main.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E canopy_vertex_main /Fo "cso/clipmap_render__canopy_vertex_main.cso" "clipmap_render/canopy_vertex_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "clipmap_render/canopy_vertex_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E canopy_fragment_main /Fo "cso/clipmap_render__canopy_fragment_main.cso" "clipmap_render/canopy_fragment_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "clipmap_render/canopy_fragment_main.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_bank /Fo "cso/clipmap_render__vertex_bank.cso" "clipmap_render/vertex_bank.hlsl"
if ($LASTEXITCODE -ne 0) { throw "clipmap_render/vertex_bank.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_bank /Fo "cso/clipmap_render__fragment_bank.cso" "clipmap_render/fragment_bank.hlsl"
if ($LASTEXITCODE -ne 0) { throw "clipmap_render/fragment_bank.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_main /Fo "cso/boulders__vertex_main.cso" "boulders/vertex_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "boulders/vertex_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_main /Fo "cso/boulders__fragment_main.cso" "boulders/fragment_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "boulders/fragment_main.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E shadow_main /Fo "cso/boulders__shadow_main.cso" "boulders/shadow_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "boulders/shadow_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E shadow_fragment /Fo "cso/boulders__shadow_fragment.cso" "boulders/shadow_fragment.hlsl"
if ($LASTEXITCODE -ne 0) { throw "boulders/shadow_fragment.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_main /Fo "cso/water__vertex_main.SEA_ICE-0.cso" "water/vertex_main.SEA_ICE-0.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/vertex_main.SEA_ICE-0.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_fall /Fo "cso/water__fragment_fall.SEA_ICE-0.cso" "water/fragment_fall.SEA_ICE-0.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/fragment_fall.SEA_ICE-0.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_main /Fo "cso/water__fragment_main.SEA_ICE-0.cso" "water/fragment_main.SEA_ICE-0.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/fragment_main.SEA_ICE-0.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_main /Fo "cso/water__vertex_main.INLAND-1.SEA_ICE-0.cso" "water/vertex_main.INLAND-1.SEA_ICE-0.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/vertex_main.INLAND-1.SEA_ICE-0.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_fall /Fo "cso/water__fragment_fall.INLAND-1.SEA_ICE-0.cso" "water/fragment_fall.INLAND-1.SEA_ICE-0.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/fragment_fall.INLAND-1.SEA_ICE-0.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_main /Fo "cso/water__fragment_main.INLAND-1.SEA_ICE-0.cso" "water/fragment_main.INLAND-1.SEA_ICE-0.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/fragment_main.INLAND-1.SEA_ICE-0.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_main /Fo "cso/water__vertex_main.cso" "water/vertex_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/vertex_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_fall /Fo "cso/water__fragment_fall.cso" "water/fragment_fall.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/fragment_fall.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_main /Fo "cso/water__fragment_main.cso" "water/fragment_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/fragment_main.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_main /Fo "cso/water__vertex_main.INLAND-1.cso" "water/vertex_main.INLAND-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/vertex_main.INLAND-1.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_fall /Fo "cso/water__fragment_fall.INLAND-1.cso" "water/fragment_fall.INLAND-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/fragment_fall.INLAND-1.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_main /Fo "cso/water__fragment_main.INLAND-1.cso" "water/fragment_main.INLAND-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "water/fragment_main.INLAND-1.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_mesh /Fo "cso/trees__vertex_mesh.cso" "trees/vertex_mesh.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/vertex_mesh.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_mesh /Fo "cso/trees__fragment_mesh.cso" "trees/fragment_mesh.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/fragment_mesh.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_impostor /Fo "cso/trees__vertex_impostor.cso" "trees/vertex_impostor.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/vertex_impostor.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_impostor /Fo "cso/trees__fragment_impostor.cso" "trees/fragment_impostor.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/fragment_impostor.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_shadow /Fo "cso/trees__vertex_shadow.cso" "trees/vertex_shadow.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/vertex_shadow.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_shadow /Fo "cso/trees__fragment_shadow.cso" "trees/fragment_shadow.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/fragment_shadow.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_bake /Fo "cso/trees__vertex_bake.cso" "trees/vertex_bake.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/vertex_bake.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_bake /Fo "cso/trees__fragment_bake.cso" "trees/fragment_bake.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/fragment_bake.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_mesh /Fo "cso/trees__vertex_mesh.LIGHT-1.cso" "trees/vertex_mesh.LIGHT-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/vertex_mesh.LIGHT-1.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_mesh /Fo "cso/trees__fragment_mesh.LIGHT-1.cso" "trees/fragment_mesh.LIGHT-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/fragment_mesh.LIGHT-1.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_impostor /Fo "cso/trees__vertex_impostor.LIGHT-1.cso" "trees/vertex_impostor.LIGHT-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/vertex_impostor.LIGHT-1.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_impostor /Fo "cso/trees__fragment_impostor.LIGHT-1.cso" "trees/fragment_impostor.LIGHT-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/fragment_impostor.LIGHT-1.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_shadow /Fo "cso/trees__vertex_shadow.LIGHT-1.cso" "trees/vertex_shadow.LIGHT-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/vertex_shadow.LIGHT-1.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_shadow /Fo "cso/trees__fragment_shadow.LIGHT-1.cso" "trees/fragment_shadow.LIGHT-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/fragment_shadow.LIGHT-1.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_bake /Fo "cso/trees__vertex_bake.LIGHT-1.cso" "trees/vertex_bake.LIGHT-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/vertex_bake.LIGHT-1.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_bake /Fo "cso/trees__fragment_bake.LIGHT-1.cso" "trees/fragment_bake.LIGHT-1.hlsl"
if ($LASTEXITCODE -ne 0) { throw "trees/fragment_bake.LIGHT-1.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_main /Fo "cso/grass_instances__vertex_main.cso" "grass_instances/vertex_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "grass_instances/vertex_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_main /Fo "cso/grass_instances__fragment_main.cso" "grass_instances/fragment_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "grass_instances/fragment_main.hlsl failed" }
fxc /nologo /O3 /T vs_5_0 /E vertex_main /Fo "cso/atmosphere__vertex_main.cso" "atmosphere/vertex_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "atmosphere/vertex_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E cloud_quarter_main /Fo "cso/atmosphere__cloud_quarter_main.cso" "atmosphere/cloud_quarter_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "atmosphere/cloud_quarter_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E cloud_main /Fo "cso/atmosphere__cloud_main.cso" "atmosphere/cloud_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "atmosphere/cloud_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E fragment_main /Fo "cso/atmosphere__fragment_main.cso" "atmosphere/fragment_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "atmosphere/fragment_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E scene_copy_main /Fo "cso/atmosphere__scene_copy_main.cso" "atmosphere/scene_copy_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "atmosphere/scene_copy_main.hlsl failed" }
fxc /nologo /O3 /T ps_5_0 /E present_main /Fo "cso/atmosphere__present_main.cso" "atmosphere/present_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "atmosphere/present_main.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E cull_main /Fo "cso/tree_cull__cull_main.cso" "tree_cull/cull_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "tree_cull/cull_main.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E generate_main /Fo "cso/tree_generate__generate_main.cso" "tree_generate/generate_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "tree_generate/generate_main.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E generate_main /Fo "cso/grass_generate__generate_main.cso" "grass_generate/generate_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "grass_generate/generate_main.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E cull_main /Fo "cso/grass_generate__cull_main.cso" "grass_generate/cull_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "grass_generate/cull_main.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E generate_main /Fo "cso/boulder_generate__generate_main.cso" "boulder_generate/generate_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "boulder_generate/generate_main.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E cull_main /Fo "cso/boulder_generate__cull_main.cso" "boulder_generate/cull_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "boulder_generate/cull_main.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E ground_main /Fo "cso/grounding__ground_main.cso" "grounding/ground_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "grounding/ground_main.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E bake /Fo "cso/terrain_shadow__bake.cso" "terrain_shadow/bake.hlsl"
if ($LASTEXITCODE -ne 0) { throw "terrain_shadow/bake.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E step_main /Fo "cso/surface_weather__step_main.cso" "surface_weather/step_main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "surface_weather/step_main.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E gen_terrain /Fo "cso/texture_gen__gen_terrain.cso" "texture_gen/gen_terrain.hlsl"
if ($LASTEXITCODE -ne 0) { throw "texture_gen/gen_terrain.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E gen_terrain_normals /Fo "cso/texture_gen__gen_terrain_normals.cso" "texture_gen/gen_terrain_normals.hlsl"
if ($LASTEXITCODE -ne 0) { throw "texture_gen/gen_terrain_normals.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E gen_flora /Fo "cso/texture_gen__gen_flora.cso" "texture_gen/gen_flora.hlsl"
if ($LASTEXITCODE -ne 0) { throw "texture_gen/gen_flora.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E gen_water /Fo "cso/texture_gen__gen_water.cso" "texture_gen/gen_water.hlsl"
if ($LASTEXITCODE -ne 0) { throw "texture_gen/gen_water.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E gen_noise /Fo "cso/texture_gen__gen_noise.cso" "texture_gen/gen_noise.hlsl"
if ($LASTEXITCODE -ne 0) { throw "texture_gen/gen_noise.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E gen_cloud /Fo "cso/texture_gen__gen_cloud.cso" "texture_gen/gen_cloud.hlsl"
if ($LASTEXITCODE -ne 0) { throw "texture_gen/gen_cloud.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E count /Fo "cso/mipgen__count.cso" "mipgen/count.hlsl"
if ($LASTEXITCODE -ne 0) { throw "mipgen/count.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E downsample /Fo "cso/mipgen__downsample.cso" "mipgen/downsample.hlsl"
if ($LASTEXITCODE -ne 0) { throw "mipgen/downsample.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E average_canopy /Fo "cso/mipgen__average_canopy.cso" "mipgen/average_canopy.hlsl"
if ($LASTEXITCODE -ne 0) { throw "mipgen/average_canopy.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E rain /Fo "cso/hydraulic_erosion__rain.cso" "hydraulic_erosion/rain.hlsl"
if ($LASTEXITCODE -ne 0) { throw "hydraulic_erosion/rain.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E outflow /Fo "cso/hydraulic_erosion__outflow.cso" "hydraulic_erosion/outflow.hlsl"
if ($LASTEXITCODE -ne 0) { throw "hydraulic_erosion/outflow.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E update_water /Fo "cso/hydraulic_erosion__update_water.cso" "hydraulic_erosion/update_water.hlsl"
if ($LASTEXITCODE -ne 0) { throw "hydraulic_erosion/update_water.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E erode /Fo "cso/hydraulic_erosion__erode.cso" "hydraulic_erosion/erode.hlsl"
if ($LASTEXITCODE -ne 0) { throw "hydraulic_erosion/erode.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E advect /Fo "cso/hydraulic_erosion__advect.cso" "hydraulic_erosion/advect.hlsl"
if ($LASTEXITCODE -ne 0) { throw "hydraulic_erosion/advect.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E evaporate /Fo "cso/hydraulic_erosion__evaporate.cso" "hydraulic_erosion/evaporate.hlsl"
if ($LASTEXITCODE -ne 0) { throw "hydraulic_erosion/evaporate.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E settle /Fo "cso/hydraulic_erosion__settle.cso" "hydraulic_erosion/settle.hlsl"
if ($LASTEXITCODE -ne 0) { throw "hydraulic_erosion/settle.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E exchange /Fo "cso/thermal_erosion__exchange.cso" "thermal_erosion/exchange.hlsl"
if ($LASTEXITCODE -ne 0) { throw "thermal_erosion/exchange.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E apply /Fo "cso/thermal_erosion__apply.cso" "thermal_erosion/apply.hlsl"
if ($LASTEXITCODE -ne 0) { throw "thermal_erosion/apply.hlsl failed" }
fxc /nologo /O3 /T cs_5_0 /E main /Fo "cso/normals__main.cso" "normals/main.hlsl"
if ($LASTEXITCODE -ne 0) { throw "normals/main.hlsl failed" }
