// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: atmosphere (ground + common + atmosphere)
// Entry point: present_main, compile with /T ps_5_0 /E present_main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) frame -> b0  constant buffer
//   @group(1) @binding(0) linear_sampler -> s0  SamplerState
//   @group(3) @binding(3) lens_source -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(3) @binding(6) lens_drops -> t1  ByteAddressBuffer
//   @group(3) @binding(7) lens_bins -> t2  ByteAddressBuffer

struct FrameUniforms {
  row_major float4x4 view_proj;
  float4 camera_position;
  float4 camera_forward;
  float4 camera_right;
  float4 camera_up;
  float4 sun_direction;
  float4 atmosphere;
  float4 sky_tint;
  float4 mist_params;
  float4 mist_colour;
  float4 mist_wind;
  float4 cloud_params;
  float4 cloud_motion;
  float4 cloud_colour;
  float4 water_params;
  float4 water_shallow;
  float4 water_deep;
  float4 water_current;
  float4 wave_params;
  float4 wave_params2_;
  float4 water_origin;
  float4 vegetation;
  float4 vegetation2_;
  float4 viewport;
  row_major float4x4 shadow_view_proj;
  float4 shadow_params;
  float4 weather;
  float4 weather2_;
  float4 surface;
  float4 clouds2_;
  float4 clouds3_;
  float4 clouds4_;
  float4 weather3_;
  row_major float4x4 previous_view_proj;
  float4 temporal;
  float4 distances;
  float4 fades;
  float4 output;
  float4 cold;
  float4 sea_ice;
  float4 rivers;
  float4 ground;
  float4 vegetation3_;
  float4 rock;
  float4 regional;
  float4 air;
  float4 light;
  float4 gust;
  float4 weather4_;
  float4 clouds5_;
  float4 alto;
  float4 rivers2_;
  float4 waterside;
  float4 mouths[16];
};

struct VertexOut {
  float4 clip_position : SV_Position;
  float2 ndc : LOC0;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const float SHAFT_START = 1200.0;

cbuffer frame : register(b0) { FrameUniforms frame; }
SamplerState linear_sampler : register(s0);
Texture2D<float4> lens_source : register(t0);
ByteAddressBuffer lens_drops : register(t1);
ByteAddressBuffer lens_bins : register(t2);

struct FragmentInput_present_main {
  float2 ndc : LOC0;
  float4 clip_position : SV_Position;
};

uint naga_f2u32(float value) {
  return uint(clamp(value, 0.0, 4294967000.0));
}

float4 present_main(FragmentInput_present_main fragmentinput_present_main) : SV_Target0
{
  VertexOut in_ = { fragmentinput_present_main.clip_position, fragmentinput_present_main.ndc };
  float2 bend = (0.0).xx;
  float rim = 0.0;
  float glint = 0.0;
  uint k = 0u;
  float2 d = (float2)0;
  float fade = (float)0;
  float3 colour = (float3)0;

  float4 _e3 = frame.output;
  float2 size = _e3.xy;
  float2 pixel = in_.clip_position.xy;
  float _e17 = frame.weather3_.z;
  if ((_e17 > 0.5)) {
    float2 screen = (pixel / (size.y).xx);
    uint columns = asuint(lens_bins.Load(0));
    uint rows = asuint(lens_bins.Load(4));
    uint column = min(naga_f2u32((((screen.x * size.y) / size.x) * float(columns))), (columns - 1u));
    uint row = min(naga_f2u32((screen.y * float(rows))), (rows - 1u));
    uint entry = asuint(lens_bins.Load(((2u + (row * columns)) + column)*4));
    uint first = ((2u + (columns * rows)) + (entry >> 8u));
    uint2 loop_bound = uint2(4294967295u, 4294967295u);
    bool loop_init = true;
    while(true) {
      if (all(loop_bound == uint2(0u, 0u))) { break; }
      loop_bound -= uint2(loop_bound.y == 0u, 1u);
      if (!loop_init) {
        uint _e147 = k;
        k = (_e147 + 1u);
      }
      loop_init = false;
      uint _e62 = k;
      if ((_e62 < (entry & 255u))) {
      } else {
        break;
      }
      {
        uint _e68 = k;
        uint _e71 = asuint(lens_bins.Load((first + _e68)*4));
        float4 drop = asfloat(lens_drops.Load4(_e71*16));
        float radius = max(drop.z, 1e-5);
        d = (screen - drop.xy);
        fade = drop.w;
        if ((drop.w >= 2.0)) {
          float side = ((((drop.w - 2.0) / 0.999) * 2.0) - 1.0);
          float2 path = float2(side, sqrt(max((1.0 - (side * side)), 0.0)));
          float2 _e101 = d;
          float2 _e102 = d;
          d = (_e101 - ((path * dot(_e102, path)) * 0.2));
          fade = 1.0;
        }
        float2 _e109 = d;
        float r = (length(_e109) / radius);
        float _e117 = fade;
        float inside = ((1.0 - smoothstep(0.85, 1.0, r)) * _e117);
        float2 _e119 = d;
        float2 normal = (_e119 / (radius).xx);
        float2 _e122 = bend;
        bend = (_e122 - (((normal * radius) * 1.6) * inside));
        float _e128 = rim;
        rim = max(_e128, (smoothstep(0.55, 1.0, r) * inside));
        float _e134 = glint;
        glint = max(_e134, ((1.0 - smoothstep(0.0, 0.25, length((normal - float2(-0.35, -0.4))))) * inside));
      }
    }
  }
  float2 _e150 = bend;
  float2 uv = clamp(((pixel + (_e150 * size.y)) / size), (0.0).xx, (1.0).xx);
  float4 _e163 = lens_source.SampleLevel(linear_sampler, uv, 0.0);
  colour = _e163.xyz;
  float scale = frame.output.z;
  if ((scale < 0.999)) {
    float4 _e174 = frame.viewport;
    float2 texel = _e174.zw;
    float4 _e183 = lens_source.SampleLevel(linear_sampler, (uv - float2(0.0, texel.y)), 0.0);
    float3 north = _e183.xyz;
    float4 _e192 = lens_source.SampleLevel(linear_sampler, (uv + float2(0.0, texel.y)), 0.0);
    float3 south = _e192.xyz;
    float4 _e201 = lens_source.SampleLevel(linear_sampler, (uv - float2(texel.x, 0.0)), 0.0);
    float3 west = _e201.xyz;
    float4 _e210 = lens_source.SampleLevel(linear_sampler, (uv + float2(texel.x, 0.0)), 0.0);
    float3 east = _e210.xyz;
    float3 _e215 = colour;
    float3 low = min(min(min(north, south), min(west, east)), _e215);
    float3 _e220 = colour;
    float3 high = max(max(max(north, south), max(west, east)), _e220);
    float amount = (saturate(((1.0 - scale) * 2.0)) * 0.6);
    float3 _e229 = colour;
    float3 _e230 = colour;
    float3 sharpened = (_e229 + (((((((_e230 * 4.0) - north) - south) - west) - east) * amount) * 0.25));
    colour = clamp(sharpened, low, high);
  }
  float3 _e242 = colour;
  float _e243 = rim;
  float _e249 = glint;
  colour = ((_e242 * (1.0 - (_e243 * 0.35))) + ((_e249 * 0.35)).xxx);
  float3 _e254 = colour;
  return float4(_e254, 1.0);
}
