// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: atmosphere (ground + common + atmosphere)
// Entry point: scene_copy_main, compile with /T ps_5_0 /E scene_copy_main
//
// Resources (WGSL group/binding -> register):
//   @group(0) @binding(0) frame -> b0  constant buffer
//   @group(3) @binding(0) scene_texture -> t0  Texture2D (Sampled { kind: Float, multi: false })
//   @group(3) @binding(1) depth_texture -> t1  Texture2D (Depth { multi: false })

struct FrameUniforms {
  row_major float4x4 view_proj;
  float4 camera_position;
  float4 camera_forward;
  float4 camera_right;
  float4 camera_up;
  float4 sun_direction;
  float4 atmosphere;
  float4 sky_tint;
  float4 mist_params;
  float4 mist_colour;
  float4 mist_wind;
  float4 cloud_params;
  float4 cloud_motion;
  float4 cloud_colour;
  float4 water_params;
  float4 water_shallow;
  float4 water_deep;
  float4 water_current;
  float4 wave_params;
  float4 wave_params2_;
  float4 water_origin;
  float4 vegetation;
  float4 vegetation2_;
  float4 viewport;
  row_major float4x4 shadow_view_proj;
  float4 shadow_params;
  float4 weather;
  float4 weather2_;
  float4 surface;
  float4 clouds2_;
  float4 clouds3_;
  float4 clouds4_;
  float4 weather3_;
  row_major float4x4 previous_view_proj;
  float4 temporal;
  float4 distances;
  float4 fades;
  float4 output;
  float4 cold;
  float4 sea_ice;
  float4 rivers;
  float4 ground;
  float4 vegetation3_;
  float4 rock;
  float4 regional;
  float4 air;
  float4 light;
  float4 gust;
  float4 weather4_;
  float4 clouds5_;
  float4 alto;
  float4 rivers2_;
  float4 waterside;
  float4 mouths[16];
};

struct VertexOut {
  float4 clip_position : SV_Position;
  float2 ndc : LOC0;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const float SHAFT_START = 1200.0;

cbuffer frame : register(b0) { FrameUniforms frame; }
Texture2D<float4> scene_texture : register(t0);
Texture2D<float> depth_texture : register(t1);

struct FragmentInput_scene_copy_main {
  float2 ndc_1 : LOC0;
  float4 clip_position : SV_Position;
};

int2 naga_f2i32(float2 value) {
  return int2(clamp(value, -2147483600.0, 2147483500.0));
}

int2 full_pixel(float2 ndc)
{
  float2 uv = float2(((ndc.x * 0.5) + 0.5), (0.5 - (ndc.y * 0.5)));
  float4 _e14 = frame.viewport;
  float4 _e21 = frame.viewport;
  return naga_f2i32(clamp((uv * _e14.xy), (0.0).xx, (_e21.xy - (1.0).xx)));
}

float4 scene_copy_main(FragmentInput_scene_copy_main fragmentinput_scene_copy_main) : SV_Target0
{
  VertexOut in_ = { fragmentinput_scene_copy_main.clip_position, fragmentinput_scene_copy_main.ndc_1 };
  const int2 _e2 = full_pixel(in_.ndc);
  float depth = depth_texture.Load(int3(_e2, int(0))).x;
  float near = frame.water_deep.w;
  float far = frame.water_current.w;
  float view_depth = ((depth >= 0.999999) ? 1000000000.0 : ((far * near) / max((far - (depth * (far - near))), 0.0001)));
  float4 _e27 = scene_texture.Load(int3(_e2, int(0)));
  return float4(_e27.xyz, view_depth);
}
