// Generated by vista_hlsl from VistaWASM's WGSL. Do not edit by hand:
// change the WGSL and run `cargo run -p vista_hlsl`.
// Licence: AGPL-3.0-only, as VistaWASM.
//
// Module: atmosphere (ground + common + atmosphere)
// Entry point: vertex_main, compile with /T vs_5_0 /E vertex_main
//
// Resources (WGSL group/binding -> register):
// D3D11: reads vertex_index: SV_VertexID does not include BaseVertexLocation in Direct3D 11. Draw with base vertex 0, or add it from a constant buffer.

struct VertexOut {
  float4 clip_position : SV_Position;
  float2 ndc : LOC0;
};

static const float SKIRT_METRES = 1500.0;
static const float LOD_BAND_WIDTH = 24.0;
static const float PI = 3.1415927;
static const float TAU = 6.2831855;
static const float3 RAYLEIGH_BETA = float3(5.8e-6, 1.35e-5, 3.31e-5);
static const float3 MIE_BETA = float3(2.1e-5, 2.1e-5, 2.1e-5);
static const float RAYLEIGH_HEIGHT = 8000.0;
static const float MIE_HEIGHT = 1200.0;
static const float SUN_RADIANCE = 15.0;
static const float ALTOCUMULUS_THICKNESS = 250.0;
static const float ALTOSTRATUS_THICKNESS = 600.0;
static const float ALTO_EXTINCTION = 0.00495;
static const float ALTO_RIPPLE = 900.0;
static const float ALTO_CELL_TILE = 1080.0;
static const float ALTO_SMALLEST = 0.3;
static const float MEADOW_LIGHT = 0.78;
static const float SHAFT_START = 1200.0;

struct VertexOutput_vertex_main {
  float2 ndc : LOC0;
  float4 clip_position : SV_Position;
};

typedef float2 ret_Constructarray3_float2_[3];
ret_Constructarray3_float2_ Constructarray3_float2_(float2 arg0, float2 arg1, float2 arg2) {
  float2 ret[3] = { arg0, arg1, arg2 };
  return ret;
}

VertexOutput_vertex_main vertex_main(uint vertex_index : SV_VertexID)
{
  float2 positions[3] = Constructarray3_float2_(float2(-1.0, -1.0), float2(3.0, -1.0), float2(-1.0, 3.0));
  VertexOut out_ = (VertexOut)0;

  float2 position = positions[min(uint(vertex_index), 2u)];
  out_.clip_position = float4(position, 0.0, 1.0);
  out_.ndc = position;
  VertexOut _e20 = out_;
  const VertexOut vertexout = _e20;
  const VertexOutput_vertex_main vertexout_1 = { vertexout.ndc, vertexout.clip_position };
  return vertexout_1;
}
