//! Embeds the Direct3D 11 port's compiled shaders and their manifest.
//!
//! `ports/d3d11/hlsl/manifest.json` (from `cargo run -p vista_hlsl`) says,
//! for every translated entry point, which register each WGSL binding
//! takes. `ports/d3d11/cso` holds them compiled with Microsoft's compiler
//! (`ports/d3d11/tools/check-hlsl.sh`). This writes both into a Rust table
//! the renderer's Direct3D 11 lowering looks shaders up in, so a host
//! ships no shader files.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
  if let Err(error) = run() {
    println!("cargo::error=vista_native could not embed the Direct3D 11 shaders: {error}");
  }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
  let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../ports/d3d11");
  let manifest_path = root.join("hlsl/manifest.json");
  println!("cargo::rerun-if-changed={}", manifest_path.display());
  println!("cargo::rerun-if-changed={}", root.join("cso").display());
  let manifest: serde_json::Value = serde_json::from_str(&fs::read_to_string(&manifest_path)?)?;
  let files = manifest["files"]
    .as_array()
    .ok_or("the manifest has no files")?;
  let mut out = String::from("// Generated by build.rs from ports/d3d11/hlsl/manifest.json.\n");
  out.push_str("pub static FILES: &[ShaderFile] = &[\n");

  for file in files {
    let text = |key: &str| -> Result<String, String> {
      file[key]
        .as_str()
        .map(str::to_string)
        .ok_or_else(|| format!("a manifest entry has no {key}"))
    };
    let name = text("file")?;
    let cso = root.join("cso").join(name.replace(".hlsl", ".cso"));
    println!("cargo::rerun-if-changed={}", cso.display());

    if !cso.exists() {
      return Err(
        format!(
          "{} is missing: run ports/d3d11/tools/check-hlsl.sh",
          cso.display()
        )
        .into(),
      );
    }

    let stage = match text("stage")?.as_str() {
      "vertex" => "Stage::Vertex",
      "fragment" => "Stage::Fragment",
      "compute" => "Stage::Compute",
      other => return Err(format!("{name}: unknown stage {other}").into()),
    };
    let mut overrides = String::new();

    for (key, value) in file["overrides"].as_object().into_iter().flatten() {
      write!(
        overrides,
        "({key:?}, {}), ",
        value.as_bool().unwrap_or(false)
      )?;
    }

    let mut bindings = String::new();

    for binding in file["bindings"].as_array().into_iter().flatten() {
      let register = binding["register"]
        .as_str()
        .ok_or_else(|| format!("{name}: a binding has no register"))?;
      let (class, index) = register.split_at(1);
      write!(
        bindings,
        "Binding {{ group: {}, binding: {}, class: b'{class}', register: {index} }}, ",
        binding["group"].as_u64().unwrap_or(0),
        binding["binding"].as_u64().unwrap_or(0),
      )?;
    }

    let special = match file["specialConstants"].as_str() {
      Some(register) => format!("Some({})", &register[1..]),
      None => "None".to_string(),
    };
    writeln!(
      out,
      "  ShaderFile {{ file: {name:?}, module: {:?}, entry: {:?}, stage: {stage}, overrides: &[{overrides}], bindings: &[{bindings}], special_constants: {special}, cso: include_bytes!({:?}) }},",
      text("module")?,
      text("wgslEntryPoint")?,
      cso.canonicalize()?.display().to_string(),
    )?;
  }

  out.push_str("];\n\npub static SOURCES: &[(&str, &str)] = &[\n");

  for (module, hash) in manifest["sources"].as_object().into_iter().flatten() {
    writeln!(
      out,
      "  ({module:?}, {:?}),",
      hash.as_str().unwrap_or_default()
    )?;
  }

  out.push_str("];\n\npub static COMPILED: &[(&str, &str)] = &[\n");
  let stamps_path = root.join("cso/sources.json");
  println!("cargo::rerun-if-changed={}", stamps_path.display());
  let stamps: serde_json::Value = fs::read_to_string(&stamps_path)
    .ok()
    .and_then(|text| serde_json::from_str(&text).ok())
    .unwrap_or_default();

  for (file, hash) in stamps.as_object().into_iter().flatten() {
    writeln!(
      out,
      "  ({file:?}, {:?}),",
      hash.as_str().unwrap_or_default()
    )?;
  }

  out.push_str("];\n");
  let target = Path::new(&std::env::var("OUT_DIR")?).join("d3d11_shaders.rs");
  fs::write(target, out)?;
  Ok(())
}
